### ISSUE TITLE
Loadout screen is kill

### ISSUE THREAD

**Issue by Magneld** [PolarisSS13/Polaris#1003]
While playing dressup with my new Teshari character the entire loadout screen died, (picture below) once I selected a brown webbing vest.

[http://imgur.com/ZsJ47gp]

**Comment by Magneld** [comment]
Good news is that ghosting and respawning seems to sort it so for now will just tell mods and mins to do that if it happens to players.

**Comment by Zuhayr** [comment]
Likely a runtime somewhere, would be good to see server logs for this if it can't be reproduced locally.

**Comment by Zuhayr** [comment]
Can't reproduce this locally.

**Comment by Magneld** [comment]
No worries, in my experience with the issue its easy enough for admins to fix if it happens again.
