### ISSUE TITLE
Succumb verb does not kill Teshari

### ISSUE THREAD

**Issue by Jakksergal** [PolarisSS13/Polaris#1013]
What I did: Playing Teshari, floating through space with no suit, used succumb at critical and did not die for another ten minutes or so.

Guessing it has to do with the fact that I wasn't actually at 'normal' critical levels that a human mob would experience.

**Comment by Telvayne** [comment]
I think there's some inconsistency with succumb across the board.  I've had it not work while I was in crit as well, as a Skrell and a human.
