### ISSUE TITLE
Robotics Console does not allow rogue cyborgs to hack themselves.

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#1026]
#### Brief description of the issue
Traitorous cyborgs cannot hack themselves due to the robotics console not having a hack button for antag synths, when it did previously. (Before NanoUI)
#### What you expected to happen
The robotics console to allow rogue cyborgs to hack themselves.
#### What actually happened
The robotics console did not have the button to hack one's self.
#### Steps to reproduce
Be a traitorous cyborg, look at the robotics console. You'll find you can't unlock your illegal equipment and abilities.
#### Additional info:
20484387b8161846a875a4915bd3088e8f52ec35 (?)

**Comment by Anewbe** [comment]
Pretty sure this is fixed, closing

**Comment by Datraen** [comment]
Rather than saying "Yeah, I think this was got, closing.", maybe you should drop a "Needs Retesting".

**Comment by Anewbe** [comment]
I've seen the console used by antag borgs to hack themselves, multiple times. It's fixed.
