### ISSUE TITLE
FBP Cultists don't heal from runes

### ISSUE THREAD

**Issue by Minijar** [PolarisSS13/Polaris#1032]
#### Brief description of the issue
As a FBP you don't heal from rune use, meaning you most constantly carr supplies otherwise you can easily cripple yourself.
#### What you expected to happen
To slowly heal after use
#### What actually happened
I did not heal and damage simply accumulated
#### Steps to reproduce
Be an FBP, draw runes
#### Additional info:
 - **20484387b8161846a875a4915bd3088e8f52ec35**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Zuhayr** [comment]
You also don't bleed. Not seeing this as a bug.

**Comment by Spacemanspark** [comment]
I thought this was because of health auto-regeneration, something IPCs/ maybe FBPs don't have due to being robotic?
