### ISSUE TITLE
Grinders don't fully get rid of reagents

### ISSUE THREAD

**Issue by SledgeLP** [PolarisSS13/Polaris#104]
The grinders when tested with phoron in chem would grind reagents, but would leave them in the list. After grinding again, you don't get products, but the name goes away.

**Comment by zaredman** [comment]
@SledgeLP BS12 Dev-Freeze issue or Polaris bug?

**Comment by Mark9013100** [comment]
Able to somewhat reproduce on bay's current dev branch. Processing solid phoron the second time will make it work for real.

**Comment by Kelenius** [comment]
Cannot reproduce.
