### ISSUE TITLE
Teshari Immune to Hallos Stuns

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1042]
#### Brief description of the issue
It is impossible to make a teshari pass out from accumulated Hallos.
#### What you expected to happen
The Teshari to pass out from taking about 500 Hallos damage.
#### What actually happened
They walked off a borg and an officer emptying an entire stunbaton into them. Later, did not pass out from taking an entire energy gun, and taser,
#### Steps to reproduce
Hit a teshari with something that does Hallos damage.
#### Additional info:
Server revision: master - 2016-02-20
20484387b8161846a875a4915bd3088e8f52ec35

**Comment by Zuhayr** [comment]
Reproduced, almost certainly due to halloss doing a hard check against 100 instead of species health as setting Teshari health to 51 caused halloss to proc fine.
