### ISSUE TITLE
Shooting targets are bugged to hell and back

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1055]
#### Brief description of the issue

http://puu.sh/mfj40/ebff1825ab.png
Shooting targets will randomly change sprites, from mobs, objects, ie.
#### What you expected to happen

For them to stay as target dummies.
#### What actually happened

They change into a non-target sprite.
#### Steps to reproduce

Happens at random. Best chance is leaving a bunch of targets around.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
  Server revision: master - 2016-02-20
  20484387b8161846a875a4915bd3088e8f52ec35 
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Kelenius** [comment]
Sounds like one persistent byond bug where random sprites get replaced with random sprites. Are you sure this is specific to dummies? Did restarting the game help? Was it local to you?

**Comment by Mark9013100** [comment]
1. Yep, specific to shooting targets.
2. Restarting the client corrects it.
3. It's local.

**Comment by zaredman** [comment]
This was an ooooooooooooold bay bug.

**Comment by Mark9013100** [comment]
But still a bug none the less.

**Comment by Mark9013100** [comment]
In this case: It's Zoe Jasper!
![](https://i.gyazo.com/f541e1d043ed201e3aab23cd2b85f5cc.png)

**Comment by Telvayne** [comment]
I have also seen them disappear.  As well, sometimes they show up as normal targets for some people, and are invisible to other people.  Those things are really, really buggy!

**Comment by Kelenius** [comment]
This can happen to other things; my guess is that since targets update their icons a lot, they are more prone to this.

**Comment by Ccomp5950** [comment]
W-hat?
