### ISSUE TITLE
PAI sees double emotes

### ISSUE THREAD

**Issue by AliciaJewel** [PolarisSS13/Polaris#1060]
#### Brief description of the issue
When playing as a pAI, emotes generated by the game are doubled. When also using the Rest command, emotes created with "me" are also doubled.

#### What you expected to happen
I only expected to see one emote when I was playing as a pAI.

#### What actually happened
I saw two of each emote.

#### Steps to reproduce
1. Load in as a pAI.
2. (Optional) Use the Rest command.
3. Watch your chat get flooded with emotes.

#### Additional info:
 - **Server Revision**: 
Server revision: master - 2016-02-20
20484387b8161846a875a4915bd3088e8f52ec35 
 - **Anything else you may wish to add**
  *Molly Highlander: i think
  *Molly Highlander: you might see emotes for each of your forms
  *Molly Highlander: like, one for the PDA form, one for the cat form

**Comment by Kelenius** [comment]
I remember an AI on an intelicard complaining about the same problem.
