### ISSUE TITLE
Reinforced windows Issue

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#107]
Reinforced windows require four sheets of reinforced glass per placement. Still only drop one glass shard and rod. And pretty much means there is literally nothing you can make with 1-3 sheets of reinforced glass. This something we inherited from bay and is it something we can easily fix or live with?

**Comment by Woodratt** [comment]
Update, deconstructing the reinforced windows only gives back one sheet of reinforced glass as well.

**Comment by zaredman** [comment]
Reference #130

**Comment by Neerti** [comment]
Fixed in #130
