### ISSUE TITLE
Natural philosopher wig doesn't do anything when clicked in loadout

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#1072]
#### Brief description of the issue
Natural philosopher wig doesn't do anything when clicked in loadout.

#### What you expected to happen
Add the wig to the loadout displaying it in the orange colour

#### What actually happened
No action at all on click

#### Steps to reproduce
Character setup -> loadout -> headware -> natural philosopher's wig

#### Additional info:
Server revision: master - 2016-02-24
33b50087e4f0f43640fbb570e30359a5323f12c5

**Comment by PsiOmegaDelta** [comment]
The issue is more likely than not the ' in the name.

**Comment by Anewbe** [comment]
Fixed

**Comment by Datraen** [comment]
What PR/commit?

**Comment by Anewbe** [comment]
I do not know, but it works on the server.
