### ISSUE TITLE
Dropping scoped weapons bugs camera.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1073]
#### Brief description of the issue

When scoped in with a LWAP or PTR, if you drop the weapon or are knocked over the camera gets stuck in the scoped mode.
#### What you expected to happen

The camera to revert to normal.
#### What actually happened

The camera gets stuck in scoped mode, and cannot be fixed except by someone else placing the weapon in the hand of the one effected.
#### Steps to reproduce

Zoom with a scoped weapon. Hit rest.
#### Additional info:

Server revision: master - 2016-02-24
33b50087e4f0f43640fbb570e30359a5323f12c5

**Comment by Atermonera** [comment]
[Could not reproduce as of 10-jun-2018](https://puu.sh/AD36H/e902fb9f84.mp4)
