### ISSUE TITLE
Bullets cannot penetrate rock tiles.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1074]
#### Brief description of the issue

Weapons with penetration values high enough to shoot through reinforced walls do not penetrate one tile of rock.
#### What you expected to happen

The bullet to penetrate rock and hit the target on the other side.
#### What actually happened

The bullets hit the rock and stopped.
#### Steps to reproduce

Place target on one side of a rock. Shoot at the target using a Heavy Sniper.
#### Additional info:

Server revision: master - 2016-02-24
33b5008

**Comment by EmperorJon** [comment]
Should we allow this? It makes sense that the rock is significantly more resistant than r-walls in terms of thickness when considering shooting ballistics. If we do implement penetration, should they be equal to, better than, or worse than r-walls?

**Comment by robovelcro** [comment]
I personally think that rock walls should be much stronger than reinforced walls. I mean, rock is probably a little stronger, contains bits of strong materials in it, and chances of deflections or ricochets, etc...
