### ISSUE TITLE
Headscarf can not be selected.

### ISSUE THREAD

**Issue by ghost** [PolarisSS13/Polaris#1087]
#### Brief description of the issue

If you select the headscarf in the custom loadout and press save, it removes itself.
#### What you expected to happen

Getting a headscarf.
#### What actually happened

Not getting a headscarf.
#### Steps to reproduce

Go to the custom loadout, click on Headscarf, and click on 'save slot'.
#### Additional info:
- **Server Revision**: master - 2016-02-25

**Comment by Woodratt** [comment]
Would this be the Tajaran headscarf? If so, are you the proper race to get it?

**Comment by PsiOmegaDelta** [comment]
I suppose I should port the small tweak were you cannot see items belonging to a race you're not whitelisted for to begin with.

**Comment by nachomeep** [comment]
It was the Tajaran headscarf, but the name was only 'headscarf', and it wasn't even in the xenowear tab, so I assumed it was public. I still wish it was, but that's irrelevant.
