### ISSUE TITLE
Elevator doesn't remove "identity from the round".

### ISSUE THREAD

**Issue by silveryferret** [PolarisSS13/Polaris#1088]
#### Brief description of the issue
So when you go hit the elevator, doesn't remove your body from the round. Like... I can hit the "Follow" button and I can find my name, despite that the body isn't really there...? The main issue is that I try to hit the "Call Communicator" button, and it says "Your identity is still present in the round. Please load another character slot first."
#### What you expected to happen
I expected the body to be gone! And to let me use communicator!
#### What actually happened
"Your identity is already present in the game world.  Please load in a different character first."
#### Steps to reproduce
Join round, go to elevator, ghost, try to call communicator. No idea if it's a one time bug or what.
#### Additional info:
 - **Server Revision**: Server revision: master - 2016-02-25
767a6e7c28ea01f05f7cb5b60858f9d64fdc22a0

**Comment by Spookerton** [comment]
This is an issue related to FBP positronics/MMIs being left at cryogenics consoles, and doesn't happen for non-FBP mobs- since the brain isn't removed from the world, the identity doesn't get removed.
