### ISSUE TITLE
Turrets can't shoot through glass

### ISSUE THREAD

**Issue by Kelenius** [PolarisSS13/Polaris#1089]
#### Brief description of the issue

Turret trajectory tracer doesn't respect `pass_flags`, and so the turret thinks that it can't shoot if there's glass between it and the target
#### What you expected to happen

Turret would shoot through the glass
#### What actually happened

Turret doesn't fire if there's glass between it and target
#### Steps to reproduce

Stand in front of AI's core and watch
#### Additional info:

Turrets fire a `/obj/item/projectile/test` to determine if they can reach their target, which has most procs completely overwritten and they probably weren't updated properly.

**Comment by Atermonera** [comment]
Turrets have been updated, can't find the appropriate PR, but this should be closeable
