### ISSUE TITLE
Bees create unviable amounts of produce

### ISSUE THREAD

**Issue by Minijar** [PolarisSS13/Polaris#1092]
#### Brief description of the issue
I set up a beehive in hydroponics, surrounded by healthy plants. Over a period of two hours, it provided a grand total of two wax - enough for two candles.
#### What you expected to happen
A bit more then two wax for two hours, some honey to also be produced would be nice.
#### What actually happened
Wax is produced at a rate of one an hour with no honey.
#### Steps to reproduce
Setup a beehive
Be disapointed with the incredibly slow production of wax.
#### Additional info:
 - **Server Revision**: 
767a6e7c28ea01f05f7cb5b60858f9d64fdc22a0 
 - **Anything else you may wish to add** The bees also don't get angry anymore.

**Comment by Kelenius** [comment]
Did you keep the beehive open for extended periods of time? It worked fine for me.

**Comment by Minijar** [comment]
I had two, one I left open forever, and one I closed and opened occasionally.

**Comment by Anewbe** [comment]
Use a beaker or bucket on the extractor after use, every frame makes I think 20 units of honey, and one sheet of wax.
Also the rate's way higher than one frame an hour, I had a single hive set up yesterday and in less than an hour it filled 5 frames.

**Comment by Minijar** [comment]
What's the correct way to setting it up? Maybe I was doing something wrong.

**Comment by Kelenius** [comment]
Put down the frame, put bees in, close the lid. Put living plants nearby. Don't smoke them and keep the lid closed. Wait until bees breed.

**Comment by Anewbe** [comment]
Gonna say this was operator error, haven't heard or seen anything about this in ages.
