### ISSUE TITLE
Appendicitis - The Silent Killer

### ISSUE THREAD

**Issue by comma** [PolarisSS13/Polaris#1094]
#### Brief description of the issue
Appendicitis condition doesn't show up on handheld scanners nor body scanners
#### What you expected to happen
Some way to diagnose appendicitis with advanced space machinery
#### What actually happened
Had to rely on my gruff medical expertise recognizing slow tox buildup and wince emotes
#### Steps to reproduce
1.Get appenditis.
2.Go to a doctor
3.Get handheld scan
4.Get body scan
5.Cry as everything shows up healthy

**Comment by comma** [comment]
Looks like appendicitis is moved into appendix organ, but it uses internal vars for tracking progress, so health/infection level are unaffected and therefore invisible on scanners.

**Comment by Kelenius** [comment]
Oh, yeah, that. Appendicitis should deal some damage to appendix up to like 10.

**Comment by comma** [comment]
Funniest thing, in the 'bursting' phase it just resets inflammed status to 0 after doing all bad stuff, so if you're unlucky enough you can get it twice in a row.

**Comment by Minijar** [comment]
I thought appendicitis was removed?

**Comment by Mark9013100** [comment]
Bump.

**Comment by Anewbe** [comment]
Shows up on hand scanners now
