### ISSUE TITLE
Removal of mechanical eyes does not result in blindness

### ISSUE THREAD

**Issue by Kelenius** [PolarisSS13/Polaris#1097]
#### Brief description of the issue
Removal of mechanical eyes does not result in blindness
#### What you expected to happen
Guy would be blind after having optical sensors removed
#### What actually happened
He wasn't
#### Steps to reproduce
Be a guy with mechanical eyes, have someone cut them out in surgery
#### Additional info:
 - **Server Revision**: 9fdce4ec3412920640bed1f597b77b876a793d8f

**Comment by comma** [comment]
Oh, that's cause Life code assumes that if you don't have eyeballs, your species doesn't need them.
Fixes in https://github.com/Baystation12/Baystation12/pull/12276
