### ISSUE TITLE
Uplink surgery kits do not have enough space to hold their own contents

### ISSUE THREAD

**Issue by Spookerton** [PolarisSS13/Polaris#1103]
Uplink surgery kits need max_storage_space = 23 to fit the objects they spawn containing, instead they have max_storage_space = 14 and so cannot be repacked once used

[/obj/item/weapon/storage/firstaid/surgery](https://github.com/PolarisSS13/Polaris/blob/d625316636eb37ff6aa52e64abe4a60c01ceda7c/code/game/objects/items/weapons/storage/firstaid.dm#L131)

**Comment by PsiOmegaDelta** [comment]
Bay resolved this with form fitted containers to avoid giving people access to silly sized storage:
https://github.com/Baystation12/Baystation12/pull/11303
