### ISSUE TITLE
RNG loves the Traitorling

### ISSUE THREAD

**Issue by Datraen** [PolarisSS13/Polaris#1111]
#### Brief description of the issue
RNG CONSTANTLY PICKS TRAITORLING FOR SECRET
#### What you expected to happen
RNG picks reasonably from the list of secret gamemodes
#### What actually happened
RNG picks Traitorling all the time
#### Steps to reproduce
1. Have people vote secret
2. Watch Traitorling get picked
#### Additional info:
 - **Server Revision**: dc572191d277ad286703fb7210be56c626248dae 
 - I don't know if this is a config issue or not, could not reproduce on a local server.

**Comment by Zuhayr** [comment]
This reeks of confirmation bias.

**Comment by EmperorJon** [comment]
Honestly inclined to agree.

**Comment by Magneld** [comment]
Past couple of days have indeed been ling happy but I'm told that all antag types are weighed equally.
Bad luck I suppose. How doable would it be though to make it so the RNG doesn't pick two of the same round in a row?

**Comment by Spookerton** [comment]
It doesn't actually constantly pick traitorling for secret.
