### ISSUE TITLE
Space Suits Can't Hold Cooling Units

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#1116]
#### Brief description of the issue
Cooling units can't be placed on the back, belt, or suit storage slot, which leaves no place to keep them except in hand when wearing a space suit.

#### What you expected to happen
The cooling unit to be equip-able on the suit storage slot, back slot, or belt slot.

#### What actually happened
The Full Body Prosthetic could only hold the cooling unit in its hands.

#### Steps to reproduce
1.) Wear a spacesuit that isn't a voidsuit/rig
2.) Try to equip a cooling unit.

#### Additional info:
 - **Server Revision**: master - 2016-02-28
 - **Mostly unrelated but relevant:** Skrellian voidsuits are actually space suits. They should probably be renamed to space suits or be made into voidsuits.

**Comment by Anewbe** [comment]
No longer accurate for voidsuits, still applies for hardsuits.

**Comment by Anewbe** [comment]
Fixed

**Comment by Datraen** [comment]
When was this fixed?
What commit/PR?

**Comment by Anewbe** [comment]
The former https://github.com/PolarisSS13/Polaris/pull/899, the later was https://github.com/PolarisSS13/Polaris/pull/2363
