### ISSUE TITLE
[Sprites] Bugs with the r_skrell.dmi (Fix inside)

### ISSUE THREAD

**Issue by RoseCG** [PolarisSS13/Polaris#1118]
#### Brief description of the issue
Female Skrell Torso isn't the same color as the male one or the rest of the body parts.
Also, r_leg shows blood pixels over the r_foot in the character setup screen (ingame works fine)
https://dl.dropboxusercontent.com/u/2264998/sprites/skrell_bug.PNG

#### What you expected to happen
To be of the same color scheme as everything else when you check the character setup or in dream maker.
And the r_leg to not show blood pixels when still attached to the leg on the character setup screen.

#### What actually happened
The female torso is clearly off color compared with everything else.
On the character screen, r_leg is on top of r_foot and shows the blood sprites. It's not very obvious due to the color overlay.

#### Steps to reproduce
Open r_skrell.dmi on dream maker and compare
OR
Create a female Skrell in Character Setup ingame.
The r_leg bug only happens in the character setup.

#### Additional info:
 - I updated the r_skrell.dmi file. In this one, the female torso is the same color as everything else. Also removed the extra pixels from r_leg since all other sprites, including the other races, lack those anyway.
https://dl.dropboxusercontent.com/u/2264998/sprites/r_skrell_fixed.dmi

**Comment by RoseCG** [comment]
Okay, finally posted the fixed .dmi. Works fine on my test server, but I would appreciate it others tested it too before someone makes a PR.

**Comment by Telvayne** [comment]
That's a bug?  I always thought my torso was just lighter naturally.  Weird.

**Comment by RoseCG** [comment]
There's nothing on the skrell lore that indicates female skrell torsos being in lighter color compared with male skrell's. I'm assuming the female torso was created much after the original set of sprites and they missed on the same color scheme.

**Comment by Telvayne** [comment]
I'll bug...whoever the current lore maintainer is about it.  A little sexual dimorphism adds character, sometimes.

**Comment by Mark9013100** [comment]
Current Lord of Skrell is Neerti I believe.
