### ISSUE TITLE
Kat-Phones custom item sprite issue

### ISSUE THREAD

**Issue by serenemelody** [PolarisSS13/Polaris#1144]
#### Brief description of the issue
When trying to turn the music on for the item, it instead made the sprite disappear.
#### What you expected to happen
I had expected the sprite to change.
#### What actually happened
The sprite disappeared. It remained spriteless after toggling it again.
#### Steps to reproduce
Like, just toggle the headphone music.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Mark9013100** [comment]
Going to assume this might be from the icon_states not being listed, atleast, this is what I thinks happening from reading the code.

/obj/item/clothing/ears/earmuffs/headphones/verb/togglemusic()
	set name = "Toggle Headphone Music"
	set category = "Object"
	set src in usr
	if(!istype(usr, /mob/living)) return
	if(usr.stat) return

	if(headphones_on)
		icon_state = "headphones_off"
		headphones_on = 0
		usr << "<span class='notice'>You turn the music off.</span>"
	else
		icon_state = "headphones_on"
		headphones_on = 1
		usr << "<span class='notice'>You turn the music on.</span>"

	update_clothing_icon()

**Comment by Datraen** [comment]
I was working on a fix for this, but it wasn't as easy as thought. I might add a variable to hold on/off states, if it's desired.
