### ISSUE TITLE
Cash Reg issue.

### ISSUE THREAD

**Issue by ghost** [PolarisSS13/Polaris#1148]
#### Brief description of the issue

Cash Reg is locked by a civilian account. It is not named, and you are unable to enter your details (PIN, ACCOUNT NUMBER) so it sends money to you. Instead, you are unable to do this, and may instead send money to the mysterious civilian account.

#### What you expected to happen

Free register with the ability to enter your account. This is unable to happen, as the Civ Account is locked.

#### What actually happened

Can not enter your account into the Cash Registers.

#### Steps to reproduce

None.

**Comment by RoseCG** [comment]
Question: What if there are two chefs in the kitchen? What if the gardener wants a cut of the profits as well?

IMO it makes sense the default account in the registers is the civilian one, managed by the HoP. But I would not mind to see an option to use another account instead, although I'm not sure if we have corporate rules about this yet given the cash registers are a recent feature.

**Comment by Arokha** [comment]
You can manually put acct# into registers now, so this can probably be closed.
