### ISSUE TITLE
You can join as jobs that don't exist or have roundstart markers

### ISSUE THREAD

**Issue by zaredman** [PolarisSS13/Polaris#115]
![job delete](https://cloud.githubusercontent.com/assets/8041697/9060842/80155c4e-3a85-11e5-9855-2891fb582e60.PNG)

Jobs that don't exist:
>Librarian
>Atmos Tech (General Engineer as replacement)
>Cargo Tech
>IA Agent
>Chaplain
>Warden
>Xenobiologist
>RD
>Psych
>Geneticist
>Gardener

**Comment by Neerti** [comment]
I'll need a list of jobs that need to get cut.

**Comment by zaredman** [comment]
Scroll up. It's the list in the first post.
