### ISSUE TITLE
Godmode doesn't protect you from cold slowdown

### ISSUE THREAD

**Issue by Kelenius** [PolarisSS13/Polaris#1152]
#### Brief description of the issue

Godmode doesn't protect you from cold slowdown
#### What you expected to happen

You wouldn't get slowed while godmode is on
#### What actually happened

Take a guess
#### Steps to reproduce

Turn godmode on, teleport to tcomms
#### Additional info:
- **Server Revision**: latest master

**Comment by Zuhayr** [comment]
Godmode is basically unmaintained, it should be pruned out entirely or reimplemented.
