### ISSUE TITLE
Natural Philosopher's Wig is Unselectable

### ISSUE THREAD

**Issue by SparklySheep** [PolarisSS13/Polaris#1155]
#### Brief description of the issue

The Natural Philosopher's wig is unselectable in the loadout menu.

#### What you expected to happen

Click on the wig and have it added to loadout.

#### What actually happened

Wig remained blue and unselected.

#### Steps to reproduce

Click on the Wig in the loadout menu under the hats option.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

This is a serious server ending issue please resolve as soon as possible as the game is unplayable without this.

**Comment by Datraen** [comment]
See #1072
