### ISSUE TITLE
Lockbox is accessible even if locked if you have its inventory open

### ISSUE THREAD

**Issue by Kelenius** [PolarisSS13/Polaris#1163]
#### Brief description of the issue
You can take items out of a locked lockbox if they have its inventory open
#### What you expected to happen
You'd be unable to take the item out
#### What actually happened
You take the item out; "It's locked!" message appears
#### Steps to reproduce
Take a lockbox; unlock it; open its inventory by dragging its sprite to your mob; lock it; take the item out of the lockbox.
#### Additional info:
 - **Server Revision**: 7b9f011d109c9d395ac218dbb6a7144ed6055b4e
 - **Anything else you may wish to add** Was tested with captain's medal lockbox

**Comment by bgobandit** [comment]
yo we just pushed a fix for this https://github.com/tgstation/-tg-station/pull/17569
