### ISSUE TITLE
2-handed weapons don't stop on hand-loss

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#1164]
#### Brief description of the issue
It seems that if you lose a hand while wielding a fire-axe the axe remains in both hands, despite one of the hands no longer existing.
#### What you expected to happen
The axe would drop or be single-handed after the loss of a hand.
#### What actually happened
The axe remained 2-handed.
#### Steps to reproduce
1. Get axe.
2. Charge Blob.
3. Lose hand.
4. Continue chopping blob with wielded axe.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Datraen** [comment]
#658
