### ISSUE TITLE
All cigarettes re-add as Trans-Stellars

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#1165]
#### Brief description of the issue
Placing cigarette packets in the Cig machine adds to the Trans-Stellar Duty-frees count, rather than the correct item.
#### What you expected to happen
Placing Lucky Stars back into the cig machine would readd Lucky Stars to the count.
#### What actually happened
Trans-Stellars went up to 8+, Lucky Stars stayed at 0.
#### Steps to reproduce
Get cigarettes. Place them back into a cigarette machine.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Datraen** [comment]
I believe I know a way to fix this, but I currently do not have the time to look at it. I'll look at it when I get done with classes for today.

**Comment by Datraen** [comment]
Self reminder: https://github.com/PolarisSS13/Polaris/blob/b7eba8ea6934aa3c1671bfb0867ce3a75dd43d8c/code/game/machinery/vending.dm#L236
