### ISSUE TITLE
Neck Grab Issues

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1178]
#### Brief description of the issue

A neck grab puts the person affected on the ground.
It also seems impossible to resist out of this level of grab.
(I'm on resist ~400)
Edit! Broke out on resist 600ish. I guess it's just a really low chance.
#### What you expected to happen

The neck grabbed person to remain upright, but unable to move.
#### What actually happened

They fall to the floor.
#### Steps to reproduce

Get a neckgrab on someone.
#### Additional info:
- **Server Revision**: Server revision: master - 2016-03-13
  2aa4e7727c70cd03a50443d9e239613cc274447e

**Comment by mwerezak** [comment]
Resisting is handled [here](https://github.com/PolarisSS13/Polaris/blob/master/code/modules/mob/living/living.dm#L641) should you wish to view the break out chances.

**Comment by Atermonera** [comment]
Cannot reproduce: ![image](https://puu.sh/GZRoy/5b698602a8.png)
