### ISSUE TITLE
Northern Star Medicine Closet Access

### ISSUE THREAD

**Issue by Idunfox** [PolarisSS13/Polaris#118]
Chemists on Master were able to access and open regular locked Medicine Closets before, but now they cannot. Not sure if this is a problem with the medicine closet or if the Chemist ID had its access levels changed.

**Comment by Woodratt** [comment]
Don't believe it's a Closet access issue, but rather a issue with the Chemist ID. Could this be looked into?

**Comment by Mark9013100** [comment]
I'll look into this if I get the chance.

**Comment by zaredman** [comment]
Presumed fixed by #100 - Will reopen if it persists.

**Comment by Woodratt** [comment]
Presuming something is fixed is not the same as checking. Was not fixed by that merge. Did some digging in the code and found it was due to a change in the access perms for the vendor from master to Dev on Bay. It'll be fixed on my next merge.
