### ISSUE TITLE
Heads can't change alert level

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#1187]
#### Brief description of the issue
Departmental Heads (ie not HoP/Captain) can't use the command console to change between green and blue alert. Confirmed with CE and HoS, may also affect AI.
#### What you expected to happen
Alert level would change to blue when the button was pressed on the console.
#### What actually happened
Error message came up, saying something about insufficient access; Alert stayed at green
#### Steps to reproduce
Go to the bridge command and communications console as a department head. Log in. Attempt to change the alert level.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Yoshax** [comment]
Not a bug. That was removed along with the ability for anyone to send emergency messages and whatnot, I do believe.
