### ISSUE TITLE
Create Multiple Pills Prompts Three Times

### ISSUE THREAD

**Issue by Idunfox** [PolarisSS13/Polaris#120]
When in chemistry, attempting to create multiple pills will prompt the pill count three times before prompting the name of the pill. Happens with any mixture, continued to happen after relogging.

**Comment by zaredman** [comment]
@Idunfox Is this a Polaris-exclusive bug or on BS12 Dev-Freeze as well?

**Comment by Mark9013100** [comment]
Was able to reproduce on the current dev branch of bay.

**Comment by Mark9013100** [comment]
Still an issue.
