### ISSUE TITLE
Pumpkins and watermelons have the same sprite + pumpkin coloring issue

### ISSUE THREAD

**Issue by Serithi** [PolarisSS13/Polaris#1203]
#### Brief description of the issue

Pumpkins and watermelons use the exact same in-tray and produce sprites, just different colors. Also for that matter, pumpkins are a light green color when i'd imagine they're meant to be yellow, unless it's done that way to counter the sprite's color or something?
#### What you expected to happen

Pumpkins and watermelons have their own in-tray and produce sprites, pumpkins come out yellow.
#### What actually happened

Pumpkins and watermelons have the same in-tray and produce sprites, pumpkins are green.
#### Steps to reproduce

Grow some watermelons and pumpkins. Compare the sprites.
#### Additional info:

This issue's been around for quite a while, even back on Bay, just now i've noticed "wait shit, this is still a thing".

**Comment by Datraen** [comment]
Issue with how Botany was redone.
