### ISSUE TITLE
Cannot shoot at dark tiles.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1208]
#### Brief description of the issue
If a tile has no light at all on it, you cannot click on anything on it.
This includes shooting into darkness.
#### What you expected to happen
Being able to click on a dark tile to shoot into it blind.
#### What actually happened
Nothing.
#### Steps to reproduce
Find a dark area, attempt to fire your gun.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2016-03-17
e8d65eb901ac50a74a585af86ba2b8edf1dc295e 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
This was a problem with cult constructs, as they remove light.
I had a Juggernaut one tile away from me, and could not click on it in any way or blind fire my gun, even through I had flashlight and PDA lights on my person.

**Comment by Kelenius** [comment]
This will require a rewrite of click code, because currently clicks are only handled if you click on something, and you can't click what you can't see. For the game, a click on a dark tile is a click on nullspace.

**Comment by PsiOmegaDelta** [comment]
Both tg and vg have invented click-on-darkness catchers that should be fairly easy to port.

**Comment by Nerezza** [comment]
I really think we should. Currently people with thermal vision can shoot someone down a completely dark maintenance tunnel, and the other person would be unable to shoot back into the darkness.

Another currently legit strategy is to put your flashlight away so you're in complete darkness. Then the person attacking you, if they don't have thermal vision, has to get up close with a light of their own to attack you. Right now it's kind of unfair and all!

Also, just imagine our noir detectives, unable to fulfill what would be an iconic scene in their noir life..
