### ISSUE TITLE
AI doesn't die

### ISSUE THREAD

**Issue by Kelenius** [PolarisSS13/Polaris#1209]
#### Brief description of the issue

AI took 200 brute and 200 burn and didn't die
#### What you expected to happen

AI would die
#### What actually happened

It did not
#### Steps to reproduce

Shoot the AI core, watch as it doesn't die
#### Additional info:
- **Server Revision**: e8d65eb901ac50a74a585af86ba2b8edf1dc295e

**Comment by EmperorJon** [comment]
Could not reproduce. AI was killed at 200 burn from a laser carbine, as expected.
