### ISSUE TITLE
Attack logs - Droppers always report as EMPTY

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1219]
#### What you expected to happen
For the logs to say what chemical was injected from the dropper.
#### What actually happened
The chemical was reported as 'EMPTY.'
#### Steps to reproduce
Get a dropper.
Fill it with a chemical.
Use it on someone.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2016-03-21
996ce92f7ff8bceab4122366ba497b03fd3f3dac 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
Tested with water, and with whatever that eye medicine is.

**Comment by Telvayne** [comment]
This looks like I could fix it pretty easily.  It seems that since it only holds 5u, and deploys that 5u on use, the dropper IS empty when the log is written.  If I just move the logging to occur prior to emptying the dropper, it should fix the problem.

**Comment by Mark9013100** [comment]
Danke, closing.
