### ISSUE TITLE
Teshari Changelings transforming to other species have low blood

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#1224]
#### Brief description of the issue
A Teshari Changeling, when changing to a different species like a Human, doesn't have enough blood and ends up in a low-blood shock-like state.

#### What you expected to happen
When changing they would maintain a proportionate amount of blood.

#### What actually happened
When changing they retain a Teshari quantity of blood, which is too low for a Human.

#### Steps to reproduce
As a Changeling, transform from a Teshari to a species such as Human, Tajaran, Skrell, or Unathi.

#### Additional info:
 - **Server Revision**: 7dfcbcbf3c47187c28edfbf3389ed2454b1126c1

**Comment by Telvayne** [comment]
What happens if you go from human to Teshari?  Do you have 2x the normal blood?

Maybe we could write in a percentage based scaling to blood post-transformation..
