### ISSUE TITLE
Riot Control Maintenance cannot be opened by security

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1232]
#### Brief description of the issue
The maintenance door to riot control cannot be opened by security personnel. In the code, it has the access requirements: 2,12,24
#### What you expected to happen
For the door to open.
#### What actually happened
Access denied.
#### Steps to reproduce
Spawn in as security.
Go to riot control(the room with the N20 controls for communal.
Try to use the maintenance door.
Try not to cry.
Cry.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2016-03-23
a9ad84da4bea4a9ea90030d54c8183b0672be08c 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

Access requirements: 
![](https://i.gyazo.com/9762e5972da6e3385c0148c42badf5cd.png)

The access numbers:

/var/const/access_brig = 2 // Brig timers and permabrig
/datum/access/holding
	id = access_brig
	desc = "Holding Cells"
	region = ACCESS_REGION_SECURITY

/var/const/access_maint_tunnels = 12
/datum/access/maint_tunnels
	id = access_maint_tunnels
	desc = "Maintenance"
	region = ACCESS_REGION_ENGINEERING

/var/const/access_atmospherics = 24
/datum/access/atmospherics
	id = access_atmospherics
	desc = "Atmospherics"
	region = ACCESS_REGION_ENGINEERING

**Comment by Neerti** [comment]
Most likely due to it checking for all of those accesses instead of just one, as ```req_one_access()``` does.  Only the captain has access to the holding cells, maint, and atmos all at once.

**Comment by EmperorJon** [comment]
This has been fixed.
