### ISSUE TITLE
Job slots stay closed upon leaving

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#1250]
#### Brief description of the issue

Leaving as a job doesn't open up the slot normally
#### What you expected to happen

Leaving as a job would open up that jobslot for another player
#### What actually happened

Frequently a sec officer or other semi-important job will leave, and the slot will remain closed
#### Steps to reproduce

Find a round with lots of security officers, wait for them to leave. Try to join as a sec officer.
Not sure it works this way every time.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Yoshax** [comment]
Unable to reproduce on latest revision.

The job slot is opened, but on the join screen it displays as:
Captain (1) (Active: 0)
And you can join.

**Comment by Anewbe** [comment]
It happens sporadically and I'm not totally sure how to reproduce it, but it's still in as of just a few days ago.

**Comment by Arokha** [comment]
```js
	proc/FreeRole(var/rank)	//making additional slot on the fly
		var/datum/job/job = GetJob(rank)
		if(job && job.current_positions >= job.total_positions && job.total_positions != -1)
			job.total_positions++
			return 1
		return 0
```

It does not seem to decrement that first number, for number of people in that job. Instead, it increases the number of slots allowed for that job. Which is ... odd. So, no, it doesn't.
