### ISSUE TITLE
Chameleon Mask shows real name

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1256]
#### Brief description of the issue
The Chameleon gasmask shows a person's real name, regardless of the mask's sprite or if there's an agent ID.
#### What you expected to happen
For only the name on my ID to show.
#### What actually happened
Both my real name and name on the ID showed up.
#### Steps to reproduce
Get a chameleon gas mask.
(Optional) Use an agent ID.
Emote/Speak

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-03-23
a9ad84da4bea4a9ea90030d54c8183b0672be08c 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

Example:
Omega Seven (as Ores Nero) shakes his head.

**Comment by Anewbe** [comment]
I think that may be ghosts/staff only, but I may be wrong.
Or maybe it's just emotes.

**Comment by Datraen** [comment]
It doesn't hide it, Anewbe.

**Comment by Anewbe** [comment]
Then I stand corrected.

**Comment by Magneld** [comment]
Don't ours have to be used in hand to actually activate them?

**Comment by Magneld** [comment]
Issue investigated, not a bug. What you have to do is put it on, rightclick it and ensure its active and then once its on rightclick it once more to set its name and bam it'll work.

**Comment by Kelenius** [comment]
The example provided in the OP is an emote. So I think this is about the cham kit. It's completely possible that cham mask doesn't adopt hiding flags from the mask it copies.

**Comment by Mark9013100** [comment]
>The example provided in the OP is an emote. So I think this is about the cham kit. It's completely possible that cham mask doesn't adopt hiding flags from the mask it copies.
