### ISSUE TITLE
Air alarm frames cannot be built. Existing frames cannot be rotated

### ISSUE THREAD

**Issue by Ithalan** [PolarisSS13/Polaris#1267]
#### Brief description of the issue
Air alarm frames can no longer be built with metal or the new frame parts item. Frames gained from deconstructing an existing alarm cannot be picked up, cannot be rotated and seems to "exist" on the floor tile adjacent to the actual sprite

#### What you expected to happen
To be able to build and precisely place air alarm frames

#### What actually happened
Air alarm frames cannot be built. Placement is limited to what can be accomplished by dragging the frame around and is unlikely to fit nicely over most walls.

#### Steps to reproduce
Open the contruction menu for metal sheet or frame parts. No air alarm option present.
Try to deconstruct existing alarm and then place the resulting frame somewhere else.

#### Additional info:
Server revision: master - 2016-03-27
ddf4cceb963cf24e2f36f502b4c9c3d2eac651d0

**Comment by Neerti** [comment]
@SinTwo
