### ISSUE TITLE
Microwaves are broken

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#1268]
#### Brief description of the issue
Microwaves (and probably) other machines, now, don't work properly 
#### What you expected to happen
Microwaves would show their ingredient contents, not their parts
#### What actually happened
Microwaves show their parts, and their ingredients. Ejecting Ingredients ejects the parts, too. Also pretty sure you can break a microwave by turning it on with only the parts inside.
#### Steps to reproduce
Find a Microwave.
Start pressing buttons.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Mark9013100** [comment]
Someone get the warranty.
