### ISSUE TITLE
Dataspike Doesn't Actually Work

### ISSUE THREAD

**Issue by ParadoxSpace** [PolarisSS13/Polaris#1272]
#### Brief description of the issue

I attempted to use IIS Dataspike on an AI unit. It didn't do anything.
#### What you expected to happen

To kidnap an AI much like I would with an intellicard, as it's supposed to do.
#### What actually happened

Nothing.
#### Steps to reproduce

Get dataspike, click active AI, be severely disappointed.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
  Server revision: master - 2016-03-27
  ddf4cceb963cf24e2f36f502b4c9c3d2eac651d0 
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Don't have any 'data spikes' in code so uh... not a bug?
