### ISSUE TITLE
Repairing internal organs surgery

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1276]
#### Brief description of the issue

When attempting to use a trauma kit on an internal organ during surgery, the step will not complete.

#### What you expected to happen

For the trauma kit to treat the damage.

#### What actually happened

The step wouldn't complete.

#### Steps to reproduce
Get someone with a damaged organ.
Do surgery until the step to use the trauma kit.
Realize it doesn't work.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

Example:
You can't see any useful way to use the advanced trauma kit on Skasar Ssei.
Tested with ten liver damage.

**Comment by RenScorch** [comment]
I personally was unable to recreate this bug, and I tried both lungs, heart, and liver. and in all cases as I was able to repair the organ. Do you have any more details on what was going on just incase this bug only crops up under certain conditions.

**Comment by Mark9013100** [comment]
This has happened to me three times. On two of those occasions, the organs were damaged by radiation, and surgery was not able to patch the damage.
On the last incident, it was a liver damaged via alcohol.

**Comment by Kelenius** [comment]
Liver, you say? Were you operating on the lower body?

**Comment by Mark9013100** [comment]
Oh. That must've been why. :V
