### ISSUE TITLE
Chargers do not charge.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1279]
#### Brief description of the issue
Putting a gun or laptop into a table, or wall recharger updates the sprite to the charging sprite, but does not actually charge the gun.
#### What you expected to happen
The charger to charge the gun.
#### What actually happened
Nothing!
#### Steps to reproduce
Fire gun. Place gun in charger.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2016-03-27
ddf4cceb963cf24e2f36f502b4c9c3d2eac651d0

**Comment by Kelenius** [comment]
Was the power out by any chance? I believe chargers pretend they charge when unpowered.

**Comment by FenodyreeAv** [comment]
All power was on. Depowered chargers reject items being put in them.
