### ISSUE TITLE
Command Laptops

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1286]
#### Brief description of the issue
Attempting to call the shuttle or messaging central command will not work. They fail to do anything. Setting the alert level works fine though.

#### What you expected to happen
To be able to call the shuttle/message central.

#### What actually happened
Nothing happened.

#### Steps to reproduce
1. Get a Captain's level ID.
2. Buy a Laptop.
3. Try to call the shuttle/send message using whatever program the communications thingamajig is.
4. Cry.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-03-27
ddf4cceb963cf24e2f36f502b4c9c3d2eac651d0 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Datraen** [comment]
#598
