### ISSUE TITLE
Pipe Coloring Issue

### ISSUE THREAD

**Issue by Mushkiller** [PolarisSS13/Polaris#1296]
#### Brief description of the issue
Distro/scrubber pipes that are placed in round can't be colored right. Ones that are already mapped in can be colored just fine.

#### What you expected to happen 
Be able to turn a blue distro pipe green.

#### What actually happened 
It turned black.

#### Steps to reproduce 
Grab a UPA and a distro/scrubber pipe, wrench both down. Observe as the color is completely different from what you want it to be.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
master - 2016-03-29
f0813162d8a0ca8750596ad3caee228bcd12fedd 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
Looks like it's taking the color of the pipe then mixing it with the new one that you're trying to turn it to.
![scrnshot1](https://cloud.githubusercontent.com/assets/2555117/14129549/a29c43de-f5c6-11e5-8921-9978a6b7f4ce.png)

**Comment by Atermonera** [comment]
I believe it's due to the pipe painter applying an overlay, but I haven't ever tried recoloring mapped in scrubber/distro pipes. Regular pipes work just fine because the base is a gray pipe, asuming the overlay method.

**Comment by Datraen** [comment]
I have a sneaking suspicion that this is due to the sprites being colored from the start, and BYOND overlaying not liking it.
