### ISSUE TITLE
pAI's can't see LOOC while compacted

### ISSUE THREAD

**Issue by robovelcro** [PolarisSS13/Polaris#1308]
#### Brief description of the issue

Not sure if just generally being compacted, or compacted AND in someone's inventory, but they cannot see or, afaik, speak in the LOOC chat unless they unfold chassis.
#### What you expected to happen

Be able to see LOOC
#### What actually happened

Cannot see LOOC
#### Steps to reproduce

Become pAI
Not hear nearby LOOC
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
  Server revision: master - 2016-03-30
  547b4994da42c827480658b2559d99cb20e3d619 
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)
  I'm pretty sure it used to work, like...1 month+ ago? Guessing at times.

**Comment by Atermonera** [comment]
Cannot reproduce
