### ISSUE TITLE
Stealthsuits cloak still doesn't break on attack

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#1309]
#### Brief description of the issue
Stealthed fights are still a thing, from what I've seen
#### What you expected to happen
Someone would have made it so stealth breaks on attack/shot
#### What actually happened
Shots outta nowhere
#### Steps to reproduce
Get Stealthsuit
Go Invisible
Blam blam
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Neerti** [comment]
Fixed by #1345
