### ISSUE TITLE
Sleep/Unconsciousness doesn't black out screen

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#1325]
#### Brief description of the issue
Falling asleep or losing consciousness doesn't darken the screen
#### What you expected to happen
Being asleep or KO'd would make me essentially blind and deaf
#### What actually happened
Being asleep/KO'd made me lay on the ground, unable to emote, but able to see and hear
#### Steps to reproduce
1. Press Sleep
OR
1. Get knocked out

Note: This is definitely not a parapen, chemical, or other thing.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by EmperorJon** [comment]
I get **...You almost hear someone talking...** but even so, I can see.

**Comment by Anewbe** [comment]
Yeah, can still see, not hear though.

**Comment by EmperorJon** [comment]
99% sure https://github.com/PolarisSS13/Polaris/commit/f2e96014008fd1f9b772b55edc2b4f0802e24968
is the culprit, given it seems to make you not-blind if you still have eyes, and also was committed about 3 days before this bug report.
