### ISSUE TITLE
Bruises/Burns are permanent

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1330]
#### Brief description of the issue

Previously, bruises and other injury flavour text used to go away after a certain period. However, this was changed on Bay.
#### What you expected to happen

For bruises/burns to go away.
#### What actually happened

They don't. Woe to cultists.
#### Steps to reproduce

Get beat/burned.
Examine self.
Examine self 30 minutes later.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

I'm well aware this is intentional, but it'd be nice to have bruises/burns go away after a certain period.

**Comment by Nerezza** [comment]
After an hour into the round, 98% of the crew have a bruise on the upper body. Truefact

**Comment by Anewbe** [comment]
If this gets changed, can we get it so fully repaired FBPs lose the "It has a  on its upper body" thing, too?

**Comment by Anewbe** [comment]
Think this has been changed.

**Comment by Arokha** [comment]
I know I fixed the permanent wounds on FBPs already. It's probably been changed for others too.
