### ISSUE TITLE
Windoors can not be dismantled

### ISSUE THREAD

**Issue by Nerezza** [PolarisSS13/Polaris#1333]
#### Brief description of the issue
For the longest time now, we've not been able to dismantle a fully constructed windoor. The only way to remove one is to smash it to pieces.
#### What you expected to happen
There should be steps to dismanlte windoors
#### What actually happened
There are no steps to do so, or they are currently bugged
#### Steps to reproduce
1) Find Windoor
2) Try anything on it
#### Additional info:
 - **Server Revision**: e939e2dd98b7df0923c629093e781a4fa00d37e2 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

There hasn't been a way to do this for as far as I can remember. Since the final step for constructing one is to pry it into its frame with a crowbar, I imagine a good first step for dismantling would be to open the windoor and pry it out of its frame with a crowbar.

On top of this issue, we also can not rename windoors with pens like we can airlocks, so they're stuck as 'interior door' or 'secure door' if made mid-round.

**Comment by Ithalan** [comment]
While we're at it, the ability to name windoors like we can name airlocks during the construction would be nice to have too.

**Comment by Nerezza** [comment]
That's actually in my OP ;P

**Comment by Ithalan** [comment]
Lies! I didn't see it so it can't be true :P
