### ISSUE TITLE
Missing progress bar during plast-reinforced-wall deconstruction

### ISSUE THREAD

**Issue by Nerezza** [PolarisSS13/Polaris#1352]
#### Brief description of the issue
During deconstruction of plasteel reinforced walls, the final step (intermediary of the entire process?) of prying the plasteel off and revealing the reinforced girder below does not get a progress bar.
#### What you expected to happen
I expect a progress bar for the step, it is particularly long for a deconstruction step.
#### What actually happened
There isn't one!
#### Steps to reproduce
With a plasteel reinforced wall, do:
 Wirecutters.
 Screwdriver.
 Welder.
 Crowbar.
 Wrench.
 Welder.
 Crowbar.
And observe the lack of progress bar while you pry the plasteel off the girder in that last step.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Yoshax** [comment]
Because it's not a do_after()
Doesn't get a progress bar unless it is.
