### ISSUE TITLE
Chameleon Projector disappears on down

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#1370]
#### Brief description of the issue

Apparently the traitor Cham Projector disappears when you lie down?
#### What you expected to happen

Cham projector would stick around even if you're downed.
#### What actually happened

Poof, gone, according to the player.
#### Steps to reproduce
1. Get a cham projector
2. Use it, maybe?
3. Get downed
   #### Additional info:
   - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
   - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Haven't used it personally, so I may be wrong, but if you have to hold it in a hand to use it, then you're probably lying on top of it when you lie down, since you drop held items.

**Comment by Anewbe** [comment]
I think it actually deletes, I wasn't the one using at the time but I was told to report it.
