### ISSUE TITLE
Spawned Cream Cheese Bread slive vanishes

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#1371]
#### Brief description of the issue
Cream cheese bread slides spawned via admins commands, or at startup, or otherwise. E.g. lunchboxes, vanish when you try to eat them. And displays the: "None of Cream Cheese Bread slice left!" message.
#### What you expected to happen
To eat the delicious bread.
#### What actually happened
It vanished.
#### Steps to reproduce
Spawn cream cheese bread slice, try to eat.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Datraen** [comment]
Working on a quick fix.
