### ISSUE TITLE
Rapid Part Exchange Device Doesn't Work

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#1379]
#### Brief description of the issue
When trying to replace the parts of a machine, it doesn't work.

#### What you expected to happen
The upgraded parts to replace the default ones.

#### What actually happened
You hit the machine.

#### Steps to reproduce
1.) Stock device
2.) Open machine panel
3.) Hit with exchange device

#### Additional info:
 - **Server Revision**: master - 2016-04-07
 - Protolathes are bugged by themselves from being deconstructed.
 - This most likely has to do with the addition of Sin's machinery update.

**Comment by SinTwo** [comment]
#1517 Fixed.
