### ISSUE TITLE
Upgrading Machinery Doesn't Improve Quality

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#1380]
#### Brief description of the issue
Upgrading a machinery with improved parts doesn't increase efficiency

#### What you expected to happen
Efficiency to be increased in the machine.

#### What actually happened
Efficiency was not increased

#### Steps to reproduce
1.) Remove components (because of #1379 )
2.) Insert the upgraded components in its place
3.) Screwdriver the machine to complete it
4.) Notice the values are all the same.

#### Additional info:
 - **Server Revision**: master - 2016-04-07
 - Again, probably an issue resulting from Sin's machinery update

**Comment by Kelenius** [comment]
AFAIK this predares machine update and it DOES increase efficiency - it just doesn't show it in the menu.

**Comment by SinTwo** [comment]
#1517 Fixed.
