### ISSUE TITLE
Engineering Camera Monitor

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#139]
![](http://i.imgur.com/rFB97EM.png)

Not an issue on Bay's current dev branch.

**Comment by Woodratt** [comment]
Could not reproduce? Doesn't seem to be a issue right now.

**Comment by Neerti** [comment]
It's possible it was just NanoUI being NanoUI and fucking up FNR.

**Comment by Mark9013100** [comment]
Haven't heard anything about this issue in awhile, closing.
