### ISSUE TITLE
Non-existent Lunchbox Food

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#1391]
#### Brief description of the issue
Food in the lunchbox doesn't seem to actually exist?

#### What you expected to happen
Eat the food!

#### What actually happened
"None of x left!" *disappears*

#### Steps to reproduce
Get lunchbox. Customise contents. Stick a vegetable pizza slice and a cheesecake slice in there, to reproduce my exact food selection.
Try to eat it. (For me this was about 2:30 into the round)
Get told that the slice doesn't actually have any bites remaining. Starve. :(

#### Additional info:
 - **Server Revision**: d9dd1221fc006ab95b822f44fa20eda4347ff0f0 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by PsiOmegaDelta** [comment]
Schrödinger's pizza slice?

**Comment by Yoshax** [comment]
https://github.com/PolarisSS13/Polaris/commit/dab56d472b2cd1b82ce08cc1eb89664199bbcf10

Already fixed, server needs upated

**Comment by EmperorJon** [comment]
Excellente!
