### ISSUE TITLE
You can still lock down traitorsynths

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#1401]
#### Brief description of the issue
An AI successfully locked down a Traitor stationbound.
This is still happening. **Again**. Agaegrrrr.

#### What you expected to happen
Nothing.

#### What actually happened
Locked successfully.

#### Steps to reproduce
Yeah yeah

#### Additional info:
 - **Server Revision**: master - 2016-04-07 d9dd1221fc006ab95b822f44fa20eda4347ff0f0 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Datraen** [comment]
#1245
