### ISSUE TITLE
Traitor datum problems?

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#1404]
Traitor and Autotraitor are two different antag types. 

`/datum/antagonist/traitor`
and
`/datum/antagonist/traitor/auto`
but the traitors datum is
`var/datum/antagonist/traitor/traitors`

They both have the same "special_role" flag ("Traitor"), and two copies show up in the traitor panel as "Traitor" (the one right at the bottom of the list is actually Autotraitor). If you were to assign both (somehow) then remove one, it would think they were still the other, but they'd have no special role.

This raises a point. There may be other checks in the code somewhere for if someone is a traitor that won't be flagged for Autotraitors. A traitors.is_antagonist() check would not return true for an Autotraitor. This probably needs investigating at some point?

**Comment by Datraen** [comment]
This'll mostly be important for other auto'd antagonists, as there aren't any is_antagonist() checks that I found involving traitors. This'll probably be something that we might want to look into for tying certain checks together.
