### ISSUE TITLE
FBP perma slowdown when injured

### ISSUE THREAD

**Issue by Verarch** [PolarisSS13/Polaris#1405]
#### Brief description of the issue

When you're a FBP and get super injured, then repaired, you still have a significant slowdown as if you're injured.
#### What you expected to happen

To move at normal speed when healed on run.
#### What actually happened

Moving at walking speed when healed fully on run.
#### Steps to reproduce

Beat yourself up severely as FBP
Get repaired
Try and run around the station.
#### Additional info:
- **Server Revision**: master - 2016-04-11
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)
  (no)

**Comment by Anewbe** [comment]
Did you try going into a recharger, and are you entirely certain you were fully repaired?
I've never had this bug, personally, is why I ask.

**Comment by Verarch** [comment]
Fully charged, was scanned several times and double checked everything. Still moved slow.

**Comment by Verarch** [comment]
also, I think this will probably only happen if severe damage happens to the legs. I'll update on that as soon as I can.

**Comment by MagmaRam** [comment]
This doesn't appear to be a problem at this point. The only way I can see FBPs gaining slowdown from injuries is by health deficiency (which is when head and chest are injured for FBP) or by stance damage (which comes from leg and foot damage). Both of those seem to heal properly from repairs.

Plus, the other day I was injured quite badly 2 or 3 times in one round and had no slowdown issues once repaired.

I've been wrong before, but I'm not certain this is still an issue.
