### ISSUE TITLE
Handcuffs can't be resisted out of

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1408]
#### Brief description of the issue:

Handcuffs will not fall off after the 2 minute mark.
#### What you expected to happen:

For the cuffs to pop off.
#### What actually happened:

They didn't come off.
#### Steps to reproduce:

1. Get cuffed.
2. Resist.
3. Wait.
4. Cry.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-04-11
a88dd1f961e7031847f8f2ddd26fb4ca13a7d7fb 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Datraen** [comment]
Should be resolved after an update, #1407

**Comment by Mark9013100** [comment]
In that case, closing.
