### ISSUE TITLE
Camera networks are finnicky

### ISSUE THREAD

**Issue by Kelenius** [PolarisSS13/Polaris#1409]
"Cafe dock", "Civilian East", "Civilian West" contain no cameras.
"MINE" should be renamed to something better.

**Comment by Kelenius** [comment]
Oh, and also "Northern Star" is listed twice.

**Comment by Ithalan** [comment]
The AI (and camera console hackers) also have access to the "Crescent" network which contain a few cameras scattered haphazardly across CentComm
