### ISSUE TITLE
Teshari Smocks turning into Aqua jumpsuits

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#1411]
#### Brief description of the issue
Whenever a Teshari spawns with their species smock
#### What you expected to happen
To spawn with a smock for my raptor
#### What actually happened
It spawned me in, said it was equiping me with it, but then turned into a aqua jumpsuit
#### Steps to reproduce
Spawn as a Teshari with any of the smocks.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Nerezza** [comment]
Can confirm, my raptor is now 50% less stylish.
