### ISSUE TITLE
Magic missile is useless

### ISSUE THREAD

**Issue by Kelenius** [PolarisSS13/Polaris#1435]
#### Brief description of the issue
MM is very slow and disappears when it hits a solid object
#### What you expected to happen
For it to not disappear like that, it's supposed to be homing
#### What actually happened
It did
#### Steps to reproduce
Duh
#### Additional info:
 - **Server Revision**: latest
 - **Anything else you may wish to add**: It's basically useless now unless you cast it point-blank, because anyone with half a brain cell will step away

**Comment by Anewbe** [comment]
No longer relevant
