### ISSUE TITLE
Skrell and the Teshari language

### ISSUE THREAD

**Issue by AliciaJewel** [PolarisSS13/Polaris#1437]
#### Brief description of the issue
Skrell can select Teshari as a language in character setup but cannot speak or understand it, nor does it appear when you select "Check Known Languages."

#### What you expected to happen
I expected to be able to speak and understand Teshari and see it in my language list.

#### What actually happened
I was not able to speak or understand Teshari, nor did it appear in my language list.

#### Steps to reproduce
1. Make a Skrell.
2. Make one of its alternative languages Teshari.
3. Join a round.
4. Check your language list to see that the language is not present. Alternatively, attempt to understand the Teshari language and fail.

#### Additional info:
 - **Server Revision**: Server revision: master - 2016-04-16 ff6526d5a30083b5fc933c8cfa200e4aa646a915
 - **Anything else you may wish to add**: N/A

**Comment by AliciaJewel** [comment]
Think I found the problem: "Teshari" isn't an actual language. The Teshari language is Schechi.

**Comment by Nerezza** [comment]
Git scares me so I'll just post the solution:

Polaris/code/modules/mob/living/carbon/human/species/station/station.dm line 152:

secondary_langs = list("Skrellian", "Teshari") should be:
secondary_langs = list("Skrellian", "Schechi")

Also someone ask Khold if max age for tesh should be 45? The wiki says they're not 'old' until 55, life expectancy being 65. ;>
