### ISSUE TITLE
Walking into something when confused produces no message to yourself

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#1444]
#### Brief description of the issue
Walking into something when confused gives you no indication you've walked into something.
#### What you expected to happen
To get a message because it damages you.
#### What actually happened
No message was shown.
#### Steps to reproduce
Get confused, try to walk and bump into something.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.https://github.com/PolarisSS13/Polaris/commit/ff6526d5a30083b5fc933c8cfa200e4aa646a915
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by EmperorJon** [comment]
Definitely can be rather annoying that you're not even aware you're smashing into stuff horrifically injuring yourself.
