### ISSUE TITLE
Ghosts can attach and detach IV drips.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1449]
#### Brief description of the issue
Ghosts can click-drag to attach and detach IVs from people.
#### What you expected to happen
Ghosts to not have magic telekinetic powers.
#### What actually happened
Spooky self detatching IV drips.
#### Steps to reproduce
Be a ghost, upset a surgeon treating IB.
#### Additional info:
 - **Server Revision**:
Server revision: master - 2016-04-19
28ab131610b5e7e98a2b847af76292b4a30880c7

**Comment by EmperorJon** [comment]
I remember this being an old one back on Bay, but I believe it was fixed. Must have slipped back in again.

**Comment by Nerezza** [comment]
I'm looking at it but I can't tell if they can really be attached by ghosts. I can see them being detached though:

`
/obj/machinery/iv_drip/MouseDrop(over_object, src_location, over_location)
	..()

	if(attached)
		visible_message("[src.attached] is detached from \the [src]")
		src.attached = null
		src.update_icon()
		return

	if(in_range(src, usr) && ishuman(over_object) && get_dist(over_object, src) <= 1)
		visible_message("[usr] attaches \the [src] to \the [over_object].")
		src.attached = over_object
		src.update_icon()`

**Comment by Kelenius** [comment]
``MouseDrop`` is a byond proc, it doesn't do checks.
