### ISSUE TITLE
First-aid kit storage is inconsistent

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1458]
#### Brief description of the issue:
Each first-aid kit has it's own storage capacity, as opposed to when they all had the same storage. IE, the advanced first-aid kit can hold much more than the other medkits.

#### What you expected to happen:
For each kit to have the same storage capacity.

#### What actually happened:
They were all unique in capacity.

#### Steps to reproduce:
1. Open a advanced first-aid kit.
2. Open a toxins first-aid kit.
3. Open a fire first-aid kit.
4. Open a oxygen deprivation first-aid kit.
5. Open a combat first-aid kit.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-04-20
a1faf6e497a3d96bb9a33929634dac469050f9f9 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

By using custom loadout items as a medical doctor, you can extend the max capacity of the standard issue advanced first-aid kit you spawn with.

**Comment by Nerezza** [comment]
They seem to define their storage capacity by how much space is needed to hold what they spawn with or something.
