### ISSUE TITLE
Upgraded fireball has low/no cooldown

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1460]
#### Brief description of the issue:
The fireball spell can be upgraded to have a very minimal cooldown, which has VERY devastating effects.

#### What you expected to happen:
For fireball to not be upgradeable/have a decent-ish cooldown.

#### What actually happened:
The Fireball spell can be upgraded to have a very tiny cooldown.

#### Steps to reproduce:
1. Be Wizard.
2. Get the fireball spell and upgrade it.
3. Spam it.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-04-20
a1faf6e497a3d96bb9a33929634dac469050f9f9 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Yoshax** [comment]
That's a feature. If you spend all your points/majority of them into one spell it becomes pretty damn strong but then you've got nothing else.

**Comment by Mark9013100** [comment]
I'm aware it's intended, but I believe it was unwanted on Bay, and I'm highly sure it's unwanted here as well.

**Comment by Nerezza** [comment]
This issue was opened immediately after we got to see the effects fireball spam produces. In particular, the spam happened on a visitors round and the poor ninja couldn't do much when the wizard pegged him with 3 fireballs in quick succession.

**Comment by Anewbe** [comment]
No longer relevant
