### ISSUE TITLE
Renegades start with weapon in hand

### ISSUE THREAD

**Issue by silveryferret** [PolarisSS13/Polaris#1473]
#### Brief description of the issue
Not really a bug or anything, I guess. It just seems kinda like a bit of an oversight... like, if you spawn in right next to someone and the first thing you have to do is stuff your gun into your bag and... yeah.
#### What you expected to happen
I don't know what I expected, it was my first time being a renegade!
#### What actually happened
started with gun in hand
#### Steps to reproduce
be renegade
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by mwerezak** [comment]
That is absolutely hilarious.
