### ISSUE TITLE
Brain damage prevents hemostat removal usage

### ISSUE THREAD

**Issue by Nerezza** [PolarisSS13/Polaris#1475]
#### Brief description of the issue
A tator had a change of heart and decided to turn herself in, and eventually admitted to having an explosive implant in her chest that needed to be extracted. After 15-20 minutes-ish in surgery of the surgeon trying and retrying to remove the implant, the hemostat refused to work giving off this message: "You can't see any useful way to use [tool] on [M]." (with relevant stuff put in)
 
#### What you expected to happen
Using hemostat on the opened chest should have given "You start poking around inside [target]'s [affected.name] with \the [tool]" followed by 40% chance of removal of the illegal implant.

#### What actually happened
The wrong message was given and the implant had to be removed via admin magic in the end.

#### Steps to reproduce
Too much surgery to list.

#### Additional info:
 - **Server Revision**: 134157feb579191f6429c479cb61572b67261971 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

Looking through the code, the message the surgeon was receiving happens if surgery code can't find a valid use for the tool he's using. He'd just used the same hemostat to remove the detective's appendix, and iirc he had to pull bullets out of someone's head prior to that. It's just that one surgery step he couldn't perform.

After looking at the surgery code until I felt insignificant and began to contemplate my life choices, I think I've narrowed down the issue to the can_use procs inside code\modules\surgery\implant.dm but that's as narrowed down as I could get it. In particular, its method of handling affected.open for encased body areas (skull and ribcage) aren't shared by other steps for the head and chest.

**Comment by EmperorJon** [comment]
Brain damage prevents the usage of the hemostat in the upper body for removal.
(wtf?)
