### ISSUE TITLE
Transforming Lings don't change name correctly

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#1485]
#### Brief description of the issue

When transforming, a changeling didn't correctly change their name to their new form.
I think "real_name" was changing but "name" was not.
The changeling had died and revived earlier.
#### What you expected to happen

Their name should update.
#### What actually happened

Their name remained for their previous form.
#### Steps to reproduce

**DIE AND REVIVE AS A CHANGELING.**
Change to a new form as a changeling.
#### Additional info:
- **Server Revision**: master - 2016-04-22
  134157feb579191f6429c479cb61572b67261971 
- **Anything else you may wish to add** 
  *_I suspect this is related to similar bugs where lings behave oddly after death+revival.
  *_

**Comment by Kelenius** [comment]
The ling also was showing up as if they had an alien larva on medhuds and couldn't get up if dropped until shaken. This only happened to that specific ling, other two had no such problems.

**Comment by Datraen** [comment]
Which was entirely strange that it had the alien larve on the medhud, as I checked and there was no way it should've occurred at all.

**Comment by EmperorJon** [comment]
I've seen it occur, but only after reviving. An odd one, this.

**Comment by SilverTalismen** [comment]
As the ling in question (Character originally as Ying Lihwa), I had died earlier in the shift to slimes and revived and died twice more trying to escape them before I did, And later on when I transformed into Klaus Gellar, it still said I was Ying Lihwa and I had to have a admin change my name twice for me to be Klaus and for me to go back to being Ying, And yes being downed did not let me get back up again until I was shaken.
