### ISSUE TITLE
HoS trenchcoat does not cover the lower body.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1487]
#### Brief description of the issue
The HoS trenchcoat does not cover the lower body in the way most armour does.
#### What you expected to happen
The coat to cover the upper body, lower body, and arms and legs, same as the other coat.
#### What actually happened
Only the upper body and arms are covered.
#### Steps to reproduce
Wear the HoS trenchcoat, and examine it.
#### Additional info:
 - **Server Revision**:

Server revision: master - 2016-04-22
134157feb579191f6429c479cb61572b67261971

**Comment by Anewbe** [comment]
The armored trenchcoat does not in fact cover the lower body and legs, the regular armored coat does. Might be an oversight.
