### ISSUE TITLE
Tanks attached to voidsuits break horribly when the voidsuit is taken off.

### ISSUE THREAD

**Issue by Spookerton** [PolarisSS13/Polaris#1492]
When a voidsuit with an attached tank is worn, the tank is placed into suit storage as expected.

When the suit is removed, the tank *remains* in suit storage, as well as in the suit's contents.

The tank can be removed by hand, and has odd contents list problems since it is two places at once. 

Suit internals can no longer be turned on until the tank is removed with a screwdriver and reattached.

**Comment by mwerezak** [comment]
It doesn't call removeItem().
