### ISSUE TITLE
Departmental ponchos defaulting to blue poncho

### ISSUE THREAD

**Issue by Verarch** [PolarisSS13/Polaris#1499]
#### Brief description of the issue
Spawning with a department poncho in your loadout will make it a blue poncho upon entering the game.
#### What you expected to happen
To get a security departmental poncho.
#### What actually happened
I got a blue normal poncho.
#### Steps to reproduce
1. Set loadout to spawn with any department poncho (preferably your department)
2. Enter game
3. Look at blue poncho.
#### Additional info:
 - **Server Revision**: master - 2016-04-26
 - **Anything else you may wish to add** (shrug)

**Comment by Datraen** [comment]
Oh, I know what causes this. Give me a little bit.
