### ISSUE TITLE
Arrivals port APC has a cut wire leading up to it at roundstart.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#150]
![image](https://cloud.githubusercontent.com/assets/8376059/9225126/50629a9a-40ff-11e5-9708-05ed83baa2b4.png)

![image](https://cloud.githubusercontent.com/assets/8376059/9225139/6e7b2786-40ff-11e5-8dea-80e83d7773f2.png)

**Comment by Woodratt** [comment]
https://github.com/PolarisSS13/Polaris/issues/149
