### ISSUE TITLE
Borg Grippers remain largely non-functional.

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#1512]
#### Brief description of the issue

Cyborg grippers broke from their full functionality some time ago. Clerical borgs used to be able to use an ID machine with no issue, Research borgs could fill lathes, Service borgs could place things into grinders.
#### What you expected to happen

Grippers to function fully, and allow the borgs they are mounted to to do their full jobs.
#### What actually happened

Grippers do not function entirely. Research borgs can't fill printers with chems, or lathes with material. Service and Research borgs can't fill grinders, Clerical borgs can't use ID machines fully anymore.
#### Steps to reproduce

Be a borg with a gripper, try doing any of the logical things you expect to be able to do with it.
#### Additional info:
- **Server Revision**: Originates from early public launch.
- **Anything else you may wish to add** See issue #349. Refresh/Re-notification of the bug.

**Comment by Datraen** [comment]
I believe this bug is inherited from Bay. Is it an issue on their codebase?

**Comment by Mechoid** [comment]
The issues cropped up separately on Bay, though seem to have been inherited all at once quite a while ago, yes.

**Comment by Atermonera** [comment]
Unable to test clerical borgs at the moment, but filling printers with chemicals was resolved when research borgs got beakers. Grinders cannot be accessed by borgs.

**Comment by Anewbe** [comment]
Bay has a fix for the grinders issue.

**Comment by Atermonera** [comment]
Clerical borgs are working, this is all cleaned up
