### ISSUE TITLE
Literally All The Issues With Robots Serving Drinks

### ISSUE THREAD

**Issue by ParadoxSpace** [PolarisSS13/Polaris#1522]
The robotic service grabber is borked as all hell, featuring drinks occasionally entirely disappearing when you pick up other drinks, drinks still being in the grabber despite being gone, and general weirdness.

**Comment by Anewbe** [comment]
There are problems with borg grippers in general, check #1512 . Also sticking to the given format for bug reports is super helpful, as is specificity.
