### ISSUE TITLE
Language Runtime

### ISSUE THREAD

**Issue by Neerti** [PolarisSS13/Polaris#1531]
#### Brief description of the issue

It appears that starting your sentence with certain characters (dash and period observed to cause these runtimes so far, possibly more) will make `parse_language` think that your sentence is a language, and as a result it causes a null language to get passed to `can_speak()`
#### What you expected to happen

For the dashes and other weirdness to not pass the checks in `parse_language`.
#### What actually happened

```
runtime error: Cannot execute null.can speak special().
proc name: can speak (/mob/proc/can_speak)
  source file: language.dm,161
  usr: (src)
  src: Tori Prescott (/mob/living/carbon/human)
  src.loc: the floor (186,143,1) (/turf/simulated/floor/tiled/white)
  call stack:
Tori Prescott (/mob/living/carbon/human): can speak(null)
Tori Prescott (/mob/living/carbon/human): parse language("--Yes?")
Tori Prescott (/mob/living/carbon/human): say("--Yes?", null, "says", "")
Tori Prescott (/mob/living/carbon/human): say(":c --Yes?")
Tori Prescott (/mob/living/carbon/human): Say(":c --Yes?")
```
#### Steps to reproduce

Start your sentence with a '-', or '.'.  Might need to be using a language while doing this as well, not too sure.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-05-01
ac74e6af0971d3579df13aa2443a04c172198af5 
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)
#1530 will probably stop the runtime, however the cause will still likely exist.

**Comment by Datraen** [comment]
Caught by #1530 as it currently stands.

**Comment by Datraen** [comment]
Low priority because it's currently being caught, actual handling of this is not occurring.
