### ISSUE TITLE
Autotraitors cannot Set-Ambition if they are not roundstart traitors

### ISSUE THREAD

**Issue by Dibasic** [PolarisSS13/Polaris#1534]
#### Brief description of the issue

n/t
#### What you expected to happen

be able to set ambition
#### What actually happened

While you may perhaps have goals, this verb's meant to only be visible to antagonists.  Please make a bug report!
#### Steps to reproduce

be autotraitor
Set-Ambition
#### Additional info:
- **Server Revision**: master - 2016-05-02
  c9c7cb588f8c86e9be54e91f72320796df3e1dc5

**Comment by Atermonera** [comment]
Haven't observed this recently, autotraitors traitored mid-round have definitely been able to set ambitions. Should be closeable
