### ISSUE TITLE
Renegade AIs

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#1549]
#### Brief description of the issue
AIs can be renegades. This is probably a bad.

#### What you expected to happen
No renegAIds.

#### What actually happened
RenegAIds.

#### Steps to reproduce
Be AI. Get your renegade on.

#### Additional info:
 - **Server Revision**: master - 2016-05-02
a2e40b53545050f2862abaa225c396aa61f42ae9 
 - **Anything else you may wish to add** Use this opportunity to remove renegade synths then separate renegade from traitor.

**Comment by Zuhayr** [comment]
Why is this bad?

**Comment by EmperorJon** [comment]
With humanoids it generally seems to be pretty clear that they've been given a gun to use to defend themselves. An AI, on the other hand, is practically everywhere and anywhere and already has laws which require it to protect the station and crew.

From the perspective of the staff, the manner in which these combine can lead to AIs justifying killing anyone who seems to be an antagonist, as opposed to protecting themselves and what is important to them defensively - something which is already covered by their lawset.
