### ISSUE TITLE
Ejecting a sleeper ejects its parts

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#1558]
#### Brief description of the issue
Ejecting a sleeper ejects it's parts
#### What you expected to happen
To not have the parts ejected
#### What actually happened
The parts were ejected
#### Steps to reproduce
Put someone in a sleeper, pretty eject occupant.

**Comment by SinTwo** [comment]
#1562 Fixed.

**Comment by Yoshax** [comment]
The PR hasn't been merged. Reference the issue in your PR and the issue's will auto-close upon merge.
