### ISSUE TITLE
Putting someone into a bodyscanner spits out all its parts

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#1559]
#### Brief description of the issue
Putting someone into a bodyscanner spits out all its parts
#### What you expected to happen
For the parts not to be spit out
#### What actually happened
The person got put into the scanner and all the parts were vomited out
#### Steps to reproduce
Grab someone, click the body scanner.

**Comment by SinTwo** [comment]
#1562 Fixed.
