### ISSUE TITLE
Taping over eyes doesn't blind + initial tape doesn't appear

### ISSUE THREAD

**Issue by Verarch** [PolarisSS13/Polaris#1563]
#### Brief description of the issue
Put tape over eyes and mouth for no reason, and had to remove and readd to get sprite to show, + blindfold doesn't blind
#### What you expected to happen
For blindfold to limit view somewhat and to appear on first applicatoin
#### What actually happened
It didn't do jack shit and had to remove to make it appear.
#### Steps to reproduce
1. Tape up eyse
2. Notice you aren't blind
3. Notice sprite is invisible on mob
#### Additional info:
 - **Server Revision**: master - 2016-05-06
 - **Anything else you may wish to add** no

**Comment by Yoshax** [comment]
Duplicate #1413.

**Comment by Datraen** [comment]
Partial duplicate, points out another bug.
I'll allow it.
