### ISSUE TITLE
Airlock electronics removal messages are incorrect

### ISSUE THREAD

**Issue by Kelenius** [PolarisSS13/Polaris#1573]
#### Brief description of the issue
When someone starts removing the electronics, a message "Urist McEngineer removes the electronics from the airlock assembly" appears when they only start removing it.
#### What you expected to happen
Engineer would get a message about starting to remove the board. This message would only appear when the removal is finished.
#### What actually happened
Duh
#### Steps to reproduce
Duh
#### Additional info:
 - **Server Revision**: what serber is running ATM
 - **Anything else you may wish to add** Also works on removing charred electronics and installing it.

**Comment by SinTwo** [comment]
Seems to have been fixed.
