### ISSUE TITLE
Cultist Robes Are Invisible.

### ISSUE THREAD

**Issue by ParadoxSpace** [PolarisSS13/Polaris#1580]
#### Brief description of the issue
what it says on the tin, the boots and hood spawn just fine, but the chest robes are invisible, leaving you naked
#### What you expected to happen
get robes on my chest slot, not be naked
#### What actually happened
emperor, we have some new clothes for you
#### Steps to reproduce
use armor rune, cry when your nudity is revealed to the world
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Searif** [comment]
It seemed to be something limited to you, I certainly saw it happen(I was wondering why there was a naked cultist), but I also saw other characters(Ikya Railey specifically) use the same rune to get the outfit and all, and the sprites all worked just fine.

**Comment by Mark9013100** [comment]
This appears to happen to all manifests.

**Comment by Minijar** [comment]
Can confirm happened to myself as a manifest.
