### ISSUE TITLE
Using 'Show list' from 'Master' on Power Monitoring Console crashes Dream Seeker

### ISSUE THREAD

**Issue by Noreaus** [PolarisSS13/Polaris#1582]
#### Brief description of issue

Using 'Show list' from 'Master' on Power Monitoring Console crashes Dream Seeker
#### What you expected to happen

Something that isn't crashing.
#### What actually happened

Dream Seeker will freeze, crash, and require rebooting
#### Steps to reproduce
1. 'Scan for devices' on Power Monitoring Console in engine monitoring room
2. Open up the menu 'Master' 
3. Click 'Show list'
4. Observe crash
5. When Dream Seeker is re-opened, clicking on the Monitoring Console again will cause another crash
#### Additional info:
- **Server Revision**: Server revision: master - 2016-05-06
  27b3df62b508f08008e5f41ff17bf0b49d2ac0ec c)

**Comment by Anewbe** [comment]
Pretty sure this is a client-side issue.
