### ISSUE TITLE
Missing wire in map - Science Auxiliary

### ISSUE THREAD

**Issue by Noreaus** [PolarisSS13/Polaris#1583]
#### Brief description of the issue
There is a mapping error - A missing wire. This causes an APC to drain.

#### Steps to reproduce
Head to science auxiliary - The missing wire is just below it. See the screenshot below.

#### Additional info:

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
![missingwire](https://cloud.githubusercontent.com/assets/5178371/15092000/5ab54410-1454-11e6-9bc9-018a77c37dc2.PNG)

**Comment by Yoshax** [comment]
Already fixed.

**Comment by Yoshax** [comment]
Fixed by #1574
