### ISSUE TITLE
Clerical/Service Borgs cannot speak the vocal version of the Taj. Language.

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#1601]
#### Brief description of the issue
Clerical Borgs and Service Borgs do not have the ability to speak the vocal form of the Tajaran language.
#### What you expected to happen
Clerical/Service borgs to be able to speak the vocal Tajaran language like the other species' languages.
#### What actually happened
The two modules cannot.
#### Steps to reproduce
Be a clerical or service borg, note you cannot speak meow.
#### Additional info:
 - **Server Revision**: 454cc25cba9d3de5a0a99b7e5586ed34790d4aed 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc):

**Comment by zekesulastin** [comment]
There should only be one cat language ingame, actually.  The split's still left over in the module code?

**Comment by Anewbe** [comment]
Apparently it's tied up in a gorillion different things, but this itself shouldn't be too difficult to fix.

**Comment by Anewbe** [comment]
Issue can be closed, methinks

**Comment by Anewbe** [comment]
Issue can be closed, methinks.

**Comment by Mechoid** [comment]
Woop, notification didn't pop up
