### ISSUE TITLE
Cyborg Recharger deconstruction bug

### ISSUE THREAD

**Issue by Edwardc120** [PolarisSS13/Polaris#1606]
#### Additional info:
 was told it was a mapping bug that the chargers wouldn't recharge

**Comment by Nalarac** [comment]
Exosuit Fabricators seems to have this same problem along with being unable to be upgraded with the Rapid Part Exchange device.

**Comment by SinTwo** [comment]
Will test Exosuit Fabricators but I could not reproduce this with Cyborg Rechargers.

**Comment by SinTwo** [comment]
Seems only Exosuit Fabricators have this problem. Problem has been solved, just need to clear somethings first.
