### ISSUE TITLE
Unable to see which character loadout sections you have spent points in.

### ISSUE THREAD

**Issue by TableTurning** [PolarisSS13/Polaris#1617]
#### Brief description of the issue
With the new update to the character setup UI, you are unable to see which categories you have spent points in on the loadout screen.  They used to have special colors to differentiate between categories you have spent in versus ones where you haven't spent any.
#### What you expected to happen
I expected there to be a difference between the headers for categories you have spent points in vs which ones you haven't.
#### What actually happened
There is no difference in the headers.
#### Steps to reproduce
1. Go to character loadout
2. Add an item to your loadout
3. Notice that there is no difference in the category headers.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2016-05-11
74f556c46a423eea3b92e165b4bae0f063c61c78 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Yoshax** [comment]
Fixed by #1630
