### ISSUE TITLE
Prometheans don't crackle with electricity

### ISSUE THREAD

**Issue by ParadoxSpace** [PolarisSS13/Polaris#1619]
#### Brief description of the issue

i'm pretty sure they're supposed to upon being shocked?
#### What you expected to happen

pretend i'm thor, get literally any message from being shocked
#### What actually happened

not a damn thing
#### Steps to reproduce

be slimekid, shock yourself, feel nothing
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Zuhayr** [comment]
Shock doesn't accumulate because of unimplemented functionality with Siemen's coefficient, I said this in the PR.

**Comment by Anewbe** [comment]
Not a bug.
