### ISSUE TITLE
Adv. Trauma kits/Burn kits don't close bleeding wounds

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1643]
#### Brief description of the issue:
Adv. Trauma kits/Burn kits don't close bleeding wounds.

#### What you expected to happen:
For it to close the bleeding wounds.

#### What actually happened:
The wounds didn't stop bleeding.

#### Steps to reproduce:
Get someone bleeding.
Apply a adv. trauma kit/burn kit.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-05-11
74f556c46a423eea3b92e165b4bae0f063c61c78 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Mark9013100** [comment]
Right now, the only way to close bleeding wounds is toss the patient in cyro.

**Comment by Yoshax** [comment]
Fixed by #1641 

Or at least, was in my testing. Have you tried since whenever server was updated?

**Comment by Mark9013100** [comment]
Server hasn't been restarted to my knowledge.

**Comment by Yoshax** [comment]
Server revision says it's live right now. It should be fixed on live.

**Comment by EmperorJon** [comment]
Seems to be fine.
