### ISSUE TITLE
DNA analyzer does not analyze 

### ISSUE THREAD

**Issue by N8-Toe** [PolarisSS13/Polaris#1644]
#### Brief description of the issue
when a used DNA swab is placed in the machien adn lid lowered. it starts but doesnt go past 0%
#### What you expected to happen
it to anallyze the DNA
#### What actually happened
it was stuck on 0%
#### Steps to reproduce
use DNA swab on blood or mouth of body, place in machine, close lid, start it
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
revision number Server revision: master - 2016-05-13

**Comment by Mark9013100** [comment]
RIP forensics.
