### ISSUE TITLE
Rapid Taser Cooling Module Can't Be Used

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#1652]
#### Brief description of the issue

The robotic Rapid Taser Cooling Module is unable to be used on security cyborgs as an upgrade.
#### What you expected to happen

The security cyborg to be upgraded
#### What actually happened

There's no mounting point for the module!
Upgrade error!
#### Steps to reproduce

1.) Have a security cyborg
2.) Open the cyborg's cover
3.) Try to insert Rapid Taser Cooling Module
4.) Get Error
#### Additional info:
- **Server Revision**: master - 2016-05-13
- **Anything else you may wish to add** The VTEC module is still able to be used on cyborgs as an upgrade. My guess would be the taser module to be incorrectly classifying security cyborgs as not security or something along those lines. This may also mean the Jetpack module is broken.

**Comment by Mechoid** [comment]
It isn't to do with the taser module, but the mining borg's jetpack has encountered the same problem. I forgot to make an issue regarding it.

**Comment by Nalarac** [comment]
This issue has been sorted at some unknown time in the past
