### ISSUE TITLE
All record photos are naked.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1660]
#### Brief description of the issue
All the roundstart and latejoin crew photos display crew in nothing but backpacks and underwear.
![image](https://cloud.githubusercontent.com/assets/8376059/15275285/1b6f1ad0-1abf-11e6-8a87-6b0506a29255.png)

#### What you expected to happen
People to get their photos taken wearing some clothes.
#### What actually happened
Everyone is an exhibitionist.
#### Steps to reproduce
Look at security records.
#### Additional info:
 - **Server Revision**:

Server revision: master - 2016-05-13
25827b3b1454b8f08903e8d2f74a08be8fd66fd7

**Comment by Serithi** [comment]
Feature~~~

**Comment by TableTurning** [comment]
Doesn't seem to just be record photos, using the in-game camera has the same effect.

![camera](https://cloud.githubusercontent.com/assets/2044259/15278592/b2331ccc-1ae8-11e6-9378-e7af0208beee.png)

**Comment by Techhead0** [comment]
It looks like the clothing and hair is actually layering below the mob. X-ray cameras?

**Comment by sabiram** [comment]
@Techhead0 That appears to be the case. Pretty obvious looking at the 2nd photo in the records.

Some record photos (the one I saw as a human FBP) are unaffected

**Comment by Arokha** [comment]
Yes, it's a layering issue. The ID cards also have this problem.
