### ISSUE TITLE
Research Outpost SMES can't hold a charge

### ISSUE THREAD

**Issue by SledgeLP** [PolarisSS13/Polaris#167]
As is, before an hour can go by, the research outpost will lose it's power. On top of this, cycling out of the airlock uses 60kwts of power over about a minute, which will drain the SMES at least about 30% of it's current max value. So, I see two fixes possible right now, lower power drain of vents and the like, or supercharge the SMES.

At least those are the two ideas that come to mind to start.

**Comment by Neerti** [comment]
I wonder if it's the airvents drawing that much power or the actual airlock?
