### ISSUE TITLE
Camera layering issue

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1675]
#### Brief description of the issue:

Cameras are completely screwed when it comes to layering.

![](https://i.gyazo.com/03d0a511f2055fdfcf2d87312ae32dc6.png)

#### What you expected to happen:
For the floor tile/blood to be layered under the table.

#### What actually happened:

Screenshot.

#### Steps to reproduce
1. Get a camera.
2. Take a photo of a turf with a table.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-05-15
cac51338283e973b11cddfb7584c8c7dd5893049 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by EmperorJon** [comment]
This also makes them take photos of naked people.

**Comment by EmperorJon** [comment]
("It's a feature" ;) )

**Comment by Mark9013100** [comment]
I-I just want cameras to work man.

**Comment by Datraen** [comment]
#1706 Should resolve.
