### ISSUE TITLE
C4 is not guaranteed to destroy a wall

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#1683]
#### Brief description of the issue
C4 is not guaranteed to destroy a wall
#### What you expected to happen
For C4 to always destroy the wall and girder it's planted it.
#### What actually happened
The C4 can explode and only destroy the covering of the wall, and not the girder.
#### Steps to reproduce
Plant C4 on the wall, wait and possibly see if only the material covering is destroyed.

**Comment by Arokha** [comment]
Fixed by #1688, can be closed.
