### ISSUE TITLE
Certain wounds over x damage do not heal over time when treated

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#1685]
#### Brief description of the issue
In a recent round, I had a patient who had 60 brute to his lower body, I applied a trauma kit and expected the 60 damage to slowly heal over time. It did not, and remained at 60.
#### What you expected to happen
For the damage to heal slowly over time
#### What actually happened
The damage did not heal
#### Steps to reproduce
Injure someone so they have more than 60 brute, apply a trauma kit, see as the wound does not heal.
#### Additional info:
 - It's possible it only happens with piercing wounds, in the case that happened it was a gunshot wound. Although, I'm not certain and it needs further testing.

**Comment by Arokha** [comment]
```
		// if damage >= 50 AFTER treatment then it's probably too severe to heal within the timeframe of a round.
		if (W.can_autoheal() && W.wound_damage() < 50)
			heal_amt += 0.5
```
organ_external : 634-636

**Comment by Yoshax** [comment]
Not a bug. Intended feature.
