### ISSUE TITLE
the research outpost airlock problem. 

### ISSUE THREAD

**Issue by RenScorch** [PolarisSS13/Polaris#169]
The ID tag is set incorrectly on the outer door it set to "escape_pod_6" and it suppose to the be "research_outer" because of this, it won't respond to attempts to open or close the airlock.

**Comment by Woodratt** [comment]
According to the map it is research_outer. This is weird, I'll investigate further

**Comment by RenScorch** [comment]
Closing issue, it seems something went wrong when I downloaded the code, Fresh downlad says the issue is fixed.
