### ISSUE TITLE
Xenobiologists cannot spawn with science ponchos.

### ISSUE THREAD

**Issue by TableTurning** [PolarisSS13/Polaris#1713]
#### Brief description of the issue
If you have selected the science poncho as a xenobiologist, the game tells you that your current job does not allow you to spawn with the poncho.
#### What you expected to happen
I expected to be able to spawn with a science poncho as a xenobiologist, because they're part of the research department.
#### What actually happened
Xenobiologists are instead considered to be plebs and unworthy of the science poncho.
#### Steps to reproduce
1. Select science poncho in character loadout.
2. Join as xenobiologist/xenobotanist.
3. Collapse in despair as the game doesn't give you the poncho.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2016-05-19
365ea43a604ace3314589fdb12640220d9548521 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
https://i.gyazo.com/88f33adeef029d519731ffe6da836218.png

**Comment by Arokha** [comment]
Criminal.
