### ISSUE TITLE
Hardsuits have doubled slowdown

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#1715]
#### Brief description of the issue
Hardsuits have twice the intended slowdown, applies once from back unit and once from chestpiece
#### What you expected to happen
Wearing a hardsuit would give me x slowdown
#### What actually happened
Wearing a hardsuit gives me 2x slowdown
#### Steps to reproduce
1. Get hardsuit
2. Apply hardsuit to back
3. Toggle hardsuit
4. Feel slow
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
I'll try to find the cause of this, but if someone else knows more, please fix this.

**Comment by mwerezak** [comment]
It's probably because the back unit and chestpiece both have a slowdown set? I mean, #1398 wasn't that long ago.

**Comment by Anewbe** [comment]
Yeah, that patch is why it happens, but the issue stems from the fact that the torso piece inherits slowdown from the backpack, which I don't actually understand the code behind.

**Comment by SkowronX** [comment]
For a while I thought this was an intended feature.

**Comment by SpadesNeil** [comment]
_Should_ the backpack give slowdown? Or just when it's deployed? I assume you're talking about rigs.

I say it should just be when it's deployed but that's just my opinion. I'm not going to mess with it unless someone confirms this.

**Comment by mwerezak** [comment]
> Yeah, that patch is why it happens, but the issue stems from the fact that the torso piece inherits slowdown from the backpack, which I don't actually understand the code behind.

The reason would appear to be because a variable was reused for something beyond it's intended purpose, seemingly under the assumption that the back unit's `slowdown` would never be used for anything. That assumption has recently been made false.

**Comment by Anewbe** [comment]
Fixed
