### ISSUE TITLE
Ore box and Cyborg weirdness

### ISSUE THREAD

**Issue by Midaychi** [PolarisSS13/Polaris#1729]
#### Brief description of the issue

When your cyborg mining satchel is one of your three active modules and you are pulling an ore box, and you are either west or east of the ore box and move north or south, sometimes the ore box will stay on your west or east side instead of following normal pull mechanics.
#### What you expected to happen

Oreboxes to respect normal pull mechanics regardless of active modules.
#### What actually happened

Difficulty in maneuvering with ore boxes when that module is active.
#### Steps to reproduce

1.Have cyborg mining satchel as active module.
2. start pull on ore box from the right or left side
3. move up or down.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
  Server revision: master - 2016-05-23
  3484d3c3d3616289b273f98167edd3472bead902 
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)
  Derp

**Comment by Atermonera** [comment]
Observed this sometime in Oct/Nov 2017, still an issue, although I didn't test to see what specifically caused it.
