### ISSUE TITLE
rig backpacks cause slowdown when in mob contents under any circumstances

### ISSUE THREAD

**Issue by Spookerton** [PolarisSS13/Polaris#1733]
As the title; reproduce by picking up an industrial rig (or any rig with a slowdown) in hand and trying to run with it. Expected behavior is that rig slowdown is applied when the rig is a) worn and b) deployed, not otherwise.

**Comment by Anewbe** [comment]
I think for backpacks in general the idea is that they give slowdown in hand, so dufflebags work as intended?

**Comment by Yoshax** [comment]
I do believe so. Items were given slowdown when in hand so you can't do the goold ol' take your suit of to run trick. @Neerti added such. So, not a bug?

**Comment by Arokha** [comment]
Realistically I'd imagine it'd be HARDER to run with an awkward bigass back thing in your arms than actually on your back so this seems like if anything it should go the OTHER direction, but I think it makes sense.
