### ISSUE TITLE
The engineering pump station has no access restrictions on its doors

### ISSUE THREAD

**Issue by Ithalan** [PolarisSS13/Polaris#1735]
#### Brief description of the issue
The engineering pump station north of of medical does not have the access restrictions that the color of its doors imply

#### What you expected to happen
To not be able to open the doors to the pump station unless I have engineering access and not be able to open the inner door to the atmospherics control without atmospherics access

#### What actually happened
I was able to access every part of the pump station without engineering or atmospherics access (was a janitor)

#### Steps to reproduce
Join as janitor. Attempt to enter pump station

#### Additional info:
Server revision: master - 2016-05-24
c9555deffa428d0b67ab87e7581a9219b66a4b00

**Comment by Datraen** [comment]
I swore I grabbed the right doors, but I guess basic engineering colored doors don't actually have the access list in the map maker.
