### ISSUE TITLE
Cryo'd taser guns don't work

### ISSUE THREAD

**Issue by Verarch** [PolarisSS13/Polaris#1755]
#### Brief description of the issue
Cryoing with a taser gun results in it fucking up when retrieved. Can't charge nor fire.
#### What you expected to happen
For the taser to charge and fire like normal
#### What actually happened
***click***
#### Steps to reproduce
Retrieve cryo'd taser gun from terminal
Try to charge and fire
***click***

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Nalarac** [comment]
Do you know if the taser was from a security cyborg or from an officer carrying a taser?

**Comment by Verarch** [comment]
The taser was from a security officer.

**Comment by Anewbe** [comment]
Finally found out why this happens, will have a fix soon.
