### ISSUE TITLE
Stuttering is broken

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1756]
#### Brief description of the issue:
Redacted 0, "L-look, i n-need-d t-to fix-x t-th-he w-w-w-wir-r-rin-ng on s-some s-sol-l-lars."

#### What you expected to happen:
For it to be 'stutters' instead of '0,'

#### What actually happened:
0,

#### Steps to reproduce:
1. Get tased.
2. Talk.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-05-26
6df5e33e363e53bd6eeb5c0f43596063c415aaa8 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Arokha** [comment]
I don't see how that's a problem, and I definitely didn't break it with a typo or anything like that, but I fixed it for you.
