### ISSUE TITLE
Synth/Android/Gynoid uses wrong gender

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#1761]
#### Brief description of the issue

The species label for FBPs uses the FBP's "biological" gender, rather than the identifying gender. Sorta ruins the surprise.
#### What you expected to happen

An FBP's descriptor (Synthetic/Android/Gynoid) would match their pronouns.
#### What actually happened

This is John Doe, a Gynoid.
It is wearing a grey jumpsuit. Attached to it is the captain's medal.
#### Steps to reproduce
1. Admit the Flesh is Weak
2. Be progressive with your gender identity
3. Weep

ALTERNATIVELY
1. Make an FBP
2. Set biological gender to Female
3. Set gender identity to Neuter
4. Join
5. Observe
   #### Additional info:
   - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
   - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by OhEmGee** [comment]
>    1. Admit the Flesh is Weak
>    2. Be progressive with your gender identity
>    3.Weep

These instructions could be used for literally anything.

**Comment by Anewbe** [comment]
That's why I wrote the Alternative steps.

**Comment by MarinaGryphon** [comment]
I believe that in the context of an FBP, "biological gender" is meant to represent whether the chassis is designed to appear masculine, feminine, or unaligned/neuter, not the sex of their original body.
If that doesn't resolve the issue, though, then I'll try changing it.
