### ISSUE TITLE
Communicators are borked, can't hear any speech

### ISSUE THREAD

**Issue by Serithi** [PolarisSS13/Polaris#1762]
#### Brief description of the issue
Can't hear any speech when in a communicator call as a ghost.

#### What you expected to happen
Hearing stuff is not borked.

#### What actually happened
Hearing stuff is borked.

#### Steps to reproduce
Be ghost, call someone's communicator, try to say stuff and get them to say stuff. Nothing will show up on your screen, though they can hear you fine.

#### Additional info:
 - **Server Revision**: master - 2016-05-27
 - **Anything else you may wish to add** I'm _guessing_ it's to do with the say/whisper rewrite we just had, possibly?

**Comment by Arokha** [comment]
Communicators have their own special code for relaying talking so I bet some aspect of this isn't compatible with the new say/whisper. I'll look at it.
