### ISSUE TITLE
Respawn Is Broken

### ISSUE THREAD

**Issue by ParadoxSpace** [PolarisSS13/Polaris#1773]
#### Brief description of the issue
http://puu.sh/p7rGZ/75ebb9dfc9.png
#### What you expected to happen
To respawn
#### What actually happened
I didn't
#### Steps to reproduce
Hit respawn, cry
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Yoshax** [comment]
Duplicate issue.
