### ISSUE TITLE
Auxillary tool storage has the wrong access and improper pipes.

### ISSUE THREAD

**Issue by Jakksergal** [PolarisSS13/Polaris#1789]
#### Brief description of the issue
Auxiliary tool storage has the wrong access set. It appears to have maintenance and some other access that's not meant to be on the station.
#### What you expected to happen
The door to just be maintenance access.
#### What actually happened
It was inaccessible
#### Steps to reproduce
- Be any job with maintenance access
- Touch door
- Get denied

#### Additional info:
 - **Server Revision**: master - 2016-05-28 01b3182004b7098f57baa249511fcb26946cb23b 
 - **Anything else you may wish to add** 
 - Located next to the coffee shop.
 - Pipes under door do not have hidden set to one and are on top of the floor tiles.

**Comment by Neerti** [comment]
Should note I was able to enter as a security officer, which is odd.

**Comment by Yoshax** [comment]
The front door has access = 12. Which is maintenance.

**Comment by Woodratt** [comment]
aux tool storage has always had maintenance as its access. Security officers, paramedics, cargo techs all have access. The pipes being visible however is a bug, which I am sorting.
