### ISSUE TITLE
Lots of immersion problems with guns.

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#1798]
#### Brief description of the issue
Lots of stupid things that annoy me with guns, such as revolvers being 7 shot, or the fact that I can jam a horizontal magazine into a vertical magazine well and turn a 9mm pistol into a 30-shot death machine, or the fact that I can shove a curved 762 clip into a (presumably) belt-fed light machine gun or the fact that casings don't change sprites when you spend the bullet inside, or the fact that I can't take casings out of my magazine and put them in different magazines, etc.

#### What you expected to happen
The opposite of everything I just described.

#### What actually happened
Well, I just explained.

#### Additional info:
 - **Server Revision**: No idea if it's live on your server, but I know the version on Github I'm working with is https://github.com/PolarisSS13/Polaris/commit/288ae3d27425f1f8c68d111734e7c99c65538450

Seeing as I previously fixed _all_ of these little annoyances once on old [Vorestation PR](https://github.com/SpadesNeil/VOREstation/pull/84), I'd be happy to do them again here for Polaris. I know guns and RP aren't usually things that come together nicely, but honestly, this little bit of immersion just makes me happy and I don't see a reason not to improve immersion a little.
- [x] Add functionality to prevent use of incorrect magazines.
- [ ] Fix guns being able to use incorrect magazines.
- [ ] Fix ammo casing sprites not updating after being spent.
- [x] Fix the dumb sprite for the Desert Eagle.
- [ ] Add the correct magazine for the Uzi.
- [ ] Add bolt-action rifles because those are just fun to use in SS13.
- [ ] Add ammo clips for bolt-action rifles.
- [ ] Add some chalk bullets so players can potentially have shooting competitions on the range.
- [ ] Add the Mosin Nagant and Obrez because those are fun.
- [ ] Allow users to add or remove casings to and from compatible magazines.

I could also add better sounds for every gun but honestly that's up to you guys. The default sound clip for gunfire is too generic for my tastes, but it gets the job done.

I can also toss in support for caseless ammunition but there's no guns in-game that currently support that functionality. If I do it, I'm going to do it differently than I previously did, though. I'll make the ammo define caseless instead of the gun.

**Comment by martin509** [comment]
Machineguns like the M249 actually can take magazines, so as long as they're both of the same caliber it's not too far-fetched.
A 7-round revolver is perfectly fine, it's just a larger circle, isn't it?
The rest is weird, yes.
Also >not sks, not mauser 98, not lee-enfield

**Comment by SpadesNeil** [comment]
I was about to mention that about the M249 being able to accept magazines, and was going to ask how the L6 SAW should behave. I can easily make that possible.

I still think 7 rounds is silly. At the very least I'm changing the mateba.

Also what are you on about regarding the SKS, Mauser, and Lee-Enfield?

**Comment by martin509** [comment]
Just standard gun-nut elitism with your mention of the Mosin.

**Comment by SpadesNeil** [comment]
I just mentioned the mosin because I added functionality to it where you can saw it down into the fire-spitting inaccurate handcannon called the Obrez.

![mosin_pistol](https://cloud.githubusercontent.com/assets/6484985/15634703/6d216c1e-2598-11e6-9d6d-33202890ba82.jpg)

**Comment by Datraen** [comment]
This would do better as a WIP PR, as this has obtainable guidelines that you are setting out AND it seems that you are working on them.

**Comment by SpadesNeil** [comment]
Good idea. I'm still not an expert with Github so bare with me. Gonna close this and make it a WIP PR instead.

**Comment by SpadesNeil** [comment]
I had to start this over because I'm a retard with Github. I'll restart this project later.
