### ISSUE TITLE
APCs and SMES lost their bars

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#1804]
#### Brief description of the issue
The screen for APCs and SMES don't have the colored bars like they used to
#### What you expected to happen
UI with bars and numbers would show up
#### What actually happened
The bars are present, but neither filled nor colored
#### Steps to reproduce
1. Click an APC or SMES
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Serithi** [comment]
Wow, that's a racist description :^).
