### ISSUE TITLE
Human sprite sex doesn't change

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#1810]
#### Brief description of the issue

Character setup preview never gives a female sprite
#### What you expected to happen

To have a female sprite when female gender in the character setup.
#### What actually happened

Had female gender and a male sprite.
#### Steps to reproduce

Open haracter setup, select female gender, cry because no bewbs.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by EmperorJon** [comment]
Whilst this is the most apparent issue and is now clear to the user, it is not an issue with the setup code and extends further. Using the appearance editor to change your gender won't update your sprite, and neither will changing the variable directly in VV. I can confirm that if you change species and back it works fine, so there's a start for something to look into.

**Comment by andrewmeythaler** [comment]
For now you can temporarily fix it by swapping species back and forth after changing genders

**Comment by Atermonera** [comment]
Still an issue as of 2017 - 12 - 29
