### ISSUE TITLE
Ghosts are never invisible, and keep their pants

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#1817]
#### Brief description of the issue
There's no longer an easy way to become an invisible (spriteless) ghost, the Choose Sprite verb is less than functional
#### What you expected to happen
Selecting Clear in the 'Choose Sprite' verb would make my ghost invisible, selecting other options would make my ghost appear as that option, without extra clothing
#### What actually happened
My preview clothing remained visible, if disembodied
#### Steps to reproduce
1. Become a Ghost with clothing
2. Select 'Choose Sprite'
3. Select Clear, or any other selection
4. Observe
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
Workaround: Join as a char that has no clothing (no slot set to high), lets you use the verb normally.

**Comment by PsiOmegaDelta** [comment]
Make choosing sprite cut all overlays of the mob and the clothes will go away.
