### ISSUE TITLE
'Northern Star' network is listed twice

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1819]
#### Brief description of the issue:

![](http://i.imgur.com/02ll2Ej.png)
#### What you expected to happen:

For it not to be listed twice.
#### What actually happened:

It was listed twice.
#### Steps to reproduce:

Look at a security camera console.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-05-29
f6762f27ee3e6b7427901173c4bf2b1cedceabcc 
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Listed under #1409
