### ISSUE TITLE
[Dev quality of life] supplypacks.dm is a clusterfuck

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#1823]
#### Brief description of the issue
I feel like the supplypacks.dm file should be separated into different files in a folder per the category they belong to, so it's a lot easier to work with this without getting a headache.

Definitely a priority zero issue but I'm leaving this issue here to remind me to do this later.

#### Additional info:
 - **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/dbcf3b18c1f392a7913fb2349f59108eb8797287

**Comment by Datraen** [comment]
I have it done + subtyping, but waiting on #1844 to be decided upon before PRing to avoid conflicts.

**Comment by SpadesNeil** [comment]
Ah, thank you! I was going to do it myself, but I hadn't even started. I was also waiting for 1844 to be resolved.

**Comment by SpadesNeil** [comment]
@Datraen This should be good to go now!
