### ISSUE TITLE
Monitor State Issues

### ISSUE THREAD

**Issue by andrewmeythaler** [PolarisSS13/Polaris#1825]
#### Additional info:
- **Server Revision**: master - 2016-05-30 dbcf3b18c1f392a7913fb2349f59108eb8797287 
- **Anything else you may wish to add** Issue discovered using the Heaphestus alternate head with a CRT visor loudout item

**Comment by ParadoxSpace** [comment]
another bug here, the sprite itself on the mob clips through everything, and appears weirdly in the inventory screen

**Comment by ParadoxSpace** [comment]
a n o t h e r  b u g
green monitor style doesn't actually exist
