### ISSUE TITLE
Throwing Grabbed mobs has no click delay.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1838]
#### Brief description of the issue

You can get a mob in an aggressive grab, stand next to a blast door, and throw the mob into it several times a second. 
#### What you expected to happen

Throw them a couple of times every few seconds.
#### What actually happened

Spam smashdown of a blast door.
#### Steps to reproduce

Grab mob, find blast door, throw at blast door.
#### Additional info:
- **Server Revision**: Server revision: master - 2016-06-01
  0c47cfe9bad277ab955794808f861f5bd91323f8

**Comment by EmperorJon** [comment]
For reference you can do this to windows too.

**Comment by SinTwo** [comment]
As a note, you have to be standing next to the item you are throwing at so that when it hits the object, the mob you are throwing hasn't been 'thrown out of the grab'. As such you still have a grab on them which allows you to throw again.

**Comment by TheFurryFeline** [comment]
This sort of aggressive grabbing throw spam has been and still is an issue as of 26/5/19 and tested on a private server running the current master branch.

**Comment by TheFurryFeline** [comment]
Resolved with https://github.com/PolarisSS13/Polaris/pull/6463
