### ISSUE TITLE
It is no longer possible for R&D to produce better power cells.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1843]
#### Brief description of the issue
Power cells cannot be built in the protolathe, Exofab or prosthetics fab machines.
#### What you expected to happen
It to be possible to build enhanced power cells in the Protlathe and Exosuit fabricator.
#### What actually happened
You can't make new power cells.
#### Steps to reproduce
Try to make power cells.
#### Additional info:
 - **Server Revision**: Server revision: master - 2016-06-01
0c47cfe9bad277ab955794808f861f5bd91323f8

**Comment by Arokha** [comment]
The fix for this was just merged, so next update.
