### ISSUE TITLE
Can't use items on surgery patient on help intent

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#1849]
#### Brief description of the issue

Related to #1687
You cannot use items when someone is on a table when using help intent. Other intents work fine. Despite the comment stating that you only get the message but it works, it does not work.
#### What you expected to happen

Syringes, health scanners, etc. work
#### What actually happened

Nope.
#### Steps to reproduce

Put someone on a surgical table. Try to inject on help. Then try on a different intent.
#### Additional info:
- **Server Revision**: master - 2016-06-01
  0c47cfe9bad277ab955794808f861f5bd91323f8 
- **Anything else you may wish to add**

**Comment by Yoshax** [comment]
I think this is more related to the attack call cleanup, it's likely the surgery thing is being called before the attack.

**Comment by mwerezak** [comment]
`do_surgery()` should become an `/obj/item` proc, I think would be the best way to resolve this.

**Comment by Yoshax** [comment]
@mwerezak does the same happen on Bay, or has it been resolved there, or perhaps never happen?

**Comment by Techhead0** [comment]
As of Monday on the Baystation server:
Health scanners currently refuse to work and give the error message, if the patient is buckled to a roller bed and you are on help intent. I think that confirms the bug exists on Bay. There might also be an open issue somewhere.

**Comment by Yoshax** [comment]
Ah, yes. But at the time, I was wrong. Before the port of the attack call stuff the action of using the item, you both scanned the person and got the message.

**Comment by EmperorJon** [comment]
This still seems to be occurring.

**Comment by Yoshax** [comment]
With what items?

**Comment by EmperorJon** [comment]
Trauma kit, most likely because it's also used for a surgery, but also it seems FBP surgery is repeatedly saying things cannot be used or otherwise not working as intended, which may or may not be related. I need replicate the exact details.

**Comment by Atermonera** [comment]
Not recently observed, should be closeable
