### ISSUE TITLE
Devs don't appear in staffwho

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1857]
#### Brief description of the issue:
Devs don't appear in staffwho.

#### What you expected to happen:
For them to appear in staffwho.

#### What actually happened:
They didn't.

#### Steps to reproduce:
1. Use staffwho when a developer is online.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by OrbisAnima** [comment]
It's a feature

**Comment by Serithi** [comment]
Why would plebs show up in staffwho :^)
