### ISSUE TITLE
Round vote should take place after all antags win / fail.

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#1858]
#### Brief description of the issue
Someone in the Discord chat mentioned that during mercenary attacks, games where security wins just aren't very fun. "Mercenaries won at 45 minutes. Welcome to hour 2:15 of extended!" which they find boring.

#### What you expected to happen
For there to be some kind of vote. Maybe, 15 minutes after the actual victory. Vote for the return shuttle.

This is just a suggestion. Some people reported being bored when security wins, while when mercs win, the server descends into chaos and hilarity.

#### Additional info:
 - **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/e62b06e8676a1faab0f9b15c449a0bdcf31b6199

**Comment by zekesulastin** [comment]
... no, that's not announced; trying to get rid of the win/lose thought process for a while now.  Also you can just say you're copy pasting ParadoxSpace; nobody will bite you for it.

**Comment by SpadesNeil** [comment]
I legitimately forgot who mentioned it but yes I think it was ParadoxSpace who suggested this.
