### ISSUE TITLE
power_alert icon for power monitoring computer is blank.

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#1865]
#### Brief description of the issue
This creates a monitor that appears to be turned off. Very straight-forward. The icon is invalid.

#### Additional info:
 - **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/574f96639a5bafbb1062f77022d1878e8c7457be

**Comment by SinTwo** [comment]
Duplicate of : #540

**Comment by SpadesNeil** [comment]
Whoops!
