### ISSUE TITLE
Security/Jobs slots don't free up after cyro'ing

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#1868]
#### Brief description of the issue:

Security Officer and Detective slots won't re-open if someone cyros.
#### What you expected to happen:

For the slots to re-open.
#### What actually happened:

For the slots to free up.
#### Steps to reproduce:
1. Cyro as an officer/detective.
2. Try to rejoin, view slots.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2016-06-02
e62b06e8676a1faab0f9b15c449a0bdcf31b6199 
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by EmperorJon** [comment]
I'm not sure this is limited to sec slots.

**Comment by Mark9013100** [comment]
I've seen it only occur with security slots to this point. Not sure what other roles it happens with.

**Comment by sabiram** [comment]
It's likely simply that non-security has never been full

**Comment by Mark9013100** [comment]
Hm, might be an issue with the elevator/gateway.

**Comment by Anewbe** [comment]
Pretty sure that this is a copy of an older issue report, but that one's gone horribly stale. Still an issue.

**Comment by MagmaRam** [comment]
This doesn't seem to be an issue at this point. In testing, CMO, detective, Warden, and HoS all freed slots properly (Detective changed from 2 allowed to 3 allowed, the rest changed to 2 allowed). If this doesn't crop up in the next day or so, I'll close this one.

**Comment by Anewbe** [comment]
Just saw it in round, still don't know how it happens.
