### ISSUE TITLE
Slimes cannot handle reagents not in their reagent list.

### ISSUE THREAD

**Issue by Datraen** [PolarisSS13/Polaris#1876]
#### Brief description of the issue

Slime reagent handling object's reagent get clogged when there's something not on the list in it.
#### What you expected to happen

To dump the chemical
#### What actually happened

The chemical clogged it
#### Steps to reproduce

Inject slime with chemical it can't handle, I.E. Hydrogen
Cry.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Datraen** [comment]
Related proc: https://github.com/PolarisSS13/Polaris/blob/78e63a00a4cdd66cfd473af9110b57067c50b561/code/modules/xenobio2/mob/xeno%20procs.dm#L48

**Comment by Anewbe** [comment]
Reopening because it's half-fixed.

**Comment by Datraen** [comment]
#2766
