### ISSUE TITLE
'Random Medicine' item does not turn into a random medicine

### ISSUE THREAD

**Issue by martin509** [PolarisSS13/Polaris#1892]
#### Brief description of the issue
There is an item that is normally meant to spawn a random medicine at roundstart (for instance, kelotane pills), used in medical lockers. It does not spawn the random medicine, instead appearing as a non-pick-up-able item with the icon of gauze titled Random Medicine.
#### What you expected to happen
I expected a random medicine.
#### What actually happened
[http://i.imgur.com/0VUpqaA.png](http://i.imgur.com/0VUpqaA.png)
#### Steps to reproduce
Look in medical lockers at round start.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Arokha** [comment]
Might be from f75d509e7fe8e364d5db5782a3dd1ced183a1dfd

**Comment by martin509** [comment]
Update: the medicine is spawned but the 'random medicine' item is not deleted.
