### ISSUE TITLE
New Xenobiology Bug List

### ISSUE THREAD

**Issue by rainbowEscapist** [PolarisSS13/Polaris#1896]
#### Additional info:
 - **Server Revision**: master - 2016-06-07
 - **Anything else you may wish to add** I'll look for more bugs with new Xenobiology.

**Comment by rainbowEscapist** [comment]
There also appears to be an issue with putting Grabbed slimes into the injector. 

What's Happening: Slimes in blue grab aren't always going into the injector.

What do I expect?: For the dumb thing to go in!

What is actually happening: The thing goes in only half the time. Sometimes it won't go in, so then I move a few tiles around, and then it goes in just fine.

Same Revision. Also no dirty jokes because of my wording!

**Comment by TableTurning** [comment]
What I think is happening with the injector thing is that both you AND the slime have to be adjacent to the injector for it to work.
![injector](https://cloud.githubusercontent.com/assets/2044259/15915944/c15ae1b8-2dbb-11e6-8dec-2d5a1d5bdfe3.png)
