### ISSUE TITLE
Prosthetic Limbs cost twice as much as before

### ISSUE THREAD

**Issue by Searif** [PolarisSS13/Polaris#1900]
#### Brief description of the issue
With the prosthetic changes to robotics, prosthetic limbs were split into arms, hands, legs and feet, where as before they were combined. Arms before costed 18000 steel and legs costed 15000 steel, and they came with hands/feet. Now, you pay the same 18000 steel or 15000 steel for an arm or leg, plus an additional 10000 steel for the hand/foot that goes with it.

#### What you expected to happen
Prices to have been split in half with the change as we were getting essentially half as much.

#### What actually happened
Instead an additional 10000 steel is required per limb, severely reducing what a roboticist can make without the assistance of cargo/mining

#### Steps to reproduce
Look at the prices of robot limbs, they have the original prices of prosthetic limbs as they were what was original used, notice how they come with hands, and how they cost the same as a prosthetic without a hand.

#### Additional info:
Server revision: master - 2016-06-07
627b63a4e31a6121cf1d3052976a2828a65b7ef9

**Comment by Arokha** [comment]
S'more of a balance issue if you guys want to fix it, but I'll just point out you can still use the cyborg limbs as prosthetics, for the original prices. Maybe it's ICly degrading or something to get cyborg limbs, idk.

**Comment by Searif** [comment]
I'd rather have robot limbs be restricted to making lawed synths and the price of prosthetics lowered. Thats just me though.

**Comment by Datraen** [comment]
Semi-Addressed in #1921
