### ISSUE TITLE
Blob doesn't devour things like it should.

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#1901]
#### Brief description of the issue

Noticed some engineers having extreme trouble in dealing with a blob. There was a water tank completely blocking their emitter.
#### What you expected to happen

Blob to eat everything not anchored down.
#### What actually happened

![screenshot-2016-06-09-01 07 40](https://cloud.githubusercontent.com/assets/6484985/15919405/02cd52b6-2ddf-11e6-91ba-260a901234ca.png)
#### Steps to reproduce
1. Spawn blob
2. Ensure blob gets in the way of something that isn't anchored but should be eaten, like any items. Not mobs.
3. Watch it not get ate.
#### Additional info:
- **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/627b63a4e31a6121cf1d3052976a2828a65b7ef9
- **Anything else you may wish to add**: This is by design because blobs would previously eat important things. I think this was the lazy way out. Any object being eaten should pass a check. If anchored (ie; can't move), do not eat it. If not anchored, it's probably replaceable, so eat it.

**Comment by Searif** [comment]
Will confirm, did not eat the water tank. I actually moved it to let the emitter fire on the blob core

**Comment by PsiOmegaDelta** [comment]
Blobs were deliberately changed to not destroy non-walls/doors due to many things being irreplaceable/unrepairable.

**Comment by SpadesNeil** [comment]
In my experience, things that are not bolted to the floor (anchored != 1) are usually replaceable. I know not of many examples to the contrary.

**Comment by Hubblenaut** [comment]
@SpadesNeil That was changed before Sin's construction PRs.

However another reason or the blob behaving like this is engineers being tired of the overly massive destruction a blob caused back then.
