### ISSUE TITLE
FBP Cutting Limbs Off and Items

### ISSUE THREAD

**Issue by ParadoxSpace** [PolarisSS13/Polaris#1905]
#### Brief description of the issue
so like
i'll try my best to explain this like
if you cut off a robot's limbs, and he has items on those limbs, he later cannot interact with said items and you cannot remove them, they do not show up
#### What you expected to happen
to be able to whip off my glasses/boots/display monitor
#### What actually happened
I can't
#### Steps to reproduce
give robot glasses, cut robot head off, put robot head back on, watch as glasses are nullspace
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Arokha** [comment]
Making PR to fix.
