### ISSUE TITLE
Runtime on server start

### ISSUE THREAD

**Issue by Arokha** [PolarisSS13/Polaris#1915]
#### Brief description of the issue
The server throws a runtime on server start about trying to call `null.raise_event()` and lists the source as line 14 on some bizarre random file that usually isn't a file because apparently Byond doesn't generate the symbols right.

#### What you expected to happen
To not have runtimes on server start.

#### What actually happened
Runtimes on server start.

#### Steps to reproduce
Start the server.

#### Additional info:
This is actually line 14 in `destroyed.dm`. It is attempting to call `destroyed_event.raise_event(src)`, however `destroyed_event` does not exist yet, as this particular error is caused when `/datum/global_init/New()` attempts to `qdel(src)` itself at the world start on line 25 of `world.dm`, and as part of the `qdel` process, it calls `Destroyed()` on the `global_init` datum, which fails.

So, there you go. Someone less lazy can fix it!

**Comment by PsiOmegaDelta** [comment]
Simply make ```/global_init/New()``` not call ```..()```.
