### ISSUE TITLE
Mechs cause FBPs to overheat in space, even if their voidsuit has a cooler

### ISSUE THREAD

**Issue by Searif** [PolarisSS13/Polaris#1924]
#### Brief description of the issue
Mechs being piloted by FBPs cause the FBP to overheat in space even when voidsuits have a cooler

#### What you expected to happen
FBPs to be able to use mechs without overheating when wearing a cooled suit

#### What actually happened
FBPs overheat in mechs despite cooled suit

#### Steps to reproduce
Wear a voidsuit with cooler, jump in mech, go into space with mech, watch as you overheat.

#### Additional info:
Server revision: master - 2016-06-11
e18666d41a426703369353fb9477243acb7a8687

**Comment by Arokha** [comment]
Actually to be honest, this makes sense, even if it's a code oversight.

The suit cooler is a radiator. If you just radiate that heat back into the mech, soon the inside of the mech will just be the same temperature as the radiator and heat won't exchange and you'll overheat.

If you turn on internal air in the mech, it should work fine.

**Comment by Searif** [comment]
But it didn't.

Also, making sense =/= fun

**Comment by Arokha** [comment]
You had the mech's internals on?

**Comment by Arokha** [comment]
```
[23:07:51] Process obj caught exception processing /obj/item/device/suit_cooling_unit (the portable suit cooling unit) (0,0,0): undefined proc or verb /mob/living/carbon/human/return temperature().
 in suit_cooling.dm, line 70
```
Gets thrown when in a mech, is why it doesn't cool you it seems.

**Comment by Searif** [comment]
I turned it on specifically to test

**Comment by Arokha** [comment]
This has been a bug since 6/21/2014. Wew. Making a PR to fix.
