### ISSUE TITLE
Biopsy Scanner Doesn't Work

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#1925]
#### Brief description of the issue
Using the biopsy scanner only results in:
You can't see any useful way to use the biopsy scanner on Unknown.
#### What you expected to happen
The biopsy scanner to scan the wound.
#### What actually happened
It did not work.
#### Steps to reproduce
1. Get wounded individual (Like a corpse)
2. Cut wound area with scalpel
3. Attempt to use the biopsy scanner
#### Additional info:
 - **Server Revision**: master - 2016-06-11

**Comment by Anewbe** [comment]
Probably related to #1849

**Comment by EmperorJon** [comment]
Definitely related.
