### ISSUE TITLE
Emotes are visible through walls if you can see the turf someone is standing on

### ISSUE THREAD

**Issue by tigercat2000** [PolarisSS13/Polaris#1933]
#### Brief description of the issue

Custom/"Me" Emotes are visible any time you can see a turf someone is on. This is primarily a problem with mesons/thermals; they behave opposite of how you would expect. Thermals cannot see any emotes through a wall, while mesons can see any custom emotes, but not */say emotes.
#### What you expected to happen

You would only be able to see someone's emotes if you can see them.
#### What actually happened

You can see a custom emote as long as you can see the turf they are standing on, but not say/\* emotes.
#### Steps to reproduce
1. Wear mesons.
2. Have someone go behind a wall.
3. Have them use a say/\* emote, such as `say *wink`
4. Observe that you are unable to see the emote.
5. Have them use the "me" command to make an emote, such as `me waves hello!`
6. Observe that you are able to see the emote, despite being unable to see them.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
  5606097aa9c6956423a98951a61ecb4c11fc63dd

**Comment by Spacemanspark** [comment]
Hi Tigercat.

**Comment by SinTwo** [comment]
I suspect this is related to #1926

**Comment by Hubblenaut** [comment]
I happened to see someone talking, presumably by using an emote, when not even seeing the turf they are on, however being in range.
Unsure if related.

**Comment by Arokha** [comment]
You might want to retest this since I rewrote say and emotes again after this.
