### ISSUE TITLE
Foam Axe can one shot reinforced glass.

### ISSUE THREAD

**Issue by OrbisAnima** [PolarisSS13/Polaris#1959]
#### Brief description of the issue
When I hit a reinforced window, wih the foam axe, it destroys the glass completly, faster than more sharper and deadly things, like a crowbar, a fire extinguisher, a bullet...
#### What you expected to happen
For my foam toys to not be able to destroy reinforced glass... or even glass.
#### What actually happened
Foam was mixed with diamonds, and thus able to destroy windows. 
#### Steps to reproduce
-Get a foam axe (cargo, arcade, spawn)
-wield it.
-hit a window
-(Optionally) wear a gas mask, robes, and do it during a Grid check.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Revision unknown
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SinTwo** [comment]
also as a note, you can't use any foam weapon to hit someone else with it seems.

**Comment by Hubblenaut** [comment]
Foam axes use the foam material and a `force_divisor` of 0, they should have `force = 0` on spawn.

**Comment by Yoshax** [comment]
You can't hit anyone with a force = 0 anything apparently.

**Comment by Anewbe** [comment]
For the initial issue: https://github.com/PolarisSS13/Polaris/blob/8f54e7778fd377296a9c895295d7977e6ce5a7eb/code/game/objects/items/weapons/material/twohanded.dm#L90
