### ISSUE TITLE
Unable to complete FBP repair surgery, Cable coil and welders un-usable.

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#1961]
#### Brief description of the issue
You cannot repair an FBP through surgery with a welding tool or cable coil.
#### What you expected to happen
FBP could be repaired after getting the panel open.
#### What actually happened
'You can't see any way to use the cable coil/welder on FBP McX.'
#### Steps to reproduce
1) Damage an FBP
2) Place on surgery table
3) Open panel, try to weld damage or fix wires, see that you cannot.
#### Additional info:
 - **Server Revision**: c0a9903a873825a0f6d0d4c57ccb7e7fd1dc6755 
 - **Anything else you may wish to add** I was not the one who encountered this, I am simply reporting it.

**Comment by Searif** [comment]
If they aren't damaged enough to take actual internal damage then putting them on the surgery table makes you unable to repair them, you'd need to take them off the surgery table then repair if the damage is below.. I think 30?

**Comment by Mechoid** [comment]
I was informed it was after actual internal damage before reporting this.
