### ISSUE TITLE
Character setup and dialogue boxes

### ISSUE THREAD

**Issue by Midaychi** [PolarisSS13/Polaris#1965]
#### Brief description of the issue

You can get around some restrictions in character setup because dialogue boxes don't check if the template is still valid AFTER you activate them

![Alt text](https://dl.dropbox.com/s/s1da1hsl519cyr2/monitor.jpg"monitorhead")
#### What you expected to happen

Not to happen.
#### What actually happened

I don't have access to all the species, so I can't test them, but I assume you can bypass species restrictions on some limbs or parts or hairdos or whatnot. I _do_ know however that you can have a prosthetic head without being a FBP using this. Or a prosthetic torso without FBP. Or whatever.
#### Steps to reproduce
1. make character 1, save. In this case, make them a FBP and save.
2. Load another slot, make it a normal human, save.
3. Go back to character 1, select limbs button but don't close or alter the dialogue box that pops up
4. Load character 2, change the head limb to be prosthetic.
5. Hey, monitor head!
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

It's probably more of a byond issue then a station code specific issue.

**Comment by SpadesNeil** [comment]
Is not bug. Is feature!

No but seriously this should be fixed. Good catch. This could be breaking other things too.

**Comment by PsiOmegaDelta** [comment]
As long as the sanitation is setup to handle it, bad settings will be catched when doing copy_to/save.
This particular instance is likely not covered however.
