### ISSUE TITLE
Global OOC cooldown timer

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#1969]
https://github.com/VOREStation/VOREStation/issues/161 Originally thought of over here.

OOC can get spammed up sometimes by both legitimate and illegitimate things. I propose adding a config option that limits how often you can post in global OOC. By default, the timer in the config should be commented out, but can be turned on to be set in seconds.

If turned on to say, 60 seconds, a user attempting to post in OOC will be limited to one post by them every 60 seconds.

**Comment by EmperorJon** [comment]
... or you could just mute them from OOC?

**Comment by SpadesNeil** [comment]
I could. Then I'd also miss out on OOC that I actually want to read.

I'd rather be able to read OOC, I just don't want it getting excessive. If you don't want OOC _ever_ that's when you mute OOC.

**Comment by EmperorJon** [comment]
No, I mean mute people from OOC.

**Comment by SpadesNeil** [comment]
Then they don't get to use OOC at all and that's a problem for reasons I explained already.

I could mute individual players but that's only helpful if an admin is online to enforce it every single shift.

**Comment by Yoshax** [comment]
Muting OOC does not mute LOOC.

They are separate afaik, or should be.

**Comment by SpadesNeil** [comment]
They should be. They are not, in my experience. I often have players complain about LOOC being muted in adminhelp after I mute them from global OOC for spamming bullshit.

**Comment by PsiOmegaDelta** [comment]
Global OOC/LOOC muting is indeed separate, per player isn't.
Perhaps replace the player "Mute OOC" with a "Ban for [Standard round duration + 1] hour" button instead. That might actually teach them.

**Comment by MagmaRam** [comment]
The better solution would be to make OOC and LOOC mutes two separate buttons, wouldn't it?

**Comment by SpadesNeil** [comment]
No. Again, 



>I could. Then I'd also miss out on OOC that I actually want to read.

>I'd rather be able to read OOC, I just don't want it getting excessive. If you don't want OOC ever that's when you mute OOC.

>Good OOC is stuff like, "Hey, Player McPerson who I was talking to, you ran off before I could post. Can you come back?" Bad OOC is memes and useless banter. If I mute OOC, I miss out on everything.

It's rude to other players who actually want to use OOC without it getting spamfucked by nonsense.

**Comment by Atermonera** [comment]
Resolved by #2906
