### ISSUE TITLE
Incapacitated people can strip adjacent mobs.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1977]
#### Brief description of the issue

Clickdrag to yourself an adjacent mob to yourself while asleep / stunned, and you can remove items they are wearing.
#### What you expected to happen

Nothing.
#### What actually happened

I took the surgeon's scalpel out of their hand mid surgery.
#### Steps to reproduce

Remove the surgeon's underwear while they are stuffing your intestines back in your mangled corpse.
#### Additional info:
- **Server Revision**: Server revision: master - 2016-06-25
  3f71640610393dd657bd7f11d10c5ca739090900

**Comment by Atermonera** [comment]
Should've been closed by #4265
