### ISSUE TITLE
Relocating heads?

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1979]
#### Brief description of the issue
When attempting to relocate one's head, every verb but the head is displayed in the menu, and none of them work.
#### What you expected to happen
To be able to relocate your head, somehow?
#### What actually happened
Needed a rejuv.
#### Steps to reproduce
Get head dislocated. Attempt to fix. Fail.
#### Additional info:
 - **Server Revision**: Server revision: master - 2016-06-25
3f71640610393dd657bd7f11d10c5ca739090900

**Comment by Serithi** [comment]
Pretty sure relocating vertebrae by hand is not realistically possible. The only non-surgical options i'm finding involve braces and weights to hold them in place, they're out in the first place because of torn ligaments.

**Comment by FenodyreeAv** [comment]
The dislocated head came from a surgeon thwacking me with something. Was then unable to be put back.

**Comment by Hubblenaut** [comment]
@Serithi ICly it's the jaw getting dislocated, but ye, the current dislocation mechanics are not too realistic.

**Comment by Anewbe** [comment]
A simple fix would be to make the head impossible to dislocate.
