### ISSUE TITLE
Manually Editing a Changeling's Max Chems breaks the HUD

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#1989]
#### Brief description of the issue
If you varedit the max chems on a ling, the chem HUD stays where it was.
#### What you expected to happen
HUD would tick up/down, wasn't really expecting anything.
#### What actually happened
HUD stayed at 20 chems, when I had anywhere between 0 and 100 actual chem points.
#### Steps to reproduce
1. Create 'ling
2. Varedit max chems
3. Observe
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
Really unimportant, just stumbled onto it while testing other things.

**Comment by Hubblenaut** [comment]
You directly access a variable and edit it without any proc calls - honestly, what do you *expect* to happen? It's not supposed to be used that way.

**Comment by Anewbe** [comment]
Just happened to come up in testing, so I reported it. Doesn't really need to be fixed, but it's there.

**Comment by Hubblenaut** [comment]
It's not a bug when you hack varibles and things break.
