### ISSUE TITLE
Formal closet has no hair flower pin

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#199]
"/obj/structure/closet/gmcloset"
contains
"new /obj/item/clothing/head/hairflower"
in the New() proc, but it never seems to actually appear. 
Reason unknown.

**Comment by Mark9013100** [comment]
Is still an issue?

**Comment by GinjaNinja32** [comment]
@EmperorJon, `new /obj/item/clothing/head/hairflower` will create it in nullspace and the GC will eat it. `new /obj/item/clothing/head/hairflower(src)` is needed so it's created in the closet.
