### ISSUE TITLE
Phoron interaction with armour and gloves.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#1994]
#### Brief description of the issue

The only thing that can remove phoron from contaminated gear is the washing machine, and armour does not fit in the washing machine.

Wearing protective gloves, or even whole bodysuits does not protect from handling phoron contaminated clothing.
#### What you expected to happen

Armour and boots to fit in the washing machines.
Wearing gloves, or a bio/space suit to protect from handling phoron clothes.
#### What actually happened

Armour and boots that touch phoron can never be cleaned.
Touching said armour or boots causes tox damage no matter what you are wearing.
#### Steps to reproduce

Contaminate armour with phoron, then handle them.
#### Additional info:
- **Server Revision**: Server revision: master - 2016-06-27
  6374bc2c4c342b53bbf2950b9e792ec7e2084495

**Comment by Anewbe** [comment]
The cleaning thing for armor isn't actually a bug, but it'd be an easy fix, if'n it's needed.
Question; What do you mean by boots? Jackboots, or leg guards?

**Comment by FenodyreeAv** [comment]
Jackboots, combat boots. Leg guards could be washed, oddly enough.
