### ISSUE TITLE
Dark Click Catcher no longer catches clicks

### ISSUE THREAD

**Issue by Datraen** [PolarisSS13/Polaris#1997]
#### Brief description of the issue

When clicking upon a black square, the character does not interact with that area.
#### What you expected to happen

Character in the direction of the black square.
#### What actually happened

Nothing.
#### Steps to reproduce

Join.
Find spot where you cannot see a section of the screen.
Face away.
Click on dark spot.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
  6374bc2c4c342b53bbf2950b9e792ec7e2084495 
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by mistyLuminescence** [comment]
Reproduceable as of 21/5/19.

**Comment by Datraen** [comment]
Thank you for reminding me to unsubscribe.
