### ISSUE TITLE
Teshari Loneliness and Welder Vision Problems

### ISSUE THREAD

**Issue by Kholdstare34** [PolarisSS13/Polaris#1999]
#### Brief description of the issue

Sometimes, although not ALL the time, Teshari that join after roundstart encounter an issue where their welder vision is not applied, and their "loneliness" mechanic kicks in way too quickly (within ~20 seconds of not having another active mob on the screen). When this bug does NOT occur, Teshari don't get lonely at all. 
#### What you expected to happen

The loneliness and welder vision mechanics to work as intended. Welder vision to be applied on latejoining, and loneliness to kick in after a reasonable (minutes, not seconds) amount of time. 
#### What actually happened

See description.
#### Steps to reproduce

Join as a Teshari after roundstart... maybe. In some rounds it is present, others not. 
#### Additional info:

Server revision: master - 2016-06-27
6374bc2c4c342b53bbf2950b9e792ec7e2084495 
Anything else you wish to add:
Might be related to #1962 ? Might also have something to do with spending a certain amount of time observing/idling on the server and not being in-round, or something to do with how long the round has been going before joining.

**Comment by Arokha** [comment]
The welder vision part of this is fixed in https://github.com/PolarisSS13/Polaris/pull/2667 though I can't say if the other part is related or not.

**Comment by Anewbe** [comment]
No longer an issue
