### ISSUE TITLE
Suits don't hide gender

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#2004]
#### Brief description of the issue

Disguises (space suits, fire suits, etc) don't conceal one's gender
#### What you expected to happen

Wearing a suit, with my face covered, would hide my identity and my gender  (This is Blah, he is... -> This is Unknown, they are...)
#### What actually happened

Wearing a suit, with my face covered, did not hide my gender.
#### Steps to reproduce

1.) Have a gender
2.) Wear any soft/hard/hidey suit
3.) Examine self
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by MagmaRam** [comment]
I fixed this one by accident when changing jumpsuits & accessories
