### ISSUE TITLE
Custom Item, incorrect sprite. 

### ISSUE THREAD

**Issue by kimiza** [PolarisSS13/Polaris#2007]
Simple issue regarding Jane-Luc Prices custom RIS vest, after being made to use the pocketed sec-vest as a parent, it no longer uses the custom sprite which it initially had(icons/mob/suit/armoralt)

**Comment by Datraen** [comment]
Wrong repo, but I'll see about resolving it.

**Comment by Datraen** [comment]
Note to self for future reference: Do not reference cross-branch until merging into a different branch.
