### ISSUE TITLE
Kitchen is an inescapable hell for small mobs

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#2014]
#### Brief description of the issue

Many of the kitchen machines are inescapable by living mobs and completely erase them during use (including Teshari)
#### What you expected to happen

A horribly messed up corpse that might have tried to escape beforehand
#### What actually happened

Qdel, qdel everywhere.
#### Steps to reproduce

1.) Acquire Teshari
2.) Apply to meat spike/grill/oven
3.) Ask them if they can escape
4.) Laugh
5.) Eat the only evidence as their ghost ~~ahelps~~  bitches in dsay about being lolgibbed.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by EmperorJon** [comment]
Merge was from Aurora, yes? I don't know if they have any considerations as to players as small mobs at all.

**Comment by Yoshax** [comment]
Was from Bay which was from Apollo.

**Comment by OhEmGee** [comment]
this is a feature

**Comment by Screemonster** [comment]
At the very least removing a mob in this way should be logged. Same as the gibber.
