### ISSUE TITLE
Ingredients used in the new kitchen stop the final product from having stuff done to it

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#2026]
#### Brief description of the issue

If I use something in one of the kitchen machines, e.g. I put a piece of meat into the frier, and then turn that piece of fried meat into something using one of the other machines such as turning it into a personal pizza with the oven, I then cannot fry my final pizza and as such do not get the delicious fried color.
#### What you expected to happen

To be able to fry my final product because only the ingredient is fried.
#### What actually happened

I couldn't as it has already been fried.
#### Steps to reproduce
1. Take an item and fry it
2. Put it into the oven
3. Try to fry the thing out the oven. You can't.

**Comment by Zuhayr** [comment]
Not a bug, deliberate. Prevents fried grilled fried grilled fried grilled fried grilled roast diona nymphs.

**Comment by Hubblenaut** [comment]
Anyone want to close this?
