### ISSUE TITLE
Hugging misgenders people

### ISSUE THREAD

**Issue by elgeonmb** [PolarisSS13/Polaris#2036]
#### Brief description of the issue

When you do a help intent hug, the sex of the recipient is used to determine whether it's "to make [him/her/them/it] feel better", not the gender ID

#### What you expected to happen

Pronouns to come from gender ID like they do in the rest of the game.

#### What actually happened

Pronouns came from sex.

#### Steps to reproduce

Build character with gender/sex mismatch, obtain hugs.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

master - 2016-07-01

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

I swear if I get one damn tumblr joke I'll [omitted]

**Comment by Hubblenaut** [comment]
Should be checked with a few other things as well. Comb is coming to my mind right now.

**Comment by EmperorJon** [comment]
I think "types on his/her PDA" does it, too.

**Comment by Hubblenaut** [comment]
Gender Identity is weird :I 
How do other people realize them as the gender they want to be but not the one they biologically are?

**Comment by elgeonmb** [comment]
Nominally that would be from gender presentation but you can also /present/ however you want since you can pick your own clothes...

It's weird.

**Comment by elgeonmb** [comment]
Also-- yes it also does it for "shakes Name trying to wake [pronoun] up!"
