### ISSUE TITLE
Grammar issue.

### ISSUE THREAD

**Issue by JackeryFox** [PolarisSS13/Polaris#2050]
#### Brief description of the issue
Just a tiny mistake with the grammar in the text that appears when somebody speaks but the character is deaf.
Image attached.
![aec34f7037ea42288f06dcb8db0037a3](https://cloud.githubusercontent.com/assets/9394123/16632345/09000da4-43c4-11e6-9ea9-ae1935438f69.png)

#### What you expected to happen
"Alistair Waters talks but you cannot hear ."
#### What actually happened
"Alistair Waters talks but you cannot hear."
#### Steps to reproduce
Be deaf and have somebody else talk.
#### Additional info:
 - **Server Revision**: master - 2016-07-06
8c8dbf55fd90d84738a1c51d2370c34a5e842eea

**Comment by Anewbe** [comment]
Seems to be an issue with \him. Similar to #2036
