### ISSUE TITLE
Dissonant Scream also confuses the changeling

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#2052]
#### Brief description of the issue
The scream that confuses people and shatters lights also confused the changeling using it.
#### What you expected to happen
The changeling to not be confused by their own screaming.
#### What actually happened
They ran into walls, unable to comprehend the magnitude of what their vocal chords could produce.
#### Steps to reproduce
Be changeling, scream (Possibly recursively?)
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
You sure it's not Resonant Shriek? Dissonant is the EMP, which almost certainly affects the ling.

**Comment by Neerti** [comment]
Tried to reproduce this, failed to do so, with both normal resonant and recursive resonant.
