### ISSUE TITLE
Language Whitelists Don't Work

### ISSUE THREAD

**Issue by Neerti** [PolarisSS13/Polaris#2053]
#### Brief description of the issue

Aliens lose their languages except for GalCommon
#### What you expected to happen

Languages to be applied correctly.
#### What actually happened

Aliens lack their languages.
#### Steps to reproduce

Make new alien.
Join.
Check languages.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
  Server revision: master - 2016-07-06
  8c8dbf55fd90d84738a1c51d2370c34a5e842eea

**Comment by Anewbe** [comment]
https://github.com/PolarisSS13/Polaris/pull/2046 probably did it, I'm too tired to learn it right now.

**Comment by Anewbe** [comment]
This fixed yet?

**Comment by Atermonera** [comment]
Haven't experienced this in the past year, or heard any complaints about it. Should be able to be closed
