### ISSUE TITLE
Coolers Have Issues with Compound Limbs

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#2058]
#### Brief description of the issue
Compound limbs don't preserve properly inside of a portable freezer.
#### What you expected to happen
For both parts of the limb to be preserved.
#### What actually happened
One limb was preserved while the other decayed to septic.
#### Steps to reproduce
1.) Chop of someone's leg (with foot attached)
2.) Store in a portable freezer.
3.) Reattach the limb after some time
4.) Notice the leg is fine but the foot is septic.
#### Additional info:
 - **Server Revision**: master - 2016-07-06

**Comment by Anewbe** [comment]
Happens because the hand/foot is in the contents of the arm/leg and sees that, rather than the cooling item. I'll see if I can get a fix for this out tomorrowish.
