### ISSUE TITLE
Can't select other species as trader

### ISSUE THREAD

**Issue by Verarch** [PolarisSS13/Polaris#2064]
#### Brief description of the issue
Trying to become aliens (unathi, tajara, etc) as a trader doesn't work.
#### What you expected to happen
There to be multiple species to select from when spawning as trader (i have whitelists for most)
#### What actually happened
Only human was selectable
#### Steps to reproduce
Be trader
Have alien whitelist
cry as you can't be xeno scum

#### Additional info:
 - **Server Revision**: master - 2016-07-08
 - **Anything else you may wish to add** EJ acknowledged this

**Comment by Anewbe** [comment]
Might be broken for other things, too.

**Comment by EmperorJon** [comment]
As you said for the languages, https://github.com/PolarisSS13/Polaris/pull/2046 probably did it.
