### ISSUE TITLE
Ninja powersink doesn't work

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#2072]
#### Brief description of the issue
The ninja powersink does nothing. This totally ruins Ninja, basically.

#### What you expected to happen
Sparky drainy stuff.

#### What actually happened
Nowt. Bugger all. 

#### Steps to reproduce
Activate power sink. Click wire. Nothing. Click APC/SMES. UI! No draining.

#### Additional info:
 - **Server Revision**: master - 2016-07-09
108a8743f5eabe238f71483a33feb181f8bcf1f7 
 - **Anything else you may wish to add** **We are suspicious of #2028**

**Comment by Anewbe** [comment]
Standard dumb questions: Was the suit on? Was the suit cell empty? Was the source in question charged and connected to an active grid? Was the module damaged?

**Comment by EmperorJon** [comment]
Yes yes yes yes yes. This was tested across several servers (live, mine, I think Yosh's) in straight-from-spawn configurations. Suit on, power flowing, etc.

**Comment by Anewbe** [comment]
Power sink here: https://github.com/PolarisSS13/Polaris/blob/master/code/modules/clothing/spacesuits/rig/modules/computer.dm
Honestly not sure how the gauntlets would have broken this, might be affecting var/atom/interfaced_with or the proximity stuff?

**Comment by EmperorJon** [comment]
From what @Yoshax was saying, it seems the engage wasn't proccing.

**Comment by Yoshax** [comment]
Was able to proccall Engage, providing it with a target, and it drained power fine. There's a problem inbetween clicking on the target and calling Engage.

**Comment by Anewbe** [comment]
Has anyone tried draining from a stray cell? I'm stuck in the city for a bit or I'd not be asking these questions.
