### ISSUE TITLE
Robo limbs announced at round start

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#209]
Adding Bishop Cybernetics as /datum/robolimb/bishop, /datum/robolimb/bishop
Adding Hesphiastos Industries as /datum/robolimb/hesphaistos, /datum/robolimb/hesphaistos
Adding Zeng-Hu Pharmaceuticals as /datum/robolimb/zenghu, /datum/robolimb/zenghu
Adding Xion Manufacturing Group as /datum/robolimb/xion, /datum/robolimb/xion
Adding Morpheus Cyberkinetics as /datum/robolimb/ipc, /datum/robolimb/ipc
Adding Unbranded as /datum/robolimb, /datum/robolimb
Welcome to the pre-game lobby!
Please, setup your character and select ready. Game will start in 180 seconds

**Comment by Neerti** [comment]
Intentional but it does clog up the screen for admins (as I'm fairly sure only admins see the startup text now), so I'm all for removing it.

**Comment by Minijar** [comment]
This still happens at lobby screen.

**Comment by Neerti** [comment]
For non-admins?

**Comment by Zuhayr** [comment]
This is a fucked up debug, my fault.
