### ISSUE TITLE
Advanced Who doubles AFK listings (May be staff only)

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#2091]
#### Brief description of the issue
Using advanced who causes the AFK listing to appear twice
#### What you expected to happen
AFK listing would appear once
#### What actually happened
Anewbe - Playing as Deadbot - DEAD - 223 (AFK - 9 minutes, 16 seconds) (?) (AFK - 9 minutes, 16 seconds)
#### Steps to reproduce
1. Wait for some AFKs
2. Use Advanced Who
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by EmperorJon** [comment]
This will probably be a side-effect of the AFK listing being added for staff.
