### ISSUE TITLE
Damp Rag wets floor

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#2092]
#### Brief description of the issue
Wiping something down with a damp rag, like a glass, also cleans the floor as if you mopped it

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SinTwo** [comment]
This is actually an intended feature.
https://github.com/PolarisSS13/Polaris/blob/990d257d08126bfa62c17e3dc31e6dd55b4d99e0/code/modules/detectivework/tools/rag.dm#L106
It checks for mob, turf, and obj atom types for wiping down; however, this could probably be changed if it's unwanted behavior, although I don't see why that would be the case.

**Comment by SinTwo** [comment]
Don't mind the label swap, I misread the issue >_>
