### ISSUE TITLE
The hit that causes internal damage does less/no damage

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#2093]
#### Brief description of the issue

The hit on a body part that causes said part to suffer internal wounds (broken bones or IB) does less damage (down to 0, at times) compared to a hit that does not
#### What you expected to happen

Internally damaging attacks would process brute/burn normally
#### What actually happened

The hit that caused IB frequently deals no actual damage. The hit that breaks bones seems to do about half, seemed to occur more reliably after the bone was already broken, further cruching sound hits did 50% damage.
#### Steps to reproduce
1. Find a victim
2. Grab an esword
3. Stab the victim 2~3 times, until you hear a crunching sound
4. Health scan the victim
5. Do some multiplication
   #### Additional info:
   - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
   - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
     Probably https://github.com/PolarisSS13/Polaris/blob/master/code/modules/organs/organ_external.dm#L464

Might be intended, although I'm not sure why.

**Comment by SinTwo** [comment]
did some testing and only could replicate this with with a melee weapon and not a gun.

**Comment by Anewbe** [comment]
I had it fairly reliably on ranged and melee, but either way, strange stuff.
