### ISSUE TITLE
Health Bar Stays Up After Taking HUD Off

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#2098]
#### Brief description of the issue
The health bar shown from wearing a medical HUD stays up after the HUD is removed.
#### What you expected to happen
The health bar to disappear.
#### What actually happened
It stayed while the little plus simple disappears
#### Steps to reproduce
1.) Put on a health HUD
2.) Remove the HUD
3.) Notice health bars are still there

Ex: http://prntscr.com/brbhpm
#### Additional info:
 - **Server Revision**: master - 2016-07-10
64edc40839c5cea4cf5447717d08f7428454ac85 
 - **Anything else you may wish to add** I was using the prescription medical HUD when i experienced this. I doubt it's only specific to that, though.

**Comment by PsiOmegaDelta** [comment]
See https://github.com/Baystation12/Baystation12/pull/13653/commits/641fbfeff12d6aafb9b9a93868b9cba5d824d474
