### ISSUE TITLE
Door Invincibility

### ISSUE THREAD

**Issue by adstatus** [PolarisSS13/Polaris#2137]
#### Brief description of the issue

Doors can no longer be broken by melee attacks, which means you can't break a door then crowbar it open.

#### What you expected to happen

Axes and oxygen tanks to break doors.

#### What actually happened

Did not break doors.

#### Steps to reproduce

Use an item such as a fire axe, oxygen tank, or fire extinguisher on an airlock, with harm intent on. Observe as the door is not affected.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

2016-07-13
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Might be a one-line fix, I'll look at it in the morning.
