### ISSUE TITLE
Drone Brains are MMI's in code

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#2141]
#### Brief description of the issue

Drone Brains can't be activated to recieve players like a posibrain can be, they work like MMI's and need a human brain
#### What you expected to happen

for it to be activated like a posibrain and not function like a MMI
#### What actually happened

Activating them gives no prompt for ghosts to inhabit it, and from what I've been told code wise they are just MMI's
#### Steps to reproduce

have someone print a drone brain, activate it and watch as you get no prompt to inhabit it as a ghost
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
No longer pops out a brain, still doesn't have a call for ghosts.
