### ISSUE TITLE
Trying to vomit with an empty stomach crits you in less than a minute.

### ISSUE THREAD

**Issue by nachomeep** [PolarisSS13/Polaris#2142]
#### Brief description of the issue
If you take toxins damage, start vomiting, and end up with low hunger/nutrients, you get spammed with messages and damaged like hell.
EDIT: As soon as you wake up, it spams you until you're in crit again.
#### What you expected to happen
I get a message every once in a while, and some damage.
#### What actually happened
http://i.imgur.com/0QwGUJx.png
I got spammed with tons of messages and put into crit in 30 seconds.
#### Steps to reproduce
Take enough toxin damage to start vomiting. Don't eat.
If woken up, wait half a second for more damage to be applied since you're no longer unconscious.
#### Additional info:
 - **Server Revision**: Server revision: master - 2016-07-15 84b353785551d4aca6728835bf0c6d8f26ffa9c1

**Comment by EmperorJon** [comment]
I've already fixed and tweaked this, just need to clean my repo up before committing.
