### ISSUE TITLE
Random Medicine

### ISSUE THREAD

**Issue by Japak121** [PolarisSS13/Polaris#2174]
#### Brief description of the issue
The random medicine icon in the map that's supposed to spawn a medical item doesn't work, it's a pullable-nonpickup-item during a round. Doesn't do anything but sit there and be a small issue.

#### What you expected to happen
Not sure what happened, so idk.

#### Steps to reproduce
Go to the maintenance below medbay, to the right of the vault. They'll be right there on the floor. Everytime.

**Comment by EmperorJon** [comment]
Duplicate of #1892
