### ISSUE TITLE
Captain's Beret spite is broken.

### ISSUE THREAD

**Issue by zaeperry99** [PolarisSS13/Polaris#2183]
#### Brief description of the issue
The captain's white beret does not appear on your person. It does in your hand, but not on your head.

#### What you expected to happen
The sprite to be visible on your head once equipped.

#### What actually happened
The sprite was invisible.  I tried both Bald and Bedhead 2, the cleanest and messiest hairstyles I could think of, and neither were visible.

#### Steps to reproduce
Put on the captain's beret. Observe that it is invisible.

**Comment by Anewbe** [comment]
Think it's all hats.
Was the Bedhead showing up, or did you go totally bald with the Beret on?

**Comment by zaeperry99** [comment]
The hair was still there. And I just realized, playing engineer, that the gloves are invisible too.
