### ISSUE TITLE
Records are FUBAR'd.

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#220]
Hard to explain, but across all records consoles, all details(aside from stuff like age, male, race), will be switched around. IE, Crewmember A will have his records, Crewmember B, C, and D will have A's records. This also applies with criminal/arrest status as well. For example, crewmember A will be set to released, and this'll apply to B, C, and D as well.

Reproduction:
Have a decent amount of people with records set up.
Start viewing records and see who has who's records.
Attempt to set someone's criminal status(not sure if medical status or whatever it's called is bugged as well) and look at a security record's console.

**Comment by Mark9013100** [comment]
Unknown if Bay issue.

**Comment by Mark9013100** [comment]
Still an issue as of 12/2/2015.

**Comment by PsiOmegaDelta** [comment]
The reproduction steps are rather vague.

**Comment by Mark9013100** [comment]
Updated them a bit, hope it helps.

**Comment by Mark9013100** [comment]
Got a screenshot, this happened when I tried to set myself(Daniel Wilson) to arrest, instead, it set Korresh Reslish to arrest. Also had my security & medical records.

![](http://i.imgur.com/ct259Z0.png)

**Comment by PsiOmegaDelta** [comment]
Looks like an id conflict, which is how records are typically acquired. The issue would likely also be replicated for Duncan Garland and Michael Wallace.

**Comment by EmperorJon** [comment]
I can confirm that, yes.

**Comment by MagmaRam** [comment]
Possible alternate solution if the above commit/PR is unsatisfactory to a lot of people: Generate the digits of the ID one by one (this would also make it possible to use the full alphabet if you wanted alphanumeric rather than hexadecimal). This would be longer, look ugly, and probably be slower, but it'd allow a six-digit ID without rewriting hex2num(). There's probably some other ways that I'm not thinking of, too.

**Comment by GinjaNinja32** [comment]
@MagmaRam,
```dm
var/id = "[add_zero(num2hex(rand(0, 255)), 2)][add_zero(num2hex(rand(0, 65535)), 4)]"
```
