### ISSUE TITLE
Disposals room conveyor belt goes the wrong way.

### ISSUE THREAD

**Issue by serenemelody** [PolarisSS13/Polaris#221]
How am I supposed to throw trash out now?

**Comment by serenemelody** [comment]
Also, some of the reinforced glass can be damaged and potentially broken by the disposals unit throwing out objects.

**Comment by serenemelody** [comment]
And also the conveyor belt area randomly loses air.

**Comment by Mark9013100** [comment]
Is this still an issue?

**Comment by Woodratt** [comment]
https://github.com/PolarisSS13/Polaris/pull/442
