### ISSUE TITLE
Surgery is being pushy again mom

### ISSUE THREAD

**Issue by Spookerton** [PolarisSS13/Polaris#2220]
#### Brief description of the issue
1. **Stand** on any valid surgery surface
2. Receive attempted surgery message for any self-interaction, such as drinking from a container, rolling dice on your face, or beating yourself to death with large tomes.
3. Also you can do surgery to yourself make it stop goddamnit.
#### What you expected to happen
1. Surgery pls stahp
2. _Surgery noh_
#### Additional info:

![step1](http://i.imgur.com/kcfsets.png)
![step2](http://i.imgur.com/rjHU96b.png)
![step3](http://i.imgur.com/Fav028X.png)
![step4](http://i.imgur.com/5bjybTH.png)

![step5](http://i.imgur.com/Y99mVIa.png)
![step6](http://i.imgur.com/VRmB020.png)
![step7](http://i.imgur.com/NYFR9oo.png)

**Comment by Spookerton** [comment]
**Kali Maaaaaa**

![glorf](http://i.imgur.com/kgcABgz.png)

**Comment by EmperorJon** [comment]
Kali Myaaa?

**Comment by Spookerton** [comment]
Yes. Yes indeed.

**Comment by Atermonera** [comment]
Hasn't been observed recently by at least one medical main. Should be closeable
