### ISSUE TITLE
Condimaster Missing Create Button 

### ISSUE THREAD

**Issue by ParadoxSpace** [PolarisSS13/Polaris#2230]
#### Brief description of the issue

As on tin.
#### What you expected to happen

get bottle
#### What actually happened

not get bottle
#### Steps to reproduce

get ketchup/hot sauce ingredients ready, insert into condimaster, be unable to make ketchup/hot sauce
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SpadesNeil** [comment]
Is this still a problem?

**Comment by Atermonera** [comment]
Kitchen currently has a ChemMaster 3000, which definitely works, because it works for chemistry, so this can probably be closed
