### ISSUE TITLE
Chaplin Hood Has no Sprite

### ISSUE THREAD

**Issue by Edwardc120** [PolarisSS13/Polaris#2235]
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Nurse's hat, Changeling Space armor, too.

**Comment by EmperorJon** [comment]
Medical belt too @SinTwo
