### ISSUE TITLE
Research Outpost Dock Airlock Doesn't Work Properly

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#2241]
#### Brief description of the issue
The access buttons on the sides of the airlock don't cycle the airlock (docking port controller works)
#### What you expected to happen
The airlock to start cycling.
#### What actually happened
Nothing happened.
#### Steps to reproduce
1.) Go to Research Outpost
2.) Use access button.
#### Additional info:
 - **Server Revision**: master - 2016-07-31
76e9a5cba62219fc5b393d9aa3e69941c1df3007 
 - **Anything else you may wish to add** The buttons probably aren't synced to the airlock.

**Comment by Yoshax** [comment]
Works for me. Could not reproduce.
