### ISSUE TITLE
Medical belt has no onmob icon

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#2251]
#### Brief description of the issue
Medical belt has no onmob icon
#### What you expected to happen
To have an icon
#### What actually happened
It doesnt
#### Steps to reproduce
Put a medical belt on

**Comment by EmperorJon** [comment]
Sec belt too @SinTwo so uh, I'd suggest checking all the belts.

**Comment by Woodratt** [comment]
Toolbelt, is the same, especially if you switch belt layer.
