### ISSUE TITLE
Diona’s name reset after evolution.

### ISSUE THREAD

**Issue by Waismuth** [PolarisSS13/Polaris#2254]
After splitting as adult diona into the nymphs, waiting 200 ticks as normal and evolving back again into the adult form I’m given a randomly generated name. Not sure if there’s even a way of having your old character’s name without admin help, or if it’s still an unimplemented feature.

**Comment by SilverTalismen** [comment]
It's a unimplemented feature, It needs to be a prompt that let's you either keept he name you had before you split, or pick a new one

**Comment by EmperorJon** [comment]
IIRC it was confirmed the other day that a Diona the splits into nymphs and then reforms as another Diona is not the same individual.
