### ISSUE TITLE
Autotraitor AI do not have access to Law Manager

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#2258]
#### Brief description of the issue
One of the bizarre differences between traitors and autotraitors.

#### What you expected to happen
Have Law Manager access.

#### What actually happened
No Law Manager access.

#### Steps to reproduce
Set yourself up as an autotraitor, check, cannot edit the laws. Change that to normal traitor and boom, done.

#### Additional info:
 - **Server Revision**: master - 2016-08-01
1c4ecc7dd5c1522970661369263bd42b0341eb1b 
 - **Anything else you may wish to add**

**Comment by Mechoid** [comment]
As a note, auto-traitored borgs seem to have this issue as well, still.
