### ISSUE TITLE
You cannot dismantle filing cabinets.

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#2259]
#### Brief description of the issue
It's impossible to dismantle filing cabinets.

#### What you expected to happen
When using a lit welder on a filing cabinet, for it to be turned into an equal amount of steel to what you initially spent.

#### What actually happened
"You can't put that into a filing cabinet!" it said.

#### Steps to reproduce
1. Build (or find) a filing cabinet.
2. Unwrench it from the floor.
3. Try to weld it.

#### Additional info:
 - **Server Revision**: Stumbled on this bug in https://github.com/VOREStation/VOREStation/commit/a3835cb52f954f5278d7987f458f75fa90ce61c7 but I'm pretty sure it hasn't been fixed in Polaris either.

Should be a really easy fix. Just check istype(blah/blah/blah/welder)

**Comment by SinTwo** [comment]
You don't use a welder to take them apart, you "unscrew the bolts holding it together" to take it apart.

https://github.com/PolarisSS13/Polaris/blob/master/code/modules/paperwork/filingcabinet.dm#L47

**Comment by SpadesNeil** [comment]
Oh, derp.
