### ISSUE TITLE
Using the *faint emote as an android will stunlock you

### ISSUE THREAD

**Issue by Chnkr** [PolarisSS13/Polaris#2260]
See title.

**Comment by Anewbe** [comment]
Worked fine for me.

**Comment by Chnkr** [comment]
Interesting, it might be related to #2261 as i tried to `*faint` once i was unable to move, and was put into a state where i was unable to hear.

**Comment by Anewbe** [comment]
Was it a permanent stun lock, or did it fix itself?

**Comment by Chnkr** [comment]
I was permanently stunlocked.

**Comment by Anewbe** [comment]
Still works fine for me, what precisely did you do?
