### ISSUE TITLE
Receiving the 'you feel a shock' message from the SM radiation will stunlock androids

### ISSUE THREAD

**Issue by Chnkr** [PolarisSS13/Polaris#2261]
See title.

**Comment by Anewbe** [comment]
Android as in Cyborg, or Android as in Full Body Prosthetic/IPC?

**Comment by Chnkr** [comment]
FBP.

**Comment by Anewbe** [comment]
Is that the exact wording of the message 'You feel a shock'?

**Comment by Chnkr** [comment]
The exact message is `You feel a powerful shock course through your body!` which was shown to me when i attempted to open the door.

**Comment by Anewbe** [comment]
Then that's not SM radiation?

**Comment by Anewbe** [comment]
Yeah, recovered from the door shock too.
