### ISSUE TITLE
Painkillers locking health indicator

### ISSUE THREAD

**Issue by Hubblenaut** [PolarisSS13/Polaris#2265]
#### Brief description of the issue

Painkillers prevent the health indicator from updating.
#### What you expected to happen

For the health indicator to update to _something_.
#### What actually happened

Health indicator getting stuck on its last appearance, even when all wounds did heal long ago.
#### Steps to reproduce

Damage yourself, take painkillers, heal yourself.
#### Additional info:
- **Server Revision**: 1c4ecc7dd5c1522970661369263bd42b0341eb1b

**Comment by Spookerton** [comment]
Without checking, are you sure this isn't just a result of still being ON painkillers?
