### ISSUE TITLE
Atmos Substation Bypass is Lacking

### ISSUE THREAD

**Issue by zaredman** [PolarisSS13/Polaris#2266]
#### Brief description of the issue
Atmos doesn't have a Substation Bypass
#### What you expected to happen
things get power
#### What actually happened
things didn't get power
#### Steps to reproduce
just start the engine without turning on the Atmos substation and eventually suffocate in two days time.
#### Additional info:
woo issue numba 200.

**Comment by Hubblenaut** [comment]
Was actually an issue somewhere in range of issue 700 to 800 :P
