### ISSUE TITLE
Xenobiology and the Xeno-Tasers

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#2272]
#### Brief description of the issue

The xenotasers do not work on the slimes
#### What you expected to happen

To be able to stun the attacking slime with the xeno-taser
#### What actually happened

It did nothing even after I unloaded the full charge into it
#### Steps to reproduce

Go to xenobiology, get any slime, taser them, watch as nothing happens and you possibly get mauled
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Datraen** [comment]
I've not personally experienced this, but if someone wants to review the code, they can.

**Comment by SpadesNeil** [comment]
Seems to be working fine as of https://github.com/PolarisSS13/Polaris/commit/729956de191474113e947f9f37ba56c83e6929e7

**Comment by Anewbe** [comment]
Seems to be fine, closing.

**Comment by Anewbe** [comment]
I was wrong, woops.
