### ISSUE TITLE
Xenobiology and mutant slimes

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#2275]
#### Brief description of the issue

It seems, from the few rounds I've played mutant slimes that I've injected with nutriment don't ever grow up, while the base grey baby ones do
#### What you expected to happen

For my blue/purple/red slimes to grow up
#### What actually happened

Three hours with a baby mutant slime
#### Steps to reproduce

Join Xenobiology, 
mutate a grey slime into any color mutant
 watch it never grow up
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
This can be closed following #3767
