### ISSUE TITLE
Missing or broken disposals pipe.

### ISSUE THREAD

**Issue by ColaFiend** [PolarisSS13/Polaris#2310]
#### Brief description of the issue
Disposal pipe not mapped correctly somewhere in red rectangle
http://i.imgur.com/undefined.png

#### What you expected to happen
The items went down disposals
#### What actually happened
The pipe wasn't there so they shot out damaging the floor tile
#### Steps to reproduce
Use disposals pipe in locker room.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Kelenius** [comment]
Your image link is broken.

**Comment by ColaFiend** [comment]
Ah sorry this should be it: http://imgur.com/a/hSFlS
