### ISSUE TITLE
Long Records Get Eaten By Attempts To Edit

### ISSUE THREAD

**Issue by elgeonmb** [PolarisSS13/Polaris#2311]
#### Brief description of the issue
If your records are sufficiently long, they'll show up fine on med/sec/employment consoles, but if someone clicks them to edit them (or accidentally clicks them to edit them) they'll be truncated.

#### What you expected to happen
Being able to change long records

#### What actually happened
All my special snowflake medical doctor's notes are destroyed

#### Steps to reproduce
1) Make edgelord with long records
2)Go to record console
3)Edit records
4)Cry

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Yoshax** [comment]
Uhh... I'm inclined to say not a bug, because the length for records is 24576 characters. Or 4900 words with an average of 5 character length. Although, I suspect there may be an issue between displaying and editing.

**Comment by SpadesNeil** [comment]
The limit between what you can edit in character setup, verses the limit set by these computers, are two different limits, and it causes problems.
