### ISSUE TITLE
Possible to clone departed players.

### ISSUE THREAD

**Issue by Screemonster** [PolarisSS13/Polaris#2312]
#### Brief description of the issue

Players that leave via the residential elevator, teleporter or cryopods remain on the cloning database if they've been scanned. On servers with respawn enabled, if they subsequently join as another character and some doctor mashes the clone button, they wind up yanked out of the character they're playing and stuffed into a clone of the character that left the station.
#### What you expected to happen

For players to be removed from cloning databases when the character leaves the game.
#### What actually happened

Suddenly in clonebay without warning while previous body drops braindead to the floor.
#### Steps to reproduce

Get scanned.
Leave game via cryo.
Ghost. Respawn. Rejoin as different character/job.
Have a doctor mash clone.
#### Additional info:

Possible fix by having the cryo pod check for the health implants the cloner uses?

**Comment by SpadesNeil** [comment]
This was once fixed by https://github.com/SpadesNeil/VOREstation/pull/682 in old Vorecode.
