### ISSUE TITLE
Atmos Substation Mapping issue

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#2333]
#### Brief description of the issue
There's no wires or pipes under the door between maint and the Atmos substation
#### What you expected to happen
The pipes and wires to exists
#### What actually happened
They do not
#### Steps to reproduce
1.) Enter atmos substation
2.) Open maint door
3.) Choke to death on airless station
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by EmperorJon** [comment]
... how did this happen? o_O

**Comment by Yoshax** [comment]
Fixed in #2331
