### ISSUE TITLE
Missing wires/piping at atmos substation

### ISSUE THREAD

**Issue by Hubblenaut** [PolarisSS13/Polaris#2336]
#### Brief description of the issue
There's missing wires and pipes at the atmospherics substation.
#### What you expected to happen
I expected there to be wiring and pipes.
#### What actually happened
Atmos is missing these pipe segments and therefore entirely disconnected from the rest of the station, leaving everyone to suffer a painful death due to suffocation.
#### Steps to reproduce
Head to atmospherics substation, open maint door, notice there's a mapping mistake.
![Image](http://i.imgur.com/E28IAj0.png)

#### Additional info:
 - **Server Revision**: 288768b9037e0a3130347b71731df554a1fc32b2

**Comment by Yoshax** [comment]
Fixed in #2331
