### ISSUE TITLE
HOS Electritrochromoboogalo Windows lack a mapped ID assignment

### ISSUE THREAD

**Issue by zaredman** [PolarisSS13/Polaris#2337]
#### Brief description of the issue
HOS Electritrochromoboogalo Windows lack an ID

#### What you expected to happen
They had an ID assigned to them.

#### What actually happened
Their ID is 'null' and would pose an annoyance for people mapping other windows since it would toggle any 'null' window.

#### Steps to reproduce
Right click > VV on window > Check ID > Find that it's NULL
#### Additional info:
WE GOIN' TA ROCK

DOWN

TO

**Comment by Anewbe** [comment]
ELECTRIC AVENUE!

Pretty sure the windows woks just fine as is, but okay.

**Comment by PsiOmegaDelta** [comment]
The buttons to toggle electrochromic windows only operate within a certain range and as such a null-id isn't necessarily a big problem unless several sets of windows are close together (for example, the patient section on Bay which require ids to not have buttons toggle the wrong windows).
