### ISSUE TITLE
Items that are "on" don't interact with alien artifacts

### ISSUE THREAD

**Issue by PurpleMartinJCK** [PolarisSS13/Polaris#2343]
#### Brief description of the issue

 As an anomalist, I was attempting to activate an artifact with several different items.
#### What you expected to happen

 I expected to get a confirmation message or whatever that's called saying "your character has hit the alien artifact with the stun baton"
#### What actually happened

When the baton was off, it hit as expected. When the baton was on, it wouldn't strike it anymore, even on harm intent. This too happened with the welder and the lighter.
#### Steps to reproduce

Find an alien artifact. Take a stun baton and turn it on. Click the artifact.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Not that they don't hit it, but that they have spaghetticode special interactions
