### ISSUE TITLE
Gear Harnesses can Be Accessed By Organics/Non-Diona

### ISSUE THREAD

**Issue by ParadoxSpace** [PolarisSS13/Polaris#2345]
#### Brief description of the issue

the tin
#### What you expected to happen

only robots and diona to access it
#### What actually happened

apparently humans/taj/unathi/whatever can access it
#### Steps to reproduce

take it from custom loadout
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Use your best judgement.

**Comment by Serithi** [comment]
Is this really a problem, though? It's not exactly ideal since non-Dionaea have access to the full inventory anyway, but why would they really be prevented from wearing them?

**Comment by ParadoxSpace** [comment]
Because i105

**Comment by Serithi** [comment]
Can have a shirt and shorts with the underwear system. Or attach the pants to the harness.

I'm just saying, if someone's running around naked except for the harness, that's no different than if they're wearing anything else while naked, and will be dealt with the same way. It's not a reason for artificial limits.
