### ISSUE TITLE
Can't Promote ID to Station Adminitrator

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#2391]
#### Brief description of the issue
There is no option to set an ID to the station administrator occupation. The old captain button doesn't work.
#### What you expected to happen
To be able to make an ID a station administrator.
#### What actually happened
I was unable to do so.
"No log exists for this job: Captain"
#### Steps to reproduce
1.) Put an ID into the ID console with another ID that can modify it
2.) Try to make it a station administraotr.
#### Additional info:
 - **Server Revision**: master - 2016-08-29
10d48d74209842cb365e15fc6b030fa3ae5be941

**Comment by Neerti** [comment]
#2386 should fix this.

**Comment by Anewbe** [comment]
Fixed
