### ISSUE TITLE
Elevator does not spawn dirt or metal when moved--just space.

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#2408]
#### Brief description of the issue
Shuttles between Z-levels was replaced with elevators for some applications on the station. There should not be a gaping hole to the void of space when an elevator is moved. Rather, it should be replaced with metal. Namely, /fixed tiles that cannot be damaged or destroyed by players trying to rip them up.

#### What you expected to happen
When an elevator moves to another Z-level, the empty zone should have steel tiles left over, or at least dirt.

#### What actually happened
![capture](https://cloud.githubusercontent.com/assets/6484985/18155072/da99665a-6fd7-11e6-96ad-1b10f79751d8.PNG)

#### Steps to reproduce
1. Move an elevator.
2. Observe the results on the spot you left behind.

#### Additional info:
 - **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/b83750a804dad7e0ce1b92e61955005db11e0898
 - **Anything else you may wish to add**: You'll notice that the map has dirt where the elevator's destinations are. These also get deleted when the elevator moves back again.

**Comment by Neerti** [comment]
This is not a bug, as those are meant to visually be elevator shafts.  You can change this behaviour by changing the ```base_turf``` type on the area.

**Comment by SpadesNeil** [comment]
>This is not a bug, as those are meant to visually be elevator shafts.

That doesn't make any sense. An elevator shaft has to go up or down. You can see down into space in both cases.

>You can change this behaviour by changing the base_turf type on the area.

So it's a mapping issue, then?
