### ISSUE TITLE
Gas coolers (and presumably heaters) cannot be built properly

### ISSUE THREAD

**Issue by MagmaRam** [PolarisSS13/Polaris#2431]
#### Brief description of the issue
When you build gas coolers, you can't add cables, a required component at the step where you insert capacitors, matter bins, etc.

Also, either connecting the cooler to a pipe network is very difficult or it's altogether impossible, and controlling the direction that it faces is impossible.

#### What you expected to happen
To be able to finish the machine. Also, to be able to face it and connect it.

#### What actually happened
When you need to add cable coils, you simply can't. It doesn't work. In addition, the cooler faced west and couldn't be rotated, and even when rotated south (via varedit) it wouldn't connect to a pipe fastened in front of it the proper way.

#### Steps to reproduce
Build a gas cooler from a machine frame and enjoy the frustration.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
cf4785364bef85d9b1eb9b85e426a1002520f4a1 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Unless Sin's rewrite of machine code changed it, the direction the heater/cooler faces and connects to other pipes is the direction you're facing when you create the machine frame, immediately prior to cabling and adding a circuit.
