### ISSUE TITLE
Cargo shuttle can be overfilled, resulting in missing crates.

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#2437]
#### Brief description of the issue
32 crates is the maximum number of boxes the shuttle can currently handle. Any more, and the rest get lost somehow, with no return on points.

#### What you expected to happen
For there to be a prompt telling you the shuttle is full.

#### What actually happened
That asshole Garry at the CentCom logistics department lost my cargo in transit and I think it got jettisoned over a small space nature reserve and now space penguins have my guns. Tim told him it wouldn't fit but did Garry listen? Ooohhhh noooo, "It'll fit!" he says. "Just stack them on top of each other!" he says.

#### Steps to reproduce
1. Get a lot of cargo points.
2. Buy all the things! More than 32 things.
3. Call the shuttle in.
4. Realize your cargo is missing.
5. (Optional) Cuss out Garry with an angry fax.

#### Additional info:
 - **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/91917eaadf5c98c07ef63dd36da334a8a1cf3433

**Comment by Screemonster** [comment]
brb spriting space penguins for the snow level
