### ISSUE TITLE
Teshari Bugs?

### ISSUE THREAD

**Issue by ParadoxSpace** [PolarisSS13/Polaris#2439]
#### Brief description of the issue

Well first off, I have an instability meter in the corner of my screen. Second, after climbing a table, I was apparently hit by the ultimate nullifier. http://puu.sh/r3yHR/1b87b9b10f.png
#### What you expected to happen

none of these things
#### What actually happened

these things
#### Steps to reproduce

be a bird, climb a table
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Trying to eat the taco is related to #2220

**Comment by Anewbe** [comment]
This was fixed a while ago.
