### ISSUE TITLE
gib() does not respect icons

### ISSUE THREAD

**Issue by Screemonster** [PolarisSS13/Polaris#2449]
#### Brief description of the issue

When a mob is gibbed, it doesn't display the correct gibbing animation. The whole proc is rather old and in need of a little love as it seems to point at mob.dmi with all the other really horrible really old icons.
#### What you expected to happen

For simplemobs, when gibbed, to not play an animation if there isn't one defined (as the icon defaults to NULL) or play the appropriate animation if it is. Also for other races when gibbed to show their appropriate icons.
#### What actually happened

Simplemobs without a defined animation very briefly turn into monkeys for their gib animation. Those with an animation defined simply don't show anything, even with the icon defined. Tajara and other nonhuman races suffer from sudden explosive humanism when gibbed.
#### Steps to reproduce

Spawn a mob.
Gib it from the VV panel.

**Comment by MagmaRam** [comment]
Do we actually have animations for the other species buried somewhere in the icons folder?

**Comment by Screemonster** [comment]
animal.dmi has a whole bunch of gib icons for cows, carp, chicks, lizards, bears, as well as a generic icon that I added in the PR that added geese.
Problem is, gib() looks in mob.dmi for its animation regardless of where it's actually told to look as far as I can tell.
I haven't tested dust() but I wouldn't be surprised if that's affected too as that's one of the other things in mob.dmi.

**Comment by MarinaGryphon** [comment]
If this is sufficiently fixed, I'll make the PR. If you want, the same changes can be made to `dust()`.
https://i.imgur.com/TKjdr7f.gifv
