### ISSUE TITLE
Caffine overdose is too inconsequential

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#2516]
#### Brief description of the issue

My CMO drank **three pints** worth of coffee in a single sitting.
#### What you expected to happen

Them to have a heart attack and die, or at least start puking and frothing at the mouth. Also seizures are nice.
#### What actually happened

They drank more coffee.
#### Steps to reproduce

Drink lots of coffee.
#### Additional info:
- **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/34cc19cf1e1f63a3ec69d5c160f308a824a78a25
- **Anything else you may wish to add:** http://www.healthline.com/health/caffeine-overdose

**Comment by Atermonera** [comment]
Coffee has an OD threshold of 45, but the only effect is that non-Diona become jittery.
Search for coffee under /code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm

**Comment by SpadesNeil** [comment]
I feel like it should cause more harm than making you jittery.

Maybe rattle your whole damn screen around at least.

**Comment by MagmaRam** [comment]
Six cups of coffee isn't enough to cause serious harm to an adult human. You have to get into the 50+ range for that. Caffiene isn't really all that dangerous, that's why it's the world's most commonly consumed psychoactive drug.

**Comment by SpadesNeil** [comment]
6 cups of coffee in real life is at least going to make you not feel very well.

Symptoms of caffeine overdose include:
    dizziness
    diarrhea
    increased thirst
    insomnia
    headache
    fever
    irritability

and more serious symptoms for more severe overdoses that **require medical aid** are
    trouble breathing
    vomiting
    hallucinations
    confusion
    chest pain
    irregular or fast heartbeat
    uncontrollable muscle movements
    convulsions

It's all in the source I left on my issue post.

**Comment by MagmaRam** [comment]
If you think six cups of coffee will do anything more than maybe make you a little jittery (and that's if you don't drink it often), you don't drink very much coffee. Six-shooters are fairly normal at places that serve espresso. Ten or more isn't unheard of. I didn't see anyone drop dead on the floor while I was working at coffee shops.

**Comment by SpadesNeil** [comment]
Again, I'm not asking for people to drop dead. Just get sick.

**Comment by RenScorch** [comment]
I think the problem here is that the amount of coffee you need to ingest to trigger problematic caffeine overdosing is theoretically impossible.  However real life caffeine overdose IS dangerous, but the amount of caffeine in coffee is TINY compared to something like an Energy drink, or a caffeine pill(the two perhaps most common ways to get caffeine overdose). 

Instead of trying to make coffee dangerous, why don't you make caffeine dangerous and add more ways to get caffeine in your systems besides just coffee.

Food for thought.

**Comment by Iamgoofball** [comment]
If you're going for MUH REELS here don't forget to take conditioning, addiction, and tolerance into account

**Comment by SpadesNeil** [comment]
> I think the problem here is that the amount of coffee you need to ingest to trigger problematic caffeine overdosing is theoretically impossible. However real life caffeine overdose IS dangerous, but the amount of caffeine in coffee is TINY compared to something like an Energy drink, or a caffeine pill(the two perhaps most common ways to get caffeine overdose).
> 
> Instead of trying to make coffee dangerous, why don't you make caffeine dangerous and add more ways to get caffeine in your systems besides just coffee.
> 
> Food for thought.

I actually quite like this.

> If you're going for MUH REELS here don't forget to take conditioning, addiction, and tolerance into account.

See, now you're just giving me ideas on how to make this _more_ complicated.

**Comment by Nerezza** [comment]
I think the jittery animation's just silly at this point. It's fine for other effects, but for caffeine overdose it's too silly.

**Comment by Iamgoofball** [comment]
lighten up, it's a slight pixel shift
