### ISSUE TITLE
Feminine Wallets Bug

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#2547]
#### Brief description of the issue
Spawning with feminine wallets gives you a blank item you can do nothing with
#### What you expected to happen
To spawn with a cute wallet for my characters purse
#### What actually happened
Got a blank non existant item taking up space in my satchel
#### Steps to reproduce
Choose a wallet in the loadout, spawn with it, watch as nothingness takes up space
#### Additional info:
 - **Server Revision**:master - 2016-09-25
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
#2550
