### ISSUE TITLE
Maintinence Drones cannot construct reinforced walls

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#2564]
#### Brief description of the issue
I'm not sure if this is intentional, but it seems like a bug. Either that or I'm dumb and don't know how to build r_walls anymore.

#### What you expected to happen
If I use the sheet collector to pick up plasteel, I should be able to construct a reinforced wall in the usual method.

#### What actually happened
A regular wall gets made.

#### Steps to reproduce
1. Obtain plasteel.
2. Build a wall girder.
3. As a drone, pick up the plasteel sheets.
4. Attempt to put the plasteel sheets onto the girder.
5. Get regular wall.
6. (Optional) Deconstruct this borked wall to get your plasteel back.

#### Additional info:
 - **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/50b07f00a707d74df0a35e0b8ff9bc68bf0381ad

**Comment by Anewbe** [comment]
Sheet Collector can't be used for building iirc, it's solely for carrying sheets.

**Comment by Screemonster** [comment]
The construction process for rwalls was changed at some point. Don't know when, but if those are the steps you took then you missed the part with the screwdriver.

The new process for rwalls is on the polaris wiki:
Click the metal in your hand to open the construction panel,
Choose 'wall girders' form the list
Use the screwdriver on the girder to begin reinforcing.
Click on the girder with the reinforced metal (or some other material) in hand.
Use the last sheet of reinforced metal (or some other material) on the reinforced girders to finish the wall

**Comment by SpadesNeil** [comment]
Closing this, then. I'm an idiot.
