### ISSUE TITLE
Spawn Character function for admins only produces male sprites

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#2568]
#### Brief description of the issue

You cannot spawn female characters.
#### What you expected to happen

To spawn female characters if the player is set as female.
#### What actually happened

Femboy instead.
#### Steps to reproduce
1. Make female character.
2. Go observe.
3. Special verbs -> Spawn character -> Spawn that person.
4. Not a girl sprite.
#### Additional info:
- **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/50b07f00a707d74df0a35e0b8ff9bc68bf0381ad

**Comment by RenScorch** [comment]
The issue here is the fact that new features have been added into the game, and the admin panel hasn't kept up very well.

**Comment by Arokha** [comment]
This was fixed, @Anewbe or @Neerti

**Comment by Atermonera** [comment]
Reportedly fixed
