### ISSUE TITLE
[Map] Dark corner in Robotics Lab

### ISSUE THREAD

**Issue by RoseCG** [PolarisSS13/Polaris#257]
Likely a illumination issue, unsure. Despite the nearby lamb, the lower left corner to the robotics lab is considerably darker compared with the rest.

![lightspot](https://cloud.githubusercontent.com/assets/4467044/10540140/32769852-73fd-11e5-9a16-f2ba652e5e95.PNG)

**Comment by Woodratt** [comment]
Fiiixed, ty.
