### ISSUE TITLE
Replace Station Administrator with Colony Director

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#2601]
#### Brief description of the issue
I hate this name. Station Administrator.

So I emailed NASA.

They emailed me back.

Turns out, we're all wrong. Administrator, Captain, Overseer, Site Manager, THEY'RE ALL WRONG. Well, not entirely, but they're not correct, either. NASA says the title they'd choose for someone running this station would be "Director." The phrase "Administrator" would be reserved for office jobs, IE, CentCom's Administrators.

To directly quote the email...

> Greetings,
> 
> Thank you for your email and interest in NASA.
> 
> This is an intriguing question and I’ve sent some queries out to other offices. I have so far come up blank on formal agency policies dealing with this, although I do not have access to the Center policies of Johnson Space Center which trains and manages the astronaut programs.
> 
> Reviewing the crew descriptions from shuttle and ISS missions (and finding a confirming section within NASA Historical Data Book, Vol. VII: NASA Launch Systems, Space Transportation, Human Spaceflight, and Space Science, 1989-1998. NASA SP-4012, Washington, DC: NASA History Program Office, 2009), the ranks are as follows:
> ·         Commander
> ·         Pilot
> ·         Mission Commander
> ·         Mission Specialist
> ·         Payload Commander
> ·         Payload Specialist
> 
>  In discussing your query with my team, we realized there could be a different analogue within the agency since your station would presumably have more than a half-dozen members – Center Management (for example, this is the Org Chart for the Goddard Space Flight Center in greenbelt, MD). **So, it this case, the title would be “Director”**. At the agency level, the top person would be the Administrator, followed by Deputy Administrator, then Associate Administrators operating the different offices. My suspicion on a large research facility such as you describe would be that the Center Management organization would be the more likely arrangement.
> 
> If I find formal policies, I will be sure to pass them along to you.
> 
> Thank you for an interesting query to end the day.
> 
> Yours,
> Rick Spencer

There you have it!

>So, it this case, the title would be “Director”

#### Additional info:
 - **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/7e79d9b5f8ae524897b944e931bd6df77968f7c7

**Comment by ParadoxSpace** [comment]
Being that NASA itself answered this, I'd throw in my vote.

**Comment by SpadesNeil** [comment]
I'm working on the PR right now.

**Comment by Anewbe** [comment]
This isn't really an issue, just make a PR for this sort of thing, please.
Also, Director's already sort of taken, by Research.
