### ISSUE TITLE
Exosuit Grippers can use the same atachment infinatly on mechs.

### ISSUE THREAD

**Issue by Edwardc120** [PolarisSS13/Polaris#2609]
#### Additional info:  This could easily be used for making infinite materials if you can recycle the parts
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Edwardc120** [comment]
Side Note as well when you try to remove the other two drills you can't there stuck there on the mech.

**Comment by Atermonera** [comment]
This should've been closed by #2864
