### ISSUE TITLE
Friend computer AI status shows on all displays

### ISSUE THREAD

**Issue by robovelcro** [PolarisSS13/Polaris#2627]
#### Brief description of the issue

Anything except Friend Computer doesn't actually display on all of the monitors.
Easiest to see in the AI Core. Left one doesn't work properly, right one does.
#### What you expected to happen

To display all Status' everywhere
#### What actually happened

Section 1
#### Steps to reproduce

Be AI, run through all the options while in the core
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
  Server revision: master - 2016-10-08
  caa7d8a32f9d128a7b90d5dca62da403beef4907 
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)
  Seems to not affect all of the monitors. I don't know if there's two kinds? Or it's issues with the monitors themselves, or the images that are stored. That ain't my area of expertise.

**Comment by Neerti** [comment]
Are you sure that the half that is not working are not the normal status displays, which display text and not pictures?

**Comment by PsiOmegaDelta** [comment]
I'm pretty sure Polaris removed the "ability" for the "Friend Computer" status to affect all displays, be they AI displays or not. That always was a bit awful.

**Comment by robovelcro** [comment]
I don't know if they are status displays or not (am not currently on it) but if that IS the case, then the bug is the other way: The "Friend Computer" status displays on screens it shouldn't.
