### ISSUE TITLE
Disassembling sleepers with people inside them deletes the mob inside!

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#2630]
#### Brief description of the issue

Surely this is a bug!
#### What you expected to happen

Not be able to deconstruct sleepers when people are in them.
#### What actually happened

Player was deleted.
#### Steps to reproduce
1. Shove ~~victim~~ patient into sleeper.
2. Be dumb engineer borg.
3. Deconstruct the sleeper with a person inside.
#### Additional info:
- **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/85d1ef3062076d89d91c00236bdf579698389d82

**Comment by SariNeruda** [comment]
On top of this bug, the Sleeper at the first aid station IIRC you could not eject the person inside, which was what prompted the disassembly

**Comment by Atermonera** [comment]
Problem appears to be [here](https://github.com/PolarisSS13/Polaris/blob/0bb15b27324a371804f8f625708cbe8bb03b00e0/code/game/machinery/machinery.dm#L129-L140) , where machine deletion also deletes all contents.
