### ISSUE TITLE
output circuits spam world with "no sound"

### ISSUE THREAD

**Issue by Screemonster** [PolarisSS13/Polaris#2635]
#### Brief description of the issue
ICs spam "no sound" to the entire world. Reported by players, haven't had a chance to test myself yet.

#### What you expected to happen
Maybe to send an error message to whoever is fiddling with them iunno

#### What actually happened
No sound
No sound
No sound
No sound
No sound
No sound
looc why the hell is my screen full of "no sound"

#### Steps to reproduce
mess with ICs, don't pick a sound.

#### Additional info:
Should probably not be "world <<" in this section:

```
/obj/item/integrated_circuit/output/sound/do_work()
	var/datum/integrated_io/ID = inputs[1]
	var/datum/integrated_io/vol = inputs[2]
	var/datum/integrated_io/frequency = inputs[3]
	if(istext(ID.data) && isnum(vol.data) && isnum(frequency.data))
		var/selected_sound = sounds[ID.data]
		if(!selected_sound)
			world << "No sound"
			return
		vol.data = Clamp(vol.data, 0, 100)
		frequency.data = round(Clamp(frequency.data, 0, 1))
		playsound(get_turf(src), selected_sound, vol.data, frequency.data, -1)

**Comment by Anewbe** [comment]
If you click the left side of the line, while in the file, it lets you link the line within the file, which is very helpful in trying to fix these things.

**Comment by Screemonster** [comment]
https://github.com/PolarisSS13/Polaris/blob/2ddaf042264c26f133e97382391a8868eade79af/code/modules/integrated_electronics/input_output.dm#L414

Oh neat. Well, that's the offending line.
