### ISSUE TITLE
Radiance Affects The User

### ISSUE THREAD

**Issue by ParadoxSpace** [PolarisSS13/Polaris#2636]
#### Brief description of the issue

Title
#### What you expected to happen

For me to not be hit with ionizing radiation.
#### What actually happened

I did.
#### Steps to reproduce

Use radiance, cry.
#### Additional info:
- **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
- **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
That's intended.

**Comment by ParadoxSpace** [comment]
That's kind of ridiculous.
