### ISSUE TITLE
Flashlights don't turn themselves off when they run out of battery power.

### ISSUE THREAD

**Issue by Atermonera** [PolarisSS13/Polaris#2639]
#### Brief description of the issue
When flashlights run out of power, they follow the steps to turn themselves off, but the icon_state doesn't update, and at the next process() tick, it repeats, spamming logs with the message.
#### What you expected to happen
The flashlight would turn itself off and everyone would be in the dark, but happy.
#### What actually happened

![](http://i.imgur.com/3zxqhcs.png)

#### Steps to reproduce
Grab a flashlight
Give it an almost empty powercell and turn it on.
Wait for the battery to die
Watch warnings fill the chat.
#### Additional info:
Within [/obj/item/device/flashlight/process()](https://github.com/PolarisSS13/Polaris/blob/master/code/game/objects/items/devices/flashlight.dm#L56-L67), it appears that when the flashlight attempts to turn itself off, it doesn't change the brightness level or the power usage, which allows it to get back into that clause at the next process(). I don't know how it gets past if(on), and I haven't seen it in a dark enough instance to tell if it's still emitting light when this occurs.

**Comment by Anewbe** [comment]
Should already be fixed, we just need an update.

**Comment by Atermonera** [comment]
Ah, ok
