### ISSUE TITLE
Research Borgs' grippers cannot insert objects into other borgs.

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#2671]
#### Brief description of the issue

Research borgs' science grippers cannot insert objects, such as powercells or upgrades, into other borgs. They can take them out, and go through the process of putting it back in, only for the object not to go in.
#### What you expected to happen

Research borg takes old cell out, grabs new one, smacks other borg, puts in cell.
OR
Research borg picks up upgrade, uses on other borg or itself. Upgrade goes in.
OR
Research borg removes broken bits from other borg, and puts in new ones using the gripper.
#### What actually happened

Cell remains un-inserted.
Upgrade remains un-inserted.
Parts remain un-replaced.

Other borg is very unhappy.
#### Steps to reproduce

-Be research borg, with other borg.
-Open other borg's panel, use gripper on borg, you now have the cell.
-Hit them with the gripper again to try and insert the cell. Notice cell doesn't go in.

-Be R. borg, other borg not needed.
-Pick up any upgrade, open to-be-upgraded borg's panel, yours or theirs.
-Smack with gripper, get told the upgrade is installed.
-Note it doesn't actually get installed.

-Be R. borg, with broken friend borg.
-Open panel of other borg, remove cell to access parts.
-Crowbar out broken pieces, try using the gripper to install the replacements.
-Note it does the same as the upgrade.
#### Additional info:
- **Server Revision**: 109e7962c4d48743688f52826a97cad8b7874175 
- **Anything else you may wish to add** Gripper bugs continue to compound on one-another. The issue seems like it would have the same reason across all of them, due to their nature.

**Comment by Nerezza** [comment]
The problem starts in 
>code\modules\mob\living\silicon\robot\drone\drone_items.dm

```
/obj/item/weapon/gripper/attack(mob/living/carbon/M as mob, mob/living/carbon/user as mob)
	src.loc << "Attack called"
	if(wrapped) 	//The force of the wrapped obj gets set to zero during the attack() and afterattack().
		force_holder = wrapped.force
		wrapped.force = 0.0
		wrapped.attack(M,user)

		if(deleted(wrapped))
			wrapped = null
		return 1
	return 0
```
wrapped.attack(M,user) /is/ being called, but it isn't being processed by robot.dm's attackby like it should.

**Comment by Atermonera** [comment]
attackby(), according to Anewbe, procs on being clicked on, or something similar. At any rate, wrapped.attack wasn't triggering the attackby. I have a fix written up, and I'll PR it later today once I do some more testing with possibly related issues.
