### ISSUE TITLE
[Feature] Hyperzine could use some more downsides.

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#2691]
#### Brief description of the issue

It's a little OP. "Hyperzine is currently only used to get an edge on time and other people / security. There's no reason not to get an IV of it watered down and drag it around with you."
#### What you expected to happen

Someone suggested, "Hyperzine has no downsides. Give it something like consistent brute damage over time and lower it's OD rate to five units. That way, it can still be useful without being openly used."

I think that's stupid tbh, but maybe consuming too much induces seizures! Stuns you, you fall over, and twitch violently on the ground. That is a huge problem in combat if you over-do it because suddenly all that mobility you had is gone, but it's not stupid now.
#### Additional info:
- **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/4130719b3b5a6945bc0b337bf940f2dc561a9f22

**Comment by Atermonera** [comment]
If hyperzine is too useful for combat, then a combat-related malus would make more sense than raw damage over time. Especially if you lower the OD threshold, if someone can get hyperzine, can't they also water it down with medications to heal damage caused by ODing, or whatever raw DOT you introduce?

**Comment by SpadesNeil** [comment]
Oh! Maybe consuming too much induces seizures! Stuns you, you fall over, and twitch violently on the ground.

That is a huge problem in combat if you over-do it because suddenly all that mobility you had is gone.

**Comment by Atermonera** [comment]
I was thinking accuracy penalties and misfires, but that could work too.

**Comment by SpadesNeil** [comment]
![why not both](https://cloud.githubusercontent.com/assets/6484985/19832293/3164d868-9dee-11e6-851e-1a0c62478c27.jpg)
