### ISSUE TITLE
Drone based FBPS

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#2698]
#### Brief description of the issue
Drone brained FBP's brains work like a MMI and have a actual human brain inside of them
#### What you expected to happen
To be like a little ramstick or something
#### What actually happened
Was a drone brain that was upturned and spilled out a drone brain
#### Steps to reproduce
Debrain drone brained FBP, remove whatever is in their head and behold, human brain!
#### Additional info:
 - **Server Revision**: master - 2016-11-02
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Known bug, issue is in here: https://github.com/PolarisSS13/Polaris/blob/master/code/modules/surgery/robotics.dm#L363

**Comment by SilverTalismen** [comment]
Any way to fix this? I assume they were supposed to work like Posi brains and not MMI's

**Comment by Nerezza** [comment]
Brains in FBPs are actually all code-wise MMIs. Yes, posibrains are an MMI too! Robobrains are just a facade to hide that they're human brains on the inside, and to make it so they can be hooked up into FBPs and cyborgs without needing an MMI of their own.

**Comment by Anewbe** [comment]
We don't have the brain-elevator issue anymore, last I checked.
