### ISSUE TITLE
Welding without protection doesn't blur vision

### ISSUE THREAD

**Issue by Nerezza** [PolarisSS13/Polaris#2709]
#### Brief description of the issue
Eye damage provides only a temporary blurred overlay, which goes away quickly. Welding things without goggles doesn't get a blurred overlay at all.
#### What you expected to happen
Partial eye damage should progressively blur vision before blindness occurs.
#### What actually happened
Vision stays clear until blindness occurs.
#### Steps to reproduce
Stab yourself in the eyes, wait, stab again, wait, rinse and repeat until you go blind.
#### Additional info:
Here's the original issue post, just to have it:

> #### Brief description of the issue
> Last night my Teshari got his eyes stabbed out. Things went blurry for a moment, then it went back to just the welding goggle overlay (which acts as teshari near-sightedness) so I thought I'd gotten lucky.
> 
> Later in medical I was given eye medicine and my vision went blurry again, progressively got better, then cleared up to normal vision once more. This indicated to me that I was supposed to actually be blind, but I was not.
> #### What you expected to happen
> Having my eyes stabbed out should have blinded me.
> #### What actually happened
> My teshari's vision returned to normal.
> #### Steps to reproduce
> Spawn teshari, stab yourself in the eyes, see the results (;D), take eye medicine and observe your 'blindness' cured.
> #### Additional info:
>  - **Server Revision**: 4b913b93537f88b6e40f305098d2ae1f27728679 
>  - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
> I don't know if this affects any other mobs, since I haven't had my eyes stabbed out on any other characters yet. Also, Teshari should probably get a special blindness overlay because I'm sure that so long as their hearing works they're not completely blind.

**Comment by Atermonera** [comment]
Still an issue as of 2017 - 12 - 29
