### ISSUE TITLE
Turbans and Beards

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#2711]
#### Brief description of the issue
Turbans, through weird hat black magic hide your beard
#### What you expected to happen
For the hair on your face, not your head, to be visible
#### What actually happened
Full dwarf beard is hidden by your Turban
#### Steps to reproduce
Get a big full beard, equip a turban
#### Additional info:
 - **Server Revision**:master - 2016-11-08
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Turbans have the BLOCKHAIR flag, since you don't want ponytails and the like to poke out the back of them.
Facial hair is, unfortunately, a part of hair
`#define BLOCKHAIR       0x40    // Hides the user's hair, facial and otherwise.`

**Comment by Anewbe** [comment]
BLOCKHEADHAIR should work for that.
