### ISSUE TITLE
Loincloths

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#2714]
#### Brief description of the issue
Unathi [and more than likely Tajara] Cannot spawn with loincloths, the one in the xenowear deselects itself saying my unathi is not whitelisted to have it and the one in the shorts selection has no icon
#### What you expected to happen
To be able to spawn with either
#### What actually happened
The one in xenowear is dissallowed and the one in shorts is without icon
#### Steps to reproduce
Select the xenowear one and get the 'You cannot take the loincloth (Tajaran, Unathi) as you are not whitelisted for the species.'
Be able to spawn with the one from shorts selection, but it has no icon
#### Additional info:
 - **Server Revision**:master - 2016-11-08
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
I'm unable to reproduce the whitelist issue. Worse comes to worst I can remove it from the xenowear tab, because it doesn't really need to be in both, I don't think.
I will have a PR up to fix the sprite shortly.
