### ISSUE TITLE
Welding Helmet Sprites

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#2752]
#### Brief description of the issue
Welding helmets it seems, atleast with the shaved hair hairstyle, vanish when flipped up
#### What you expected to happen
To have it on my head
#### What actually happened
The helmet vanished when I flipped it up
#### Steps to reproduce
Have shaved hair
Get a welding helmet
Flip it up
Have a invisible welding helmet
#### Additional info:
 - **Server Revision**: master - 2016-11-16
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SilverTalismen** [comment]
On further investigation, They loose their sprite entirely.

**Comment by MagmaRam** [comment]
Testing this on the live server just now, helmet sprite worked fine both with hair and when bald. Were you using a custom sprite of some sort, or any specific items of clothing other than the welding mask that might have changed things?

**Comment by SilverTalismen** [comment]
I was wearing baggy black jeans a red hoodie and the usual  Roboticst gear, tool belt, gloves and the welding helmet.

**Comment by MagmaRam** [comment]
Testing on a local server (rather than Polaris), it's happened, so at least I've got it reproduced.
