### ISSUE TITLE
Lungs Get Popped On Internals Below 21 kPa

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#2809]
#### Brief description of the issue
Without any suffocation beforehand, lungs will randomly become popped on safe pressure from 16-20 kPa in pure oxygen tanks
#### What you expected to happen
Lungs not to be popped
#### What actually happened
Lungs popped and started receiving brain and suffocation damage
#### Steps to reproduce
1.) Wear breath mask and oxygen tank
2.) Set oxygen tank to 16, 17, 18, 19, or 20 kPa
3.) Wait
4.) Get pain message for ruptured lung
#### Additional info:
 - **Server Revision**: http://prntscr.com/dazk7n 
 - **Anything else you may wish to add**: Picture I did when testing: http://prntscr.com/dazk7n

**Comment by Nerezza** [comment]
Let's code in a ghostly hand to slap people who lower the default internals output.

I kid, let's just make them slowly suffocate or something because doing that is dumb :|
