### ISSUE TITLE
Chief Engineer Doesn't Spawn with Experimental Welder

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#2810]
#### Brief description of the issue
I believe the welder is supposed to spawn on the suit storage slot of the CE, but the CE doesn't have one at the start of the round.
#### What you expected to happen
To spawn with the experimental welder
#### What actually happened
Spawned normally without it
#### Steps to reproduce
1.) Join as Chief Engineer
#### Additional info:
 - **Server Revision**: master - 2016-11-23 ea28bc8a44e0d7ea198bb4465a169e0003d12b0d 
 - **Anything else you may wish to add**: It may be better to just have it spawn in the CE's backpack or just in the locker.

**Comment by MagmaRam** [comment]
Fixed by #2812
