### ISSUE TITLE
Time for respawn timer warning when observing is wrong.

### ISSUE THREAD

**Issue by SledgeLP** [PolarisSS13/Polaris#2826]
#### Brief description of the issue
From the lobby, when you click observe, it gives you a warning that you can't respawn for 15 minutes. Our current respawn timer is set for 5 minutes though.

#### What you expected to happen
See above

#### What actually happened
See above

#### Steps to reproduce
Click observe

**Comment by Anewbe** [comment]
Ah, forgot about this, thanks.
