### ISSUE TITLE
Aim mode on guns is an instant-lock-on of death

### ISSUE THREAD

**Issue by MagmaRam** [PolarisSS13/Polaris#2830]
Way back in the day, Bay used to have a 2-second-ish delay on aim mode before it started to shoot. This served two purposes.

One, it stopped you from using aim-mode in combat and being an aimbot (our accuracy system somewhat mitigates this, but I'm still not a fan).

Two, it prevented you from shooting someone accidentally because they didn't have god-tier reaction time and ping.

This issue is here so people can discuss this a bit before I start working on it, since I have a couple other things on my list before this.

Also to remind me to do it, because I'm a goddamned space cadet.

**Comment by Anewbe** [comment]
From my list of nonsense, I'd appreciate it if you added these in when you work on this:

Aiming
- Apparently there is a bug that means the accuracy bonus from aiming takes effect before the lock is complete.
- The first shot from aiming should give the bonus, then it should need to take the relock time again.
