### ISSUE TITLE
Integrated circuit screens don't display

### ISSUE THREAD

**Issue by Atermonera** [PolarisSS13/Polaris#2868]
#### Brief description of the issue
The integrated circuit screens don't add their data to the description of the assembly, even when updated.

#### What you expected to happen
To be able to see the data

#### What actually happened
Had to open the assembly and look at the screen component, refreshing the page as necessary
[http://i.imgur.com/iWpnqpP.png](url)

#### Steps to reproduce
Build a device that outputs data to a screen
Observe the lack of data being displayed anywhere but the screen's GUI

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

Edit: Link's now by imgur, should hopefully work. Don't know why github was having a hard time with the puush link.
Doubleedit: Okay, github doesn't like this one either. Should work fine if you copy the link into a new tab manually

**Comment by Anewbe** [comment]
Image isn't working properly, I'm getting a 404.
