### ISSUE TITLE
Voice changers do not work at all

### ISSUE THREAD

**Issue by Noreaus** [PolarisSS13/Polaris#2872]
#### Steps to reproduce
Spawn voice changer
Use "set voice" to set a voice
wear voice changer
"toggle voice changing" to turn it on
Speak

#### Additional info:
 - **Server Revision**: Server revision: master - 2016-12-18
a5bfef5551fb1128e84a4a58fd6b411ea3a1a474 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Tested, works fine.
