### ISSUE TITLE
Service Borgs and Custom-Cooking

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#2873]
#### Brief description of the issue
The service borg's gripper will not put food items into the specialized kitchen machinery (Cereal maker, oven, candy maker, etc, not including microwave.)
Service borgs are capable of performing standard cooking via microwave, but (Similarly to research or med) cannot use the grinder.
#### What you expected to happen
Service borg using its gripper to put food-stuffs into assorted kitchen machines, and acquire various processed food-stuffs in return from said machines.
#### What actually happened
Service borg grippers cannot interface with the machinery, prompting the statement 'That item is not edible.'
#### Steps to reproduce
1.) Acquire some form of food-stuff in service gripper
2.) Use gripper with food-stuff on various kitchen machinery, not including the microwave.
3.) Your gripper is not edible.
#### Additional info:
 - **Server Revision**: a5bfef5551fb1128e84a4a58fd6b411ea3a1a474 
-**Anything you wish to add**: Slowly weeding various things to the open, one gripper at a time

**Comment by Atermonera** [comment]
The cooking machinery has the same issue as the circuit imprinter and the protolathe, where the attackby() processing the gripper returns 1, and the attackby() called in the gripper's attack() to process wrapped doesn't process.
Grinders remain their own issue.

**Comment by XenosTiger** [comment]
Just gonna throw in a bit more info on this.

Borgs in general seem to be unable to place any items at all on a table, via their grippers. This makes most jobs considerable more hellish for them. Another issue is a Service Unit's inability to handle egg-cartons and other hand-held containers that must be opened with a second hand. The fix I've seen most implemented on other servers, is having them simply take one item out of said boxes, but I'm not sure how that's implemented in code. I'm going to try to get a few pieces of code from Aurora to see if they help any.

**Comment by Mechoid** [comment]
@XenosTiger Borgs used to be able to look into containers (And now can't, either by bug or intent [I hope it was a bug, because flipping open a box or forcing open a bag is really, really easy with industrial clamps]). So if the one item at a time uses that, nice, but if it doesn't, I don't know how you would choose what you want from it, if it contains multiple different things you might want (and don't want to make a mess you can't clean up).
Simply dumping things out of a container, if people for some reason don't want borgs to look into them to shuffle one item out at a time without a mess, could also work. Right click on a bag, box, or whatever container, 'dump contents', "Xborg lifts the Ybox and shakes it, spilling its contents!" ..Of course that may also lead to messes a borg can't clean up. Or people complaining human-based can't do that.

**Comment by Atermonera** [comment]
Can you not click and drag from the box to yourself to open it?

**Comment by Mechoid** [comment]
No, that is what I was talking about when I said they used to be able to look into containers. Now, they can't, by (hopefully) a bug, or (problematically) direct change from Bay long ago.
