### ISSUE TITLE
Irish cream has excessive D

### ISSUE THREAD

**Issue by Neerti** [PolarisSS13/Polaris#2874]
#### Brief description of the issue
Irish cream reagent has seven characters in their RGB variable (ignoring the hash), where a proper RGB is six.

#### What you expected to happen
No error messages.

#### What actually happened
```## WARNING: Reagent irishcream has an incorrect color set (#DDDD9A3)```

#### Steps to reproduce
Start the game.
(maybe) Make irish cream.
Observe logs.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
```
Server revision: master - 2016-12-23
525643eb020cbdb7e4a71ec656fdef0b255ed43e
```
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
ZekeS told me about this bug.

**Comment by Anewbe** [comment]
Fixed
