### ISSUE TITLE
Borgs can't use grinders

### ISSUE THREAD

**Issue by Atermonera** [PolarisSS13/Polaris#2875]
#### Brief description of the issue
Known issue, supposedly there's a fix on baycode I'll look into in the near future. Mostly just making this a separate issue so I can close other issue reports that are and/or will only be open until that gets ported because of this.

#### What you expected to happen
Borgs can use grinders and be able to fully into chemistry, cooking, and maybe some other applications

#### What actually happened
Nope

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Baystation may have a fix for this.
