### ISSUE TITLE
Borgs lack Typing Indicators

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#2877]
#### Brief description of the issue
A borg, when typing into the text-box provided by the say and me verbs, do not have a typing indicator.
#### What you expected to happen
Borg to have a typing indicator over its head like anyone else.
#### What actually happened
Borg did not have a typing indicator over its head.
 This leads to problems if it's trying to respond to something that requires other players to (Hopefully) slow or stop an action to respond to it as well, such as an attack.
#### Steps to reproduce
Be a borg, use the say, me, or other chat verbs.
Have someone else observe. (Can be a local guest)
Notice the indicator doesn't exist for the borg.
#### Additional info:
 - **Server Revision**: 525643eb020cbdb7e4a71ec656fdef0b255ed43e
 - **Anything else you may wish to add** Just causes problems in high-risk RP situations, preventing say, emoted surrendering, if the aggressor can't see any typing indicator.

**Comment by Anewbe** [comment]
#2974
