### ISSUE TITLE
Farmbot Construction Runtimes

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#2879]
#### Brief description of the issue
Attempting to build a Farmbot leads to multiple runtimes.
#### What you expected to happen
Farmbot construction steps to occur without issue.
#### What actually happened
Even trying to start construction runtimes upwards of four times.
#### Steps to reproduce
1) Acquire watertank and full set of tools, bucket, arm, and plant analyzer.
2) Use screwdriver and each part on watertank. Notice multitude of runtimes.
3) Notice tank doesn't actually change at all, and you have all the parts you started with.
4.) Be sad you don't have a farmbot.
#### Additional info:
 - **Server Revision**: 525643eb020cbdb7e4a71ec656fdef0b255ed43e

**Comment by Anewbe** [comment]
Runtime that comes up is this 

> /obj/item/weapon/reagent_containers/glass/bucket/var/robotic

**Comment by Anewbe** [comment]
Fixed by: https://github.com/PolarisSS13/Polaris/pull/2887
