### ISSUE TITLE
Multiplication Circuits return null

### ISSUE THREAD

**Issue by Atermonera** [PolarisSS13/Polaris#2882]
#### Brief description of the issue
Multiplication circuits still don't actually multiply the values, but instead of returning 0, they now return null

#### What you expected to happen
5 x 5 = 25

#### What actually happened
[5 x 5 = null](https://i.gyazo.com/86f1b30718af5d50d43db777de61f2f1.gif)

#### Steps to reproduce
Put numbers into the multiplication circuit
Attempt to multiply

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

This might mean that subtraction et al is also still broken, will test those momentarily

**Comment by Neerti** [comment]
Believe this was fixed but not 100% sure.
