### ISSUE TITLE
Light tiles cannot be deconstructed.

### ISSUE THREAD

**Issue by LordJike** [PolarisSS13/Polaris#2884]
#### Brief description of the issue
I am unable to dismantle light tiles (the ones in the bar).
#### What you expected to happen
For the light tiles to dismantle when I use the needed tools.
#### What actually happened
I am only able to detach (unbolt) the light tiles from the floor, but nothing else
#### Steps to reproduce
1) go to the bar
2) attempt to dismantle the light tiles in it's dance floor
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Leshana** [comment]
What tool would you recommend?  Wrench?

**Comment by Anewbe** [comment]
That or crowbar?

**Comment by LordJike** [comment]
wrench seems like the one to me.

**Comment by Anewbe** [comment]
Most every other tile gets dug up with the crowbar.

**Comment by LordJike** [comment]
That is true, I was thinking more about how windows are dismantled, as glass is one of the main materials in light tiles, also, using a crowbar to dismantle something that's already unscrewed from the floor and that can be freely pulled around seems weird.

I think a good solution would be to make it so that when you use a screwdriver on the light tiles they become hold-able, as if dismantling a wooden tile

**Comment by Anewbe** [comment]
@Leshana I forget, did anyone ever make headway on this?
