### ISSUE TITLE
Reset Issues

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#2963]
#### Brief description of the issue
The reset slot button does nothing
#### What you expected to happen
For it to do whatever it's supposed to do.
#### What actually happened
Nothing happens.
#### Steps to reproduce
Go to any character slot
Hit reset
Watch nothing happen
#### Additional info:
 - **Server Revision**: master - 2017-01-28
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
It resets any changes made since you last saved the slot
