### ISSUE TITLE
Suspected bug with gender in new character menu

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#297]
I suspect it's defaulting to null and getting confused or something, as when I open a new character slot for the first time, the character is female, but the name generator gives me a male name. If I spawn in as that character I spawn as male, and default to bald, thirty, and black-eyed. It's like it fails to create the character properly so most of the mob's physical details go to default.

**Comment by Neerti** [comment]
Locally I get a runtime that says 'bad gender', so perhaps that's why.

**Comment by Neerti** [comment]
Fixed by a revert, the new character creation menu caused it.  I believe bay has fixed it now so we can possibly cherrypick it later.  It would also make it easier to fix the preview icon problem.
