### ISSUE TITLE
Hallucinations should make things taste CRAZY

### ISSUE THREAD

**Issue by Screemonster** [PolarisSS13/Polaris#2979]
#### Brief description of the issue
Food tastes the same when all your other senses are scrambled like so many eggs.

#### What you expected to happen
These snozzberries to taste like snozzberries.

#### What actually happened
Flavour is unaffected by just how _ludicrously dank_ you are.

#### Steps to reproduce
- trip balls
- eat stuff

### Other stuff
- revision as per this commit: https://github.com/PolarisSS13/Polaris/commit/9cbee4baf4970b36bd692469f1a4adb526582828
- probably doable with something like the following if you'll pardon the pseudocode:
`if`` (prob(min(100, hallucination)) || druggy)
   out = pick("purple", "deadly poison", "snozzberries", ...)``

**Comment by Anewbe** [comment]
From personal experience, that's not how it works. *shrug
