### ISSUE TITLE
Cannot deconstruct fax machines

### ISSUE THREAD

**Issue by Leshana** [PolarisSS13/Polaris#2982]
#### Brief description of the issue
Attempting to deconstruct a fax machine creates a frame on the tile, but does not remove the fax machine.  Also throws a runtime.
```
[12:39:06] Runtime in machinery.dm,374: Cannot read /obj/item/weapon/circuitboard/... (/obj/item/weapon/circuitboard/fax).board_type
   proc name: dismantle (/obj/machinery/proc/dismantle)
   usr: (the wooden floor) (145,140,1) (/turf/simulated/floor/wood)
   usr.loc: (the wooden floor) (145,140,1) (/turf/simulated/floor/wood)
```

#### What you expected to happen
Fax machine replaced by a frame and components

#### What actually happened
Runtime exception, fax machine remains, frame created.

#### Steps to reproduce
1. Screwdriver to open the cover.
2. Crowbar to pry out the circuit.

**Comment by Anewbe** [comment]
Should be fixed by #2983
