### ISSUE TITLE
Circuit Not-equal gates lack a sprite.

### ISSUE THREAD

**Issue by Screemonster** [PolarisSS13/Polaris#2999]
#### Brief description of the issue
As per https://github.com/VOREStation/VOREStation/issues/982

the not equal gate custom circuit doesn't have a sprite on it

#### What you expected to happen
for there to be be a sprite on the not equal circuit

#### What actually happened
![image](https://cloud.githubusercontent.com/assets/14942479/23108060/47423bf2-f6ff-11e6-91de-bc39c92c53e8.png)

#### Steps to reproduce
- (Step 1) open up the logic circuit box
- (Step 2) see there is a blank box
- (Step 3) dump out box to see what doesnt have a sprite/ be able to grab said spriteless circuit

#### Additional info:
 - **Server Revision**: actually vorestation but inherited from Polaris

**Comment by Atermonera** [comment]
This should have been closed by #3023
