### ISSUE TITLE
IPC/FMB's scream when injured.

### ISSUE THREAD

**Issue by Nandabun** [PolarisSS13/Polaris#3020]
#### Brief description of the issue
https://puu.sh/ulb2S/a9848e30f4.png
When injured, my full body prosthetic, mechanical brain included, fell over and screamed in pain.

#### What you expected to happen
Falling over makes sense, if a component gives way. Screaming does not. It is a machine. It may think like an organic, but it can not physcially feel pain, in my optinion.

#### Steps to reproduce
Smash it up.

#### Additional info:
Server revision: master - 2017-02-06
bb7cae47652047682133d6900a662451e91f6873

**Comment by SkowronX** [comment]
WHY WAS I PROGRAMMED TO FEEL PAIN

**Comment by Anewbe** [comment]
https://github.com/PolarisSS13/Polaris/pull/3158
