### ISSUE TITLE
Diona Movement Speed

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#3036]
#### Brief description of the issue
Diona don't move slowly like they usually do
#### What you expected to happen
To take about two minutes or so to get to my workplace
#### What actually happened
Got there in about a minute or less moving at human/FBP speed
#### Steps to reproduce
Spawn as Diona
Not take three hundred years to get someplace
#### Additional info:
 - **Server Revision**:master - 2017-03-03
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Already see the issue.

**Comment by Anewbe** [comment]
Fixed this.
