### ISSUE TITLE
Shuttle Announcements Display Incorrectly

### ISSUE THREAD

**Issue by nachomeep** [PolarisSS13/Polaris#3051]
#### Brief description of the issue

Rather than showing a time, it says %ETA%.

#### What you expected to happen

It to give a time in minutes.

#### What actually happened

http://i.imgur.com/K1aQtEH.png

#### Steps to reproduce

Wait for a crew transfer to dock with the station.

#### Additional info:
 - **Server Revision**: master - 2017-03-04 c831df104bc6489883b9002e162d2a501b684b1f 
 - **Anything else you may wish to add**: The shuttle took 7 minutes to arrive for whatever reason.

**Comment by Anewbe** [comment]
Known, fixed in a PR that's being reviewed.

**Comment by nachomeep** [comment]
Ah. I missed that part of it.
