### ISSUE TITLE
Taste system frequently makes no sense

### ISSUE THREAD

**Issue by Screemonster** [PolarisSS13/Polaris#3073]
#### Brief description of the issue
Food now displays taste according to its reagents. This can be a problem when things have reagents that don't taste like what the meal is supposed to taste like.

#### What you expected to happen
Yum, delicious carrot cake.

#### What actually happened
My delicious carrot cakes tastes of "dull toxin" because it has imidazoline in it.
My cheesecake tastes of "some sort of meat" because it has protein in it.

#### Steps to reproduce
Make a cheesecake or carrot cake and eat it.

#### Anything else
I'd propose giving actual food items an override on the taste system and only display additional reagents if they're _not_ part of the original recipe.

**Comment by Anewbe** [comment]
I'm very much in agreement with this, but I'm not currently sure of a better way to do this.

**Comment by Atermonera** [comment]
The problem with giving each food item its own taste and then adding flavors by extra reagents is that you have to create flavors for _every_ food item, and then somehow determine what the base reagents for the food item are, and then subtract that from the list of flavors drawn from reagents when you take a bite.

**Comment by ArbyTheDragon** [comment]
Sure, the quickest, easiest way is to assign tastes to reagents; Conveniently coverering EVERYTHING that can break down into reagents. That probably shouldn't go away, but can't we add tastes to things by virtue of what they are as an item as well as a reagent? (So putting capsaicin into things will still make them hot and sugar will still make it taste sweet outright)

**Comment by Atermonera** [comment]
We could, so carrot cake tastes like carrot cake, but it would still inherit the taste of dull poison from the imidazoline, and the cheesecake will still taste of meat.
