### ISSUE TITLE
Message Formatting Issues

### ISSUE THREAD

**Issue by Arokha** [PolarisSS13/Polaris#3084]
#### Brief description of the issue
The message formatting asterisks mess with messages modified by the stars proc, such as overheard distant whispers.

#### What you expected to happen
Not to have whispers full of random bold text and no stars.

#### What actually happened
Whispers full of bold text and no stars.

#### Steps to reproduce
Whisper with someone standing 2 turfs away.

#### Additional info:
@Neerti :0

**Comment by Anewbe** [comment]
Also apparently causes the AI to get bolded messages from any use of any word with the characters 'ai' in it.
