### ISSUE TITLE
Vox are blinded in pure Phoron Atmospheres

### ISSUE THREAD

**Issue by Poojawa** [PolarisSS13/Polaris#3090]
#### Brief description of the issue
Vox depend on meme gas to survive, but their eyes are vulnerable to the effects

#### What you expected to happen
Vox being able to exist in the phoron gas they were changed to depend upon, rather than a nitrogen pure enviroment.

#### What actually happened
https://i.gyazo.com/da8dbfda8a4193f7cf574d5028e98008.png
#### Steps to reproduce
Be Vox, stand in phoron-rich atmosphere, instantly turn blind.

#### Additional info:
built a 'Vox Lounge' for the Virgo downstream server, since there are no places other than Outer Space for Vox to interact with the environment 

https://i.gyazo.com/c36908545c007a1207e08b5185abae86.png

Besides air alarm wonkiness, which can be sorted out pretty easily, transporting into the room caused near instant blindness. the phoron floor pressure is room standard.

**Comment by Anewbe** [comment]
Literally just tested this on the Polaris live server, it's working fine, they're not going blind or anything else.
Tested in pure phoron, pure oxygen, and a mix.

As long as the code starting on: https://github.com/PolarisSS13/Polaris/blob/81c8570ba81c3b8a7ef8336943caa96275cf9878/code/ZAS/Phoron.dm#L127
is in the only effect they should get from Phoron is clothing contamination.

Gonna close this bug soonish unless you can reproduce it on Polaris' active code.

**Comment by Poojawa** [comment]
https://gyazo.com/5697da6be968e2fcf1bf0170eeb6816b

Just downloaded Polaris - Master
compiled fresh, started up anew.
buildmode constructed an airless room in space. Opened a single phoron canister
Proceeded to go completely blind.

**Comment by Anewbe** [comment]
Try spawning in a Vox, then moving your ckey into it. VV transforms may be the issue, because my default Vox was fine.

**Comment by Anewbe** [comment]
Have you modified the code at all? Is the /mob/living/carbon/human/vox/pl_effects() proc in there still? Have you renamed your vox species for any reason?

**Comment by Poojawa** [comment]
I did not modify any code other than to give myself administrative rank for testing.  The problem happened on both code instances with a normally spawned vox and a VV species changed vox. The godmode var simply prevents the screen from going entirely black, it doesn't protect from eye damage..

The downstream server has no modifications to that pl_effects code. 
https://github.com/VOREStation/VOREStation/blob/94b621b3106703cf3788f62f427ddcd6abbbfb8f/code/ZAS/Phoron.dm#L127

**Comment by Techhead0** [comment]
The problem is that players who join normally are `/mob/living/carbon/human` with the species set by the spawn code. That proc override will only affect mobs specifically spawned as the `/mob/living/carbon/human/vox` subtype.
