### ISSUE TITLE
Translators don't work on comms

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#3108]
#### Brief description of the issue
The new translators don't work on things heard over comms.
#### What you expected to happen
Gibberish on the radio turning into delicious works.
#### What actually happened
Stayed gibberish
#### Steps to reproduce
1.) Get a translator
2.) Find a gibberer
3.) Get the gibberer to gibber over the radio
4.) Hear gibberish
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Were you trying this near an intercom, or just while wearing an earpiece?
