### ISSUE TITLE
Posting links in chats such as deadchat are broken due to formatting

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#3124]
#### Brief description of the issue
Due to being able to bold, underline, or italicise text links get broken when posted, making it impossible to post helpful things to people such as guides.

#### What you expected to happen
To be able to post a links such as: https://github.com/PolarisSS13/Polaris and have it be clickable
#### What actually happened
It gets turned into: https:github.comPolarisSS13Polaris
#### Steps to reproduce
Post a link in a chat that has formatting available, such as dead chat.

**Comment by Anewbe** [comment]
We're going to replace the / with | for italics, methinks.
