### ISSUE TITLE
Accessories and colors

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#3154]
#### Brief description of the issue
A.) A uniform that takes a custom color also gives any accessories on it the same color overlay

B.) An accessory that gets a color overlay doesn't apply it on the mob sprite
#### What you expected to happen
A.) Accessories would remain their own colors on overlay clothes

B.) Accessories would actually use their color overlay.
#### What actually happened
A.) Black pants, black armband

B.) Normal pants, white armband on-mob
#### Steps to reproduce
A.)  1.) Select yoga pants in loadout, color.
      2.) Select armband
      3.) Join
      4.) Observe

B.)  1.) Select armband in loadout
      2.) Apply armband to uniform
      3.) Observe
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Uniform isn't giving color to the accessory, but the accessory isn't getting its own color.
