### ISSUE TITLE
Diona Health

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#3156]
#### Brief description of the issue
Diona health is...inaccurate at times, if not abit glitchy
#### What you expected to happen
Sitting on yellow health after survivng a phoron fire I expected to recover
#### What actually happened
I died.
#### Steps to reproduce
Survive any fire with youyr entire doll sitting on yellow health
Go into white screen flashing
Die whilte on yellow health
#### Additional info:
 - **Server Revision**:master - 2017-03-26
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
You were in a light place, not still on fire, and not (somehow) overheating?

**Comment by SilverTalismen** [comment]
No, I had put the fire out on myself and had all of my lights on like I usually do, I did have a temperature warning but I am fairly certain Dion  ahve a ridiciulo9usly high set temp resistance for heat and cold.

I assumed it was due to the change to burn damage and blood loss done for the squishies

**Comment by Anewbe** [comment]
Doona don't bleed, iirc, so I don't think that was the issue... Will look into this sooner or later.
