### ISSUE TITLE
Drones/Posi's and Numbers

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#3157]
#### Brief description of the issue
Drones and Posi Brains cannot have numbers, such as 16, in their name
#### What you expected to happen
To be able to be Drone number 16 or something
#### What actually happened
Had to be Drone number Sixteen
#### Steps to reproduce
Make a posi or drone brained FBP, try to set a number in your name, be forced to spell it out
#### Additional info:
 - **Server Revision**:master - 2017-03-26
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
I think this is part of name sanitation, will get someone on it eventually.

**Comment by Spacemanspark** [comment]
We fixed this over at Paradise.

**Comment by Atermonera** [comment]
Looks like it's an easy fix, you just have to pass a flag to sanitizeName in Polaris/code/_helpers/text.dm
