### ISSUE TITLE
Translators can understand monkeys and dogs

### ISSUE THREAD

**Issue by Anewbe** [PolarisSS13/Polaris#3161]
#### Brief description of the issue
Ian can talk to people with translators
#### What you expected to happen
Barks and growls, it's a dog.
#### What actually happened
... Fluent conversation?
#### Steps to reproduce
1.) Get a dog
2.) Get a translator, turn it on
3.) Hold a conversation with the dog
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by SilverTalismen** [comment]
Pfft. But it was so funny when the translators understood me as TraitorDog

**Comment by Atermonera** [comment]
Monkeys have a language, so I just have to add a tag. Dogs don't have a language, which I think means I need to make one. I should probably also do so for runtime.
