### ISSUE TITLE
Pulse Rifle size is wrong inside backpacks

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#3221]
#### Brief description of the issue
An advanced energy pistol takes up more space than a pulse rifle.

#### What you expected to happen
The thing that can melt walls should not be as small as a cardboard box in my backpack.

#### What actually happened
It took up far too little space.

#### Steps to reproduce
Jam a pulse rifle into a backpack.

#### Additional info:
 - **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/c52bab3439e8ecbffd6b98cd6c00344625d703c9
 - **Anything else you may wish to add:** Found in Vorestation downstream but I'm pretty sure we didn't screw with the pulse rifle.

**Comment by Anewbe** [comment]
Pulse rifle meaning the admin gun?

**Comment by SpadesNeil** [comment]
Are _all_ the pulse rifles admin only? I know the /pulse_rifle/destroyer and /pulse_rifle/m1911p are, but not the regular /pulse_rifle or so I thought.

**Comment by Anewbe** [comment]
No, those absolutely are.

**Comment by SpadesNeil** [comment]
Oh. Well if they're all admin guns, then this is a very very minor issue.
