### ISSUE TITLE
Pipe painter uses wrong inhands on east face.

### ISSUE THREAD

**Issue by ghost** [PolarisSS13/Polaris#3262]
#### Brief description of the issue

When facing east, it uses the south-facing inhands, shifted a pixel down.

#### What you expected to happen

The pipe painter to be in my hands.

#### What actually happened

It was floating in front of my crotch.

#### Steps to reproduce

Pick it up, look east.

#### Additional info:
 - **Server Revision**: Server revision: master - 2017-04-09
bff7d59312157bd7c61995fa73c162113a7ef468

**Comment by Atermonera** [comment]
[Tested](https://puu.sh/yQCHj/e841d47f71.mp4)
In all directions, it's positioned to be visible.
