### ISSUE TITLE
Smoking Pipe Sprite issues when lit

### ISSUE THREAD

**Issue by LorenLuke** [PolarisSS13/Polaris#3293]
#### Brief description of the issue
When lighting a smoking pipe, there seems to be no icon
http://ss13polaris.com/forums/viewtopic.php?p=14047#p14045
#### What you expected to happen
Not this.
#### What actually happened
This.
#### Steps to reproduce
Fill a smoking pipe, light it.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
It also seems that there's no on-char sprite for it either, when lit.

**Comment by Anewbe** [comment]
Which pipe? I need specifics.

**Comment by LorenLuke** [comment]
@Anewbe 
/obj/item/clothing/mask/smokable/pipe

Possibly also (though I can't confirm this one):
/obj/item/clothing/mask/smokable/pipe/cobpipe
