### ISSUE TITLE
Some of the TG clothing items do not have floor sprites

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#330]
Some of the TG clothing items such as military jackets and other items such as pants do not have floor sprites

**Comment by Sabess** [comment]
I can make sprites for that if needed, but, would be nice to know what exactly doesn't have floor sprites.

**Comment by Sabess** [comment]
https://github.com/PolarisSS13/Polaris/pull/419
assuming I didn't break everything

**Comment by Neerti** [comment]
It just occurred to me that not all the sprites might've been fixed.

**Comment by EmperorJon** [comment]
I haven't seen any recently or heard any instances of this.
