### ISSUE TITLE
*halt has improper grammar.

### ISSUE THREAD

**Issue by Belsima** [PolarisSS13/Polaris#3309]
#### Brief description of the issue

When you use *halt, it shows your name twice.

#### What you expected to happen

Incandescence's speakers skreech, "Halt! Security!"

#### What actually happened

Incandescence Incandescence's speakers skreech, "Halt! Security!".

#### Steps to reproduce

Join as a lawed synthetic. Select security module. Type *halt into the chat.

#### Additional info:
 - **Server Revision**: 80a70aed7eaf8a8163621c74ffeb4c22d6edd825

**Comment by Anewbe** [comment]
Sort of fixed in #3313
