### ISSUE TITLE
Lings show up as dead on medHUD, if they were dead at some point.

### ISSUE THREAD

**Issue by SubberTheFabulous** [PolarisSS13/Polaris#3341]
#### Additional info:
 - **Server Revision**: Server revision: master - 2017-04-18
b551a30f3c5243e1a8b644d05b840a94e93fb935

**Comment by Nalarac** [comment]
Generally when I've seen this happen, it takes a minute or two for the dead icon to become a living icon again but in the end it does go back.

**Comment by LorenLuke** [comment]
#3365

**Comment by Neerti** [comment]
This should be fixed now, right?

**Comment by Anewbe** [comment]
Think so?
