### ISSUE TITLE
Advanced voidsuit module problems

### ISSUE THREAD

**Issue by Noreaus** [PolarisSS13/Polaris#336]
The following issues exist:

1. The helmet light control does not appear after activating the suit. Clicking on the helmet removes the helmet. Throwing away/dropping the helmet causes you to be able to use 'toggle helmet' to spawn another, which can then be removed and thrown away. This can be repeated numerous times.

2. Removing the module does not remove the suit parts, which must be removed afterwards. When dropped, they disappear.

![hardsuit](https://cloud.githubusercontent.com/assets/5178371/11453666/82767fd6-960b-11e5-84dd-550f164eac78.PNG)

**Comment by EmperorJon** [comment]
Seems to be fixed by #383.

**Comment by Zuhayr** [comment]
I tagged #378 by accident, meant to tag this one, whoops.
