### ISSUE TITLE
(Wooden) Bats go dull (in 5 hits)

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#3360]
#### Brief description of the issue
Material weapons such as bats made of a material like wood end up going 'dull' in like 5 hits. Not only does it not make any sense for something like a bat to go 'dull' it's made of solid wood and not glass or plastic. 
#### What you expected to happen
For my bat made of solid wood to not go dull after barely any use.
#### What actually happened
My bat went dull on the 5th delivery to someone's skull.
#### Steps to reproduce
Make a wooden bat. Hit someone with it 5 times.

**Comment by Anewbe** [comment]
Going dull is based on the material's stats, and happens at roughly the same pace as they would have broken. Bats specifically don't lose as much damage as other material weapons would, though. They probably shouldn't go dull, admittedly, but that means they'd likely shatter instead. I'll look into this eventually.

**Comment by SilverTalismen** [comment]
I trust Anewbe to fix this in a amazing way, The code will be..Batter after this~

**Comment by Magneld** [comment]
Aren't bats already dull by nature?

**Comment by ArbyTheDragon** [comment]
Any item with no usage beyond a blunt instrument should be an equally effective blunt instrument no matter how "dull" it is, if you are even able to discernibly call a blunt instrument "dull". Unless we're talking about a meat tenderizer, a blunt instrument is probably dull by its own nature.

Tweak pls. 
Instead, have the bat break outright after X number of solid hits? 
Maybe even break the bat as percentage chance upon each hit (this % should be VERY low.) The bat could also do boosted damage on the 'breaking hit' for those mysterious _**RNG one-shot wonder hits**_, just as baseball bats in play do occasionally splinter/explode upon a perfect strike of a baseball.
