### ISSUE TITLE
Can't hit people with foam weapons

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#3361]
#### Brief description of the issue
Can't hit people with foam weapons
#### What you expected to happen
Hit someone with the foam weapon
#### What actually happened
Nothing at all
#### Steps to reproduce
Click someone with a foam weapon

**Comment by Atermonera** [comment]
[https://github.com/PolarisSS13/Polaris/blob/master/code/_onclick/item_attack.dm#L56](https://github.com/PolarisSS13/Polaris/blob/master/code/_onclick/item_attack.dm#L56)

```
/obj/item/proc/attack(mob/living/M, mob/living/user, var/target_zone)
	if(!force || (flags & NOBLUDGEON))
		return 0
```

This appears to be the root cause of this
