### ISSUE TITLE
Thermals don't play well with new lighting.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#3372]
#### Brief description of the issue
Thermals do not highlight mobs that are lit up, and within your line of sight.

#### What you expected to happen
Thermals to always light up mobs.

#### What actually happened
![image](https://cloud.githubusercontent.com/assets/8376059/25432382/20b3798c-2a7c-11e7-97e5-c3855370108c.png)
![image](https://cloud.githubusercontent.com/assets/8376059/25432387/243cdca6-2a7c-11e7-863d-3e6dc3d4c87e.png)

#### Steps to reproduce
Wear thermals. Look at people in dark and light.

#### Additional info:
Current update as of: 26/04/2017

**Comment by Neerti** [comment]
I thought thermals acted as night vision now in order to fix this?

**Comment by FenodyreeAv** [comment]
Not as far as I saw.

**Comment by PJB3005** [comment]
Yeah only way to fix this is to give them some way of hiding overlays.

**Comment by Anewbe** [comment]
Hasn't been merged yet @Neerti

**Comment by Anewbe** [comment]
Should be fixed by #3267
