### ISSUE TITLE
Xenobio issue

### ISSUE THREAD

**Issue by Magneld** [PolarisSS13/Polaris#3391]
I'm reporting this on behalf of a player who is unable to do so themselves, additionally I'm not familiar with xenobio in general so apologies for this being possibly annoyingly vague.
#### Brief description of the issue
To quote the ahelp: "the biological genetic bombarder thinks it has a slime in it when it doesnt and you cant use it ever again"

#### What you expected to happen
Not that.
#### What actually happened
That.
#### Steps to reproduce
Put a slime in the biological genetic bombarder, use it for.. whatever its used for, remove the slime. Attempt to put the slime back in or a different slime altogether and the machine won't let you, saying that something is already inside it.
#### Additional info:
 - **Server Revision**: Server revision: master - 2017-04-28
5ff71f926c50487fea14fefe4a99f8e0b7120dbd 
 - **Anything else you may wish to add** I had totally forgot we even had a xenobio to be honest.

**Comment by Anewbe** [comment]
No longer relevant.
