### ISSUE TITLE
Infinite Machine Frames

### ISSUE THREAD

**Issue by Wutnold124** [PolarisSS13/Polaris#3404]
#### Brief description of the issue
When you crowbar a destructive analyzer that has been screwdrivered, it makes a machine frame without actually taking apart the DA.
#### What you expected to happen
I expected to be able to take apart the DA because I can't RPE it when it's constructed.
#### What actually happened
I got infinite frames.
#### Steps to reproduce
Screwdriver DA, crowbar DA.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
master - 2017-04-29
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
this basically gives you infinite metal

**Comment by Leshana** [comment]
To reproduce, you must have deconstructed something, and wait a few minutes; then try to dismantle.
