### ISSUE TITLE
The AI can teleport food

### ISSUE THREAD

**Issue by PrismaticGynoid** [PolarisSS13/Polaris#3406]
#### Brief description of the issue
While a food item is being cooked with one of the machines in the kitchen (Deep fryer, grill, oven, likely candy machine and cereal maker too), the AI can click on the machine to remove the food. This moves the food item straight to the AI's core.
#### What you expected to happen
The AI would be unable to interact with the machines, or for the food to be ejected on top of them.
#### What actually happened
The food item in the machine is teleported to the AI's core
#### Steps to reproduce
Be AI, have someone cook something with one of the kitchen machines. Click on it and have the food teleported directly to your core. 
#### Additional info:
 - **Server Revision**: master - 2017-04-29
3c8088015df26236fdb2734f9eda0f97d95ab665 
 - **Anything else you may wish to add**: Cyborgs/robots/drones can also probably use this to teleport food to them.

**Comment by Atermonera** [comment]
I don't know why the attackby() is processing for AIs using cookers, but when the cooker ejects food, it tries to put it into the attacker's hand. If the attacker doesn't have a hand, it puts it at their feet. This can probably be fixed with a pretty simple adjacency check

**Comment by Neerti** [comment]
For some reason this didn't get autoclosed so wew.
