### ISSUE TITLE
The SOP-6 Grenade launcher issues.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#3447]
#### Brief description of the issue
The SOP-6 grenade launcher (the mech one) fires clusterbangs that delete without splitting into other flashbangs.
The SOP-6 grenade launcher does not rearm after all six shots have been fired, like it's lower tech version the SG6, or the AC10 and scattershot.

#### What you expected to happen
Many many flashbangs to fly everywhere.

#### What actually happened
A clusterbang vanished doing nothing.

#### Steps to reproduce
Fire an SOP-6 grenade launcher.

#### Additional info:
Server revision: master - 2017-05-11
7502a32fd747f055e83a2e868808e8210a2cb466

**Comment by Mechoid** [comment]
The printable clusterbang launcher is specifically not reloadable, for assumedly balance reasons from ages since passed. Source: Touched mech guns and designs recently. ***/limited*** subtype.
