### ISSUE TITLE
Can't Put Cyborgs in Storage

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#3452]
#### Brief description of the issue
It's impossible to put cyborgs/robots/drones into storage once they go SSD
#### What you expected to happen
To be able to move a cyborg into cyborg storage, the elevator, or the gateway.
#### What actually happened
It's impossible to do so.
#### Steps to reproduce
1.) Have a cyborg
2.) Attempt to put them into storage.
#### Additional info:
 - **Server Revision**: master - 2017-05-11 7502a32fd747f055e83a2e868808e8210a2cb466

**Comment by SilverTalismen** [comment]
I usually just dismantle them after a hour and keep the brains around so if they return I explain to them what occurred and why and rebuild them if need be. Dismantling them as  far as I am aware free's the slot

**Comment by Mechoid** [comment]
Deconstructing a borg does not in-fact open a slot. Source: Checked on-server,
![Post-Deconstruct](https://puu.sh/w19Ay/ee7951cefe.png)

**Comment by Nalarac** [comment]
Fixed with #3659
