### ISSUE TITLE
Neck grab yoyo

### ISSUE THREAD

**Issue by Chr1sC** [PolarisSS13/Polaris#3455]
#### Brief description of the issue
Using grab up to neck and throwing then moving causes the person thrown to teleport back to grabber
#### What you expected to happen
Them to be thrown  and let go
#### What actually happened
Threw them and then moved and they came right back to me
#### Steps to reproduce
Grab intent then upgrade to neck grab and throw then move right after
#### Additional info:
master - 2017-05-11
7502a32fd747f055e83a2e868808e8210a2cb466 

Did it in the holodeck only so far boxing ring module as DICE and with DACE both IPC's

**Comment by TheFurryFeline** [comment]
Seems similar to #1838 perhaps?

**Comment by TheFurryFeline** [comment]
Tested this and the grab is dropped once thrown. A non-issue now.
