### ISSUE TITLE
AI Can't See Inside Transfer Shuttle

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#3468]
#### Brief description of the issue
Even with the cameras on the shuttle (and trying to use a robot), it's impossible for the AI's vision static to disappear in the middle of the shuttle. (Cameras were not broken)
#### What you expected to happen
The proper vision to be given to the AI.
#### What actually happened
Vision was obscured
![](https://image.prntscr.com/image/74886bfc98d44c5ba74fd032fe5fcedb.png)

#### Steps to reproduce
1.) Be AI
2.) Try to view transfer shuttle
#### Additional info:
 - **Server Revision**: master - 2017-05-21 8a2f69d439e33bf5193044e18e71a14a7ca7651f
- **Anything Else**: This is a pretty minor issue as the shuttle only arrives at round end

**Comment by PrismaticGynoid** [comment]
This only happens when the shuttle is docked at the colony. Once the shuttle is back on the centcomm z-level, vision returns on it, if you use the jump to network verb or similar to view the cameras.
