### ISSUE TITLE
Thermostats take forever to work

### ISSUE THREAD

**Issue by Atermonera** [PolarisSS13/Polaris#3472]
#### Brief description of the issue
Mostly just posting this here so Neerti remembers it at some point in the far future, or someone else sees this and works on it.

With their current active_power_usage of 1000, a thermostat can alter the temperature of a room by about 0.5 degrees C per tile of 1atm air per second.
If someone were to attempt to raise the temperature of the medbay lobby by 10C, with the firelocks closed and the desk windoors open (Limiting the zone to 77 tiles), the change would take place at 0.0064935 degrees C per second, Which would take 1540s, or 25m40s. Other rooms, like Central Primary Hallway, are much larger, and will take much longer.

#### What you expected to happen
Thermostats to work on a much more noticeable timescale.

#### What actually happened
The bar caught on fire. Instead of just filtering off the unbreathable gasses in the air and letting the thermostat work, the atmos techs resolving the issue find it extraordinarily quicker to siphon off most to all of the gas, and then use the 'replace' environment mode, to reduce the temperature to habitable. (Not that that's necessarily bad, but even if the room were only 50 or 60C, I'd siphon air instead of letting the thermostat handle it.)

#### Steps to reproduce
Put an air alarm in the toxins mix chamber, then heat it up, and watch how slowly the temperature changes.

#### Additional info:

There's a couple of ways to go about fixing it (That I can think up, anyways):

- You could raise the active_power_usage of air alarms, which could change powernet balance in worst-case situations.
- You could break physics and improve the ratio of electrical power to thermal energy that air alarms are able to affect their local zones with.
- Or you could dick around with ZAS to some effect or another.

**Comment by Nalarac** [comment]
Or, you know.. use the big space heaters.
