### ISSUE TITLE
Rebalance Carbine to be used as a traitor gun.

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#3477]
#### Brief description of the issue
/obj/item/weapon/gun/projectile/automatic/carbine is a very nice looking gun with a lot of punch, but it's too much punch at 20 round magazines using 7.62 ammunition.

To make this no longer brokenly overpowered, make the initial gun spawn with only 10 round magazines, take away the gun's automatic fire, and adjust its description a bit to the following:

```
name = "carbine"
desc = "The bullpup configured GP3000 is a compact rifle produced by Gurov Projectile Weapons LLC. As a semi-automatic rifle, it was meant to be more easily sold to civilians, but its stopping power has made it a favorite weapon among police, pirates, and mercenaries alike. Uses 7.62mm rounds."
```

A traitor might choose this gun as an alternative to usual STS assault rifle because of its heavier stopping power per bullet.

#### Additional info:
 - **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/aad701fee7e811224732da2701910fe9754225d7
 - **Anything else you may wish to add**: I can do this later. This issue post is just for sake of discussion of how much the traitor item should cost because I have no idea.

**Comment by Atermonera** [comment]
#3688 I think
