### ISSUE TITLE
Xenobiology Mapping

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#348]
![](https://i.gyazo.com/3f108781ea641554c9399d6c38ef7368.png)
The two inner glass doors are all access, meaning slimes can open them

More of a request, but if the disposals unit could be moved one tile closer, slimes can be dumped into it straight off the table, which is a huge labor saver.
![image](https://cloud.githubusercontent.com/assets/8376059/11457084/b57a6956-9697-11e5-9a10-225856a274ba.png)

**Comment by Woodratt** [comment]
The only issue I see here is then there would be a empty space behind the disposals, unless I filled it with something. Is noted and will probably be changed once I can decide what to do

**Comment by Woodratt** [comment]
Adjusted and fixed https://github.com/PolarisSS13/Polaris/pull/442
