### ISSUE TITLE
FBPs can taste things.

### ISSUE THREAD

**Issue by ghost** [PolarisSS13/Polaris#3480]
#### Brief description of the issue

When drinking or eating things, even positronic FBPs are able to taste it.

#### What you expected to happen

Sweet, sweet lack of sensory detail.

#### What actually happened

I actually enjoyed the drink instead of needing to pretend to enjoy it.

#### Steps to reproduce

1. Set character to FBP.
2. Join.
3. Walk to the canteen.
4. Eat that pie.
5. Read the chat.

#### Additional info:
 - **Server Revision**: 8a2f69d439e33bf5193044e18e71a14a7ca7651f 
 - **Anything else you may wish to add**: I'm fairly sure lorewise most aren't meant to taste, like most aren't meant to feel pain.

**Comment by Atermonera** [comment]
This is desired behaviour for a lot of people. Most people (From my observation) consider that if you're equipped to eat and drink, you're equipped to taste. If you're not equipped to eat, then you have no need to taste.

As well, is there anything stopping you from ignoring the taste messages and just pretending to enjoy it anyways?
