### ISSUE TITLE
Prometheans cannot wear Voidsuits

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#3481]
#### Brief description of the issue
A promethean, which is shaped like a human, cannot by default wear a voidsuit of any kind.
#### What you expected to happen
Promethean is able to fit into the voidsuit no matter its shape, because they're made of jello.
#### What actually happened
Your species cannot wear this suit, in reference to a voidsuit.
#### Steps to reproduce
-Be a promethean,
-Acquire voidsuit, was tested with security's
-Try putting it on.
-Be sad you are made of flowing jello but can't gooform yourself into a voidsuit.
#### Additional info:
 - **Server Revision**: 8a2f69d439e33bf5193044e18e71a14a7ca7651f
 - **Anything else you may wish to add**: Changing your shape to a Teshari already tries to find the teshari version of the worn object. Even if they have no sprite.

**Comment by MagmaRam** [comment]
This doesn't seem to be an issue anymore, but the sprite weirdness with Teshari form does exist.

**Comment by Mechoid** [comment]
Teshari sprite weirdness is fully on the Teshari side, they don't have sprites for a lot of things.
