### ISSUE TITLE
Mining exterior conveyor.

### ISSUE THREAD

**Issue by ariever** [PolarisSS13/Polaris#3489]
The conveyor will alternate between going the right way (into the sorting machine) and the wrong way(back outside) when the lever is used.
![2017-06-01_02-58-10](https://cloud.githubusercontent.com/assets/26043258/26668135/5ae30c88-4676-11e7-94af-9c258cab4f2e.gif)

**Comment by Nalarac** [comment]
I don't see the issue. It can go in reverse in case you get an ore box stuck inside.

**Comment by Neerti** [comment]
I'm pretty sure this is working as intended.

**Comment by Anewbe** [comment]
Working as intended, it lets you get the boxes out if you use them that way.
