### ISSUE TITLE
Research Borg's Grippers and Analyser

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#349]
Research borg's portable destructive analyser doesn't produce research.
![image](https://cloud.githubusercontent.com/assets/8376059/11457097/173ab5f6-9698-11e5-83eb-13c20d51af5b.png)
The above has biotech and magnets tech.

Research borg's sheet stacker can't put metal and glass into the circuit imprinter or protolathe. (Autolathe works fine)
![image](https://cloud.githubusercontent.com/assets/8376059/11457111/3fe967e0-9698-11e5-83ca-48a0ceddfd11.png)

Research borg's scientific gripper can't interact with Xenobiology fridge, protolathe, destructive analyzer. Possible there are more, but that's all I found.
![image](https://cloud.githubusercontent.com/assets/8376059/11457122/846c035a-9698-11e5-92d6-83da74cc968e.png)
Trying to interact with the destructive analyzer gave no message.

**Comment by SpadesNeil** [comment]
The sheet stacker still doesn't work correctly as reported at https://github.com/VOREStation/VOREStation/issues/526

**Comment by Atermonera** [comment]
Sheet stacker doesn't work with stacks of fifty sheets because that's actually a different object. Working with smaller stack sizes, I only had issue with the circuit imprinter.

**Comment by Anewbe** [comment]
We're working to remove the stacks/fifty (or whatever) item because it's causing a load of issues.

**Comment by Atermonera** [comment]
Sheet loader is pending #2871; destructive analyzer is fixed; xenobio to come with the next round of fixes, I'll look into that with the kitchen equipment, per #2873, as I suspect they're the same issue in different places.

**Comment by Atermonera** [comment]
Unable to reproduce the destructive analyzer part, which is the only remaining bit of this that hasn't been fixed. [https://puu.sh/wNXg6/ba39a85940.mp4](https://puu.sh/wNXg6/ba39a85940.mp4)

Only need about the first half of that mp4, pushed the wrong button to stop recording and took a bit to realize that.

**Comment by Atermonera** [comment]
This can be closed
