### ISSUE TITLE
Warden's office mapping.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#350]
Warden's office glass windoor can be accessed by regular security officers.
![image](https://cloud.githubusercontent.com/assets/8376059/11457152/8882df76-9699-11e5-8c9b-b3c16930d0aa.png)

**Comment by Mark9013100** [comment]
Intentional, not a bug.

**Comment by FenodyreeAv** [comment]
Okay.

**Comment by Spookerton** [comment]
We have way too many labels. Leaving this open as a mapping request.

**Comment by Woodratt** [comment]
Noted, request has been brought up at least one time previously, will modify the map to suit said needs.

**Comment by Woodratt** [comment]
Fixed https://github.com/PolarisSS13/Polaris/pull/442
