### ISSUE TITLE
Pistol bullet damage values need rebalancing

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#3502]
#### Brief description of the issue
The damage levels of pistol bullets is rather absurd. So, here's what we're looking at:

Pistol: 20 (9mm for example)
Pistol (Medium): 25 (.45 or 10mm)
Pistol (Strong): 60 (.357, .50AE) <- This makes the least sense.

Kind of a substantial leap between medium and high powered guns compared to everything else. For comparison, a _shotgun slug_ does only 50 damage last I checked. This just doesn't seem right.

What I propose is the following, but this will obviously disrupt some (im)balance in the game.

Pistol Weak: 20 (9mm/.40 if we ever add that)
Pistol Medium: 30 (.45/10mm)
Pistol Strong: 40 (.357)
Pistol Very Stronk: 50 (.44)
Pistol Fuck-You-And-Fuck-Everything-Along-Your-Trajectory: 60 (.50AE)

Note I plan on adding the .44 for the Desert Eagle, as a means of keeping it SORT OF balanced. I could leave a .50AE version for purposes of admin abuse, but 60 damage for a 7 round mag is a whopping 420 damage per magazine, out of a semi-automatic gun no less. This gun should be restricted to FUN™ where something absolutely positively needs to **die** horribly.

On the other hand, a .44 D'Eagle with 8 rounds gets neutered down to 400. If we go even lower to .357 (which the D'Eagle also can carry), even with a 9 round mag, that's just 360 damage. Personally I think it'd be really cool if I coded the D'Eagle to be modifiable to accept all of these calibers depending which barrel the gun had attached.

But, enough about the D'Eagle. I don't think it's available outside Renegade game mode right now anyway.

- Mateba with this nerf is now just 240 total per full magazine. Suddenly a lot less bullshit.
- Derringer, which can currently shoot someone right into 120 (crit/dying) and has no accuracy debuf. That's kind of bullshit for a gun that's so easily concealed. Now it's just 80 damage. Enough to fuck a person up, but not enough to insta-murder them. These aren't even hollow point rounds. They will still ruin your day, and they have a chance of blowing your head off, but they won't instantly fucking wreck you well into crit with just two shots. Also this probably needs an accuracy debuf, but more on that later.
- .45 Pistols will see a slight buff in damage capability to make them not completely worthless in a fire fight. I feel like 30 damage is the bare minimum for a weapon in SS13 being viable in combat. Anything less, and it just doesn't feel like it has any stopping power. With 7 rounds a mag, a colt can only hold 210 worth of damage points.
- 9mm stays as it is, because the goal of a 9mm is to put a lot of holes into someone, rather than big holes. This is true to the game, and true to realism.

#### Code Revision
- https://github.com/PolarisSS13/Polaris/commit/b9007d11a898f498465f672bada422b8350d09c2
 
#### Anything else you may wish to add:
- Discuss the matter. Some of the guns in Polaris code feel OP and bullshit, while others just don't pack enough of a wallop. What do you all think? These damage values I gave are not final. I'm not making changes if no one feels they are necessary.

**Comment by SpadesNeil** [comment]
Y'all need a "Feature Suggestion" or "Balance" tag for issues. Then again my Github looks like a bag of skittles so maybe not.

**Comment by SpadesNeil** [comment]
Yay!

**Comment by Yoshax** [comment]
Dropping .357 damage is a really poor idea, in my opinion. The Revolver is quite possibly the most staple weapon in the game, and has been for the longest time. That's losing 33% of it's damage. Especially not with what you're proposing in having .357 only do 10 more damage than .45, that's kinda awful balance for the antagonists. The .45 changes are take it or leave it, it's not much of a difference and I feel like the .45 serves the role it serves fine. It's a weak weapon provided to security as a step between 'oh shit' and 'im bored'.

**Comment by Anewbe** [comment]
Yeah, I'm not really seeing the need for this, overall. The guns seem to mess people up just fine in my experience, and the revolver doing 60 is balanced by the fact that it's expensive and loud.

**Comment by SpadesNeil** [comment]
(To confess, I agree, but @Arokha was the one who brought this to my attention so...)

-throws fox to the wolves and flees-

**Comment by SpadesNeil** [comment]
seriously though the derringer needs a debuff in accuracy at least, because that's a little insane, but that's a separate issue

**Comment by Arokha** [comment]
> -throws fox to the wolves and flees-

Wat, I never told you to post an issue about it here or anything. For them the only way to get a derringer is to spend 40tc on it which is actually a decent amount. For us... one person starts with one for some reason. ;c

**Comment by SpadesNeil** [comment]
>Wat, I never told you to post an issue about it here or anything. For them the only way to get a derringer is to spend 40tc on it which is actually a decent amount. For us... one person starts with one for some reason. ;c

-**FLEES LOUDLY**-
