### ISSUE TITLE
Clickdelay issues

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#351]
Fire axe cabinet has no click delay, results in being able to bash it open in under a second.
![image](https://cloud.githubusercontent.com/assets/8376059/11457162/bc924180-9699-11e5-9f51-90c2b7865121.png)

**Comment by Spookerton** [comment]
Laptops also suffer from no click delay in at least a couple of ways - I was treated to someone hitting one with a booze bottle about eight times a second for a couple of seconds.
