### ISSUE TITLE
Mech Cable Layer Doesn't Work

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#3515]
#### Brief description of the issue
The mecha cable layer does not lay down any cable when activated.
#### What you expected to happen
The mech to place cable under it while it walks with the equipment activated.
#### What actually happened
Nothing happened.
#### Steps to reproduce
1.) Make a Ripley
2.) Attach Cable Layer
3.) Pick up cable coil to stock equipment
4.) Activate equipment
5a.) Walk around on plating and notice nothing happens.
5b.) Click the plating in front of you and notice that nothing still happens
#### Additional info:
 - **Server Revision**: master - 2017-06-04  24b35ace2f2fbbc711ece3c5f5b821935e685c25 
 - **Anything else you may wish to add:** Step 5a was how the cable layer originally worked. Step 5b was simply seeing if it could still work in any other way.

**Comment by Nalarac** [comment]
Still an issue on: master - 2017-12-08 11757132352255fa88f0d06597edcb4efa816fa7

**Comment by lbnesquik** [comment]
Bump.
