### ISSUE TITLE
Destructive analyzer does not 'come apart' when crowbarred

### ISSUE THREAD

**Issue by thezblah** [PolarisSS13/Polaris#3547]
It just spits out a frame and remains whole, it can be repeatedly crowbarred for many, many frames. https://i.gyazo.com/4e12fdcebf607099d474ff3992d5bed1.png

**Comment by Atermonera** [comment]
Unable to reproduce: [https://puu.sh/wz9ZY/d4bd605b3a.mp4](https://puu.sh/wz9ZY/d4bd605b3a.mp4)

Had anything special happened to the analyzer before you tried to deconstruct it?

**Comment by FenodyreeAv** [comment]
I reported this a long time ago. Might have something to do with using the analyser to deconstruct something first, as you'll never disassemble it until you've got better tech.

**Comment by SpadesNeil** [comment]
We're having a similar bug. Not sure if related.

https://github.com/VOREStation/VOREStation/issues/1883

**Comment by Atermonera** [comment]
This is actually a duplicate of #3404
