### ISSUE TITLE
Defibrillators Don't Have Cells

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#3553]
#### Brief description of the issue
The new defibrillators do not start with cells in them.
#### What you expected to happen
The defibrillators to have cells in them (I was told they were supposed to be high-capacity cells?)
#### What actually happened
The defibrillators were empty and required someone to find a cell to slot in.
#### Steps to reproduce
1.) Find a defibrillator
2.) Notice it has no power
3.) Put a cell in
#### Additional info:
 - **Server Revision**: master - 2017-06-29  7164f8ed2301bda770d1ac0da95ed3e93efe655e 
 - **Anything else you may wish to add:** Just an added note that the defibrillators in robotics are not useless since they don't work on FBPs.

**Comment by Atermonera** [comment]
Defibs spawn without a cell, so as to prevent R&D from getting free cells when they manufacture them. This could probably be fixed by editing the mapped-in defibs to have a cell, or by causing defibs in general to spawn with a high-capacity cell (Same power tech rating as defibs) and adjust the material cost of defibs accordingly.

**Comment by Nalarac** [comment]
I'm pretty sure the defibrillator is not even construct-able in the protolathe.

**Comment by Andromeda-K22** [comment]
Defibs do have a tech level, but i'm unsure if they're constructable in the protolathe. I'l look into this.

**Comment by Atermonera** [comment]
Looking through the code a bit more closely, it looks like this is mostly a map change. 
There's a subclass of defibs that will spawn with a high-cap cell, but when #3528 was merged, the mapped defibs weren't updated to the appropriate type.
They need to have /loaded appended to their path

**Comment by Anewbe** [comment]
https://github.com/PolarisSS13/Polaris/pull/3573
