### ISSUE TITLE
Alien Autopsy Feature

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#3569]
#### Brief description of the issue
When I get home from work I am going to begin putting this together. I am posting this as an issue because I want feedback and ideas. I just need to get them all written down so I don't forget again.

So here's the way it's going to work. I'm going to add new variables to every mob to give them a list of organs, and that list will contain the properties of those organs. I am only going to be using the base internal organ object type, because the idea is I will spawn the object and update its variables on the fly, allowing developers to come up with literally whatever they want for a body's internal organs.

So a list item would contain for instance...

Item path probably, name, description, icon path, icon state, and possibly tech levels.

This list will be possible to expand and contract however a developer of a given mob sees fit. For example, Ian is going to have the basics. A brain, eyes, stomach, lungs, etc. However maybe I make some sort of floating jellyfish mob https://github.com/VOREStation/VOREStation/pull/1828 that has no brain. We remove brain from the list. Let's now say that we want to give the mob unique organs like a gas bladder or an extra stomach. Add these to the list with their specified details.

By default, all mobs will have a simple organ name like `[mob.name] [organ.name]`. Example: `corgi liver`. The description will be generic usually. `This organ is used to filter toxins from the blood.` But sometimes you might have more interesting descriptions, such as... `This corgi stomach has trace amounts of beef jerky and paperwork inside of it.` Same as Xenoarcheology, much of the fun is taking apart these creatures to see how they tick.

Every mob you kill though, you only get to collect one or two organs from it intact. When you do the surgery on them, you'll randomly get one from this list. After all, death is a traumatizing experience, and chances are you used an even more traumatizing method to make the creature dead. Lasers, bullets, knives, and blunt impact are not very good for internal organs, y'know.

**However one question remains to all of this.** _Why?_ What should the purpose of alien autopsy be? What is the gain from it? Aside from tech levels, what other things could be unlocked by exploring alien biology? Special chems? A chance to find rare and unique items the creature ate? Say you cut open a Xeno. The chat says, "You find something interesting inside the xenomorph!" And out pops an assistant's uniform. Perhaps certain organs can be used in the construction of some special items. Maybe skin grafts off an alien creature could be used as an alternative to burn healing kits? Or something's liver happens to taste JUST LIKE an ingredient you use in some kind of food? The list of possibilities goes on.

I need more ideas. Any item in the game will be possible to shove into an alien body, resprite, rename, and maintain all the mechanics attached to that item, while turning it into a special organ. One silly idea I had was maybe a Xenomorph femur can be used as a crowbar.

#### Additional info:
 - **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/bbfb6f01fee267907b5736db9ec76c994a257fee

**Comment by SpadesNeil** [comment]
https://github.com/VOREStation/VOREStation/issues/907 Old Vorestation idea we never got to starting.

**Comment by Atermonera** [comment]
@SpadesNeil Any plans on continuing work on this?

**Comment by SpadesNeil** [comment]
I'm fucked on a technical problem that I know is possible to fix but I do not know how.

I need to create a list of lists, and I need to know how to read it. The pieces are otherwise all there. See the old PR and you'll likely see what I screwed up.

**Comment by Atermonera** [comment]
```for(var/list/l in outerlist)
   for(var/thing in l)
      [Do stuff to the thing]```
^ If you need to iterate through everything in the list of lists

If you just need to iterate through each list (The items in the outer list) then you can just scrap the second `for` loop and do stuff with each inner list
