### ISSUE TITLE
Electric Welders Don't Charge in Rechargers

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#3598]
#### Brief description of the issue
Putting an electric welder (with cell inside) into a recharger doesn't charge the cell. The cell needs to be taken out and put into the recharger independently.
#### What you expected to happen
The electric welder to charge in the recharger.
#### What actually happened
The electric welder is put into the recharger and the "recharging" icon occurs, but the cell doesn't actually charge.
#### Steps to reproduce
1.) Create an electric welder
2.) Put an empty cell inside
3.) Put electric welder into a recharger
#### Additional info:
 - **Server Revision**: master - 2017-07-12  ffd1f03e88fb9b8ad06a5f24fbec12845d28fa21

**Comment by Anewbe** [comment]
This isn't a borg issue, is it?

**Comment by Atermonera** [comment]
Rechargers that're used for guns and laptops and whatnot can hold electric welders, but they don't have a block in process() to actually recharge electric welders.

**Comment by Nalarac** [comment]
The electric welders I'm talking about are the ones you can order from cargo or print from a hacked autolathe, not the borg versions.

**Comment by Anewbe** [comment]
Alright, thanks.
