### ISSUE TITLE
Aim Intent issues

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#364]
Aim intent doesn't turn off when the person leaves the screen.
Aim intent isn't disabled by holstering your weapon, changing hands, etc.

A separate person who picks up the gun which had the aim intent stuck on it will inherit that aim with the gun.

**Comment by Neerti** [comment]
Should be fixed with Zuhayr's aim rewrite.  If this is still bugged, reopen the issue.
