### ISSUE TITLE
Using one droppod door activates them all.

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#365]
Title. Priming the door charge on one pod, will also activate ALL of the rest.

**Comment by Zuhayr** [comment]
By design.

**Comment by Neerti** [comment]
I think he means if you drop two pods, both open at the same time if one of them is triggered.

**Comment by Zuhayr** [comment]
Currently they just prime all doors within a small radius. Not sure how you would easily check this without maybe grabbing the center pod turf using the dir of the doors and doing range(1).

**Comment by Zuhayr** [comment]
I swear I posted here!

Currently pods just do a loop over range(3) or something and activate every door they find. You might have some trouble working out how to limit it only to local doors.

**Comment by PsiOmegaDelta** [comment]
On pod creation I suppose you could generate a random number that's assigned to the doors and the primer, and checked on activation.
Don't really have to complicate it more than that the risk of having two drop pods (within range of each other) getting the same id is rather small.

**Comment by Zuhayr** [comment]
Better to just increment a pod count var, that way there's no crossover potential at all.

**Comment by Mark9013100** [comment]
Right, closing since this isn't a bug.
