### ISSUE TITLE
Off for a joy ride on the Zero G Trolly

### ISSUE THREAD

**Issue by HawkerTheGreat** [PolarisSS13/Polaris#3693]
#### Brief description of the issue

I have no idea if this is normal, but apparently the trolly breaks the laws of physics, because it can just drive in the air wherever it wants to as if its some sort of space craft... The Other carts don't seem to follow it, however.

There is no better physics than this.

---

Anyone who is curious about what it looks like, I posted a picture on our port's side.

https://github.com/VOREStation/VOREStation/issues/1968

I think this is just about applying the same physics that the mechs get to the trollys and so.

**Comment by HawkerTheGreat** [comment]
Just curious - to make sure... You all have trollys, correct?... I honestly have no idea.

**Comment by SpadesNeil** [comment]
Yes they have trollies. They do not have multi-Z though.

**Comment by HawkerTheGreat** [comment]
This is irrelevant in that case. Closed.

**Comment by Belsima** [comment]
We have Multi-Z code, just not the map. Any fix you guys have would probably be good to forward here.

**Comment by SpadesNeil** [comment]
I think you guys might just be better off porting from downstream because there's *a lot* we messed with so it'd work.
