### ISSUE TITLE
Shotgun clips are unbalanced

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#3696]
#### Brief description of the issue
Loading ammo into a shotgun is supposed to take time. It's a shotgun. I'm not really a fan of the fact that its a clip instead of some kind of storage container such as the actual boxes of shotgun ammo.

#### What you expected to happen
I expect there to be some kind of cooldown or time constraint to reloading your shotgun shell-by-shell, like you do with the shotgun ammo boxes.

#### What actually happened
I can instantly reload my gun.

#### Steps to reproduce
1. Fire a shotgun a few times.
2. Reload a shotgun using a clip.
3. Spam steps 1 and 2 to output an obscene amount of firepower.

#### Additional info:
 - **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/33cf688b7b84a80dd87d74df706ac7404e3aee8b
 - **Anything else you may wish to add:** If we could use code similar to how the donut boxes work for overlays, combined with the shotgun ammo box code, we could create something that isn't brokenly OP and is also very satisfying to use.

**Comment by SpadesNeil** [comment]
Furthermore, shotgun clips are in every way superior to shotgun ammo boxes.

- Easier to make.
- Faster reload.
- Takes up the same bag space.
- Fits in pockets.

**Comment by Atermonera** [comment]
#4308
