### ISSUE TITLE
Issue With Research Machinery Efficiency Upgrades

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#3709]
#### Brief description of the issue
When upgraded with superior parts from the protolathe, the research machinery (protolathe, circuit imprinter, prosthetic fabricator, and mech fabricator) uses less materials but still requires the default amount of materials to start production.
#### What you expected to happen
Only the used amount of resources to be required.
#### What actually happened
The default amount of materials was required despite only uses the efficiency upgraded amount in production.
#### Steps to reproduce
(Best seen in the robotics fabricators)
1.) Stock research machinery with just enough materials
2.) Upgrade machinery with superior parts
3.) Attempt to create part that you have just enough materials for
4.) Watch part not be created
ex.
![](https://image.prntscr.com/image/lNzByKwuS4K108ASJA_6qg.png)
#### Additional info:
 - **Server Revision**: master - 2017-08-05  1a7d47fc6bf3d06d29a83501847496c4a87fb66c 
 - **Anything else you may wish to add** The protolathe shows default materials required after being upgraded despite using the new efficient prices.

**Comment by Atermonera** [comment]
It looks to me like you had a tenth the required diamonds, although the warning is still in error

**Comment by Nalarac** [comment]
I just took the picture to give a better visual of the bug.
