### ISSUE TITLE
Flares cause input delay when carried

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#3753]
#### Brief description of the issue
Large radius coloured light sources cause massive input lag when carried, or dragged by players. (Flares being the only example in game.)

#### What you expected to happen
To be able to walk normally when carrying a flare.

#### What actually happened
Walking very slowly, and carrying on moving after the momement key has been released.

#### Steps to reproduce
Pop a flare and go for a jog.

#### Additional info:
Server revision: master - 2017-08-20
676fb6daf631c113312f08eeeb35207b033112c7

**Comment by MisterLayne** [comment]
I think this is a more of a problem with the lack of optimization for BYOND in general.
