### ISSUE TITLE
Prometheans still have to choose male or female as a biological sex.

### ISSUE THREAD

**Issue by MagmaRam** [PolarisSS13/Polaris#3754]
#### Brief description of the issue
Prometheans are, biologically, sexless. They still have to pick male or female on character select under "biological sex"

#### What you expected to happen
Not to have any options but "sexless" there.

#### What actually happened
slime grills and slime boings

#### Steps to reproduce
Change your species to Promethean in character setup

#### Additional info:
I need to look into how plausible changing this even is myself, it might be that SS13 code is stupid and relies on biological sex being one of two things way too much to make this change easily.

**Comment by Mechoid** [comment]
The male/female option for biological is for sprite base appearance, so it'd be a good idea to keep that there, though adding a 'sexless' option would be advisable, yeah.

**Comment by Belsima** [comment]
https://github.com/PolarisSS13/Polaris/pull/3799
