### ISSUE TITLE
Floor decals are deleted when a shuttle moves

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#3755]
#### Brief description of the issue
See title

#### What you expected to happen
For floor decals to be carried with everything else on the terrain

#### What actually happened
Floor decals disappear permanently.

#### Steps to reproduce
1. Be on a shuttle at its starting location. Observe (or place) floor decals.
2. Launch the shuttle.

#### Additional info:
 - **Server Revision**: Technically found on Vorestation but I'm like 98% sure we didn't do this. https://github.com/VOREStation/VOREStation/commit/f2e7f35a5db60bc7487ae1b7f969a753d94cfdc8

**Comment by Neerti** [comment]
Did this happen before or after #3726 got added?

**Comment by SpadesNeil** [comment]
Definitely after. If you guys aren't having a similar issue then the problem must be on our end.
