### ISSUE TITLE
Joined as Tajaran Station Engineer, was swallowed by the cold vastness of space

### ISSUE THREAD

**Issue by Earthcrusher** [PolarisSS13/Polaris#376]
As much data as I have:

* Round type: Autotraitor
* Round duration: approx. 1:10
* Character: Female Tajaran
* Attempted to join as: Station Engineer
* Arrivals point: Arrivals shuttle

Spawned into the round with no possessions but a pair of black jeans (in my loadout), no IC mind notes, and... out in some unspecified point in outer space. Was given a respawn, tried joining again as the same job. Same result. Given another respawn. Set my arrivals point to Gateway, tried joining as an atmos engineer.

SPACE.

Final round: Joined as a female human whose starting point was the Arrivals Shuttle. Joined as a station engineer. Worked just fine.

Server racism confirmed

**Comment by Earthcrusher** [comment]
Forgot to mention: I had the "Regurgitate" ability.

**Comment by mwerezak** [comment]
Sounds like a runtime in the player setup and spawning code.

**Comment by Mark9013100** [comment]
Happened again, station engineer, regular title.

**Comment by Bromuzl** [comment]
Happened again last afternoon, human male chief medical officer, slot 5. Will paste screenshot tomorrow.

**Comment by SinTwo** [comment]
And another. This time tried a known to work character slot, Engineer job, late join. Attempted to create the character in another slot, still did not work. Attempted to use both to join as an assistant, still spawned in space.

**Comment by Bromuzl** [comment]
CKEY ackserious, Morgan Wolfe, Assistant (Technical Assistant) first and only slot and shuttle arrival.

**Comment by Neerti** [comment]
He failed to spawn with a manifest entry, and had no radio, PDA, ID card, and one custom item (a scarf IIRC).

**Comment by zaredman** [comment]
Happened again. Assistant, human, female.

 [Player PM] Dragon2323/(Ciaran Kyander)(?): Personal Communicator, Black Gloves, Orange Scarf, Orange Bandana, Simple Webbing, a Military Jacket, and Camo Pants are all that I spawned with.

Only spawned with gloves.

**Comment by Zuhayr** [comment]
Sounds like a runtime error with loadout, potentially.

**Comment by Mark9013100** [comment]
Current suspect is the scarves.

**Comment by Neerti** [comment]
It is indeed the orange scarf.  The loadout list entry lacks a ```path``` variable.  This is actually a super easy fix.
