### ISSUE TITLE
Toxins Mixing Airlock does not cycle properly

### ISSUE THREAD

**Issue by SledgeLP** [PolarisSS13/Polaris#38]
Cycling to the mixing chamber it's self seems to work mostly fine, except that the external airlock doesn't work properly and must be forced to work properly. The dual end vent also does not seem to syphon.

**Comment by Woodratt** [comment]
Dual end vents as far as I know are broken and never work. Someone test to see if this airlock cycles properly. I think I fixed it but I don't remember.
