### ISSUE TITLE
Prone people can interact on all intents.

### ISSUE THREAD

**Issue by Spookerton** [PolarisSS13/Polaris#380]
It's pretty funny, but two people prone next to one another punching and pushing and shaking each other upright is probably no intended behaviour.

**Comment by Spookerton** [comment]
As #379 , https://gyazo.com/d79841fd5a8c10355a974772d6547e3b

**Comment by EmperorJon** [comment]
This sounds hilarious, can we keep it?

**Comment by Neerti** [comment]
No.

**Comment by zaredman** [comment]
Able to recreate on Bay-Dev

**Comment by MagmaRam** [comment]
This is still an issue as of now.

**Comment by Bromuzl** [comment]
I was looking for old bugs to piddle away at, but I'm not sure why 410199b was referenced? It looks unrelated unless this is a mechanic in BS12 which is working as intended for another part of their code?
