### ISSUE TITLE
Autoheal is a little bit too much

### ISSUE THREAD

**Issue by Wickedtemp** [PolarisSS13/Polaris#3817]
#### Brief description of the issue
Right now, you can autoheal yourself from 110 damage.
#### What you expected to happen
Ended up taking around 90 burn damage from a mix of fire and acid. You should need medical attention for that.
#### What actually happened
Autoheal took care of it in about a minute.
#### Steps to reproduce
Damage every limb to around 9 brute/burn damage. This adds up to 108 damage. You'll autoheal from this. 
#### Additional info:
 - This is because of autoheal working on each limb independently. If the limb takes 10 damage, the autoheal process stops and has to be restarted by an advanced trauma/burn kit, which then resumes autoheal for that limb and raises the cut-off damage to 50 instead of 10. 

This reduces the effectiveness of fire, since the bulk of the damage is dispersed and you're autohealing as you're being burnt. It also means if someone pumps you full of acid, unless the dose is high enough to kill you outright, you're going to not only survive, but autoheal from all of it. 

As a medical player, this kinda takes action out of my game, and watching someone magically heal themselves all the way from severely damaged to green is a little odd to explain ICly. As a solution for this, I'd suggest either reducing the cut-off point per limb from 10 to 5. Trauma/Burn kits restarting it at 50 seems fine enough to me, I'd personally keep it between 20-60. As an alternative, if 5 damage per limb is too low, it could be modified to have a cut-off of 20 *total* limb damage, instead of 10 damage per limb. I think that makes a little more sense.

**Comment by Wickedtemp** [comment]
Another alternative is to give autoheal a delay. Perhaps maybe 60 seconds or so after damage is received, that way you aren't autohealing fire burns *as* it's burning you.

**Comment by Atermonera** [comment]
Tox damage isn't autohealed, so I think fire is about the only damage source that will regularly cause damage to be distributed over a million tiny burns than in one single wound

**Comment by Wickedtemp** [comment]
It's burn/brute, so a few causes of widespread burn and brute damage would be: Acid injections, atmos fire, having your character itself ignite, brute damage from arithrazine... I'm sure there are others, but those are the ones off the top of my head. I think the best course of action for this is to just add a delay, so if you're taking damage, you aren't autohealing as you're being injured.

**Comment by Wickedtemp** [comment]
Closed, since it's getting a much needed delay.
