### ISSUE TITLE
CryoStorage Escapepod doors

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#3853]
#### Brief description of the issue
When you arm the Cryo escape pod, it bolts open one of the closed doors, so when it launches it immidietly spaces the hallway
#### What you expected to happen
For all the doors to remain closed and perhaps even bolt shut for safety reasons
#### What actually happened
The door here [https://gyazo.com/262bf460e5c71e7c35b987f156aa6b13] will open when you arm the pod and bolt open. [disregard the traitor assistant please]
#### Steps to reproduce
Go to the cryo storage, switch the pod doors to manual and arm it and watch as that door opens and bolts open or remains open and bolts
#### Additional info:
 - **Server Revision**: master - 2017-09-16
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Should be fixed.
