### ISSUE TITLE
Corprate Regs not showing

### ISSUE THREAD

**Issue by ApolloDensin** [PolarisSS13/Polaris#3858]
#### Brief description of the issue
When opening the corporate regs there is an error message
#### What you expected to happen
A list of laws and regulation
#### What actually happened
Error messages without regs displaying
#### Steps to reproduce
open a corp reg book
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Thank you.
