### ISSUE TITLE
Camera's in research not connected to anything

### ISSUE THREAD

**Issue by ApolloDensin** [PolarisSS13/Polaris#3860]
#### Brief description of the issue
There are nine camera's in the research wing that appear to be disabled, but are not connected to anything on the list. These are present at each round start
#### What you expected to happen
All camera's to be linked to something or not show up if there is no camera
#### What actually happened
Nine camera's are register that are not actually there.
#### Steps to reproduce
Start a round, look at security camera's, see nine camera's that are not linked to anything and are not present
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Those cameras are present so enterprising Scientists can set up new cameras for whatever reason.

If memory serves, the reason they show up on the consoles is because they need to be connected to a network to be mapped in, even if they're not attached to walls.

I don't think this is a bug.

**Comment by ApolloDensin** [comment]
I think actually part of it is helmet cameras for their units, just saw the RD with a rig with it on.

**Comment by SubberTheFabulous** [comment]
It's integrated circuits cameras.

**Comment by Belsima** [comment]
Shouldn't this be closed?
