### ISSUE TITLE
Ninja ID cards do not confirm copying access.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#389]
Attempted to copy the Captain's spare ID card.
Using the card showed it had full access, but there was no message telling me that stealing the access was successful
![image](https://cloud.githubusercontent.com/assets/8376059/11530980/264e8b84-98f1-11e5-9713-802b6d2d1115.png)

**Comment by PsiOmegaDelta** [comment]
See https://github.com/Baystation12/Baystation12/pull/11568.

**Comment by zaredman** [comment]
Fix-o maybe exist-o so marking as 'easy fix'
