### ISSUE TITLE
Ninja power sink does not drain power.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#391]
Using the power sink will cause a shower of sparks, and then nothing. No power will be drained from a SMES or APC, and the suit will not gain charge.
Clicking the second time with the power sink still active will bring up the NanoUI of the SMES or APC.
![image](https://cloud.githubusercontent.com/assets/8376059/11531186/ec9b913c-98f2-11e5-8348-d5c16b847e9e.png)

Retracting and redeploying the power sink will allow allow you to begin power draining again, but the suit will not recharge, and there is only one shower of sparks.

**Comment by zaredman** [comment]
Polaris-only bug.

**Comment by Spookerton** [comment]
Unable to replicate after testing by @SinTwo @zaredman
