### ISSUE TITLE
Pumpkins

### ISSUE THREAD

**Issue by ApolloDensin** [PolarisSS13/Polaris#3934]
#### Brief description of the issue
Pumpkins are green and look like a watermelon, but turn into a pumpkin shape and color when carved
#### What you expected to happen
For ripe pumpkins to look the correct shape
#### What actually happened
they look like a watermelon
#### Steps to reproduce
Grow a pumpkin and then harvest them
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Known thing, the way hydroponics works might make this unfixable.

**Comment by Atermonera** [comment]
Duplicate of #1203
