### ISSUE TITLE
Simple Mob's with guns don't fire.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#394]
All simple mobs play sound effects, and display messages saying they have fired.
Simple mobs intended to fire ballistics have the bullets hang in the air.
Simple mobs that fire lasers seem to just do nothing.

![image](https://cloud.githubusercontent.com/assets/8376059/11532806/435f8572-98fe-11e5-9692-3ade69f334f2.png)

**Comment by Datraen** [comment]
I bet it has something to do with firing code for them not being updated when projectiles were changed.
