### ISSUE TITLE
Skrell female colorable headtail cloth

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#3990]
#### Brief description of the issue
Spawning with the colorable headtail cloth[ female] for skrell just gives you the black headtail cloth
https://gyazo.com/7fc3fb104345cd1a86a481ae4d754fa5
#### What you expected to happen
To get the cloth I wanted.
#### What actually happened
Spawn with just a black pair.
https://gyazo.com/1d4a1c48c2809e2cc0c944939a06fca3
#### Steps to reproduce
Pick out the cloth and a nice color.
spawn in
Realize you only got the black varient.
#### Additional info:
 - **Server Revision**:master - 2017-09-29
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by PrismaticGynoid** [comment]
The male cloth too, last I checked.

**Comment by Belsima** [comment]
Fix is up.
