### ISSUE TITLE
Blood cult images not appearing.

### ISSUE THREAD

**Issue by bewawolf19** [PolarisSS13/Polaris#3996]
#### Brief description of the issue
Images drawn in blood by (Presumed) cultists do not appear visible to the stationbound AI vision, and only appear if an image is taken (And then only in the photo)
#### What you expected to happen

I expected to see the garden entirely filled with blood images
#### What actually happened

I saw the normal garden floors with nothing on them
#### Steps to reproduce

Be a stationbound AI, and have (presumed) cultists make blood runes on the floor within camera range
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
Server revision info:
b31df8b4aeb028611fe19732137f6c0ead043da6 

Date:09/29/17

I do not know if normal crayon graffitti is visible or not.

Favorite type of cookie: Chocolate Chip

**Comment by Neerti** [comment]
I believe that is intended.

**Comment by bewawolf19** [comment]
Alright, though it is weird that an AI wouldn't be able to see an entire room filled with blood images, but can see a small mouse on the ground, and still weird that taking a camera picture reveals it.

**Comment by Woodratt** [comment]
Thought it used to show the runes as drips or puddles of blood.

**Comment by Anewbe** [comment]
That's a feature, in complete and utter seriousness. It's old code from at least /tg/ that stops the all-seeing Camera God from ending a cult round in the first ten minutes.

**Comment by Wutnold124** [comment]
honestly their fault if they don't know how to cut or hack a camera

**Comment by MisterLayne** [comment]
You can't expect everyone to know how to hack a camera.

**Comment by elgeonmb** [comment]
You can on /tg/ .

**Comment by MisterLayne** [comment]
Your argument is invalid, because this isn't /tg/.

**Comment by Wutnold124** [comment]
your argument is invalid because anybody with common sense who can't hack would just snip the wires to disable the cam
