### ISSUE TITLE
Integrated Electronics Issues

### ISSUE THREAD

**Issue by Atermonera** [PolarisSS13/Polaris#4000]
#### Brief description of the issue
Someone by the username of Selea on the discord made a list of various bits to do with integrated circuits, but lacks a github account to post that here.

> 1.pathfinder circuit just don't want to work.I am simply can't make it to calculate direction to any thing.
> 2.multiplexer don't want to work with ref data type.
> 3.Reagent pump and injector don't work if you are holding device in your hands.

#### What you expected to happen
Presumably, the inverse of the listed conditions.
#### What actually happened
The listed conditions
#### Additional info:
Further information: Ping @selea#8026 on our discord
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by MarinaGryphon** [comment]
When porting Integrated Electronics to Aurorastation, we encountered some of these issues and fixed them. [@Lohikar](https://github.com/Lohikar) should have more information.

**Comment by MarinaGryphon** [comment]
Pathfinder works fine. It has to be within one screen distance.
Multiplexers work with any data type, I believe.
Reagent injectors work, for sure.

**Comment by Atermonera** [comment]
Yeah, they then made an account and coded a bunch of stuff for integrated electronics, and then disappeared with the wind
