### ISSUE TITLE
Prometheans losing gear with limbs.

### ISSUE THREAD

**Issue by Atermonera** [PolarisSS13/Polaris#4004]
#### Brief description of the issue
When a promethean loses a limb, anything that was attached to that limb is deleted along with it.
#### What you expected to happen
For my hat and headset to remain in the puddle of goo when I fell and hit my head.
#### What actually happened
The puddle of goo digested my hat and headset
#### Steps to reproduce
Be promethean
Wear a bunch of stuff in various slots
Fall and break a limb, causing it to splatter everywhere
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Interesting.

**Comment by SilverTalismen** [comment]
Yeah, the only limb I've ever lost as a Promethean is arms and legs, but that was back when the core was in the head so *shrug*

**Comment by Atermonera** [comment]
Probably related to this popping up on the server console:
## TESTING: GC: -- [0x200015f] | /obj/item/organ/external/head/unbreakable/slime was unable to be GC'd and was deleted

**Comment by Atermonera** [comment]
Further testing, looks like this might've just been me being a donk and not seeing them in the pile.
[https://puu.sh/xNyjW/8b17ee5c03.mp4](https://puu.sh/xNyjW/8b17ee5c03.mp4)
That said, falling appears to disproportionately affect arms, legs, heads, and chests in favor of hands, feet, and asses

**Comment by Anewbe** [comment]
IIRC it doesn't actually target any body part, it just picks a random one and slaps it.

**Comment by Magneld** [comment]
I've lost a head before but the headset was fine on the ground.
