### ISSUE TITLE
Picking up the kitten at Central turns you into a fab cube

### ISSUE THREAD

**Issue by Nilsius** [PolarisSS13/Polaris#401]
When I rushed through Central at the end of the round, I picked up this kitten and suddenly turned into a literal 32x32 pink square. Than I tried putting it on my head and it wasn't visible on my character.

**Comment by Earthcrusher** [comment]
I swear to god Polaris has the most amazing bugs

**Comment by MagmaRam** [comment]
This is a sprite issue. Someone needs to make inhand sprites that match cat2 (the default sprite of generic "cat" mobs) and kitten, and put them in lefthand_holder.dmi and righthand_holder.dmi (under the names cat2 and kitten).

I am terrible at spriting and will not be attempting this.

**Comment by Mark9013100** [comment]
I'll try to get to this over the weekend if no one else does.

**Comment by Zuhayr** [comment]
The giant pink square of doom just means that the holder has no icon.
