### ISSUE TITLE
Dionaea constantly starve

### ISSUE THREAD

**Issue by FearTheBlackout** [PolarisSS13/Polaris#403]
I entered a round for the first time as my Diona, Looping Song, only to notice that, no matter how much light I seemed to exist or not exist in, I kept losing nutrition to the point of complete malnourishment. Dionaea, as you probably know, are already slow as-is, making the process of getting anywhere even more grating.

**Comment by MagmaRam** [comment]
This doesn't seem to be bugged. The way diona feeding currently works is that it takes the total light level of the tile you're on (red+blue+green, capped at 10 total), subtracts five, and changes your nutrition by whatever number that comes up with. However, most tiles on the station are in the 1.0-1.5ish range, meaning that through most of the station, light levels are just under what you need to be able to feed. Seems like it's unintended for it to be this tough to feed, though.

**Comment by zaredman** [comment]
Going to close this off. Looking like @MagmaRam fixed this on #417 - as shown above.
