### ISSUE TITLE
Upgrading Cloner Causes Issues

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#4046]
#### Brief description of the issue
When cloning someone after the cloning pod has been upgraded, the patient will be restored to 100% health and awake before the process of cloning is finished, causing them to be stuck in the cloning pod for another few minutes.
#### What you expected to happen
The patient to be ejected when cloning is finished with the enhanced speed.
#### What actually happened
The patient was forced to sit in the cloner for a few minutes until it finally ejected them.
#### Steps to reproduce
1.) Get two pico manipulators and two phasic scanning modules
2.) Upgrade the cloning pod
3.) Get a corpse that can be cloned
4.) Clone individual and watch results
#### Additional info:
 - **Server Revision**: master - 2017-10-11 c343d182ce38d820c3406ea3c22eaad8b7c07df1 
 - **Anything else you may wish to add** This is probably an oversight with the new cloning changes implemented by @Neerti in relation to how the upgrades work.

**Comment by Anewbe** [comment]
Working on a fix right now, may or may not work.
