### ISSUE TITLE
Only Crew Member Law Can't Be Removed

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#4096]
#### Brief description of the issue
The law circuit that adds "0. Only X is an crew member." to synthetics can not be removed with resets or a law purge.
#### What you expected to happen
The law to be removed with at least a purge.
#### What actually happened
The law is impossible to remove.
#### Steps to reproduce
1.) Get One crew member law board
2.) Have AI or cyborg that can have its laws modified
3.) Modify laws with the board
4.) Attempt to remove the law with purge or reset

#### Additional info:
 - **Server Revision**: master - 2017-10-17 fb158c255bcaf1eed10c64b4e41d504962bc600e 
 - **Anything else you may wish to add** I believe someone else using the one crew member board overrides any current "only crew member" laws. I also believe the only crew member law might override traitor law 0's

**Comment by elgeonmb** [comment]
Issue is at AI_modules.dm, line 170. I'd do the fix PR myself but don't wanna break anything; probably change the law from a zeroth law to a supplied law.
