### ISSUE TITLE
Minimum Access config option now broken

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#4138]
#### Brief description of the issue
For the "Minimum Access" thing to remove the "Minimum Access" restriction to jobs when it's commented out.

#### What you expected to happen
To be able to have expanded access on downstream servers.

#### What actually happened
You ding dongs hard-coded job access.

#### Steps to reproduce
1. Disable minimum access in config.
2. Watch as nothing changes.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/f83ede7428a4e422bfdfb8f1763480fddaf5dc64

**Comment by Cameron653** [comment]
https://github.com/PolarisSS13/Polaris/blob/master/code/datums/outfits/outfit.dm#L151-L163

The above lines is where the the id is made & applied to the person currently, while it used to do the below:

https://github.com/PolarisSS13/Polaris/blob/master/code/game/jobs/job_controller.dm#L505-L532

See:
```c
C.access = job.get_access()
```

The get_access proc itself:
https://github.com/PolarisSS13/Polaris/blob/7cafd7d2391e823eccaa0688e536d8dec1e2f1da/code/game/jobs/job/job.dm#L88-L92

**Comment by Anewbe** [comment]
Aim to look into this today, but I'm running on about a third as much sleep as I'd like to be.

**Comment by SpadesNeil** [comment]
https://www.youtube.com/watch?v=1Isjgc0oX0s
