### ISSUE TITLE
Dead & Unconcious people can take other people's clothes off.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#4218]
#### Brief description of the issue
I took the CMO's pants off while they were doing surgery on my heart.

#### What you expected to happen
Not that

#### What actually happened
De-pantsed my doctor.

#### Steps to reproduce
Be dead, and be operated on.
Clickdrag their sprite to you, as normal for stripping.
See it work, giggle.

**Comment by OrbisAnima** [comment]
Polaris Issue.

That said, it could be a feature for us..

**Comment by Atermonera** [comment]
Should've been closed by #4265
