### ISSUE TITLE
Deconstructing VR sleepers causes your consciousness to be adrift in the network for all time.

### ISSUE THREAD

**Issue by elgeonmb** [PolarisSS13/Polaris#4220]
#### Brief description of the issue
If you decon a VR sleeper someone's in, the link between them breaks.
#### What you expected to happen
This to eject the mind back into the body.
#### What actually happened
The above
#### Steps to reproduce
Decon a VR pod someone's in.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Andromeda-K22** [comment]
This should be an e-mag feature.

**Comment by Belsima** [comment]
sounds perfect to me

**Comment by Atermonera** [comment]
Do you become totally unable to exit VR, or does it just not eject you?

**Comment by elgeonmb** [comment]
Apparently can't exit-- I haven't tested extensively.

**Comment by MarinaGryphon** [comment]
This happened to me once. My physical body disappeared and I couldn't exit.

Should probably just eject the occupant's body and remove them from VR on deconstruction?

**Comment by Atermonera** [comment]
Yeah, I'll get around to it probably next week, unless a fit of boredom brings me to do it sooner
