### ISSUE TITLE
Autohiss converts 'R' to 'r'

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#424]
Only tested with Tajaran, but probably happens the same for Unathi. The capitals are converted to non-capitals. Only tested on full mode.

**Comment by GinjaNinja32** [comment]
It'll convert 'R' to 'Rrr', I didn't think of full-caps when I wrote it. I'll do a Bay fix PR today, merge it down to dev and poke Neerti or whoever to merge it over here.

**Comment by zaredman** [comment]
Fix exists on Baystation12/Baystation12#11597
