### ISSUE TITLE
Able to attempt to pull off people's gear while stunned.

### ISSUE THREAD

**Issue by MerekBlack** [PolarisSS13/Polaris#4244]
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Duplicate of #1977

**Comment by Atermonera** [comment]
Missed this when I put up #4265 but it should've been closed by it
