### ISSUE TITLE
show-hidden-verbs don't work reliably

### ISSUE THREAD

**Issue by elgeonmb** [PolarisSS13/Polaris#4251]
#### Brief description of the issue
The AI HUD we've had for like a year now has never actually been backwards compatible; show-hidden-verbs doesn't actually show all hidden verbs in the tabs and in verb autocomplete
#### What you expected to happen
To be able to ignore the HUD and continue typing verbs
#### What actually happened
Having to remember which ten verbs got made into buttons for some reason
#### Steps to reproduce
Use the hidden verbs command
Try using one of these verbs
Quit AI in frustration, become a secofficer main.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Inform the Mechoid, this has drawn his ire in the past.

**Comment by elgeonmb** [comment]
@Mechoid save us

**Comment by elgeonmb** [comment]
fixes https://github.com/PolarisSS13/Polaris/pull/893

the relevant pr

**Comment by elgeonmb** [comment]
...also like, if it could be.... on.... by default.... that would be grand....... admin hidden verbs are on by default.....

**Comment by Atermonera** [comment]
Did the original PR actually add any verbs, and if not, would people be opposed to reverting it outright?

**Comment by elgeonmb** [comment]
It didn't add any verbs and I want it dead if possible

**Comment by Nalarac** [comment]
@elgeonmb You can close this now since the fix was merged.
