### ISSUE TITLE
F6 > Player Panel > Search feature not working

### ISSUE THREAD

**Issue by zaredman** [PolarisSS13/Polaris#427]
See title.

**Comment by EmperorJon** [comment]
Please at least do a rudimentary search before reporting... :p

Duplicate of #341.

**Comment by zaredman** [comment]
YOU KNOW WHAT I LOOKED OK

I DIDNT LOOK HARD BUT I LOOKED

GIVE ME THAT AT LEAST

**Comment by EmperorJon** [comment]
Well maybe you should have looked harder. Using the search function. Not the one in the player panel, though, that's broken. Someone should report that.
