### ISSUE TITLE
Small memory circuit has no sprite.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#4273]
#### Brief description of the issue
Small memory circuit has no sprite.

#### What you expected to happen
It to have a sprite

#### What actually happened
No sprite
![image](https://user-images.githubusercontent.com/8376059/32904610-a1b02788-caef-11e7-9bad-1e6da1342aca.png)

#### Steps to reproduce
Make one from a circuit printer

#### Additional info:
 - **Server Revision**: 
![image](https://user-images.githubusercontent.com/8376059/32904631-b18e2e0c-caef-11e7-95c6-9dd261277769.png)

**Comment by Belsima** [comment]
On this one. Give me a couple days.

**Comment by Belsima** [comment]
...got my computer up, finally. NOW give me a couple days.
