### ISSUE TITLE
Putting an item into a full container (or one that's too small) makes said item drop

### ISSUE THREAD

**Issue by Sabess** [PolarisSS13/Polaris#428]
If you put an item into any container that's full (i.e a full backpack) or any item that has storage, but can't fit the item (i.e hand labeller on a heavy vest), the item will drop to the ground rather than remaining in your hand.

**Comment by Mark9013100** [comment]
Duplicate of #256.

**Comment by Sabess** [comment]
Sortaish duplicate, I guess. That's saying it's just with duffle bags, so.

**Comment by Hubblenaut** [comment]
This is more exact than #256. The issue revolves around a code cleanup from bay dev, resulting in any content rejection to be dropped on the floor.

**Comment by Mark9013100** [comment]
No longer an issue.

**Comment by Zuhayr** [comment]
Can you ref the fix for the sake of completeness?

**Comment by GinjaNinja32** [comment]
#717
