### ISSUE TITLE
Cameras lag the server really hard

### ISSUE THREAD

**Issue by Dibasic** [PolarisSS13/Polaris#431]
If you set a camera to 7x7 and click to take a photo the whole server stops for 5-10 seconds.

**Comment by Hubblenaut** [comment]
This is due to the resource-expensive icon procs. It's the primary reason cameras were used to only take 3x3 pictures. There is no way to circumvent the lag, either leave or delete.

**Comment by RenScorch** [comment]
This most likely should be something that should be brought back down to 3x3 as I forsee this being abused by trolls to freeze and abuse the server.
