### ISSUE TITLE
Southern Cross camera consoles have a 'null' option.

### ISSUE THREAD

**Issue by Belsima** [PolarisSS13/Polaris#4353]
#### Brief description of the issue

![image](https://i.imgur.com/HCB4T6G.png)

#### What you expected to happen

No 'null' option that does nothing when clicked.

#### What actually happened

The above.

#### Steps to reproduce

Find a security camera console. Click on it. 

#### Additional info:
 - **Server Revision**: master - 2017-11-26 63a62a273911fdb20fd1fc9019dc85b6d8e411bf

**Comment by Belsima** [comment]
fuck i pressed enter lemme edit that

**Comment by Nalarac** [comment]
This is no longer an issue and can be closed. Likely fixed by #4694 specifically.
