### ISSUE TITLE
Advanced Roller Beds Turn Invisible

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#4363]
#### Brief description of the issue
When someone is buckled into one of the new advanced roller beds that can be created from RnD, the roller bed turns invisible.
#### What you expected to happen
The advanced roller bed to have a sprite when a patient is buckled to it.
#### What actually happened
The advanced roller bed was invisible
#### Steps to reproduce
1.) Get an advanced roller bed
2.) Unfold it
3.) Buckle someone onto it
#### Additional info:
 - **Server Revision**: master - 2017-11-28 667931ae2da7861435877823d9f5f83408c07cdb 
 - **Anything else you may wish to add** This item was recently added in #4319

**Comment by mistyLuminescence** [comment]
Working on it rn, whoops (could've sworn I tested this??)

**Comment by mistyLuminescence** [comment]
Fixed by #4364
