### ISSUE TITLE
Teshari Prosthetics+FBP Non-existant

### ISSUE THREAD

**Issue by Lemmypepper** [PolarisSS13/Polaris#4368]
#### Brief description of the issue
Teshari do not have prosthetics or FBPs like other species have.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
This is intentional.
