### ISSUE TITLE
Teshari Prosthetics+FBP Non-existant

### ISSUE THREAD

**Issue by Lemmypepper** [PolarisSS13/Polaris#4369]
#### Brief description of the issue
Teshari do not have prosthetics or FBPs like other species have.

#### What you expected to happen
Options for prothetics that atleast match the Teshari bodytype.

#### What actually happened
Species specific prosthetics are unavailable and the other options do not match since they were made with a humanoid figure in mind

#### Steps to reproduce
(Step 1) Choose Teshari as a race
(Step 2) Find that there are no prosthetics or a FBP for the species
(Step 3) Try not to cry
(Step 4) Cry a lot.

**Comment by Anewbe** [comment]
This is intended. Please don't open bug reports for issues that are not bugs, especially not immediately after said reports are closed.

**Comment by Lemmypepper** [comment]
The last issue I made was sent by accident and wasn't complete. And you say that the lack of prosthetics is intentional?

**Comment by Belsima** [comment]
@Anewbe Kholdstare last told me that Tesh FBPs are wanted. I'd say this is classified as a feature request.
