### ISSUE TITLE
Cargo tugs are hilariously bork.

### ISSUE THREAD

**Issue by Magneld** [PolarisSS13/Polaris#441]
Any attempts to hop in the driver seat of a cargo tug results in the picture down below, essentially you uh.. I dunno sit on it ass up and.. yeah I dont know I cant stop laughing but basically you cant drive them at the moment.

http://imgur.com/MzWDL5J

**Comment by Zuhayr** [comment]
Does not seem to be an issue on the current build.

**Comment by Datraen** [comment]
Ah, forgot to ref the proper fix, will resolve later.

**Comment by Datraen** [comment]
#443 is the fix
