### ISSUE TITLE
Rainbow slime cores can make wild dark blue slimes

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#4436]
#### Brief description of the issue
The rainbow slime core has a chance of creating the wild dark blue slimes that inhabit Sif.
#### What you expected to happen
The wild dark blue slime to be excluded from the choices for the rainbow core.
#### What actually happened
![](https://image.prntscr.com/image/Zjwe8AytSX6L_SjVlzoV2Q.png)
#### Steps to reproduce
1.) Get rainbow slime core
2.) Inject with phoron
3.) Random chance of getting wild slime
#### Additional info:
 - **Server Revision**: master - 2017-12-08 11757132352255fa88f0d06597edcb4efa816fa7

**Comment by Atermonera** [comment]
#4482
