### ISSUE TITLE
GPS Research Levels

### ISSUE THREAD

**Issue by MisterLayne** [PolarisSS13/Polaris#4447]
#### Brief description of the issue
GPS has weird research levels.

#### What you expected to happen
Get me some hot research.

#### What actually happened
I have no clue. Research names wouldn't show.

#### Steps to reproduce
Make a GPS. Decon it.

#### Additional info:
 - **Server Revision**: 
Server revision: master - 2017-12-08
11757132352255fa88f0d06597edcb4efa816fa7 

 - 
![image](https://user-images.githubusercontent.com/31356648/34084285-6958fb70-e34b-11e7-9e48-abb625690167.png)

**Comment by Atermonera** [comment]
Typos in the origin tech
`origin_tech = list(TECH_MATERIALS = 2, TECH_BLUESPACE = 2, TECH_MAGNETS = 1)` 
should be
`origin_tech = list(TECH_MATERIAL = 2, TECH_BLUESPACE = 2, TECH_MAGNET = 1)`
