### ISSUE TITLE
Sleepers cannot be seen from spinned views. 

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#447]
Original view:

![](http://i.imgur.com/kEWF55l.png)

From the sides:

![](http://i.imgur.com/nJj1CQH.png)

![](http://i.imgur.com/ThDJv8V.png)

Upside down: 

![](http://i.imgur.com/eVPyvsw.png)

**Comment by GinjaNinja32** [comment]
i am 100% sure i added vertical sprites for them from /tg/, at least on bay, so unless you guys have poked sprites it should work :c

**Comment by Woodratt** [comment]
I think we did when we mucked with getting the consoles back. I'll take a look see.

**Comment by GinjaNinja32** [comment]
partially fixed in #504

**Comment by GinjaNinja32** [comment]
fully fixed in #504
