### ISSUE TITLE
[Discuss] Rebalance Security's sidearm

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#4472]
#### ~~Brief~~ description of the issue
Being discussed at https://github.com/VOREStation/VOREStation/issues/2649 currently.

So here's the issue. The ammo capacity compared to damage output of the Colt M1911 and its variants which all have the same ammo capacity is downright pathetic. One of my users suggested replacing it with a 9mm gun that has 17 rounds of ammo.

Obviously there's problems with that suggestion.

To quote @Yoshax:
>So. Let's get things straight for a moment. You want to replace the 7 shot 25 damage gun, with a 17 shot 20 damage gun?

>.45: 7 * 25 = 175
>Proposed 9mm: 17 * 20 = 340
>Revolver: 6 * 60 = 360
>Machine Pistol; 20 * 20 = 400
>DMR: 10 * 35 = 350 (15 armor penetration)

_But_ as a gun owner IRL, I happen to own a Beretta 92FS which can accept both Massachusetts compliant 10 round magazines _or_ magazines of capacities up to 17 rounds in the same sized mag.

So here is what I propose instead.

Let's replace the current sidearm accepting .45 with a pistol that accepts 9mm or even .40 caliber instead, though .40 would be a new ammo type which we may wish to avoid. I just say .40 caliber in case you want the stopping power of a .45 with the ammo capacity of a 9mm, as IRL, a .40 is basically just a 9mm with more kick behind the bullet.

The reasoning behind this:

- Currently: **(.45) 25 brute * 7 rounds = 175 brute** total per magazine. This is so low that if you miss even a few shots, you might not even crit your target.
- Proposed: **(9mm) 20 brute * 10 rounds = 200 brute**. This allows a slightly bigger margin of error without being overpowered.
- _And_ now we can have _super illegal traitor magazines_ that would work with the same exact gun, but go up to a whopping 17 rounds! This puts it on par just below the Mateba, which would be a very interesting but still _balanced_ alternative to the Mateba. More rounds in exchange for less impact per bullet.
- Maybe also put preban magazines in that are rare, only found sold by traders, etc. Just for funsies.

I'll obtain sprites for this but what do you lot think of this?

I'm going to be doing this for Vorestation either way. A 9mm sidearm with 10 rounds for Security is much more reasonable than the .45 is for them. The .45 should still be an option for you fudds who want STOPPIN POWAH but the added variety makes things more fun for the rest of us.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Belsima** [comment]
https://github.com/PolarisSS13/Polaris/issues/4369

>Please don't open bug reports for issues that are not bugs

The appropriate forum can be found [here.](https://forum.ss13polaris.com/viewforum.php?f=14)

**Comment by SpadesNeil** [comment]
Oh, my bad.

**Comment by SpadesNeil** [comment]
Aaaaaaand forum won't let me sign up because the confirmation email isn't sending. RIP me. I'll just make a PR for it later and go from there since I'm going to be coding this for Vorestation _anyway_.

**Comment by Belsima** [comment]
...that came off a bit too passive aggressive. Sorry! But I like the idea of this, personally.

**Comment by SpadesNeil** [comment]
Das is good.
