### ISSUE TITLE
Setting vote_no_dead makes people unable to vote for gamemode.

### ISSUE THREAD

**Issue by Cameron653** [PolarisSS13/Polaris#4517]
#### Brief description of the issue
Setrting vote_no_dead to 1 in the config makes people unable to vote for the gamemode at round start.
#### What you expected to happen
People can vote, just no voting while dead mid round.
#### What actually happened
Nobody but admins can vote at round start 
#### Steps to reproduce
Try to vote on a server w/ it enabled and not be an admin
cri
#### Additional info:
 - **Server Revision**: Current polaris code. Branch.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc):
Modifiy this line to check if round has already started. If not, allow ghosts to vote:
https://github.com/PolarisSS13/Polaris/blob/5d81148ab8a1657ce82fc2466aad6aa2a65f4b5e/code/controllers/voting.dm#L180

**Comment by Atermonera** [comment]
From say_dead_direct(), the proc that does dsay, `if(M.client && ((!istype(M, /mob/new_player) && M.stat == DEAD)` (Other stuff in that if, that's what's relevant)
`/mob/new_player`s are therefore considered dead, so that check will need a similar exception for `/mob/new_player`
