### ISSUE TITLE
Horse head masks protect against acid, and thus can't be taken off by any normal means.

### ISSUE THREAD

**Issue by SledgeLP** [PolarisSS13/Polaris#452]
What it says on the tin, wizard round had a bunch of people with horse heads, doctors couldn't remove any of them, and when splashed with acid, gave the following message.

"Your the horse head mask protects you from the acid."

**Comment by PsiOmegaDelta** [comment]
I am fairly certain that is the intention.

**Comment by FenodyreeAv** [comment]
As far as I'm aware, it protects against sulfuric acid.
Enough polytrinic should take one off.

**Comment by Datraen** [comment]
Horse-head spell has been removed from the choices of the wizard.
