### ISSUE TITLE
Crew Manifest Doesn't Show Silicons

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#4536]
#### Brief description of the issue
This is a **feature request**. The cyborg and AI crew manifests allow them to see silicon jobs which include the aforementioned AI and cyborgs. The standard crew manifest that is available on PDAs does not show these silicons, leaving the crew unsure if any synthetics are available
#### What you expected to happen
I would like for the standard crew manifest to show cyborgs and the AI as well
#### Additional info:
 - **Server Revision**: master - 2018-01-14 cb22407e7cd99809f5eb79a55e9929c5d03c3a84

**Comment by Anewbe** [comment]
This is a known issue, but it has been deemed Low Priority, because PDA code is complicated and the end-result isn't hugely important. If someone wants to look into it, though, they're free to do so.

**Comment by elgeonmb** [comment]
https://github.com/PolarisSS13/Polaris/pull/4540
