### ISSUE TITLE
TTV Bombs inconsistent with Baycode

### ISSUE THREAD

**Issue by zekesulastin** [PolarisSS13/Polaris#457]
Not sure if this is the intent or not, but a 250-300 deg C ~1200 kPa phoron, 20 deg C 1013 oxygen gives a 0,1,something explosion on Polaris and a 3,7,14 on current Bay master.

**Comment by Neerti** [comment]
Preemptive request: Can you test Bay-Dev with the same bomb recipe?

**Comment by zekesulastin** [comment]
ADMIN LOG: Explosion with size (3, 7, 14) in area Toxins Mixing Room (184,107,1) (JMP)

((Also, interestingly, the TTV+tank assembly survived the explosion but no body parts did.))
