### ISSUE TITLE
Seconds of Radiation Storm exposure causing hundreds of Radiation

### ISSUE THREAD

**Issue by Bromuzl** [PolarisSS13/Polaris#458]
Three patients, two I treated one I saw while ghosted.

Each report only being outside of maintenance for anywhere from seconds to a few moments.
200+ radiation when they arrive in medbay after, Arithrazine and Hyornaline taking off only about 3-20 radiation per minute, leading us to continue to have to give them treatment for anywhere from 30 minutes to an hour while treating genetic damage, treating Arithrazine side-effects, and Ryetalyn for occasional mutation.

**Comment by RenScorch** [comment]
this clearly needs to be a feature.....
