### ISSUE TITLE
"obj/effect/effect/sparks was unable to be GC'd and was deleted"

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#460]
http://puu.sh/lLOFE/68028ac859.png

Investigation needs to be done as this /may/ be the cause of all the lag.

**Comment by EmperorJon** [comment]
Not the cause of all the lag but needs looking at.

**Comment by PsiOmegaDelta** [comment]
https://github.com/Baystation12/Baystation12/pull/11620

**Comment by EmperorJon** [comment]
Thanky Psi.
