### ISSUE TITLE
Real mouse on my stuffed mouse

### ISSUE THREAD

**Issue by MisterLayne** [PolarisSS13/Polaris#4612]
#### Brief description of the issue 
When I spawn with my mouse plushie, not only is my mouse plushie a dead mouse plushie, but an actual mouse spawns right on top of me.

#### What you expected to happen
To have a nice cuddly plushie that doesn't look dead

#### What actually happened
My plushie looks dead and I get a real mouse spawned with me

#### Steps to reproduce
1. Add mouse plushie to your loadout.
2. Spawn in any way- shuttle, gateway, elevator.
3. Cry about your dead plushie.
4. Cry because a mouse is on top of you.

#### Additional info:
 - **Server Revision**: Will add when I get home.

**Comment by Anewbe** [comment]
Is the character a promethean?

**Comment by MisterLayne** [comment]
@Anewbe Yes.

**Comment by Anewbe** [comment]
That's why the real mouse spawns, at least.

**Comment by MisterLayne** [comment]
Well, I wouldn't call dead mouse sprite a real problem, then. My bad.
