### ISSUE TITLE
AIs can see above-darkness overlays off-camera

### ISSUE THREAD

**Issue by PrismaticGynoid** [PolarisSS13/Polaris#4633]
#### Brief description of the issue
The AI can see parts of sprites which appear over the darkness layer, such as health bars and light switches, even when these are off-camera. The layer of static which is supposed to hide this appears under the darkness, rather than on top of it.
#### What you expected to happen
Static
Overlay
Darkness
#### What actually happened
Overlay
Darkness
Static
#### Steps to reproduce
Be AI. Look at places off-camera with light switches or giant spiders, see their glowing bits. Choose one of the sensor augmentations, watch someone go into maintenance, see the HUD stay over them.
#### Additional info:
 - **Server Revision**: master - 2018-01-22
2692c924487955f91b8f485c1ee9e950fdc9dbc1 
 - **Anything else you may wish to add**: 
![overdark1](https://user-images.githubusercontent.com/16697591/35370884-8700d658-0145-11e8-966d-040ebeeb6d8f.png)
![overdark2](https://user-images.githubusercontent.com/16697591/35370888-8d0fdb16-0145-11e8-856f-6cb56f59ebcd.png)

**Comment by Arokha** [comment]
Darkness static overlay should be moved up, plane-wise. Probably to somewhere around plane 90 as the planes are currently arranged. Below the UI, above everything else.
