### ISSUE TITLE
Butchered spiders briefly appear as a monkey

### ISSUE THREAD

**Issue by elgeonmb** [PolarisSS13/Polaris#4642]
#### Brief description of the issue
Title
#### What you expected to happen
Not title
#### What actually happened
title
#### Steps to reproduce
Butcher a spider
It turns into a monkey then explodes into meat and gibs
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Nalarac** [comment]
I believe this was because the monkey is part of the gib animation? I'd need to fact check it.

**Comment by Anewbe** [comment]
Correct

**Comment by Atermonera** [comment]
Duplicate of #2449
