### ISSUE TITLE
Lockers can double as emergency parachutes.

### ISSUE THREAD

**Issue by zaredman** [PolarisSS13/Polaris#4662]
Alt title: "Ghetto Drop-pods."

#### Brief description of the issue
If you are in a locker that is pushed out the back of the shuttle while it is in transit, you land on a planet without any noticeable damage.

#### What you expected to happen
Itty-bitty monkey chunks due to high-speed impact with the planet's surface

#### What actually happened
Not that.

#### Steps to reproduce
1) Get locker.
2) Close self in locker.
3) Have someone push locker out back of ship that is in transit.
4) Fall.
5) Land.

#### Additional info:
 - Server revision: master - 2018-01-26
4b6e64111e6521b3d8e9feb3bbac855aac4cc56f

**Comment by Atermonera** [comment]
If a locker falls, apply falling to anything inside said locker. Some putting-of-contents back in said locker maybe be desirable/necessary
