### ISSUE TITLE
Being hit by a shuttle launches you into orbit

### ISSUE THREAD

**Issue by Derpoo** [PolarisSS13/Polaris#4670]
#### Brief description of the issue
Being hit by a shuttle teleports you into space.
#### What you expected to happen
I expected to be gibbed.
#### What actually happened
I teleported into space, taking no damage and suffocating slowly. I only tested the planetside landing pads for this.
#### Steps to reproduce
1. Stand on pad
2. Go make tea
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
4b6e64111e6521b3d8e9feb3bbac855aac4cc56f

**Comment by MarinaGryphon** [comment]
@Atermonera You can close this, it should be fixed with the duplicate.

**Comment by Atermonera** [comment]
I closed the other one because it's a duplicate of this. This will be closed when the appropriate PR is closed

**Comment by Atermonera** [comment]
(Put `fixes #[issue number]` in the pr somewhere and it'll do it automatically)
