### ISSUE TITLE
Organs cannot be eaten

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#4686]
#### Brief description of the issue
You can't eat organs anymore.

#### What you expected to happen
Feed a human heart to an innocent baby slimegirl.

#### What actually happened
Them holding a beating heart awkwardly.

#### Steps to reproduce
Remove heart. Attempt to eat. Fail.

#### Additional info:
Server revision: master - 2018-01-29
6c1ab66d446b3dfca29053b107bb9f4a964c63da

**Comment by Anewbe** [comment]
Help intent > aim at mouth > Click self or click item?

**Comment by FenodyreeAv** [comment]
They couldn't be forcefed on any intent.
I tried on a Taj a Prommy and a Human.
No combination of intents or aims.

**Comment by Cameron653** [comment]
https://github.com/PolarisSS13/Polaris/blob/0ce8d465f221b2ad1a9b684a6b22a028b99920c1/code/modules/organs/organ.dm#L382-L387

Relevent code section

**Comment by Wickedtemp** [comment]
https://gyazo.com/5da3d10c4c87c1113ae8aff7b5016659
ate organ. forcefed organ to the organ donor.

**Comment by Anewbe** [comment]
Right, as was pointed out, you can't forcefeed the organ before someone takes a bite out of it first. I believe that's a preventative measure so you don't accidentally feed someone their own organs when trying to reattach it, or something similar.
