### ISSUE TITLE
Ghosts can't see whispers.

### ISSUE THREAD

**Issue by mistyLuminescence** [PolarisSS13/Polaris#4692]
#### Brief description of the issue
Ghosts can't see whispers.
#### What you expected to happen
To be able to see whispers.
#### What actually happened
Couldn't see whispers.
#### Steps to reproduce
Be a ghost. Try and drop some eaves around a whisperer. Don't be droppin' no eaves.

#### Additional info:
 - **Server Revision**: Current.

couldn't find this listed as an issue yet so

**Comment by Cyantime** [comment]
This is when ghost radio is enabled. I assume it's because headset use involves whispering, and someone along the line wanted to cut down on chatspam?

**Comment by Anewbe** [comment]
Yeah, I believe that's the case.
