### ISSUE TITLE
ERT shuttle dock does not work.

### ISSUE THREAD

**Issue by zaredman** [PolarisSS13/Polaris#474]
See title. Door don't open.

**Comment by Neerti** [comment]
ERT got called earlier tonight and had no problems with the shuttle.  You sure the dock wasn't just depowered or some nefarious AI was fucking with you?

**Comment by Woodratt** [comment]
Believe I sorted it with this fix https://github.com/PolarisSS13/Polaris/pull/465

**Comment by zaredman** [comment]
Going to close this out then. If it cocks up, will reopen.
