### ISSUE TITLE
Space is solid.

### ISSUE THREAD

**Issue by Andromeda-K22** [PolarisSS13/Polaris#4744]
#### Brief description of the issue
You fall off and hit space!

#### What you expected to happen
To not hit the literal absence of matter.
#### What actually happened
I hit space. And went into crit.
#### Steps to reproduce
Blast a hole in the station. Walk over hole.
Hit space.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by FenodyreeAv** [comment]
You can also attempt to climb up the space.
Which results in you immediately falling down again.
It also doesn't check for being incapacitated, so hardcrit people can climb up to end their lives.

**Comment by Atermonera** [comment]
#4774
