### ISSUE TITLE
Ethylredoxrazine is broken.

### ISSUE THREAD

**Issue by Wickedtemp** [PolarisSS13/Polaris#4752]
#### Brief description of the issue
Ethyl's been broken since day one of Polaris.
#### What you expected to happen
Well, I expect it to synth with ethanol to create water, and to neutralize alcohol in the bloodstream and stomach when administered. https://gyazo.com/b81abf227ccc96c091b264778df2a98a
#### What actually happened
It still doesn't remove alcohol from stomach or bloodstream. It also doesn't combine with ethanol to make water.
#### Steps to reproduce
Someone drinks a keg.
"We'll use ethyl!"
Doesn't work. Still have all the booze ever.
"We'll use carbon pills!"
Do so. Realize this is going to take quite a while because carbon removes 1u per tick, which is fine for pretty much everything except things people are likely to binge on, such as coffee and alcohol.
Babysit the drunk patient that you aren't legally allowed to let refuse treatment.
#### Additional info:
 - Been a thing since Polaris was live, pretty sure
 Doesn't synth to make water: https://gyazo.com/35393ea62397daa0e3f00d0c011f14b5
Code that... makes it look like it's supposed to remove the alcohol, but for some reason just isn't: https://gyazo.com/b609bced2de7bc055d49d6d68887d2f9
Not removing alcohol in bloodstream: https://gyazo.com/780b33a5f6a30302de8decac592f5410
Not removing alcohol in stomach: https://gyazo.com/ac78fd61727b64cdfc453759387f2a65

Alternatively, porting Bay's stomach pumps may be better long-term, since that'd cover everything from mushrooms to coffee to alcohol, and simply edit Ethyl's description to fit what it does currently.

**Comment by Atermonera** [comment]
It needs to call `R.remove_self` instead of trying to modify cars directly
