### ISSUE TITLE
Health Meter Tattoo Issue

### ISSUE THREAD

**Issue by MerekBlack** [PolarisSS13/Polaris#4764]
#### Brief description of the issue

Tattoos marking over the health bar when having full body ones.

#### What you expected to happen

To see all my health bar clearly.

#### What actually happened

Not that.

#### Steps to reproduce

Full body markings in tattoo and look at health thing.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
That's not actually a bug, it's part of the health doll system.

**Comment by Belsima** [comment]
I love the look of it, personally.
