### ISSUE TITLE
People with robolimbs/mech hearts not squishy to EMPs

### ISSUE THREAD

**Issue by zaredman** [PolarisSS13/Polaris#477]
See title. Maja Dahl took like two EMPs and had not much happen to her.

**Comment by Zuhayr** [comment]
Can you check variables and see if her limbs are busted beyond repair? Under the new system, IIRC robolimbs do not contribute to bodily death or pain.

**Comment by Dibasic** [comment]
That was an admin just fucking with me p. sure

**Comment by zaredman** [comment]
@Dibasic - Presuming you're Maja/PersonaE. There was no admin fuckery keeping you alive.

Going to throw a bunch of EMPs at myself on a different z/private server and see what happens.

**Comment by zaredman** [comment]
So just downloaded the latest Polaris from git. Set a character with complete Bishop mech limbs, mech eyes, mech heart. Popped an EMP point-blank. Zero damage.

Grabbed a second. Held it in her hand. Pulled the pin. Zero damage.

Switched to unbranded prosthetics. No damage.

So there is confirmed zero damage to robolimbs via EMP @Zuhayr

**Comment by zaredman** [comment]
This bug seems to exist for mechanical hearts/eyes on Bay-dev. As for limbs? It damages limbs.

**Comment by zaredman** [comment]
Partial/complete fix on Baystation12/Baystation12#11637
