### ISSUE TITLE
Drones cannot pickup Power Cable or place Floor Tiles

### ISSUE THREAD

**Issue by Bromuzl** [PolarisSS13/Polaris#478]
Joined as Drone, was unable to pickup cable coils in space. I realized that this has been around for a while and had assumed it was a faeture, but this time I noticed I could pick up every other color/source of cable I could find/make including cutting cables up, disassembling the SMES, and spawned cable in Misc research.

Later the same round I noticed someone had picked up a floor tile while crowbarring a door and discovered that they are also unable to deploy floor tiles on the station. I tested a hallway and AI Upload during the round.

Repeat: Join as drone, place wires, change-colour to yellow, try to pick up the yellow cable coils outside solars. Cry.

Crowbar up some tiles on station. Select Floor Tiles and try to replace them. Cry as you are now also unable to pickup the previous tiles.

**Comment by Hubblenaut** [comment]
The power cable bug is independent of the mob merging it. Happens with all coils that are a subtype of /cable_coil.
