### ISSUE TITLE
Free Sif Radio pOI has the wrong ammo type as loot

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#4780]
#### Brief description of the issue
In the bottom room of the POI there is a rifle that fires 7.62, which has a spare ammo clip of 5.45 on top of it.

#### What you expected to happen
To be able to load the spare ammo into the gun.

#### What actually happened
Fight a spider and realize my bullets don't fit. Die.

#### Steps to reproduce
Go to Sif Free Radio outpost, try to load gun, fail.

**Comment by mistyLuminescence** [comment]
aaaaaa sorry
