### ISSUE TITLE
Holographic Tie Stuck On Selection

### ISSUE THREAD

**Issue by MerekBlack** [PolarisSS13/Polaris#4814]
#### Brief description of the issue

Selected a cloak model from tie, put on cloak, then removed it as accessory, changed it to a different cloak, the ground sprite changed, but the main sprite remained at first chosen cloak regardless of changes.

#### What you expected to happen

Different Cloak.

#### What actually happened

Same Cloak.

#### Steps to reproduce

Select holoequipment tie.
Change to cloak (research)
attach to suit
unattach from suit
change tie model
put on suit again
remains as original selection

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Heroman3003** [comment]
This is fixed as of https://github.com/PolarisSS13/Polaris/commit/7cc993f28db9f9aa3650c396147f97e9680f8721#diff-100f787f4b39acf7b42b433bbc7c388e
