### ISSUE TITLE
Cannot build grilles in space.

### ISSUE THREAD

**Issue by Kyoshiku-git** [PolarisSS13/Polaris#4824]
**Brief description of the issue**
Cannot build grilles in space, to replace missing/busted grilles around station.

**What you expected to happen**
To be able to construct grilles, either over lattices, or adjacent to other grilles.

**What actually happened**
_'The grille must be constructed on the floor!'_ regardless of in space, next to another grille, on lattice, or even on top of constructed catwalk.

**Steps to reproduce**
Try to build a grille to replace broken grille in space around station.

**Additional info:**
 - **Server Revision**:
Server revision: master - 2018-02-13
76fa2f82bf05075dc151a6332774f916b3a8967f 

 - **Anything else you may wish to add**
N/A

**Comment by Atermonera** [comment]
Probably to do with the addition of catwalks requiring a menu to select what to build from teh rods
