### ISSUE TITLE
Cargo shuttle explodes when hit by space dust

### ISSUE THREAD

**Issue by NortonDK** [PolarisSS13/Polaris#486]
I was QM inside the shuttle when i presume it was hit with spacedust(since the event just began as it happened) Then my body was gibbed and most of the shuttle was gone.

https://gyazo.com/13f3668e8ca02ac467baae1f2d0e4bf3 Image of the incident.

**Comment by PsiOmegaDelta** [comment]
The vessel was lost to the warp, probably the Gellar Field that failed. No one quite knows why but this has been happening randomly every once in a blue moon on Bay code for as long as I can remember.

**Comment by zaredman** [comment]
The dude was in the shuttle, he says. So it already made it over intact @PsiOmegaDelta

**Comment by Zuhayr** [comment]
Shuttle wouldn't have moved if he was in it.

**Comment by Magneld** [comment]
He was in the shuttle, unloading it and something hit it and the walls and floor went away god knows where.
What remained of him, his crates, the wall lights and the thrusters stayed behind.
