### ISSUE TITLE
Grey baby slimes have weird notification

### ISSUE THREAD

**Issue by MerekBlack** [PolarisSS13/Polaris#4872]
#### Brief description of the issue

When slime assaults you.

The grey baby slime (672) has /list Merek Black!

This happened a few times. Don't know what this is.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Nalarac** [comment]
This is probably linked to #4821
