### ISSUE TITLE
Clicking anything other than the floor as a ghost does not examine it

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#488]
Instead you have to right click examine or shift click.

**Comment by GinjaNinja32** [comment]
did you have inquisitiveness off?

**Comment by Neerti** [comment]
Probably caused by the recent ```attack_ghost()``` addition to objects for nanoUI.

**Comment by PsiOmegaDelta** [comment]
Should be sufficient to add a call to ..() [here](https://github.com/PolarisSS13/Polaris/blob/master/code/game/objects/objs.dm#L118).

**Comment by Yoshax** [comment]
No, Inquisitiveness was turned on.

Anything that isn't the floor or a NanoUI thing doesn't get examined.
