### ISSUE TITLE
Station SMES settings at roundstart.

### ISSUE THREAD

**Issue by martin509** [PolarisSS13/Polaris#490]
The main station SMES (i.e. the other one the engine outputs to) currently has input/output settings reminiscent of Bay, at 500kw in/500kw out. This is not enough to power the station, and the first power alarm (Virology as always) appears within moments of roundstart. I'd suggest 700kw/700kw would be enough, along with maybe an increase to the amount of power stored in the SMES at roundstart to give engineering more time to set up the engine.

**Comment by NortonDK** [comment]
Atmos SMES could also use an adjustment

**Comment by Hubblenaut** [comment]
500.000 kW are enough to power the station, which needs around 460.000 kW including atmospherics.
We can up the maximum charge from 20 MJ to 30 MJ by going maximum capacity with current coil limit.

That would also change max I/O to 1.5 MW, a value the TEGs wouldn't achieve on standard operating unless we adjust the constants a bit.

**Comment by GinjaNinja32** [comment]
SMESes don't start fully charged though hubble, so a capacity increase isn't needed to increase initial charge.

**Comment by martin509** [comment]
I say this from experience as a borg, the first power alarm (coming from virology) hits pretty much immediately after roundstart, with more arriving later on. I'm not sure where you're getting that 460kW figure from, because from my experience power draw seems to be around 525 kW without anything charging (and with charging can exceed 800kW, but that's what RCON is for), and at least this way if power is set up by an inexperienced engineer who doesn't fiddle with SMES settings, the station actually will be getting enough power.

**Comment by Woodratt** [comment]
https://github.com/PolarisSS13/Polaris/pull/496

**Comment by Hubblenaut** [comment]
This can be closed
