### ISSUE TITLE
Simple Mobs Are Attacked Twice Per Hit

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#4900]
#### Brief description of the issue
When fighting (at least simple mobs), cyborgs hit the target twice for every attack
#### What you expected to happen
To attack once per hit
#### What actually happened
![](https://user-images.githubusercontent.com/8042031/36456572-25943500-166b-11e8-9f0d-0afbf41d8a4d.png)

#### Steps to reproduce
1.) Be a cyborg
2.) attack a simple mob
#### Additional info:
 - **Server Revision**: master - 2018-02-19 d498beffdb24c5df981c5f896ea1fe608f64c96b 
 - **Anything else you may wish to add** This issue doesn't extend to hitting objects like trees.

**Comment by Anewbe** [comment]
So this seems to be something that happens with all mobs towards simple mobs. Will try to squash by the end of the night.

**Comment by Anewbe** [comment]
#4904 corrects this.
