### ISSUE TITLE
Floors tiles can't be placed unless the target flooring already exists on the map somewhere

### ISSUE THREAD

**Issue by Nerezza** [PolarisSS13/Polaris#4947]
First, I'm 100% sure this is why blue (now teal) carpet doesn't work, however this bug extends to ALL floor types. Second, I recall symptoms of this on Baystation from like 3 or 4 years ago so this has likely looooong been an issue.

Basically, flooring types are defined in code/game/turfs/flooring/flooring.dm but the flooring_types list used in tile placement (in code/game/turfs/simulated/floor_attackby.dm) only populates with floors that exist in-round already.

This means that a hackish solution to floor tiles not being placeable is to toggle build mode and manually place one of the target floor type somewhere (ie, put just one teal carpet square in central and teal carpet begins working everywhere in our current build) or mapping in a room full of floor tiles we want constructible.

The real solution would be for the flooring_types list to populate with all of /decl/flooring at server start, but I have no idea how to do that myself

**Comment by MarinaGryphon** [comment]
> The real solution would be for the flooring_types list to populate with all of /decl/flooring at server start, but I have no idea how to do that myself
I believe we already do something like this with robot parts.
