### ISSUE TITLE
pAI crew manifest is nonfunctional

### ISSUE THREAD

**Issue by PrismaticGynoid** [PolarisSS13/Polaris#4951]
#### Brief description of the issue
When a pAI tries to use their crew manifest, it does not show the crew. Instead, an error message pops up.
#### What you expected to happen
A list of who is on the crew to show up.
#### What actually happened
![manifesterror](https://user-images.githubusercontent.com/16697591/36636708-ad04ff34-1980-11e8-9680-735670acf270.png)
#### Steps to reproduce
Become pAI, download crew manifest, try to use it.
#### Additional info:
 - **Server Revision**: master - 2018-02-24
74a4e993ee624f33ab537ab425b0476578e5fd4a 
 - **Anything else you may wish to add**: Probably has something to do with #4540

**Comment by Atermonera** [comment]
Angry grumbling about the ui not getting the right info
