### ISSUE TITLE
Edit appearance doesn't update icon for gender/sex

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#498]
It seems that if you swap to female from the default male your sprite doesn't update, and Regenerate Icons seems to do nothing.

This occurred and was noticed with ERT and a Ninja over the past few days.

**Comment by zaredman** [comment]
Bug does not exist on Bay-dev. A Polaris Exclusive.

**Comment by mistyLuminescence** [comment]
Reproduceable as of 21/5/2019.

**Comment by Atermonera** [comment]
Probably related to getFlatIcon() (exact spelling uncertain)
