### ISSUE TITLE
Rolling Paper packs dissapearing

### ISSUE THREAD

**Issue by A-Vulture** [PolarisSS13/Polaris#4992]
#### Brief description of the issue
Taking a roll of paper out to hella blaze it up, causes it to go invisible.
#### What you expected to happen
The icon to stay the same, or change like how cigarette packets do.
#### What actually happened
It became invisible. Unable to interact with.
#### Steps to reproduce
-Dry something
-Pull out a rolling paper
-Get to toke up but can't make more as the pack's gone into stealth mode
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
master - 2018-03-01
09dd73ae64200dae708fa3e6486b19124f74f3d6 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Nerezza** [comment]
Testing testing testing testing testing! >:O
