### ISSUE TITLE
Snow overlay on tiles around the main outpost block floor tile interactions

### ISSUE THREAD

**Issue by Nerezza** [PolarisSS13/Polaris#4993]
![snowbug](https://user-images.githubusercontent.com/1986009/36877526-426ddf02-1d80-11e8-8304-582fe807ab46.png)

The snow overlay used to hide the icy exterior plating around the main outpost also prevents most interactions with the turf underneath, such as laying wire, without admin intervention.

The turf-examine doesn't allow for attacking turfs as a valid workaround unfortunately.

**Comment by BillyBangles** [comment]
Perhaps we could give shovels the capability to clear overlay snow off of tiles? Let's get out there and shovel our space driveways.

**Comment by Neerti** [comment]
Setting ``mouse_opacity = 0`` should fix the clicking problem.
