### ISSUE TITLE
Surgery sometimes borks.

### ISSUE THREAD

**Issue by PotatoOS** [PolarisSS13/Polaris#500]
Once i was doing the internal organ surgery with a patient that had a fucked up liver,i followed the procedure until step 7,called Use the retractor to pull their ribcage/skull open.
When i try to use the advanced trauma kit,it just completly ignores the patient's situation and if i try to use the retractor again it just puts the ribcage back.
It also may happen to other surgeries,but that's unlikely.

**Comment by Hubblenaut** [comment]
Not having checked the code for some time. But isn't the liver positioned in the groin area now?

**Comment by Zuhayr** [comment]
Does not appear to be reproducible.
