### ISSUE TITLE
Ninja can teleport to turfs visible on camera console

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#501]
Not tested with laptops. Massive oversight that allows a ninja to use their "within vision" turf jumping ability to jump even between Z-levels if necessary. Discovered when a ninja teleported from security to the mining outpost.

**Comment by Zuhayr** [comment]
Just chuck a distance check into the rig click procs.

**Comment by zaredman** [comment]
Marking as Easy Fix as the fix exists via Baystation12/Baystation12/#1646

Just needs someone who is a ton more knowledgeable than I to yoink it over here.
