### ISSUE TITLE
Missing(?) emergency shutters

### ISSUE THREAD

**Issue by sabiram** [PolarisSS13/Polaris#502]
Captain's Quarters (from office to bedroom)
Private Restroom (from bedroom to lavatory)
Bridge maintenance (topmost section of bridge, T junction)

Emergency shutters are present in window to space adjacent to the array of computers in the main room (south wall), but not the on the window facing space on the western wall of the conference room. 

No shutters are present in the window wall on the western face of the head of personnel's office either, but this does not face open space.

---

Vault

Chapel entrances, both of them
Chaplain's office

Security restroom

Mech bay hangar door thing

Every door in the engine core (?)
Window looking into engine core from monitoring room

Engineering locker room from maintenance

**Comment by Woodratt** [comment]
Sorted https://github.com/PolarisSS13/Polaris/pull/511
