### ISSUE TITLE
Alien Wood Tiles go invisible instead of updating stack icon

### ISSUE THREAD

**Issue by Schnayy** [PolarisSS13/Polaris#5042]
#### Brief description of the issue
For I believe 20-40 quantity stacks, alien wood disappears and loses it's sprite rather than updating to what should be an icon of two tiles stacked.

#### What you expected to happen
The equivalent of this.
![image](https://user-images.githubusercontent.com/26665154/37229565-fe796c64-23a9-11e8-9bd1-92e2a04f4f51.png)

#### What actually happened
Invisible and a menace.

#### Steps to reproduce
Stack alien wood tiles.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Nerezza** [comment]
The 'tile-sifwood_2' icon is incorrectly named 'tile-sifwood'

One moment
