### ISSUE TITLE
Item icons sometimes disappear when equipped/in inventory

### ISSUE THREAD

**Issue by Neerti** [PolarisSS13/Polaris#5094]
#### Brief description of the issue
Certain items have their icon disappear when being placed in inventory (Told it happens w/ suit storage and backpacks)
#### What you expected to happen
For item icons to remain.
#### What actually happened
The item icons were blank, appearing as if the item disappeared, however they remained, just without an icon. Taking the item out and re-equipping it sometimes fixes it, I'm told.
#### Steps to reproduce
<s>Unfortunately I do not yet know the precise conditions to reproduce this.</s>
Found out how to reliably reproduce it now.

Join the round.
Get a suit that can hold something, like armor.
Get an item you know will fit in suit storage.
Make sure your inventory toggle (the button on the bottom-left of the screen that toggles slot visiblity) is turned OFF.
Equip the item into suit storage.
Observe how the icon is not shown in the slot, however it does show if inventory toggle is ON.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
master - 2018-03-21
ebeb513b31b73e594e1c5e5ef1e136d6bc01ce16 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
So far I've observed this occur three times, two of which being secondhand (people ahelping). The two occurrences I was told about involved weapons or handcuffs on suit storage. The one instance I personally saw it occur was a gun and ammo box inside a dufflebag. I was a ghost.

**Comment by MisterLayne** [comment]
Happened to me, not really sure why. If I put on a new suit, the icon stays there for a while, but then eventually dissapears. I've lost many PDAs this way..

**Comment by Neerti** [comment]
Updated with new information.
Here's how it works in .gif form.
https://puu.sh/zPE41/6430da5d41.gif
