### ISSUE TITLE
Body temperate falls too slowly

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#5096]
#### Brief description of the issue
When set on fire, the Mob's body temperature is immediately set very high.
It takes over a minute for this temperature to return to normal.
This means you can be on fire for a couple of seconds, get put out immediately, and still die.

#### What you expected to happen
Body-temp to fall to normal levels when fire is extinguished.

#### What actually happened
The moment your body-temp reaches damaging levels, you are dead.

#### Steps to reproduce
Set self on fire. Extinguish self. Die anyway.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
I believe this will be addressed by Anewbe's cold rewrite, which is in the works. Could be wrong, though.
