### ISSUE TITLE
Character Setup Is Nude

### ISSUE THREAD

**Issue by Neerti** [PolarisSS13/Polaris#5097]
#### Brief description of the issue
My character lacks hair and clothes on the setup screen.
#### What you expected to happen
For their job/loadout items to be visible, and for their hair to be visible.
#### What actually happened
![Example](https://puu.sh/zOfSQ/2d11e4c6c9.png)
#### Steps to reproduce
Open character setup.
Notice lack of modesty.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2018-03-24
c75158b14d76ef37886f7d825c4bf4f2588464fd 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
May or may not be related to a similar issue of ghosts being naked.

**Comment by MisterLayne** [comment]
Probably has to do with the changes in PR #5091 , getFlatIcon is also used to get the character_setup [previews](https://github.com/PolarisSS13/Polaris/blob/9f5641668416c5ce05d5c0199ee030a4706699ba/code/modules/mob/new_player/preferences_setup.dm#L258).
