### ISSUE TITLE
Ghost Sprite Weirdness

### ISSUE THREAD

**Issue by Neerti** [PolarisSS13/Polaris#5106]
#### Brief description of the issue
Ghosts are Naked/Bald when observing from lobby.

#### What you expected to happen
For my ghost to resemble my preview icon.

#### What actually happened
My ghost was bald and unclothed.

#### Steps to reproduce
Run a local server or join the server.
Make sure you have a job selected in character setup, so that your preview icon is clothed.
Hit observe.
Notice you are naked and bald.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2018-03-24
c75158b14d76ef37886f7d825c4bf4f2588464fd 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
I thought it was related to #5097 , but the PR that fixes it does not appear to fix this upon local testing, so it seems to be a separate issue.

**Comment by Atermonera** [comment]
Server is still c75158b, the fix for the other issue was merged since then. This is reportedly a different issue, in that the fix for #5097 did not fix this
