### ISSUE TITLE
Botany seed vendor cannot be hacked

### ISSUE THREAD

**Issue by Magneld** [PolarisSS13/Polaris#5109]
#### Brief description of the issue
It is not possible to screwdriver and hack the botany vendor for tasty mushrooms and weed
#### What you expected to happen
For me to be able to grow weed without using my admin powers.
#### What actually happened
The botany seed vendor is not screwdriver-able
#### Steps to reproduce
Attempt to hack the vendor, so you can get ambrosia seeds and fun mushrooms, anger the spirit of Space Snoop Dog with your inability to do so.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2018-03-24
c75158b14d76ef37886f7d825c4bf4f2588464fd 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
Smoke weed certain days.

**Comment by Nalarac** [comment]
Fixed by #5277
