### ISSUE TITLE
Teshari have no arms on their sprite.

### ISSUE THREAD

**Issue by MarinaGryphon** [PolarisSS13/Polaris#5120]
#### Brief description of the issue
Teshari lack arms on their sprite.
#### What you expected to happen
Teshari would have arms on their sprite.
#### What actually happened
https://gyazo.com/d9c4f6d725c48c1cff1d5497f5bf1a81 Arms are invisible.
#### Steps to reproduce
Look at a Teshari.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Belsima** [comment]
I'm experiencing plenty of arms in my plays as Teshari.

**Comment by Arokha** [comment]
Haven't seen this issue
