### ISSUE TITLE
All NPC mice spawn in nullspace

### ISSUE THREAD

**Issue by ghost** [PolarisSS13/Polaris#5139]
#### Brief description of the issue

All NPC mice spawn in nullspace rather than on the station.

#### What you expected to happen

Squeakers in the maint tunnels.

#### What actually happened

No trace until you ghost and follow only to be brought into nullspace.

#### Steps to reproduce

1. Start server.
2. Observe
3. Follow verb, select a mouse (NPC)
4. Note the lack of anything

#### Additional info:
 - **Server Revision**: 185201c112605acaf67b720de542024e35321265 
 - **Anything else you may wish to add**: Noticed on live, Southern Cross. Haven't tested on Northern Star, will do so later.

**Comment by TheFurryFeline** [comment]
This doesn't seem to happen anymore, from what I've seen.
