### ISSUE TITLE
pAI gets odd UI.

### ISSUE THREAD

**Issue by martin509** [PolarisSS13/Polaris#514]
http://i.imgur.com/VY6ktIp.png 
I joined as a personal AI, and upon becoming one, got a bunch of weird UI, pictured above. Those two slots next to the hands are a back and mask slot according to mouseover text. None of the slots, buttons, etc. do anything, and as far as I can tell this may be from simple mobs like monkeys (who have two hand slots, a back slot, and a mask slot as well).

**Comment by Zuhayr** [comment]
This should be fixed now.

**Comment by Yoshax** [comment]
No reproducerino: https://i.gyazo.com/dd9afdcc1b32e9a3d077659cd8db66b4.png
