### ISSUE TITLE
Moving through pipe adapters or gas pumps in vents causes immediate freezing or CTD.

### ISSUE THREAD

**Issue by ghost** [PolarisSS13/Polaris#5141]
#### Brief description of the issue

If you go through maintenance vents which often lead through one or both of these, you will suffer freezes and/or crashes, as well as the indicator disappearing. I also believe other non-standard pipe objects may cause this, but have not yet tested. It also doesn't happen every time, but especially happens if you move the way the gas pump is pointing rather than the opposite. This also seems to apply to canister ports.

#### What you expected to happen

Not getting a CTD.

#### What actually happened

![image](https://user-images.githubusercontent.com/31827220/38179214-8892d6d2-35ee-11e8-96b7-7dcafed3ec09.png)

#### Steps to reproduce

1. Observe
2. Join as mouse
3. Alt-click a vent
4. Adventure into maint
5. Pass through pipe adapter
6. notice that you're now dead

#### Additional info:
 - **Server Revision**: 185201c112605acaf67b720de542024e35321265

**Comment by Leshana** [comment]
What is your exact client version?
