### ISSUE TITLE
Tooltips work in very dark areas

### ISSUE THREAD

**Issue by ghost** [PolarisSS13/Polaris#5142]
#### Brief description of the issue

Tooltips can easily be used to scan dark areas, thereby rendering any form of trying to hide using the cover of the night entirely useless.

#### What you expected to happen

Perhaps being able to hide by dispelling Lady Light

#### What actually happened

![image](https://user-images.githubusercontent.com/31827220/38179457-8de03442-35f1-11e8-8227-6689c3e7beeb.png)

#### Steps to reproduce

1. Walk into dark area or have another mob do so. Genetics lab is useful for this.
2. Observe first mob with another, or just wildly fling mouse around in advanced search tactic.
3. Notice how swaying the the mouse around all the tiles usually discovers mobs quickly.

#### Additional info:
 - **Server Revision**: 185201c112605acaf67b720de542024e35321265 
 - **Anything else you may wish to add**: May not be a bug, may not even be an oversight, but 'Issues' is a very broad word. I feel this just creates issues regarding stealth gameplay.

**Comment by Arokha** [comment]
Only works through lighting system darkness, not byond darkness.
