### ISSUE TITLE
Search And Rescue occupation title is Yes/No toggle like assistant; not Low/Med/High

### ISSUE THREAD

**Issue by Jennalele** [PolarisSS13/Polaris#5148]
#### Brief description of the issue
Unlike any other profession which has a low/medium/high setting, the SAR job slot in the character profile has a yes/no toggle similar to assistant that disables all other jobs when selected, and also appears to toggle assistant itself on and off rather than the SAR job.

#### What you expected to happen
To have a low/medium/high preference toggle

#### What actually happened
it's yes/no and seems to toggle assistant status

#### Steps to reproduce
Create a new character and try to make them a SAR operator

**Comment by elgeonmb** [comment]
https://github.com/PolarisSS13/Polaris/pull/5088/commits/eabec5fb1ee38492baa8d82d56491264b3cc5643 might be related
