### ISSUE TITLE
Meson-Material Scanner combo don't show ores in darkness

### ISSUE THREAD

**Issue by Dunmeritude** [PolarisSS13/Polaris#5159]
#### Brief description of the issue
Material scanners are, in theory, supposed to show you ores through the rocks. The issue is if you are ALSO using mesons, such as material goggles + meson hardsuit overlay, and the area the ores are in are unlit, IE, in the middle of a rock, the ores don't appear on the scanner until they -are- lit, which only happens when you're on top of them, making the entire point of having the scanners useless.

#### What you expected to happen
To be able to see ores regardless of if they're lit up or not when using meson/material scanner combo

#### What actually happened
I can't see jack until I'm on top of the ore 

#### Steps to reproduce
Acquire material scanners, acquire a meson visor for a RIGsuit. Use both. Go mining. See heck-all until an ore is exposed to light directly.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by TheFurryFeline** [comment]
I've had this sort of issue further downstream, actually, in the inverse scenario..... Using the Meson goggles combined with a mining hardsuit's material scanner visors don't combine like you'd want them to. 

As I recall from trying this downstream, I wear a pair of mesons, put on the mining hardsuit with the material scanners module installed. I then go outside with both sets on and I can see ores in the distance, but I am unable to see where the closest gap in the rocks are until I switch off the hardsuit's visors.

**Comment by TheFurryFeline** [comment]
#5669 pretty much renders this null, doesn't it?

**Comment by Dunmeritude** [comment]
oh look this one actually SHOULD be closed but nobody on this server ever wants to do their jobs and enforce things do they.
