### ISSUE TITLE
Hull shields do not actually shield.

### ISSUE THREAD

**Issue by zekesulastin** [PolarisSS13/Polaris#5181]
#### Brief description of the issue
[HeadDeveloper PM] Anewbe: 5 Renwicks completely stops all but the largest rocks.
 [HeadDeveloper PM] Anewbe: What was it at?
PM to Anewbe: 7 stable, 6.something when I ran to check mid storm
 [HeadDeveloper PM] Anewbe: Also RE: Meteors, looks like they hit and exploded on areas that were above or below the main level.
PM to Anewbe: ... but the shields are also above and below the main level
 [HeadDeveloper PM] Anewbe: Yeah, but the above and below areas aren't the same shape as the mid level, and the shield follows the outline of the station.
PM to Anewbe: Soooo because the shield hugs the deck outline they are useless because multiz

#### What you expected to happen
The hull shields at 7 rw to block a majority of the incoming meteors

#### What actually happened
Thirty-six atmos alarms

#### Steps to reproduce
Put up hull shields, wait for larger meteor event

#### Additional info:
 - **Server Revision**: master - 2018-04-13 fd29a3b841c2440608ed2a785b1fd877f14853e6
 - **Anything else you may wish to add** It might be nice to have a way to bubble the shields around the engine cooling loops.

**Comment by Anewbe** [comment]
'bout half of that is apparently dead wrong, on my end. Looking into this now, no idea if I'll have a solution any time soon so if anyone else wants to take a gander, feel free.
