### ISSUE TITLE
A few chems no longer work when ingested

### ISSUE THREAD

**Issue by Wickedtemp** [PolarisSS13/Polaris#5214]
#### Brief description of the issue
Soporific and chloral won't put someone to sleep anymore when ingested, due to metabolizing super, super slow.
#### What you expected to happen
Take a 30u soporific, 10u chloral pill. Get knocked out.
#### What actually happened
Was stunned by chloral, and yawned a fuck-ton. Nothing else, though.
#### Steps to reproduce
Do above steps.
#### Additional info:
It's possible that this is the case for other reagents - no longer working when ingested.

**Comment by MisterLayne** [comment]
#5011 
Not sure how long Sopo or Chloral haven't worked, but something tells me this PR is the culprit.

**Comment by Wickedtemp** [comment]
Reagents in the stomach are metabolized more slowly. Half the rate. They USED to metabolize at the same speed. But a somewhat recent-ish PR changed that. 

I think that PR's broken some stuff, because some reagents are now metabolizing so freakin' slowly that they're completely ineffective.

**Comment by Jennalele** [comment]
I think this is the same issue that Dylovene has right now: It's seemingly not processing at all, meaning toxins seem to stay with you the entire round.
