### ISSUE TITLE
Atmos Scrubbers suck

### ISSUE THREAD

**Issue by Mushkiller** [PolarisSS13/Polaris#522]
So right now, atmos scrubbers can't deal with phoron well at all. They stop scrubbing when there's about .03% phoron left in a normal 101.3 kpa atmosphere. This is still enough to deal tox damage to people, and also enough to set people on fire if they happen to have a cig. Only way to really deal with this right now is drain and refill, which takes too long.

Other gases probably have this same issue, and if I had to take a guess at what's causing it is probably the fact that atmos devices stop pumping/scrubbing/whatever after a certain point has been reached in how much gas remains.

**Comment by RenScorch** [comment]
The problem with atmos is that when a new gas is added into the math, it becomes very VERY hard to remove it, high power scrubbers(or any scrubber for that matter) start the diminishing returns as the gas gets closer and closer to zero. Fixing this may more or less require some(if not a lot) of atmoscode rewrite.

**Comment by Hubblenaut** [comment]
Add to that, atmosphere alarms do currently show green with a miniscule amount of phoron in the air that is however still enough to poison people.

**Comment by zaredman** [comment]
iirc that's a bay-bug. I remember rounds being a tad FUBAR due to this.

**Comment by EmperorJon** [comment]
"Atmos Scrubbers suck" - Tags as "Intended functionality" ;)

**Comment by Hubblenaut** [comment]
> The problem with atmos is that when a new gas is added into the math, it becomes very VERY hard to remove it, high power scrubbers(or any scrubber for that matter) start the diminishing returns as the gas gets closer and closer to zero. Fixing this may more or less require some(if not a lot) of atmoscode rewrite.

Or setting MINIMUM_MOLES_TO_FILTER to something else than 0.1

Only problems I see is that the air alarms deem 0.2% phoron completely safe, whereas the safe percentage is about 0.005% and lower, as well as that the phoron overlays vanish at 0.7 moles of phoron, a value that is not reached due to the scrubbers shutting down shortly prior to that.

**Comment by RenScorch** [comment]
Give it a shot Hubble, tell us how it goes. If it works, then it should be an easy fix. If you get some kind of crazy Run-time error, well, let us know that as well so that a plan can be created in fixing this problem.

**Comment by Hubblenaut** [comment]
I already tested it, there's all there is to it. I'm working on another ZAS-related bug right now though, will be in the same PR if I make it by tomorrow.
