### ISSUE TITLE
More layering issues

### ISSUE THREAD

**Issue by Atermonera** [PolarisSS13/Polaris#5223]
#### Brief description of the issue
Atmos canisters, and possibly other equipment, are over regular items

#### What you expected to happen
Not having to rely on alt-click to fetch my tank from the canister after filling it

#### What actually happened
![can v item](https://puu.sh/AbJsC/2227184fef.png)
#### Additional info:
 - **Server Revision**: 2018-04-23 - d102dd5da6f793d449c3d9af41f127f33f389bd3 

EDIT: shower curtains have been resolved

**Comment by PrismaticGynoid** [comment]
Displaced girders go underneath catwalks, too.

**Comment by Neerti** [comment]
All of these appear to be resolved.
