### ISSUE TITLE
Airlock Button Mapping Issue near Dock 2

### ISSUE THREAD

**Issue by ta3370** [PolarisSS13/Polaris#5245]
#### Brief description of the issue
Unable to activate the airlock next to me in the screenshot with internal or external access buttons.
However, the airlock controller does work.
#### What you expected to happen
I expected to walk up, press internal access, replace the light, use the controller to re-close the door, and float off to the rest of the busted lights in the civilian deck.
#### What actually happened
Walked up, pressed the internal access, did not work, tried again x3, used airlock controller to access, replaced light, began reporting at the request of DevMin Mechoid after adminhelping the issue, tested external access button which also did not work, continued reporting.
#### Steps to reproduce
As Lawed Engineering Drone, attempt to use the airlock internal access button (or external) of the airlock in the screenshot.
#### Additional info:
![bug report](https://user-images.githubusercontent.com/38930352/39557448-86b584ca-4e3c-11e8-8c97-57e1b0463f3f.png)

 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2018-05-02
5e9533e8a9d3ac39ea5ca776806321062b09f65d

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
Escape Airlock at Dock 2, first one from the bottom on the left.

**Comment by ta3370** [comment]
First time using github and it thinks the "Server Revision" hash is in scientific notation, not sure how to fix that.

**Comment by ta3370** [comment]
Addendum: The next airlock above it is also similarly broken.

**Comment by Nalarac** [comment]
Fixed by #6209
