### ISSUE TITLE
Airless plating in first deck construction area opposite Gym

### ISSUE THREAD

**Issue by mabmoro** [PolarisSS13/Polaris#5251]
#### Brief description of the issue
Two Airless Platings in the construction area on deck 1

#### What you expected to happen
Regular plating

#### What actually happened
Air got drained out endlessly

#### Steps to reproduce
Have a blob appear and blow up what I suspect was a fuel tank.

#### Additional info:
Submitted due to request from Elgeonmb, after a blob caused a breach and we couldnt refill. I noticed two spots where there was 'airless plating' instead of normal plating, and when Iris put flooring over the plating, the air stopped draining.

**Comment by Atermonera** [comment]
The affected tiles are mapped as `/turf/simulated/floor/plating`.
A fuel tank vented the area, so when new plating was placed in the now vented area, they were spawned as `/turf/simulated/floor/airless`.
Despite this, they're still simulated and so process ZAS normally.
Tested with a drone by removing the floor tiles placed that seemed to fix the issue, did not have an effect on the local atmos.

Most likely just ZAS being sluggish, sometimes it goes to sleep for reasons beyond the ken of mortals.
