### ISSUE TITLE
Evidence Bag Boxes Don't Open

### ISSUE THREAD

**Issue by Sabess** [PolarisSS13/Polaris#527]
No clue why this is. Evidence bags work, but the boxes don't. You simply can't open them.

**Comment by zaredman** [comment]
As seen in #456

**Comment by zaredman** [comment]
runtime error: Cannot modify null.screen_loc.
proc name: standard orient objs (/obj/item/weapon/storage/proc/standard_orient_objs)
source file: storage.dm,161
usr: Leila Berkheimer (/mob/living/carbon/human)
src: the evidence bag box (/obj/item/weapon/storage/box/evidence)
call stack:
the evidence bag box (/obj/item/weapon/storage/box/evidence): standard orient objs(0, 5, null)
the evidence bag box (/obj/item/weapon/storage/box/evidence): orient2hud(Leila Berkheimer (/mob/living/carbon/human))
the evidence bag box (/obj/item/weapon/storage/box/evidence): open(Leila Berkheimer (/mob/living/carbon/human))
the evidence bag box (/obj/item/weapon/storage/box/evidence): MouseDrop(Leila Berkheimer (/mob/living/carbon/human), the floor (148,214,1) (/turf/simulated/floor/tiled/white), the floor (148,213,1) (/turf/simulated/floor/tiled/white), "mapwindow.map", "mapwindow.map", "icon-x=18;icon-y=21;left=1;scr...")
runtime error: wrong type of value for list
proc name: show to (/obj/item/weapon/storage/proc/show_to)
source file: storage.dm,95
usr: Leila Berkheimer (/mob/living/carbon/human)
src: the evidence bag box (/obj/item/weapon/storage/box/evidence)
call stack:
the evidence bag box (/obj/item/weapon/storage/box/evidence): show to(Leila Berkheimer (/mob/living/carbon/human))
the evidence bag box (/obj/item/weapon/storage/box/evidence): open(Leila Berkheimer (/mob/living/carbon/human))
the evidence bag box (/obj/item/weapon/storage/box/evidence): MouseDrop(Leila Berkheimer (/mob/living/carbon/human), the floor (148,214,1) (/turf/simulated/floor/tiled/white), the floor (148,213,1) (/turf/simulated/floor/tiled/white), "mapwindow.map", "mapwindow.map", "icon-x=18;icon-y=21;left=1;scr...")

**Comment by Mark9013100** [comment]
Fixed in #546.
