### ISSUE TITLE
Luminol/UV Light do not work when cleaned with soap

### ISSUE THREAD

**Issue by Minijar** [PolarisSS13/Polaris#530]
Spray area with blood, spray with luminol, clean with soap, use UV lights and notice the lack of CSI blood appearing.

**Comment by zaredman** [comment]
Iirc I know it is supposed to not show with sterilizine. 

Tried with cleaner/non-steri spray and it worked before.

**Comment by Datraen** [comment]
Have you tried spraying the luminol after cleaning the area?

That being said, we might have to look at how the soap works to see if it is cleaning everything, and not just the visible sprites.

**Comment by Minijar** [comment]
Yep, I cleaned the area, then sprayed and it didn't show even under UV light.

**Comment by Zuhayr** [comment]
Soap MAY just call qdel instead of clean_blood().

**Comment by Datraen** [comment]
https://github.com/PolarisSS13/Polaris/blob/125e654fe0c9e34f7615025234778fbd9aedf55a/code/game/objects/items/weapons/mop.dm Might be related to how the mop works.

**Comment by Datraen** [comment]
https://github.com/PolarisSS13/Polaris/blob/8f54e7778fd377296a9c895295d7977e6ce5a7eb/code/game/objects/items/weapons/clown_items.dm#L31 just needs to be updated.
