### ISSUE TITLE
Certain devices cannot be used while sitting

### ISSUE THREAD

**Issue by Mewchild** [PolarisSS13/Polaris#5332]
#### Brief description of the issue
Text-to-Speech device cannot be used while buckled to a chair
#### What you expected to happen
Able to be used normally, as it's a small device.
#### What actually happened
"You cannot activate the device in your state."
#### Steps to reproduce
Have a TTS device
Buckle self into chair
Try to use device
#### Additional info:
 - **Server Revision**: Server revision: master - 2018-06-03
493a497d25a32cc9cafe75b10757a2acaf597958 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Being buckled is a form of restraint currently, so you're technically gripping the chair like your life depended on it, for lack of a better analogy

**Comment by Mewchild** [comment]
>Next update: Can no longer do basic actions while buckled to a chair.

**Comment by Verkister** [comment]
That's not how seatbelts work
