### ISSUE TITLE
Pipe meters can no longer be fastened down

### ISSUE THREAD

**Issue by Nerezza** [PolarisSS13/Polaris#5340]
#### Brief description of the issue
Unfastened pipe meters can no longer be fastened onto pipes via wrench.
#### What happened
The game acts as if no pipe is present under any meters, complete with red text stating as such.
#### Additional info:
 - **Server Revision**: Server revision: master - 2018-06-03 493a497d25a32cc9cafe75b10757a2acaf597958 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
A good way to check this out is to find a meter that's been mapped in, unwrench it, then try to wrench it down again. You can also try with meters spawned from the pipe dispenser, of course.

**Comment by Atermonera** [comment]
Unable to reproduce,
Server revision: master - 2019-01-20
48c4ec46e2d008de415f02539e9d5f2d543f7e82
