### ISSUE TITLE
Communicators can be used while lying prone

### ISSUE THREAD

**Issue by Nerezza** [PolarisSS13/Polaris#5345]
Although PDAs cannot be used while lying prone, you can drag-and-drop your communicator from a storage slot (like your pocket) to operate it as if you were standing up.

This does open up some RP possibilities when you're in paincrit, lying on the floor going in and out of consciousness, but it's probably an unintended feature since PDAs can't be used in a similar manner.

**Comment by Anewbe** [comment]
This is a deliberate feature.

**Comment by Nerezza** [comment]
Awesome o3od
