### ISSUE TITLE
A Veil of Mist Concealing the Rock

### ISSUE THREAD

**Issue by Hjorthorn** [PolarisSS13/Polaris#5362]
#### What actually happened: 
[Common] VMV Veil Of Mist Concealing The Rock states, "Southern Cross STC, this is **Vey-Med** VMV Veil Of Mist Concealing The Rock on a medical resupply flight to a station in Isavau's Gamble, calling for permission to depart system."
 [Common] Southern Cross Space Control states, "**Vey-Med** VMV Veil Of Mist Concealing The Rock, this is Southern Cross TraCon, permission to depart granted, good day."
 [Common] VMV Veil Of Mist Concealing The Rock states, "Southern Cross TraCon, thank you, good day."

#### Steps to reproduce: unknown

**Comment by Serithi** [comment]
... Well yeah, Vey-Med is the correct name. https://wiki.ss13polaris.com/index.php?title=Vey-Medical
