### ISSUE TITLE
Clicking various consoles as a ghost doesn't give a popup view

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#537]
Clicking them should let you view them, but it doesn't.

Known suspects:
Station Alert Console
Medical Records Console
Security Records Console

There's likely more.

**Comment by Zuhayr** [comment]
Why the heck did pushing to Europa close this?

**Comment by PsiOmegaDelta** [comment]
Nice Github bug.

**Comment by Atermonera** [comment]
This is the case with anything that doesn't use NanoUI

**Comment by mistyLuminescence** [comment]
Reproduceable as of 21/5/19. Partially, but not purely, a NanoUI issue- security camera monitor, which uses NanoUI, doesn't display to ghosts, but atmospherics control, which also uses NanoUI, does. My guess would be it requires both NanoUI and a check to allow ghosts.

**Comment by Atermonera** [comment]
Specifically missing a proc that handles when ghosts click on a thing. Nanoui machines that don't have it are most likely a trivial fix, because other nanoui things have that proc. Non-nanoui is harder, because you want to display the page without allowing interaction via links etc
