### ISSUE TITLE
Voidsuits don't block weather effects

### ISSUE THREAD

**Issue by Mewchild** [PolarisSS13/Polaris#5412]
#### Brief description of the issue
Wearing a voidsuit doesn't protect you from weather effects, such as being soaked by rain, or battered by hail

#### What you expected to happen
For a rigid suit of hard material to block ice chips and rain drops

#### What actually happened
Rain falls on you, drenching you in water.
Rain falls on you, drenching you in water.
Rain falls on you, drenching you in water.
Rain falls on you, drenching you in water.
Rain falls on you, drenching you in water.
Rain falls on you, drenching you in water.
Rain falls on you, drenching you in water.
*---------*
This is   Phi Vietsi
They are wearing   a prototype voidsuit helmet on their head.
They are wearing   a prototype voidsuit. Attached to it is The head of security's cloak.

#### Steps to reproduce 
- Wear a voidsuit
- Step into hail
- Enjoy the concussion

#### Additional info:
 - **Server Revision**: master - 2018-07-09
a7789447e0a0e81492f3b5ab6bb98e9f97ab0deb 
 - **Anything else you may wish to add** 
![image](https://user-images.githubusercontent.com/13400422/42727936-f0087b00-8774-11e8-8d0b-659777fa18e8.png)

**Comment by Neerti** [comment]
This could be fixed by checking permeability of worm objects (there's a proc laying around somewhere that does that painlessly)
