### ISSUE TITLE
CrashedContainmentShuttle PoI lacks a reward

### ISSUE THREAD

**Issue by SubberTheFabulous** [PolarisSS13/Polaris#5419]
#### Brief description of the issue

At the center of the PoI, there's a crate in which something is supposed to be.

#### What you expected to happen

Open the crate around which the whole PoI is centered, get the knick-knack.

#### What actually happened

Open the crate around which the whole PoI is centered, get the nothing.

#### Steps to reproduce

Get to the PoI
Open the crate
Cry.

#### Additional info:
Server revision: master - 2018-07-09
a7789447e0a0e81492f3b5ab6bb98e9f97ab0deb

**Comment by lolman360** [comment]
Intended, sometimes the crate is empty.

**Comment by SubberTheFabulous** [comment]
> Intended, sometimes the crate is empty.

At the time of making this issue, it would be empty 100% of the time.
