### ISSUE TITLE
CyroSleepers, (Round Exit) Don't allow you to leave them.

### ISSUE THREAD

**Issue by Edwardc120** [PolarisSS13/Polaris#5422]
#### Brief description of the issue
CyroSleepers, (Round Exit) Don't allow you to leave them if you are put into them. Regardless if you haven't ghosted.
#### What you expected to happen
It has been in the past, that if as long as you don't leave the round occly, Logging out or ghosting you have been able to get out of the Cyrochambers if you changed your mind/where using them to be able to go afk a bit if you needed to do something, without it being jarring icly.
#### What actually happened
Even if you where put there by someone else or try to back out the second after entering, you are stuck there forever without being able to move out or eject from them. the only way to exit the chamber is for someone else to eject you for you.
#### Steps to reproduce
Enter Cyrosleeper, Notice how you are now trapped forever without outside help, or exiting the round completely then re entering through the cyrosleep spawn, winch is annoying for those that don't want the round spoiled by being a ghost, or having to do two separate logs for the round because you had to log out, and You have to wait about five mins for your body to despawn in the first place.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by TheFurryFeline** [comment]
Fixed with https://github.com/VOREStation/VOREStation/pull/5078. On my list to port.
