### ISSUE TITLE
Medical laptop turns into console if you rebuild it

### ISSUE THREAD

**Issue by Mwahahahaha** [PolarisSS13/Polaris#5434]
Taking steps to disassemble a fixed medical laptop (as in the medical console subtype) and then finishing its assembly once more constructs an entire console mainframe instead of a laptop.
This can be achieved, for example, by using a screwdriver to disconnect the monitor and then using the screwdriver on the frame to connect the monitor.

Revision: e29884bfdfa1e049a2186ab664ffc29cab62bd57

**Comment by Atermonera** [comment]
Laptops of that sort are a subtype of the main computer, and without a separate board to distinguish it in construction, the construction functions will build the base type
