### ISSUE TITLE
Robotics Lab closet names

### ISSUE THREAD

**Issue by Mwahahahaha** [PolarisSS13/Polaris#5436]
In the robotics laboratory, the closet labelled "welding equipment" contains robotics parts, and the closet labelled "robotics parts" contains welding equipment.

Server Revision: e29884bfdfa1e049a2186ab664ffc29cab62bd57

**Comment by elgeonmb** [comment]
keep this bug, it adds verisimilitude to my Space Office RP

**Comment by lbnesquik** [comment]
Ok i guess.

**Comment by Nalarac** [comment]
Fixed in #5653
