### ISSUE TITLE
Deadspy PoI spawns in the rocks

### ISSUE THREAD

**Issue by Atermonera** [PolarisSS13/Polaris#5447]
#### Brief description of the issue
The turfs in the PoI submap aren't actually set, so it doesn't override whatever the terrain generation makes

#### What you expected to happen
A cavern containing the contents of the PoI

#### What actually happened
![This](https://puu.sh/B3PZS/aa568a6a89.png)
`Request for Help: ____/(_____)(?)(PP)(VV)(SM)(JMP)(CA)(TAKE) there's a turret INSIDE of a rock that's shooting at me `

#### Steps to reproduce
Make a mountains submap that looks something like ![this](https://puu.sh/B3Qb4/74dca2574f.png)
Spawn it in the mountains.
Observe the buried nature of various contents

#### Additional info:
Protip: When making a PoI, set the turf.

**Comment by drexample** [comment]
Making a PR to fix it.
