### ISSUE TITLE
Hanging up from a communicator call will instantly allow the caller to respawn.

### ISSUE THREAD

**Issue by Dibasic** [PolarisSS13/Polaris#545]
To reproduce:

1. Die.
2. Call someone.
3. Have them pick up the call.
4. Chat for a bit, have them hang up.
5. Respawn.

I think the expected behavior is that it resets your respawn timer to 0 either when they pick up or hang up the call.

**Comment by Zuhayr** [comment]
Your mob does not technically have a time of death I suspect.

**Comment by Neerti** [comment]
This /should/ be fixed with the new communicator update.
