### ISSUE TITLE
Headphones cannot be properly removed

### ISSUE THREAD

**Issue by Mwahahahaha** [PolarisSS13/Polaris#5454]
When removing headphones after placing them on your left ear, they do not seem to be properly removed from your right ear slot and need to be manually removed from there as well. I suspect it may be possible for earmuffs to hold a similar issue.

Server Revision: 5a223610bc13410146477800370d50a88b14320f

**Comment by Atermonera** [comment]
Unable to reproduce as of
Server revision: master - 2019-01-20
48c4ec46e2d008de415f02539e9d5f2d543f7e82
