### ISSUE TITLE
Safe Slicing Open

### ISSUE THREAD

**Issue by redstryker** [PolarisSS13/Polaris#549]
I was captaining and had a box of spare PDA's in my hand.  I clicked the safe with it and it 'cut' the safe open. Don't know how to better describe it, but that is what happened.  At least the bug is up there.

**Comment by Hubblenaut** [comment]
What safe, the wall safe?

**Comment by redstryker** [comment]
Yes.

**Comment by Neerti** [comment]
I believe the safe thinks it's being sliced by a ninja blade, since it made the sound for it.
