### ISSUE TITLE
Ballistic Weaponry causes heavy CPU usage

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#551]
Any time there's a major firefight and ballistic weaponry is used the CPU usage climbs to extremely high levels and lags up the server until the firefight is over. Not certain if it has to do with the projectiles hitting mobs or just the amount of projectiles flying about. Also not quite certain it's just ballistic weapons that cause the lag, but it seems to be more comment with sabers and STS weapons than energy and laser.

**Comment by Neerti** [comment]
I'm fairly sure lasers are causing similar issues, but whenever I try to reproduce locally, it doesn't cause any noticeable lag, gonna do some testing regardless.

**Comment by EmperorJon** [comment]
I also get no local lag, and from my experience I've seen the lag occur with laser/taser projectiles too.
Neerti - if you want, I can see about port-forwarding my box (or you could do the same) and we can see if it's something that's just not noticeable locally?

**Comment by EmperorJon** [comment]
Cause identified by Datraen and I.
The visible messages which report firing/hits are causing a /lot/ of lag, presumably because they're looping through all nearby objects to make the messages for each shot, which is why it's extremely apparent with burst weapons.

**Comment by Neerti** [comment]
You could make a variant called ```visible_message_mobs()``` that only shows mobs the message, or add an argument to ```visible_message()``` to prevent showing items the message, that would presumably make it less costly to call.  Another option is to make a new type of proc which does what ```visible_message()``` does but lets you supply a list of mobs/atoms to hear the object, so you can sorta 'cache' what is meant to see the message, to make burst first not cause lots of unnecessary CPU usage.

**Comment by EmperorJon** [comment]
The thing is, the definition for the problem proc already hardcodes a pair of flags for getting mobs or objects.

/proc/get_mobs_or_objects_in_view(var/R, var/atom/source, var/include_mobs = 1, var/include_objects = 1)


I simply passed through 1,0 from visible_message and the situation was immediately noticeably better. We should maybe identify exactly which objects are actually able/required to get the messages?

**Comment by Neerti** [comment]
By default it should just return immediately for most objects for ```show_message()```.

**Comment by Zuhayr** [comment]
This has been fixed functionally in #711. A more elegant solution may be implemented later but for now this issue is resolved.
