### ISSUE TITLE
Skipjack floor tiles have wrong atmos settings.

### ISSUE THREAD

**Issue by GrayRachnid** [PolarisSS13/Polaris#5513]
#### Brief description of the issue
Dey dun it wrong.

#### What you expected to happen
Default atmos settings

#### What actually happened
Some weird atmos settings.

#### Steps to reproduce
open floor_types.dm and look for /skipjack floortiles.

#### Additional info:

```
/turf/simulated/shuttle/plating/skipjack //Skipjack plating
	oxygen = 0
	nitrogen = MOLES_N2STANDARD + MOLES_O2STANDARD

/turf/simulated/shuttle/floor/skipjack //Skipjack floors
	name = "skipjack floor"
	icon_state = "floor_dred"
	oxygen = 0
	nitrogen = MOLES_N2STANDARD + MOLES_O2STANDARD
```

**Comment by mistyLuminescence** [comment]
vox raiders breathe nitrogen, right? might be so they don't have to use N2 tanks while in the skipjack

**Comment by Atermonera** [comment]
I believe oxygen is indeed toxic to vox, so they need standard pressure of pure nitrogen.

**Comment by Mechoid** [comment]
Vox breathe Phoron, and Vox raiders are only ever admin bus, while raiders in the mode need oxygen. They have to keep phoron internals on anyway.
