### ISSUE TITLE
Floor Tile placing sets air to zero automatically

### ISSUE THREAD

**Issue by weaversam8** [PolarisSS13/Polaris#552]
We just exposed one of the asteroid pockets of vacuum to air, and we pressurized it. At the point when we began putting down lattice and plating, every time we placed the initial plating on top of the lattice, the air on the tile went to zero. We had already pressurized the room, but the air on each tile set to zero each time we added plating, quickly depressurizing the room.

**Comment by weaversam8** [comment]
**Update:** more clarification, I believe when a floor tile is placed upon a lattice outside an interior area, it defaults to "airless tile," regardless of whether there is air on the tile or not.

**Comment by Hubblenaut** [comment]
Looks like the setup of flooring on asteroid turfs is a shameless copytaste of the space turf. Spawns an airless turf without any concerns about atmosphere.

**Comment by weaversam8** [comment]
Yeah, I figured as much. I might be able to fix it myself in a few days, if anyone else wants to fix it though, be my guest.
