### ISSUE TITLE
Wielded Phase Cannon Sprite Too Low

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#5542]
#### Brief description of the issue
![image](https://user-images.githubusercontent.com/8042031/44939391-60eb0400-ad4a-11e8-8e2a-86c848e9e25b.png)

**Comment by Anewbe** [comment]
That's exactly where it's supposed to be. Picture Classic Badass Minigun style.

**Comment by Nalarac** [comment]
Neither of my hands are touching it
