### ISSUE TITLE
Some sort of whitelisting bug

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#556]
It seems some people have issues with species and whitelisting.
They're  unable to open the species selection menu, and any species whitelisted items in the loadout menu, such as Skrell headtail chains, are removed from their character.

**Comment by Datraen** [comment]
Can confirm it happens, will have to double check and make sure it happens
on all of my slots.

**Comment by Datraen** [comment]
I can also confirm the species selection menu, as I'm having that issue now.

**Comment by Zuhayr** [comment]
Hard to reproduce locally for me, and I don't have access to the runtime logs for the server.
