### ISSUE TITLE
The entertainment console loses it's sprite when reconstructed.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#5569]
#### Brief description of the issue
The entertainment console loses it's sprite when deconstructed, then reconstructed.

#### What you expected to happen
The console to appear on the wall after being rebuilt.

#### What actually happened
Alt click showed it was still there, but I couldn't see it.

#### Steps to reproduce
Deconstruct the bar entertainment console.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Schnayy** [comment]
Assuming this is fixed as I couldn't reproduce it and it's ages old, so closing it.
