### ISSUE TITLE
Webspitters don't respect mobs falling into crit

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#5570]
#### Brief description of the issue
Webspitters (the green and white bloated looking spiders) continue to fire their webs, even if the target is on the floor in paincrit or hardcrit.

#### What you expected to happen
Them to stop like other mobs

#### What actually happened
Slam face into wall, go into paincrit and get machinegun'd to death.

#### Steps to reproduce
Fight a webspitter. Be a scrub. Fall over. Die.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
I can't find any mob that checks for crit.

**Comment by Anewbe** [comment]
... That's a lot more logical than my method of "Spawning in a bunch of animals and putting myself in paincrit", but I'm still not sure it's happening, which may point towards a larger issue.

**Comment by Atermonera** [comment]
This was prior to neertAI and I think the similar issue that cropped up with that was resolved. Regardless, this is addressing an issue with a now unsupported system
