### ISSUE TITLE
Command Secretary Quarters' Electrochromatic Window not so tinty

### ISSUE THREAD

**Issue by Hjorthorn** [PolarisSS13/Polaris#5571]
#### Brief description of the issue:
Secretary Quarters window tint control does not work

#### What you expected to happen
Pressing Command Secretary window tint button will tint the quarter's window
#### What actually happened
The button toggles but has no effect

#### Steps to reproduce
Attempt to darken the windows in the command secretary quarters

#### Additional info:
 -Server revision: master - 2018-09-13
8094bbd74682c2ef08672f90ad42bb26855934cf 
 - **Location: command secretary's quarters

**Comment by Nalarac** [comment]
Fixed by #6209
