### ISSUE TITLE
Hallucinated mobs apparently burn on the Supermatter.

### ISSUE THREAD

**Issue by EmperorJon** [PolarisSS13/Polaris#558]
Someone having hallucinations around the Supermatter reported Pun Pun as burning up in contact with it - and over-energising it as a result!

**Comment by EmperorJon** [comment]
See https://github.com/Baystation12/Baystation12/issues/11687

**Comment by Ccomp5950** [comment]
https://github.com/Baystation12/Baystation12/pull/11716
