### ISSUE TITLE
One of the Red Slime's Attacks does not respect armour

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#5597]
#### Brief description of the issue
The red slime (the angry one that throws you around) does not respect armour with it's sends X flying attack.
The other attacks (excluding the clone damage) did seem to get mitigated by my armour.

#### What you expected to happen
Riot armour to protect me from approximately 80% of the damage.

#### What actually happened
The ruby baby slime (639) sends Durathror Korakov flying with the impact!
Durathror Korakov screams!
The wound on your right arm widens with a nasty ripping noise.
Something feels like it shattered in your right arm!
Durathror Korakov screams!

#### Steps to reproduce
Put some really heavy armour on and get attacked by a red slime.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
That's just throw code.
