### ISSUE TITLE
Radiation and FBPS

### ISSUE THREAD

**Issue by SilverTalismen** [PolarisSS13/Polaris#5601]
#### Brief description of the issue
FBP's recieve no warning whatso ever that radiation is affecting them severely until it's too late
#### What you expected to happen
To recieve some sort of warning in the chatbox about rising system issues due to radiation
#### What actually happened
Had to use the diagnostics button when my controls inverted to find out what was wrong.
#### Steps to reproduce
Be a FBP
Be exposed to either constant or bursts of radiation
Abruptly decompile as the rads cause you to shut down.
#### Additional info:
 - **Server Revision**: master - 2018-09-23
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Nalarac** [comment]
#5077
