### ISSUE TITLE
Dug in rock Sprite broken.

### ISSUE THREAD

**Issue by Multi-Kill401** [PolarisSS13/Polaris#5606]
#### Brief description of the issue
I'm on my Anomalist and I go to dig an artifact up. While digging around a EDIT: 150 cms deep this pops up https://i.gyazo.com/18b02745dbbacfc03d1a8749ec373709.png
#### What you expected to happen
It's actual dug in sprite to show up.
#### What actually happened
A sprite that says 'No Sprite' crossed out.
#### Steps to reproduce
1.Find a rock with artifacts in it
2.Extract two or three artifacts from it until you reach around a EDIT: 150 cms deep or deeper
3. sprite pops up
#### Additional info:
Immersion = broken

**Comment by Schnayy** [comment]
Fixed by #5652
