### ISSUE TITLE
Using Resist to Unbuckle from Space Bike Breaks Bike

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#5658]
#### Brief description of the issue
If you use the resist verb to unbuckle yourself from the space bike instead of clicking the bike to unbuckle yourself, you are unbuckled but keep your pixel shift and become unable to climb back onto the bike (and no one else can either).
#### What you expected to happen
To be unbuckled normally like when you click the bike.
#### What actually happened
Acero was pixel shifted higher and neither I nor the roboticist could get back on the bike.
#### Steps to reproduce
0.) I was Acero, cyborg, so 1 trial as human and 1 as cyborg?
1.) Create space bike
2.) Buckle self to bike
3.) Use resist to unbuckle
#### Additional info:
 - **Server Revision**: master - 2018-10-02 7ee626869ea48947e6f84102f7cf499c9583cc68 
 - **Anything else you may wish to add** When putting up the kickstand it states "You put up the space-bike's kickstand." to everyone around you as well

**Comment by TheFurryFeline** [comment]
Fixed with #6087, I believe. Except for the displayed message. That is still happening, but perhaps an easy fix.
