### ISSUE TITLE
Runtime on wiki/Special:Log/delete/

### ISSUE THREAD

**Issue by zaredman** [PolarisSS13/Polaris#567]
![sin](https://cloud.githubusercontent.com/assets/8041697/11790347/46b5e436-a269-11e5-9ba2-b897fe23b1b2.PNG)

**Comment by Minijar** [comment]
Augh firefox.

**Comment by Neerti** [comment]
Occurs for any page with a forward slash in it's name.

**Comment by Lorwp** [comment]
Should probably close this. This does not seem to be an issue currently.
