### ISSUE TITLE
Emergency Oxygen Wall Locker Sprite

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#5688]
#### Brief description of the issue

The Blue Oxygen Wall Lockers have the default 'wall-locker' sprite instead of 'emerg'

#### What you expected to happen

For them to have the correct sprite under icon_state and as shown in their file and in map maker.

#### What actually happened

When the map loads on server they default to icon_state = 'wall-locker'

#### Steps to reproduce

Spawn in a /obj/structure/closet/walllocker/emerglocker

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

master - 2018-10-17
670e64adacd0264a5c70b6dfccd63e312f96aac2 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

n/a

**Comment by Schnayy** [comment]
Fixed by #6793
