### ISSUE TITLE
Fulltile windows are of the same type as directional windows

### ISSUE THREAD

**Issue by Atermonera** [PolarisSS13/Polaris#5707]
#### Brief description of the issue
Any operation that sets the dir of a full tile window object, such as PoI rotation, forces them to use directional-window properties

#### What you expected to happen
Fulltile windows to remain as such when dir is set

#### What actually happened
PoI rotation breaks fulltile windows

#### Steps to reproduce
I'm specifically asking that fulltile windows be made a different type than directional windows. Inheritance makes it logical to make one the child of the other. Window construction would need to be updated, and any mapped objects of the changed type would need to be remapped, including in all PoIs

#### Additional info:
 - I should fix this, but due to school, do not have time.

**Comment by Verkister** [comment]
This also affects roundstart engine rotation where applicable and sounds more like a startup initialization issue rather than mapping issue.
https://i.gyazo.com/d8b8f0046ee7f7e4f8091033fab49511.png
