### ISSUE TITLE
Double-wide doors around new xenobotany are all access

### ISSUE THREAD

**Issue by zekesulastin** [PolarisSS13/Polaris#5717]
#### Brief description of the issue
The doublewide doors at the new xenobotany entryway and by the stairs to the main research area are all-access (or at least engineer access).
#### What you expected to happen
To have to engineering-master-key in
#### What actually happened
Wandered aimlessly in the whole research wing
#### Steps to reproduce
Join as someone without research access and try to get into new xenobotany
#### Additional info:
 - **Server Revision**: 75c872ccd65c4564a6baf3b1ce1a048555ff8fe6 
 - **Anything else you may wish to add**
Xenobotany deck 1 entry

**Comment by Jennalele** [comment]
Can confirm it's all access, have gotten into science from the basement as medical, security, even a fuckin' assistant.
