### ISSUE TITLE
Depth rendering for seated players is messed up

### ISSUE THREAD

**Issue by ax-rwnd** [PolarisSS13/Polaris#574]
When buckled into chairs and having a rotated view, players get rendered on the wrong side in some directions.

**Reproduction**
* Buckle into a chair.
* Turn your view clockwise or counter-clockwise.
* Watch your player stand in front of the chair when they're supposed to be behind, or behind the chair when they're supposed to be in front of it.

It's obviously not a big issue, but it looks weird and makes the use of the buckle mechanic a bit offputting.

**Comment by GinjaNinja32** [comment]
iirc i fixed this on bay dev, need to port the thing over at some point

**Comment by ax-rwnd** [comment]
Yeah, I've never seen the issue over there, so it's probably just a matter of porting it.
