### ISSUE TITLE
Buckling into chairs disable hands for some tasks

### ISSUE THREAD

**Issue by ax-rwnd** [PolarisSS13/Polaris#575]
Buckling into chairs seem to disable the hands of the buckled player for some tasks.

**Recreation**
* Buckle into a chair in front of a machine (chemical dispensers are affected, at least, some others are not).
* Try to use the machine or a PDA, action-fields should be greyed out.

**Comment by Hubblenaut** [comment]
What type of chairs?

**Comment by ax-rwnd** [comment]
I've seen the issue occuring on PDAs with both swiveling chairs and regular steel ones, yet I've only been able to try using machines with the swiveling ones.

**Comment by sabiram** [comment]
happens in the HoP's office with the office chairs and ID computer and employment records
