### ISSUE TITLE
Simple Mob AI Attacks Empty Mechas

### ISSUE THREAD

**Issue by Neerti** [PolarisSS13/Polaris#5750]
#### Brief description of the issue
Empty mechs will get attacked by any mob with ``hostile = 1``.

#### What you expected to happen
For them to ignore empty mechs.

#### What actually happened
They attacked them.

#### Steps to reproduce
Spawn empty mech.
Spawn simplemob.
Observe fighting.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2018-12-01
e145b5c0f7b52ab6ad12e2c1c53445aebb825bb1 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Does this take priority over chasing other mobs?

**Comment by Neerti** [comment]
Ian's AI has ``hostile = FALSE`` so no, however things with their AI having ``hostile = TRUE`` and their mob having``faction = "neutral"`` will attack empty mechs, meaning things meant to be friendly to the station and fight things not friendly to the station (like carp or spiders) will attack empty mechs.

**Comment by Anewbe** [comment]
We can't give mechs a faction, can we?
