### ISSUE TITLE
Dorm Area isn't Radiation Shielded

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#5766]
#### Brief description of the issue
The dorm area connected to the locker room isn't radiation shielded, so people who go SSD in the dorms will suffer from rad storms.
#### What you expected to happen
The SSD people to be safe from radiation.
#### What actually happened
SSD person got irradiated and medical had to rescue them.
#### Steps to reproduce
1.) Go into dorm bedroom
2.) Start a radiation storm
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Unable to reproduce
![test](https://puu.sh/CfGg6/b5599f4053.png)

**Comment by Nalarac** [comment]
Hm. I went SSD in the dorms one round and ended up in medical when I came back, and I was told in TeamSpeak that it was because there was a radiation storm. So I guess I was lied to and something else happened?
