### ISSUE TITLE
Guns no longer have log their firing.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#5810]
#### Brief description of the issue
Guns no longer show the 'X has fired X' message.
All guns are super silenced.

In times past you would get 
Durathror Korakov has fired the Energy Gun!
and
 Kathala Lobarn has been hit by the Taser in the Chest!
but now there is nothing.

#### What you expected to happen
A log to show up when I accidentally shot a detective.

#### What actually happened
No log, just a sound effect and a tasered detective.

#### Steps to reproduce
Fire a gun. Observe lack of logs, both of hitting and of firing.

#### Additional info:
 - **Server Revision**: 
Server revision: master - 2019-01-03
2651bc3520612d6ea463847e58147b81ba9126f5

**Comment by Anewbe** [comment]
This is apparently a year old bug. I know where the issue is, will fix post haste.
