### ISSUE TITLE
Trash bags no longer pick up tiny objects

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#5836]
#### Brief description of the issue
It used to be that trash bags could sweep up lots of tiny objects for easy cleanup. For some reason, this feature was removed or broken and nobody has reported it.

#### What you expected to happen
To clean up the shitton of ammo casings left scattered around the firing range.

#### What actually happened
I had to tediously pick them up one at a time.

#### Steps to reproduce
1. Produce mess of tiny items.
2. Click on them with a trash bag.
3. Nothing happens.

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/a0cb0a347db73611b7da9a3cca46d33c392a8e73 Yes I know this isn't Polaris but we use your code damn it. As far as I can tell we haven't messed with this.
 - **Anything else you may wish to add:** If this was removed on purpose, because "muh crime scene", let's be honest. One, how often does anyone actually investigate crime scenes to bother asking why the casings are where? Two, how often does the traitor actually bother to pick up casings, especially when they can just use revolvers? Even before this change. Three, even if my assumptions of both prior points are wrong, it's pretty absurd that you can only hold one bullet casing in your hand at a time. Hardly believable! :U

**Comment by Nalarac** [comment]
Is it all tiny objects or just bullet casings, because as far as I know, trash bags were never able to pick up bullet casings.

**Comment by SpadesNeil** [comment]
I know for absolute certain that you could previously pick up bullet casings with trash bags. We used to stock them on the firing range in Vorestation's code when we used Polaris's map, specifically for that reason.
