### ISSUE TITLE
Green blobs actually don't destroy rock walls but grow in/through them.

### ISSUE THREAD

**Issue by zaredman** [PolarisSS13/Polaris#584]
https://gyazo.com/d2db4343e044a00984b10043c6d0922b

**Comment by Minijar** [comment]
This actually looks quite cool as if the blob was growing in the rock cracks. COuld be a feature.

**Comment by Spookerton** [comment]
Blobs also grow OVER many objects instead of destroying them, such as fuel tanks, water tanks, etc.

**Comment by EmperorJon** [comment]
My experience has been that they do start to destroy the walls after a while.

**Comment by SinTwo** [comment]
A most likely reason they grow over rocks is that they have never had a reason to do anything to the asteroid rocks as they should never interact with them on bay map.

**Comment by Hubblenaut** [comment]
I'd say it should not be able to tear down solid rock and be restricted by its geography.

**Comment by PsiOmegaDelta** [comment]
@Spookerton This in particular is an intended change for Bay-Dev blobs, due to many objects currently being irreparable.
However, turfs should always be affected and block blob progress.
