### ISSUE TITLE
Suit Cooling Units no longer work

### ISSUE THREAD

**Issue by Neerti** [PolarisSS13/Polaris#5854]
#### Brief description of the issue
When wearing a voidsuit as an FBP, the suit cooler no longer stops you from eventually overheating.

#### What you expected to happen
To be able to wear a voidsuit with an active suit cooler.

#### What actually happened
Temperature steadily rises, eventually causing overheating.

#### Steps to reproduce
Join as FBP.
Get voidsuit of any kind.
Get suit cooler.
Wear both.
Turn on suit cooler.
Observe temperature rising.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2019-01-16
e0d442b54470a0693218e37b53845d73f2fb413b 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
This appears to be caused by the suit cooler not passing a pressure argument into ``get_pressure_weakness()`` and as a result it always returns 1, resulting in ``var/efficiency`` equaling 0, and no cooling.
RIG suits may or may not have the same issue, I wasn't able to test that so far.
Appears to have been introduced by #5776

**Comment by Atermonera** [comment]
Will have time later today, wasn't aware that that's how suit coolers actually functioned.

**Comment by Neerti** [comment]
Update: RIGs have the same issue.
