### ISSUE TITLE
Stasis bags kill patients

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#5860]
#### Brief description of the issue
Placing a body within a stasis bag will rapidly kill the patient inside

#### What you expected to happen
To keep the squishy meatbag stable until taken for heals

#### What actually happened
Meatbag was pounded to a pulp by the power of stasis

#### Steps to reproduce
Spawn in a stasis bag, health analyzer, and human mob. Place human mob within the bag, scan with the health analyzer and watch the brute damage go up.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2019-01-18
0c11bdb87997c0560ac3a14d09cbec9d45d6f40a 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Damage type?

**Comment by Woodratt** [comment]
"Steps to reproduce

Spawn in a stasis bag, health analyzer, and human mob. Place human mob within the bag, scan with the health analyzer and watch the brute damage go up."

**Comment by Atermonera** [comment]
#5779 causes the emergency double oxy tank that stasis bags spawn with to have a pressure of 10 atmospheres, up from 3. The former is damaging, the latter is not. Stasis bags take their environmental pressure directly from the contents of the tank, using the volume of the tank, so mobs start taking damage from too much pressure

**Comment by Anewbe** [comment]
Possible fix be refactoring the internal tank to output at survivable atmos and having the cryobag check for release pressure?

**Comment by Atermonera** [comment]
I've just made a subtype that starts with a valid atmospheric value. Considered making starting atmospheres an initialization parameter but didn't see a clean way to get Initialize() that parameter
