### ISSUE TITLE
Chem dispensers not updating

### ISSUE THREAD

**Issue by Schnayy** [PolarisSS13/Polaris#5862]
#### Brief description of the issue
When mixing chemicals the chem dispenser did not update the reagents listed when mixed until I open/closed the window.
#### What you expected to happen
For my chemicals to mix properly
#### What actually happened
Ominous bubbling as they stayed listed as separate reagents.
#### Steps to reproduce
Use the chem dispenser to make anything.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2019-01-18
0c11bdb87997c0560ac3a14d09cbec9d45d6f40a 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by MagmaRam** [comment]
Can't reproduce in private testing or on server.

**Comment by Schnayy** [comment]
Seems to have been fixed at some point, I assumed this had gotten closed.
