### ISSUE TITLE
Atom ProcCall cannot be cancelled after entering a number of arguments.

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#5864]
#### Brief description of the issue
View Variables PR changed proc-calling as well.
You cannot cancel a proc call, as the proc is called anyway just without arguments after entering the [assumed] number of arguments.
#### What you expected to happen
The proc to not go through.
#### What actually happened
The proc went through. Ian shrank to infinitesimal size because I cancelled an adjust scale.
#### Steps to reproduce
VV a mob.
Call proc
Enter 'gib'
Enter 1 argument
Hit cancel because you decide not to gib whatever mob you were just about to.
Gib the mob anyway.
#### Additional info:
 - **Server Revision**: 0c11bdb87997c0560ac3a14d09cbec9d45d6f40a 
 - **Anything else you may wish to add** Why.

**Comment by Atermonera** [comment]
@kevinz000 introduced this in #5829 and this really should have been caught in testing
