### ISSUE TITLE
FBPs switch to gibberish for no reason.

### ISSUE THREAD

**Issue by martin509** [PolarisSS13/Polaris#5884]
#### Brief description of the issue
For some reason, FBPs seem to have the issue of randomly speaking gibberish instead of common.
#### What you expected to happen
Normal common speech
#### What actually happened
Random bouts of speaking in gibberish for a few seconds at a time. When it happens, it's also seemingly restricted to either radio chat or normal speech, either or.
#### Steps to reproduce
Try to speak normally in common. Keep trying until randomly you speak gibberish.
Edit: The issue is caused by starting a sentence with '-', and has nothing to do with being a FBP or not.
#### Additional info:
None

**Comment by Schnayy** [comment]
This appears to be caused by "-" being at the beginning of a sentence. Still a big issue because many people use it that way to indicate cutting off what they were previously saying. Seen several people have this issue, not just FBPs.

**Comment by Anewbe** [comment]
This is actually a prefs/config thing. The default language keys are `, # -` which is why the thing is freaking out. Gonna see if there's a config-fix to be done.

**Comment by Anewbe** [comment]
#5898 should have fixed this by default, if you still have this as an issue be sure to turn your language keys to something else.
