### ISSUE TITLE
Mechs cannot cross planet Z levels

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#5911]
#### Brief description of the issue
You can't walk a mech into the caves, or out of them.

#### What you expected to happen
To walk into the caves in my Riply.

#### What actually happened
Walked up to the black edge to no effect.

#### Steps to reproduce
Try to enter the caves in a  mech.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
Mechs are anchored, anchored things no longer trigger the invisible teleporter on those tiles.
