### ISSUE TITLE
Emitters vs Blobs is broken

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#5927]
#### Brief description of the issue
Attempting to use a emitter on a iron tide blob, resulted in the emitter fire missing 8 blob chunks and instead taking out a wall behind the blob

#### What you expected to happen
For the emitter beam to hit the blob chunk and destroy it

#### What actually happened
Shot through the blob chunk like it wasn't even there and took out the wall behind it

#### Steps to reproduce
Set up emitter, Spawn in blob core, Turn on emitter

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2019-02-02
ca2dab5c62cf16f282490804b6cff73a94242a41 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Mechoid** [comment]
Blob collision is broken due to the projectile thing, as well.
