### ISSUE TITLE
Weldinghelmet button not working while buckled in.

### ISSUE THREAD

**Issue by DasIrrlicht** [PolarisSS13/Polaris#5930]
#### Brief description of the issue
While buckled in(but not cuffed), one can not adjust ones weldingmask.
#### What you expected to happen
To laszyly dowse off and flipping the mask before my face to dampen the light.
#### What actually happened
Needed to unbuckle, adjust mask and buckle again.
#### Steps to reproduce
Sit down, try to flip the mask using the button.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
May applies to other cloths with function, too.
May applies to wheelchairs, and that would be actually problematic then.

**Comment by Atermonera** [comment]
Being buckled generally considers you to be holding on for dear life, see: not falling over when a shuttle moves if you're buckled in, or otherwise that you're physically restrained by the chair. Not really a good way to fix this without fundamentally changing how being buckled works
