### ISSUE TITLE
All Turrets seemingly useless

### ISSUE THREAD

**Issue by DasIrrlicht** [PolarisSS13/Polaris#5931]
#### Brief description of the issue
I builded, mainly out of boredom and because it is 'good training', a turret with a security-training-rifle in the Engineering-lobby. The AI was supossed to turn it on to see if it works.
#### What you expected to happen
Getting attacked by a flashlight-turret.
#### What actually happened
Nothing. No matter what settings.
#### Steps to reproduce
Build a Turret and let the AI turn it on.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
Maybe effects all homebuild-turrets. Maybe only the practice-rifle-ones.

**Comment by Anewbe** [comment]
Turrets are bugged at the moment, in general.
