### ISSUE TITLE
installing glass issue

### ISSUE THREAD

**Issue by Chr1sC** [PolarisSS13/Polaris#5932]
#### Brief description of the issue
http://www.rkszone.com/apps/kittypics/chrisc/dreamseeker930be.png
#### What you expected to happen
The normal process
#### What actually happened
Fastened pried then unfastened 
#### Steps to reproduce
Try undo and window and redo it
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
http://www.rkszone.com/apps/kittypics/chrisc/dreamseeker231b4.png -Undoing a window works fine

**Comment by Schnayy** [comment]
Pretty sure this is an issue in text only, as I've experience the window still being fastened in.
