### ISSUE TITLE
Hivebots unable to harm Beepsky

### ISSUE THREAD

**Issue by DasIrrlicht** [PolarisSS13/Polaris#5934]
#### Brief description of the issue
Officer Beepsky does Anger Iron Tide Hivebots and draws their Agro , but gets not actually attacked by them.
#### What you expected to happen
Beepsky getting overwhelmed by superior numbers.
#### What actually happened
Beepsky stand atop a pile of Hivebot-remains, pointing down and killing more of them coming to stand in front of the officer.
#### Steps to reproduce
Spawn a Iron Tide Nanobot-Blob. Let Beepsky run into the general area the hivebots hang out at.
#### Additional info:
 - **Server Revision**: ca2dab5c62cf16f282490804b6cff73a94242a41
 - **Anything else you may wish to add** Maybe related to other Blob-Issues, likely not.

**Comment by DasIrrlicht** [comment]
![space_station_13_2019-02-06_132358](https://user-images.githubusercontent.com/40157006/52341942-50833780-2a14-11e9-9fe7-dbcdccb097bb.png)
Basically how it looks.

**Comment by DasIrrlicht** [comment]
Server revision: master - 2019-02-02
ca2dab5c62cf16f282490804b6cff73a94242a41

**Comment by Schnayy** [comment]
They weren’t attacking me, either, when I fought an iron tide blob a few days ago.
