### ISSUE TITLE
Walking through dense objects

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#5939]
#### Brief description of the issue
I could walk through grills, and roller beds with people buckled into them.

#### What you expected to happen
Push the roller bed with the patient on it up the stairs.

#### What actually happened
I walked through it.

#### Steps to reproduce
Walk through a grill.
Walk through a buckled roller bed.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by DasIrrlicht** [comment]
I assume it is identical to the blob-issue.

**Comment by Anewbe** [comment]
Seems to be the case, but I specifically want as much of a comprehensive list as we can get, to be sure in testing that we've fixed it.

**Comment by Wickedtemp** [comment]
Adding onto this, Iunno if this is fixed on Polaris' side of things, but bodybags, when open and tagged, can become 'solid/dense', and you cannot walk through them.

**Comment by Anewbe** [comment]
That's mostly known, but unrelated.
