### ISSUE TITLE
Silicons Can't Climb Ladders

### ISSUE THREAD

**Issue by Naidh** [PolarisSS13/Polaris#5945]
#### Brief description of the issue
Silicon mobs such as construction drones, maintenance drones, or cyborgs are unable to climb ladders.

#### What you expected to happen
To ascend the rungs.

#### What actually happened
You fail to reach the ladder.

#### Steps to reproduce
Be 'borg, attempt to climb ladder.

#### Additional info:
 - **Server Revision**: master - 2019-02-09 f702142e00685d7ca30ed4f82a3f9ce917852ece 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Anewbe** [comment]
This isn't really a bug, more a feature request.

**Comment by Naidh** [comment]
> This isn't really a bug, more a feature request.

It's been possible to (with a module active and on the ladder tile) climb them in the past, and that suddenly stopped being possible; unless I'm missing a PR that specifically nixed it.

**Comment by Atermonera** [comment]
That seems like an oversight. If ladders were meant to be climbable by robots, as they are by humans, then they would have been designed to work fine for robots without needing an active module or any other janky steps
