### ISSUE TITLE
breaching a shroud renames it to Hegemony Shroud

### ISSUE THREAD

**Issue by elgeonmb** [PolarisSS13/Polaris#5948]
#### Brief description of the issue
when you breach a shroud, it resets the customized name you gave it with the customize shroud verb.
#### What you expected to happen
Breaching a customized shroud to modify its custom name.
#### What actually happened
Breaching a customized shroud modifies its default name.
#### Steps to reproduce
Breach a shroud.
#### Additional info:
I'll fix this myself, I just want it on paper so I don't forget.

**Comment by Schnayy** [comment]
I think it said Hegemony Shroud before I fixed it, Elgie. I think the damage reset it?

**Comment by elgeonmb** [comment]
yeah i figured that was entirely possible
