### ISSUE TITLE
Medical Records Photo Broken

### ISSUE THREAD

**Issue by MisterLayne** [PolarisSS13/Polaris#5952]
#### Brief description of the issue
Medical record pictures are bald.

#### What you expected to happen
People with hair to have hair when I look at pictures of them

#### What actually happened
Rampant baldness overswept the records

#### Steps to reproduce
- Be doctor
- Open medical records
- Find bald people on pictures

#### Additional info:
 - **Server Revision**: f702142e00685d7ca30ed4f82a3f9ce917852ece 
 - **Anything else you may wish to add**
[Image Here](https://prnt.sc/mjtmr8)

**Comment by DasIrrlicht** [comment]
They are also nude.
And all records have the issue.
I think even on you IDs, you are naked and bald.

**Comment by Bromuzl** [comment]
**cough**  https://github.com/PolarisSS13/Polaris/issues/5554
