### ISSUE TITLE
Do not get Records

### ISSUE THREAD

**Issue by DasIrrlicht** [PolarisSS13/Polaris#5955]
#### Brief description of the issue
I joined as Zaddat Cargo Technician only minutes after roundstart.
#### What you expected to happen
To be on the manifest.
#### What actually happened
Get boinked for not being on the manifest during extended.
#### Steps to reproduce
I have no idea. Be Zaddat Cargo Technician, have the occupation on medium, latejoin? I have no idea what triggered it...
#### Additional info:
 - **Server Revision**:
Server revision: master - 2019-02-12
a23982d9601bd3b9e6614b3d8de818082d92e7cd 
 - **Anything else you may wish to add**
Still got my ID and all, was able to do my job.

**Comment by elgeonmb** [comment]
it is possible, though i'm not sure how likely, that you playing Ataz in a round where I am also playing Ataz is the problem.

**Comment by DasIrrlicht** [comment]
its not, i was alone...
