### ISSUE TITLE
Laptop ID link makes you drop ID

### ISSUE THREAD

**Issue by comma** [PolarisSS13/Polaris#596]
1.Get laptop with Sec records.
2.Click on ID slot linke with ID in hand to log in.

ID ends up on floor, and you are still not logged in and look like a doofus.
Clicking laptop itself with ID is a workaround.
Not sure if present on baycode or specific here. Found here.

**Comment by zaredman** [comment]
There are quite a few "ID + Computer = Issues" issues on this fork for one reason or another that are known -- But I don't know if anyone pushed them to git. Staaaandby.

**Comment by zaredman** [comment]
Oddly enough, could not recreate this one on bay-dev.
