### ISSUE TITLE
Laptop communication console emergency message does not work

### ISSUE THREAD

**Issue by babydoll** [PolarisSS13/Polaris#598]
As captain/big ID man, the laptop contains the communication console program which works as intended, save for the emergency message functionality, which does not.

**Comment by zaredman** [comment]
May be tied to #599 and #596

**Comment by zaredman** [comment]
Managed to get this when I was dicking around with the laptop. Changing alert level w/o ID in hand prompts this:

runtime error: Cannot execute null.GetID().
proc name: Topic (/datum/file/program/communications/Topic)
  source file: communications.dm,88
  usr: Donovan Ward (/mob/living/carbon/human)
  src: Centcom communications relay (/datum/file/program/communications)
  call stack:
Centcom communications relay (/datum/file/program/communications): Topic("src=\[0x21004d50];swipeidsecle...", /list (/list))
Za_Redman (/client): Topic("src=\[0x21004d50];swipeidsecle...", /list (/list), Centcom communications relay (/datum/file/program/communications))
Za_Redman (/client): Topic("src=\[0x21004d50];swipeidsecle...", /list (/list), Centcom communications relay (/datum/file/program/communications))

**Comment by sabiram** [comment]
Changing alert levels doesn't work, either.

**Comment by sabiram** [comment]
I think this is no longer a bug from bay, since they've changed the way laptops work over there.
