### ISSUE TITLE
HOP Computer borked - Duplicates IDs, does not accept IDs, etc.

### ISSUE THREAD

**Issue by zaredman** [PolarisSS13/Polaris#599]
Possibly linked to #596 

Everything works up until point of ejection; it shows the ID in your hand but then tosses a duplicate on the ground. Sometimes both exist as two separate entities. If you drop the one in your hand in a tile beside, both IDs merge into one.

**Comment by zaredman** [comment]
Happens on Bay-Dev too, it seems.

**Comment by Hubblenaut** [comment]
Almost panicked there seeing the title - that's no duplication. The sprite left showing in your hand is a ghost/reference.

**Comment by zaredman** [comment]
No, it duplicates at times. Unpredictable and unable to consistently recreate - But it does happen @Hubblenaut

**Comment by Neerti** [comment]
An object in BYOND cannot be duplicated without explicitly creating a new object.  An object's loc is locked to one location, but can appear on people's screenlocs an arbitrary number of times, as well as being represented as a sprite inside the HUD or on the mob an arbitrary number of times.  It can also be referenced by two different variables that just so happen to be the same variable on two separate mobs.  The actual object's location is determined by it's loc variable, but an object reference somewhere is not being properly cleared.

**Comment by zaredman** [comment]
I've deleted duplicate, usable ID's before that honest dudes and dudettes have reported. All have come from that computer.

So le shrug.

**Comment by Datraen** [comment]
Note about these duplicated IDs:
I had it happen to me just now and I've seen that it's location is on the ground, which means there's something going on with assigning it to inventories, I'll check the checks.
