### ISSUE TITLE
Spawnpoint not getting saved

### ISSUE THREAD

**Issue by Hubblenaut** [PolarisSS13/Polaris#610]
Spawnpoint keeps getting reset to Arrivals Shuttle as it is not saved with the rest of the character settings.

**Comment by zaredman** [comment]
That would explain a few things on my end. This is a bug that's started up recently - Like, putting it 'within the past week' recently.

**Comment by Datraen** [comment]
Worked fine for me as of 12/20/2015 and 12/21/2015, 12AM EST.

**Comment by Hubblenaut** [comment]
It no longer seems to occur

**Comment by PsiOmegaDelta** [comment]
Bugs that cease to occur for no evident reason are the scariest.

**Comment by Datraen** [comment]
I have a feeling it's a database issue.
