### ISSUE TITLE
Robo-limbs borked in the regards that normal surgery works on them.

### ISSUE THREAD

**Issue by zaredman** [PolarisSS13/Polaris#612]
Eg:
-mech eyes
-mech heart
-mech limbs

<12:12:42> "EmperorJon": They're mistaken for normal limbs for all circumstances AFAIK

Limbs also borked in the regards that trauma kits/burn kits work on them.

If #609 goes through, I'm presuming that would fix them out-right by a totally different system.

**Comment by Zuhayr** [comment]
Robolimbs appear to actually just be renamed regular limbs at the moment. Still working on why. That PR will fix the issues but not change the mechanics though.

**Comment by Zuhayr** [comment]
This is fixed in #609.

**Comment by Neerti** [comment]
Should be fixed now.
