### ISSUE TITLE
Bad recipes produce iron ingots

### ISSUE THREAD

**Issue by PrismaticGynoid** [PolarisSS13/Polaris#6141]
#### Brief description of the issue
When the microwave receives an incorrect recipe and is supposed to produce a burned mess, instead, an iron ingot comes out.
#### What you expected to happen
A burned mess
#### What actually happened
A single iron ingot
#### Steps to reproduce
Stick some random ingredients that don't form a recipe into the microwave. Turn it on and wait. Out comes a delicious warm ingot!
#### Additional info:
 - **Server Revision**: pr-6031 - 2019-04-28
a41e6343b60a7dfe31886bd6644a7ff81efc4b25 
 - **Anything else you may wish to add**: Only affects the microwave. Can still produce burned mess from the grill and oven.

**Comment by zekesulastin** [comment]
We're Minecraft now

**Comment by PrismaticGynoid** [comment]
After further testing, it looks like it only does it if there are no reagents in the microwave. If there are, it produces a burned mess like usual.
