### ISSUE TITLE
Event Timer starts even if round start fails

### ISSUE THREAD

**Issue by Dunmeritude** [PolarisSS13/Polaris#6145]
#### Brief description of the issue
When the round start fails due to whatever reason (not enough readies, usually), the event timer begins ticking, even though the game has not started. This tends to lead to, when starting a game after a straight hour of no pop, starting the game, joining, and immediately getting "Starting event Blob of severity Major." Because fuck you, engineering. 

#### What you expected to happen
For the event timer to start ticking when the game ACTUALLY starts

#### What actually happened
Not fucking that

#### Steps to reproduce
Turn on Debug, watch the vote fail, watch the game fail to start, watch the event timer start going.
![image](https://user-images.githubusercontent.com/9397405/56999205-4472c600-6b7c-11e9-8856-7df303192db2.png)

#### Additional info:
 - **Server Revision**: master - 2019-04-30
2c20c129fc5f679e04ef19f819e4ddd529c1523e

**Comment by mistyLuminescence** [comment]
Confirmed as still an issue, and a pretty severe one- the round starting and immediately having your department be breached isn't fun.
