### ISSUE TITLE
Emitters vs Blobs is broken v2

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#6173]
#### Brief description of the issue
Attempting to use a emitter on a iron tide blob, emitter could hit the blob chunks, however it could not hit the core, instead going through the core and hitting the chunk on the other side of it.  

#### What you expected to happen
For the emitter beam to hit the blob core and destroy it

#### What actually happened
Shot through the blob core like it wasn't even there and took out the blob chunk behind it

#### Steps to reproduce
Set up emitter, Spawn in iron tide blob core, Turn on emitter

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2019-05-14
9a6246067f1158ae14d4de7082857bf0617d26c8 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
n/a

**Comment by zekesulastin** [comment]
On the plus side, it looks like regular laser guns do work on the blob core - watched someone kill a core on live while the emitter shot was still passing through.

**Comment by mistyLuminescence** [comment]
07/06/19- Issue is specifically that AI-controlled blob core tiles cannot be indirectly targeted (e.g. by emitters). If you directly click the blob core tile, you're fine (so lasers work if you click on the core, but not if you click on the wall behind the core). 

Not an issue with non-core tiles, and not an issue with player-controlled blobs- very specifically AI-controlled cores.

**Comment by zekesulastin** [comment]
Still broken as of today 
![brok (2)](https://user-images.githubusercontent.com/1291682/61481424-41f75f80-a966-11e9-9c14-ef74fe85e315.png)
