### ISSUE TITLE
Hivebot Melee is Broken

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#6174]
#### Brief description of the issue
Hivebots that use melee attacks will not attack despite obviously targeting and moving towards said target.
#### What you expected to happen
The (melee) hivebots to attack the target once in range.
#### What actually happened
They just followed the target around.
#### Steps to reproduce
1.) Spawn a hivebot that uses melee (e.g. swarm bot, strong bot, bulky bot)
2.) Spawn something the hivebot would kill (e.g. Pun Pun, corgi, human)
3.) Watch the hivebot charge the target but then just kind of rub up against them without attacking.
#### Additional info:
 - **Server Revision**: master - 2019-05-14 9a6246067f1158ae14d4de7082857bf0617d26c8 
 - **Anything else you may wish to add** The ranged hivebots still worked perfectly fine

**Comment by DasIrrlicht** [comment]
Related:
https://github.com/PolarisSS13/Polaris/issues/5934
