### ISSUE TITLE
No log shown when shooting a mob

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#6220]
#### Brief description of the issue

When shooting another mob with a weapon no log is shown in game to indicate you shot your target or 'narrow missed'

#### What you expected to happen

To see some sort of indication that I have hit my target with a laser or a ballistic gun

#### What actually happened

No log shown that I had hit the target

#### Steps to reproduce

Take two mobs, set one upright, spawn gun, shoot at the other mob.

#### Additional info:

 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2019-06-02
305ffcb7a776050b4cfb7ea4a9d67a8aa3eb0618 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

Still shows attack logs for admins about shooting at targets. 

https://i.imgur.com/3H2DbMP.png

**Comment by Neerti** [comment]
Going to test this now.

**Comment by Neerti** [comment]
Confirmed to still be a bug, going to try to fix it now.
