### ISSUE TITLE
Almost No Security and Medical Record Consoles

### ISSUE THREAD

**Issue by Schnayy** [PolarisSS13/Polaris#6222]
#### Brief description of the issue
Modular(?) consoles were mapped in I think all over the station. It replaced records consoles, but there is no records option on those computers. The same for the air alarm console in the bridge, it only has a station alert option.

Basically the wrong consoles got replaced in the bridge & *almost* all of the records consoles.

Unless I'm somehow blind and missed the records viewing app in the computer.

#### What you expected to happen

The replaced consoles to actually have an accessible option in the computer to fill the previous console's use.

#### What actually happened

The records consoles were replaced instead of the camera consoles, in addition to the atmos computer in the bridge being replaced instead of the station alerts console.

#### Steps to reproduce

Enter the game. Look at the consoles.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

If there is a console option to view these things in the new computers I sure didn't see it.

**Comment by mistyLuminescence** [comment]
If it's anything like the tablets and laptops, you might have to download the apps (but AFAIK there isn't even an app for records viewing? At least, there isn't for tablets).

**Comment by Schnayy** [comment]
That's what I meant. The consoles they were meant to replace that there are apps for were not replaced.

**Comment by Woodratt** [comment]
Fixed
