### ISSUE TITLE
Duct Tape Eye/Mouth Mob Sprites Don't Work

### ISSUE THREAD

**Issue by Sabess** [PolarisSS13/Polaris#623]
Yep. I assume it just doesn't update properly. Duct tape hand cuffs work, though.

**Comment by Zuhayr** [comment]
Sprites are fine, it looks like screen loc isn't set and the icon doesn't update.

**Comment by Zuhayr** [comment]
Confirmed, took it off, put it back on, showed up in the slot and on the mob fine.
