### ISSUE TITLE
EVA and CE Rigs have no overpressure resistance

### ISSUE THREAD

**Issue by zekesulastin** [PolarisSS13/Polaris#6237]
#### Brief description of the issue
The EVA (and CE) rig does not protect against any overpressure.

#### What you expected to happen
The EVA (and CE) rig to provide at least some resistance.

#### What actually happened
Once overpressure occurs, you immediately start taking damage.  I had a red warning before hitting 874 kPa when it should be at least 10x resist.

#### Steps to reproduce
Don EVA rig, release the engine pixies (if it is phoron anyways), get rekt.  I didn't test the CE specifically, but the CE rig wearer in round was also rekt 

#### Additional info:
 - **Server Revision**: 8b14c49d52eb8fcd3aa233d14f3ed1373c7ae610

 - **Anything else you may wish to add**
Really the values for all of them should be higher anyways 1.013 kPa or 2.026 kPa is not all that much even if they weren't broken.

**Comment by Atermonera** [comment]
EVA rig protects up to 10 atmospheres (going a little bit over that didn't trigger the warning, but I didn't test for the precise boundary):
![EVA Rig, <10 atmospheres](https://puu.sh/DLPss/1692cf4401.png)
![EVA Rig, 13-14 atmospheres](https://puu.sh/DLPuT/fcf9ab5d6d.png)
CE rig protects up to 20 atmospheres:
![CE Rig, <10 atmospheres](https://puu.sh/DLPyO/2e1f02f7c7.png)
![CE Rig, ~15 atmospheres)[https://puu.sh/DLPzt/3251ae9863.png]
![CE Rig, >20 atmospheres](https://puu.sh/DLPAi/a01a558c4e.png)

**Comment by zekesulastin** [comment]
I rechecked it on latest and it's working as intended now as far as I can tell.  Didn't check the CE rig, but I'm sure it's the same too.

The protection level should still probably be at least the 15x the regular engineering voidsuit gets given that it and the CE rig are the only pressure suits usable around the engine.  Maybe I'll remember to ask about it next staff meeting.
