### ISSUE TITLE
The ban panel is busted

### ISSUE THREAD

**Issue by Magneld** [PolarisSS13/Polaris#625]
It should look like the below image, this allows us to yknow, ban people.
http://imgur.com/Bb0J3Ga

instead it looks like this (Edited slightly to hide sekrit admin doings) Not very useful image I know but yeah its pretty useless in comparison.
http://imgur.com/qS5GPKM

**Comment by EmperorJon** [comment]
Seems to now be resolved. Was something weird on the server end.
