### ISSUE TITLE
No Sanitising With Papers and Pens

### ISSUE THREAD

**Issue by TheFurryFeline** [PolarisSS13/Polaris#6292]
#### Brief description of the issue
If you don't have a pen in the right hand after writing out a long thing, and then hit OK, all your hard word gets erased to oblivion.

This is more of a proposal to add a confirmation prompt after hitting OK when a pen is NOT in your active hand. 

..... This may or may not be a salt Issue/Suggestion but it'll be useful if/when implemented.

Addendum 14/7/19:  When you type more than the text limit, it doesn't tell you that and wipes whatever's after that point. Another non-sanitised thing discovered today.

**Comment by Nalarac** [comment]
I personally copy everything I have written on a piece of paper before hitting OK so I can immediately re-paste it to another paper if I notice some kind of error in my work, but this would be nice.

**Comment by TheFurryFeline** [comment]
> I personally copy everything I have written on a piece of paper before hitting OK so I can immediately re-paste it to another paper if I notice some kind of error in my work, but this would be nice.

It's easily preventable, yeah, but I was writing out a long-winded thing and neglected to have the pen in the right active slot and all that stuff went poof. Spent four hours on that only for it to be for naught.
