### ISSUE TITLE
Xenobotanists Lack Access to Farmbots

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#6296]
#### Brief description of the issue
Farmbots requires **access_xenobiology** so xenobotanists can unlock them
#### What you expected to happen
To be able to unlock a farmbot as xenobotanist.
#### What actually happened
You are unable you
#### Steps to reproduce
1.) Spawn farmbot
2.) Be Xenobiologist / Xenobotanist
3.) Swipe ID on farmbot
#### Additional info:
 - **Server Revision**: master - 2019-07-05 438e113621ce62899e9d7cb60bb187b30b6fc582 
 - **Anything else you may wish to add** I tried doing this simple fix twice (#6291 & #6288) but Travis hates me for some reason and screams about a completely random file.

**Comment by TheFurryFeline** [comment]
Lemme see if the same thing happens in DM..... Gonna try in your stead.

**Comment by TheFurryFeline** [comment]
No errors appearing when compiled. Testing it now.

**Comment by TheFurryFeline** [comment]
Works fine. Gonna run Travis on my branch before submitting the PR.

**Comment by TheFurryFeline** [comment]
Travis passed and my branch's files for silicon/robot/robot.dm shows the exact same damn snippet that was making it grumble for you. Very odd.... PR going up in a mo.
