### ISSUE TITLE
Cyborgs Can Crawl While Locked Down

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#6307]
#### Brief description of the issue
If a cyborg is locked down (unable to move) it can still crawl around.
#### What you expected to happen
To be stuck in one place
#### What actually happened
I could slowly wiggle my way around
#### Steps to reproduce
1.) Be cyborg
2.) Be locked down
3.) Click+drag yourself onto an adjacent tile and notice you crawl to it
#### Additional info:
 - **Server Revision**: master - 2019-07-15 887804ea10ea399bb464dccb908cbc6dbfa4d377

**Comment by DasIrrlicht** [comment]
Does little to no harm and is actually a nice 'But thou resist' kinda thing.
