### ISSUE TITLE
Xenoarchaeology broken.

### ISSUE THREAD

**Issue by Crackers5** [PolarisSS13/Polaris#631]
Often, the saraspova counter will direct me to an area with no rocks around, or rocks containing no anomalies. This makes finding an actual anomaly difficult, and very annoying.

**Comment by EmperorJon** [comment]
It's suspected that it may be generating caves on the asteroid after the anomalies are being placed.

**Comment by Zuhayr** [comment]
Two solutions:
- Make all the xenoarch digging stuff usable on floors.
- Remove all xenoarch data when the turf becomes a floor.

Which would be preferable?

**Comment by Crackers5** [comment]
I don't know, whichever is better for you.

**Comment by Zuhayr** [comment]
They're both the same amount of work. I don't play xenoarch so I don't know which solution will be more annoying.

**Comment by Crackers5** [comment]
Making equipment usable on floors sound kind of nice, then.
