### ISSUE TITLE
Lethal Turrets not commited to their job.

### ISSUE THREAD

**Issue by DasIrrlicht** [PolarisSS13/Polaris#6318]
#### Brief description of the issue
Lethal turrets do not finish off unconscious players.
#### What you expected to happen
It not going to try an bleed me out, but keeping firing till dead.
#### What actually happened
Only died once I came back to senses and getting shot then.
#### Steps to reproduce
Turn a turret to lethal. Get shot till knocked out. (Maybe Sleep-Verb or chemical-induced sleep, too?) See how the turret retracts, having lost interest in you.
#### Additional info:
 - **Server Revision**: master - 2019-07-15

**Comment by Nalarac** [comment]
If we want to change this behavior, it'd be at these lines.

https://github.com/PolarisSS13/Polaris/blob/801f873d6d71233914d5b046764f12b0ed7983bf/code/game/machinery/portable_turret.dm#L683-L684
