### ISSUE TITLE
Hell-Ramen is death for anyone who drinks it.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#6326]
#### Brief description of the issue
Hell-ramen (hotsauce and ramen) got missed in the body-temp adjust chemical thing. 

#### What you expected to happen
A flavor message.

#### What actually happened
Hell-ramen reagent maxes body temperature in under 5 seconds. From then its about 20 seconds to death, even when taking anti-burn drugs and bandaging.

#### Steps to reproduce
Mix vending machine ramen with hotsauce, to make super-cyanide.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Shadow-Quill** [comment]
Couldn't reproduce. Body temp maxed out at `347.804` for me.

**Comment by zekesulastin** [comment]
Right, ran this since it came up in round again on polcode - tajaran body temp stabilized at 64 C which is quite lethal to them.
