### ISSUE TITLE
turret settings confusing/unrelated to actual targeting

### ISSUE THREAD

**Issue by DasIrrlicht** [PolarisSS13/Polaris#6327]
#### Brief description of the issue
Build a turret and set it to shot 'misc Lifeforms'.
#### What you expected to happen
It going after a mouse, for example.
#### What actually happened
Prometheans are, ID in hand or not, a valid target.
#### Steps to reproduce
Build the usual setup. Test the settings with different targets, ideally a mix of what should be valid and what shouldn't be.
#### Additional info:
 - **Server Revision**: master - 2019-07-21
 - **Anything else you may wish to add** I think everything of the turrets is broken by this point...

**Comment by Nalarac** [comment]
Misc life checks if the creature is small

https://github.com/PolarisSS13/Polaris/blob/00bce77d9cc1db29217c2e55bb3281dcaf12021b/code/game/machinery/portable_turret.dm#L706-L707
