### ISSUE TITLE
Autolathe + partial sheet of metal (from circuit printer) refills infinitely

### ISSUE THREAD

**Issue by Kyoshiku-git** [PolarisSS13/Polaris#6340]
#### Brief description of the issue
Inserting a partial sheet of steel (ex. 0.8 sheets of steel) refills Autolathe with partial steel contents(sheet size x 2000 steel), but does not remove sheet from hand. Can insert infinite times to completely fill autolathe.

#### What you expected to happen
Inserted 0.8 sheets, added 1600(2000*0.8) steel to autolathe, and removed partial steel sheet from hand.

#### What actually happened
Inserted 0.8 sheets, added 1600(2000*0.8) steel to autolathe, and DID NOT remove partial steel sheet from hand.

#### Steps to reproduce
make partial steel sheet by using circuit printer to make a small items, so there is under 9/10 sheets(ex. 7.9), add steel sheets so it creates partial, leaving with partial sheet. Stick sheet in autolathe.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2019-07-21
801f873d6d71233914d5b046764f12b0ed7983bf 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
May work with other devices, such as fabricators? Untested.

**Comment by DasIrrlicht** [comment]
Personally, I just want the circuit printer to be unable to output partial sheets. Would solve the issue on the sideline without needing to check for all the other potential issues it could cause.

**Comment by Kyoshiku-git** [comment]
It doesn't output partial sheets, it loads partial sheets, leaving the last one(s) that didn't fit partial.
