### ISSUE TITLE
Surgery while Suited

### ISSUE THREAD

**Issue by DasIrrlicht** [PolarisSS13/Polaris#6348]
#### Brief description of the issue
One can do Surgery past Space Suits, or at least past Zaddat Shrouds.
#### What you expected to happen
Die a painfull death on a surgery table trying to save me and in turn, getting Robotics-play.
#### What actually happened
Lung mended, no exposure to pressure.
#### Steps to reproduce
Surgery on a Zaddat in Shroud / Person in Suit
#### Additional info:
 - **Server Revision**: master - 2019-07-21
 - **Anything else you may wish to add** Is that a break of contract that Zaddat should expect death?

**Comment by Wickedtemp** [comment]
...I actually think this might be better for gameplay, so Zaddat aren't permanently screwed over the second they take 30 brute damage and end up with a fracture. Being able to operate through the suit, in my opinion, makes more sense from a gameplay perspective than having a species thats basically "if you get hurt you might as well leave the game".

**Comment by DasIrrlicht** [comment]
I actually had a discussion with misty about this thinking of it the same way, but you would lose the main mechanical disadvantage of playing Zaddat: The fact that outside of chemistry, you can do very little in rapid response.

I will spare you my rant about about Zaddat being technological inferior because they have not the capacitys for proper high scale production or safe enviorment for science experiments because hwile other species had their industrial revolution, Zaddat did skip the Nano-Age and likely much of the Digital-Age in favour of homemade postapocalypse and living of Unathi scraps.

I will instead point on the mechanical side of things and balance, as Zaddat are the species which has a odd place.
Most passive forms of getting people damaged will not work on you, for you are unaffected by Space, Toxins in the Air, Illnesses, Cold, and even major dosis of Radiation.
In turn, if someone is out for you in particular, you have under average speed, can take from any weapon enogh damage to get your suit leaking (What, interestingly, is outside of space well survivable for quite a time) and should you ever get stunned, or even just particulary slow react to a pickpoket, your suit could be stolen, throwing you into a frenzy comparable to a freshly spaces spessman of finding a replacement.
You are vurnable. If anything trys to kill you in particular, they have good chances to do so. You are robust. If anything unforseen happens, it is likely to just pass you. Inflatables are your revolting doors because spaced only means that you need to flip a switch on your suit. Breach means that you slip for the initial air floating out, before standing up and returning to do what you do, or maybe even help others out of the breach...

If Chemistry is unable to heal your injuries, they are likely still able to stabalise you while a room gets prepared for surgery. If you need a room quick, turn of lights, suit the Surgeon and drag in a Airpump or any gas-canister and open the value. If that's no option, turn just the lights off and stand next to them with Bicar-Tri, for that will at least slow, any effect.

**Comment by DasIrrlicht** [comment]
tl:dr
Surgery only after preparations, Chemistry is your friend and you are meant to be fragile against direct damage, but robust against things everyone else would find really problematic or at least inconvinient.

**Comment by Neerti** [comment]
Was this fixed by #6667 ?
