### ISSUE TITLE
Pipes not rupturing when over alert/max pressure

### ISSUE THREAD

**Issue by Atermonera** [PolarisSS13/Polaris#6365]
#### Brief description of the issue
Someone reportedly caused the pipes in the engine room to rupture on a phoron setup. However, while testing, Feno, Nal and I were unable to cause pipes to rupture, despite the code indicating that they had three different vars containing failure pressures.
#### What you expected to happen
Filling a simple pipe to over 55atm OR 70atm to make it pop.
#### What actually happened
![testing](https://puu.sh/E04xf/ffd8a2f45c.png)
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Nalarac** [comment]
If this does get fixed, I'd like it if the standard max pressure / alert pressure would be increased as well.

**Comment by Atermonera** [comment]
Discussed at staff meeting, we're not interested in this being corrected, such that pipes could rupture in the normal course of playing the game. However, we are interested in an event (similar to grid check or radstorm) where some number of random pipes break
