### ISSUE TITLE
Emagging the cargo console does not unlock it.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#6369]
#### Brief description of the issue
Emagging the cargo console doesn't let a tator order things unless they are a cargo tech or QM.

#### What you expected to happen
To be able to order all the bad stuff.

#### What actually happened
Loud clicking noises, and no UI.

#### Steps to reproduce
Emag cargo console.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Shadow-Quill** [comment]
Couldn't reproduce with given steps.
