### ISSUE TITLE
Electrified grills no longer check conductivity of the item hitting them.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#6373]
#### Brief description of the issue
Hitting an electrified grill with anything at all, while not wearing gloves, has a very high chance to electrocute you.

(Please don't make glass shards unconductive again, without making them cut your hands when you hit something with them)
#### What you expected to happen
To be able to poke an electrified grill with my insulated plastic stick, and not have my arms melt.

#### What actually happened
Melted arms, no matter what the grill was hit with.

#### Steps to reproduce
Hit electrified grill with almost every weapon in the game.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
I believe this was changed a few months ago such that the default behaviour is for things to be conductive, and they need to be specified as not conductive. So if you could report things that shouldn't be conductive, but are, that'd be useful.

**Comment by FenodyreeAv** [comment]
Uh. Okay. But the list is absolutely huge.
I'll start with stuff in the brig, because I found that breaking out is next to impossible without traitor gear, or help.

- Broken Bottles
- Unbroken Bottles
- Anything made of wood, (inc baseball bats)
- Mops
- Soap
- Books (Nanotrasen Regulatory Compendium)
- Pretty much anything you grow.
- Stunbatons

**Comment by Atermonera** [comment]
The issues reported here were fixed by 6393, further issues should be reported separately
