### ISSUE TITLE
Turrets do not shoot mechs.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#6384]
#### Brief description of the issue
Turrets do not shoot mechs on any setting.

#### What you expected to happen
Turrets to try to pewpew the Durand breaking into the AI core.

#### What actually happened
A peaceful stroll.

#### Steps to reproduce
Walk Mech into AI core with turrets set to lethal.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Nalarac** [comment]
Fixed in #6358
