### ISSUE TITLE
Hardsuit Mounted energy gun cannot go off stun

### ISSUE THREAD

**Issue by Lorwp** [PolarisSS13/Polaris#639]
Whenever i attempt to switch the mode of a Hardsuit mounted energy gun (such as the one on ERT-S hardsuits), it switches the mode twice and forces it to stay on stun.

E.g:
![capture](https://cloud.githubusercontent.com/assets/8052896/11926964/010ee432-a81d-11e5-9367-8e6289b54fab.PNG)

**Comment by Neerti** [comment]
Duplicate of #79
