### ISSUE TITLE
Cloning does not copy identifying_gender or body_descriptors variables to the clone

### ISSUE THREAD

**Issue by Cerebulon** [PolarisSS13/Polaris#6395]
#### Brief description of the issue
When cloning a person, their pronous will resets to the defaults for the 'sex' variable and they will be described as medium build/height, as identifying_gender becomes null, and body_descriptors becomes null.

#### What you expected to happen
Cloned people to retain their gender and build information.

#### What actually happened
Cloned people are reset to the variable defaults for these identifying features.

#### Steps to reproduce
Clone a person with they/them or it pronouns and/or non-default height/weight settings. Examine the corpse, examine the clone, observe differences.
View variables reveals identifying_gender and body_descriptors listed as 'null'

#### Additional info:
 - **Server Revision**: 4e317c5c23fc62709bd0b15c0404ae27205fc9f6
 - I tried to fix this myself but had no idea how to test it with one person since the cloner requires an active mind in the body, but I assume it's simply adding to dna2.dm datum/dna

	var/identifying_gender
	var/list/body_descriptors = list()

and under proc/Clone

	new_dna.identifying_gender=identifying_gender
	new_dna.body_descriptors=body_descriptors.Copy()

Though that may also make some changeling code redundant as changeling code DOES specifically copy the identifying_gender variable.

**Comment by zekesulastin** [comment]
I just cloned someone with a specified identifying_gender and it did not transfer over, leaving the cloned body with a null value.  Server revision: master - 2020-09-02
1a91b1c38044b7e517b0e68e7301200e109f6967
