### ISSUE TITLE
Cannot put down plating on asteroid turf

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#642]
Tacking two bugs on here.

First off we can no longer build on asteroid turf. Can't put down lattices nor plates.Thus we can't patch holes on the deck.

Two, building lattices in space still creates asteroid turf underneath the lattice.

**Comment by EmperorJon** [comment]
The latter point is probably caused by the area around the transfer shuttle still being the old mining area as opposed to space, as this seems to be where it was occurring.
