### ISSUE TITLE
Mass spectrometer does not detect ingested reagents.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#6425]
#### Brief description of the issue
Taking a blood sample does not show what chemicals are acting on a person, if the chemicals were taken as a pill.

This is because there's only 0.1u of a chemical in the bloodstream at any one time, even if the dose is large.

#### What you expected to happen
To know if someone's on drugs with a bloodtest.

#### What actually happened
No trace chemcials detected.

#### Steps to reproduce
Take a blood sample from a guy who just took a pill.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Or perhaps add a stomach pump to sleepers.

**Comment by Wickedtemp** [comment]
...thats already a thing.
