### ISSUE TITLE
Medihud doens't update properly when people die

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#643]
When someone dies you expect the little health bar thingy to go black, like it should, but instead it just stays a flashing dark red.

See: https://i.gyazo.com/a4d0a0305d3ac1cd0f04fdfbee7b1c0a.png

**Comment by zaredman** [comment]
This has been a long-standing issue on BS12-Main (or BS12-Dev) iirc.

**Comment by Neerti** [comment]
Probably a Life() issue.

**Comment by Zuhayr** [comment]
This does not seem to be the case current, reopen if it persists.

**Comment by Yoshax** [comment]
Saw it happen yesterday. I'll test a bit, and see if I can't find the circumstances.

**Comment by Zuhayr** [comment]
If you can find specific repro information that would be good.
