### ISSUE TITLE
Placing Glass Shards In Disposals Hurts You

### ISSUE THREAD

**Issue by Wickedtemp** [PolarisSS13/Polaris#6449]
#### Brief description of the issue
So uh.. The whole 'glass now breaks when you attack someone with it" thing also makes it break and hurt you when you throw it away.

#### What you expected to happen
To be able to throw away trash as usual.

#### What actually happened
Cut and bleeding.

#### Steps to reproduce
See litter, throw it away, get cut for your effort.

#### Additional info:
 - https://gyazo.com/c26d4ec472ed9ba6bcde14ca4a1553f1

**Comment by Atermonera** [comment]
#6418 for reference
