### ISSUE TITLE
Distillery has no Assembly-Sprites

### ISSUE THREAD

**Issue by DasIrrlicht** [PolarisSS13/Polaris#6472]
#### Brief description of the issue
The Chemical Distillery has no sprites during the whole construction.
#### What you expected to happen
Seeing the Frame
#### What actually happened
Invisible Frame I lost until I runned into it as a invisible wall.
#### Steps to reproduce
Make a Frame. Select Distillery from it.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Wickedtemp** [comment]
Distillery in general has a number of issues x.x
