### ISSUE TITLE
Radiation appears to have been weakened severely

### ISSUE THREAD

**Issue by Neerti** [PolarisSS13/Polaris#6488]
#### Brief description of the issue
At some point a few weeks ago, radiation appears to have become a lot weaker in terms of penetrating solid objects. I assume it might be due to #6471 , or something else.

I recall before whatever changed, a standard nitrogen setup for the SM, with the blast doors closed, would result in the whole engine room (the place with the emitter/TEGs/tec) getting low but still dangerous amounts of radiation, and a phoron setup would make a lot of radiation and manage to spread into the monitoring room and possibly the hallway, if lead walls were not used.

Now, the same setup for nitrogen causes the adjacent tiles to the r-wall/blast doors to have very tiny amounts of radiation (so small the geiger counter stays green), and all other tiles to have no radiation at all, making the radiation suit not needed, and possibly makes lead useless for phoron setups (untested).

Phoron setup under the new system remains untested by me, would need someone else to comment for that.

#### What you expected to happen
Radiation range to remain relatively unchanged.

#### What actually happened
Radiation is very weak and the rad suits are essentially optional if you don't stand adjacent to the reactor chamber.

#### Steps to reproduce
Join as Engineer/CE.
Set up the engine, or hit the magic admin button to do it for you.
Get geiger counter, turn it on.
Note how safe the engine room is.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2019-10-18
5c849287c5b268ff243f1556e47629e4875561a1 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
This has been a pretty active back-and-forth between radiation being too powerful and reaching cargo, and it being not powerful enough to pose a risk to engineers, for context.

**Comment by Atermonera** [comment]
After looking properly at the PR neerti mentioned, and doing rudimentary testing, I've determined the cause of this issue. The PR changes the method for determining effective radiation level at a turf by raytracing from the destination back to the source.  And that raytracing uses `get_step_towards()`, and appears to assume that the computed path is effectively straight (i.e., it doesn't clip any tiles by potentially very small margins). And the radiation resistances of blast doors, rwalls, etc., appear to be having far too much of an effect upon the value.

Consider the following example:
![example.png](https://puu.sh/EPZaN/3edc5cc83e.png)

The radiation on the turf of the emitter is 16.98
The radiation on the turf immediately down from the emitter is 0.132
The radiation on the holopad on the right is 4.28

If we close both sets of blast doors, as seen in [this setup](https://puu.sh/EPZjt/b502051e23.png),
then the radiation on the emitter falls to 0.104,
and the radiation on the holopad is 0.
I'll play with the resistances tomorrow and should have some results within the next few days.
