### ISSUE TITLE
Trying to delete my communicator or ID deleted my mob.

### ISSUE THREAD

**Issue by MistakeNot4892** [PolarisSS13/Polaris#649]
I have no idea how to reproduce this.
- Right-click delete on a communicator on the ground with my mob and my ID card: deleted my mob.
- Right-click delete on the communicator with my resulting ghost + ID on the turf: deleted my ghost.
- Moved off the turf, right-click and delete the ID or the communicator: deleted my ghost.
- Right-click deleted a random wheelchair: deleted the wheelchair.

**Comment by Arokha** [comment]
Yeah it does this. I dunno why. Only sometimes, on some IDs. It's ... odd.

**Comment by MarinaGryphon** [comment]
I attempted to point at someone's ID yesterday, and pointed at them instead. I feel like this is a symptom of a larger issue- and despite being year old, it may still exist.

**Comment by Atermonera** [comment]
Still an issue as of Server revision: master - 2018-04-07
4ef644ffb8d69f49172202c1401607833bdfe713

**Comment by Serithi** [comment]
Still an issue as of June 10 2018.

**Comment by Zuhayr** [comment]
thanks byond

**Comment by GeneriedJenelle** [comment]
I believe it's due to the delete proc, I think the delete proc searches by "name" rather than the actual src. 

That's my theory anyhow, haven't looked.
