### ISSUE TITLE
Proposal to substantially rebalance ballistics by introducing shock pain.

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#6496]
#### Brief description of the issue
So, there's always been a problem with weapons in Space Station 13 in that you're constantly fighting this battle between what stops the player most effectively, and it always goes in a never ending circle of nerfs and buffs that are never satisfactory because if you "fix" one you always make the other feel overpowered.

What I mean is this. Guns used to be proper killing tools. Maybe a little too effective. Over time, the damage values got nerfed massively from damage rates of about 60 as with the old revolvers to more "reasonable" values like 20 and 30... to the point where they barely even cause proper bleeding damage. Literally, 9mm ammo sits on such a razor's edge that it just _slightly_ does enough damage to meet a thresh hold to cause bleeding. This nerf was made for a good reason however. It was because once you got shot, you basically stood no chance of survival. That's all well and good.

Then tasers became the new meta. Why? Because guns don't stop a target. Tasers _do_. Tasers would one-shot stun a person and allow you to do whatever the hell you wanted to them, even if you just ran up and beat them with a fire extinguisher. This, again, was nerfed for reasons of "you literally have no chance" so that's reasonable.

But after all that, now you've been stuck in this everlasting awkward dance trying to nerf tasers enough that guns aren't totally inferior, while guns can't be so OP that they just kill you before medical has a chance to do literally anything. Tasers are still the meta because they reliably _stop_ a target more effectively than _the actual guns meant to kill things_.

So I propose a new system. All projectiles, in addition to the damage values they currently inflict, _also_ should inflict an amount of pain from the _shock_ of being shot with a particular bullet or laser. _Certain_ ammunition types would cause more shock damage, such as hollow points. Tasers for instance would be all pain damage as they are currently, and maybe even could afford a little buff in the future, but 9mm and .45 weapons would no longer be **absolutely useless** compared to _everything else_ in the game.

Let's not forget about lasers, also. Lasers for some reason do a _lot_ more damage than any of the pistol caliber weapons. They do more damage because brute, bleeding, and the projectiles getting lodged is a pain to treat. However, ballistics are still over-nerfed in that regard, or lasers are a leftover relic of bygone days when _guns were actually dangerous in SS13._

By giving deadly projectiles an amount of pain to each shot, we introduce two new gameplay styles. One, pain _killers_ are suddenly useful. If you have enough pain killers, you might be a dead man walking after getting pumped full of lead, but it isn't enough to take you down. Two, bullets will actually **stop** a threat after a couple of hits unless they are on space meth.

I am aware that pain is already a mechanic. I am talking pain _on top of_ what pain is already dealt by the game normally. It's called hydrostatic shock. It's what a bullet does when it goes through the watery meaty flesh bag that is a human body.

The end goal being that all ballistic weapons will overall do _generally_ the same amount of _pain_ damage, either through direct brute damage or through the pain of it. I don't need to tell you that a shotgun slug is going to splatter your insides and there's not much a doctor can do, but a pistol is going to put you on the ground almost just as easily, it just might not kill you. I want to replicate that to make guns more dangerous without being more outright _deadly_. This would benefit game balance by allowing developers to fine tweak a gun's stopping power by editing its pain damage without necessarily making it more lethal.

#### Additional info:
 - **Server Revision**: https://github.com/PolarisSS13/Polaris/commit/5aeb868df5f243fecf1f276e6adba5c45cb94bb4

#### Anything more you'd like to add.
Also, shotgun beanbag rounds should again knock you the fuck over, just not long enough to actually arrest you. Just a quick knock-down. Right now, beanbags serve no purpose and are inferior in every way to stun slugs.

**Comment by Woodratt** [comment]
Commenting here to remind myself to bring this up at the staff meeting on Sunday.

**Comment by SpadesNeil** [comment]
It's a pretty dramatic balance change so I understand if they don't want to jump on this idea right away, but I feel like the concept would add a lot more flexibility to how weapons do damage.

I have plans to also change how body armor protects from damage but that is an unrelated issue that I will handle another day.

**Comment by Atermonera** [comment]
@SpadesNeil any updates regarding whether you still want to do this stuff?

**Comment by SpadesNeil** [comment]
For some reason I didn't get an email regarding your reply. Weird.

You can keep it closed, but I wanted you to see it first and get your opinion of it before I start an excruciating amount of work only to possibly have it rejected.
