### ISSUE TITLE
Rock walls can be walked through.

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#65]
Title.

**Comment by Woodratt** [comment]
Neerti?

**Comment by Neerti** [comment]
Was this the white unsimulated walls or normal rock walls?

**Comment by Mark9013100** [comment]
The ones on the colony map. Named 'mask'.

**Comment by Neerti** [comment]
They're placeholders for map generation, that isn't enabled at the moment, soooo.. technically not a bug.
