### ISSUE TITLE
Fingerprints can't be taken from cuffed people.

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#653]
When you try to, it doesn't work, and only gives this message:
X tries to take prints from Y, but they move away.

**Comment by zaredman** [comment]
@Mark9013100 - Most every department I have worked at or had exposure to? You can not fingerprint those who are handcuffed.

I am strongly leaning toward this not being a bug or oversight. Paging @Zuhayr to ask that.

**Comment by Mark9013100** [comment]
As of now, I'm pretty sure it's possible to instantly take fingerprints from people who aren't cuffed.

**Comment by Zuhayr** [comment]
I implemented this as-written from Aurora forensics, which I didn't design, so I don't know if it's intended or not.

**Comment by Mark9013100** [comment]
bump

**Comment by Atermonera** [comment]
[Tested](https://i.imgur.com/vkBQfds.mp4)
