### ISSUE TITLE
MMIs in mechs are blind.

### ISSUE THREAD

**Issue by listerla** [PolarisSS13/Polaris#6546]
#### Brief description of the issue
See title.
#### What you expected to happen
When placed in a mech, I could function as a horrifying bastard.
#### What actually happened
I was blind.
#### Steps to reproduce
1. Die.
2. Have a friend cut your brain out and place it in an MMI. Notice how the MMI is blind, that's good.
3. Have the brain placed in a mech. Everything works, except for your sight. That's bad.
#### Additional info:
 - **Server Revision**: Server revision: master - 2019-11-26 4aecbd344d033a6bcc7535c0eaddf2e2f45d7eb1

**Comment by Nalarac** [comment]
I think the real issue is that the MMI itself is blind when it really shouldn't be

**Comment by Atermonera** [comment]
Reportedly no longer an issue
