### ISSUE TITLE
HoS' Prototype Pistol Issues

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#6568]
#### Brief description of the issue
HoS' pistol is unusable.

- Doesn't spawn with a matter cartridge.
- The firecost is far too high, a capacitor isn't big enough to fire a single shot.
- An advanced capacitor can fire 1 shot.
- A super capacitor can fire 2 shots.
- A hyper capacitor can fire 3 lethal, 4 nonlethal
- Windows take no damage, and are not pierced.
- Walls take no damage, but are pierced.
- Gun does not go into security belt, despite being the right size.

#### What you expected to happen
To be able to fire 5/10 shots non-lethal, lethal respectively, without needing to forage ammo first.

#### What actually happened
Functionally useless, even with precursotech parts, it's worse than an egun.

#### Steps to reproduce
Spawn in as HoS. Attempt to use pistol.
Alternatively, try and capture a Vox using only this gun. Cry.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
No longer an issue, to my knowledge? It's in the process of being rebalanced as it's suddenly seen very frequent use.
