### ISSUE TITLE
Your sprite is stuck in the floating animation sometimes (or maybe always) after leaving space.

### ISSUE THREAD

**Issue by weaversam8** [PolarisSS13/Polaris#657]
On two occasions, I have seen an Engineer go out to wire the solars and then come back in and still look like they're floating (without gravity.) Once it was me, and another time it was another player, so it's not a client side issue. Thoughts?

**Comment by Sydrec** [comment]
Also witnessing this bug; fairly amusing to watch people bob up and down. Probably a state not being set or reversed when people get back on to actual walk-able tiles when magboots aren't needed.

**Comment by SpadesNeil** [comment]
Seeing as this still isn't fixed, why not just disable this feature entirely until it's actually fixed and works correctly? It's obnoxious that this useless little feature--which is bugged--is in the game in the state that it is.
