### ISSUE TITLE
Loadout Medicl Turtleneck and Psychiatrist/Psychologist

### ISSUE THREAD

**Issue by DasIrrlicht** [PolarisSS13/Polaris#6599]
#### Brief description of the issue
Psychiatrist can not get department-turtleneck in th loadout.
#### What you expected to happen
No Medical Turtleneck for Psychiatrist.
#### What actually happened
Loadout gives a clearance to wear a turtleneck to [Psychologist], but the role is called [Psychiatrist].
#### Steps to reproduce
Just check the loadout-page. Using the Psychologist alt-title does not help.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Shadow-Quill** [comment]
Couldn't reproduce.
