### ISSUE TITLE
Roundstart Radiation of Supermatter

### ISSUE THREAD

**Issue by DasIrrlicht** [PolarisSS13/Polaris#6604]
#### Brief description of the issue
Supermatter Radiation at roundstart pierces into maintenance-tunnels, if only weak.
#### What you expected to happen
The SM in its non energised form to be not able to harm crewmembers outsidee of the engineroom.
#### What actually happened
Minimal toxins-damage. (In a 'robust against radiation' suit)
#### Steps to reproduce
Start a round, move into cargo/enginering shared maintenance... Probably disposals-driver, too.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Oh hey I fixed this with my radiation tweaks
