### ISSUE TITLE
Most ghosts lack sprites

### ISSUE THREAD

**Issue by Neerti** [PolarisSS13/Polaris#661]
Upon observing from the lobby, your sprite does not appear.  Ghosting from a mob works as intended.
This did not occur prior to the full body prosthetics change.

**Comment by Zuhayr** [comment]
Probably because your mob is not generated in the same way if you're ghosting.

**Comment by Zuhayr** [comment]
This is pretty odd, it tries to use your preview icon if you are observing. No reason for it to break.
