### ISSUE TITLE
Energy shield sprite is backwards

### ISSUE THREAD

**Issue by SpadesNeil** [PolarisSS13/Polaris#6635]
#### Brief description of the issue
See title. Specifically, the left hand sprite while facing west is backwards.

#### What you expected to happen
This but facing west
![image](https://user-images.githubusercontent.com/6484985/72667070-eaee4800-39e5-11ea-9ea8-f06dcf75dc7a.png)

#### What actually happened
This
![image](https://user-images.githubusercontent.com/6484985/72667060-d14d0080-39e5-11ea-9228-ba165b7786a5.png)

#### Steps to reproduce
1. Obtain energy shield.
2. Place it into left hand.
3. Turn it on.
4. Notice that it has no color, either. Is that a bug too?

#### Additional info:
 - **Server Revision**: https://github.com/VOREStation/VOREStation/commit/ff00f4280fbdbe5faf91b4328669dfdf8e539d11
 - **Anything else you may wish to add:** It doesn't have color. That looks like a bug too.

**Comment by Schnayy** [comment]
Appears to be fixed?
![image](https://user-images.githubusercontent.com/26665154/76834592-75430480-67fb-11ea-8f6d-68ce5c91c692.png)

**Comment by SpadesNeil** [comment]
> Place it into left hand.

**Comment by SpadesNeil** [comment]
The lack of color appears to still be a bug, but is a separate bug from this.
