### ISSUE TITLE
Move gamemode datum onto GLOB

### ISSUE THREAD

**Issue by Atermonera** [PolarisSS13/Polaris#6655]
#### Brief description of the issue
Nefarious geese seeking to edit the round-end text cannot do so. Or other people actually doing official things. The custom event thing isn't really applicable because it's mostly just used as a "heads-up" to people as they join the server, I'm specifically looking to edit game-mode name and round-end text through VV.
#### What you expected to happen
Edit gamemode's round-end display to indicate whatever it is I want them to indicate
#### What actually happened
`master_mode` lives on `/world`, which is sadly out of reach for VV

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - Honk!

**Comment by Amunak** [comment]
You *can* actually edit with VV what you want already, it's just a little more involved:

1. Use `Show-Game-Mode` to display the admin gamemode panel
2. Click the "config name" of the current gamemode, just beyond the "Current mode" name.
3. This opens VV for the current gamemode. What you want to change here is `name` and the two descriptions.
4. Profit!!!

## Some screenshots
![dreamseeker_2020-01-29_18-51-49](https://user-images.githubusercontent.com/781546/73383513-c50c5180-42c9-11ea-8595-a58638c016f1.png)
![dreamseeker_2020-01-29_18-58-59](https://user-images.githubusercontent.com/781546/73383518-c63d7e80-42c9-11ea-9f46-c0fe8b51ffbf.png)

**Comment by Atermonera** [comment]
Alas, such buttons are beyond the reach of the lone pure dev
