### ISSUE TITLE
[Master] Full Body Prosthetic Damage Readout

### ISSUE THREAD

**Issue by ParadoxSpace** [PolarisSS13/Polaris#666]
I honestly have no idea what this is.
http://puu.sh/m7ExF/7dd953ff1b.png

**Comment by SparklySheep** [comment]
Happens with burn damage. Doesn't occur with brute.

**Comment by Anewbe** [comment]
I've gotten it from brute, too.

**Comment by ParadoxSpace** [comment]
This still happens

**Comment by Atermonera** [comment]
Puush has expired so there's no way for me to know what this is describing.
