### ISSUE TITLE
Cargo Console Order Bug

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#6663]
#### Brief description of the issue

Cannot order any items off of the cargo console after a gridcheck

#### What you expected to happen

To be able to order items after a gridcheck

#### What actually happened

Was unable to order any items off of the cargo console after the gridcheck passed. 

#### Steps to reproduce

Trigger a gridcheck, let it pass normally, attempt to order a supermatter crate or other crate.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Attempting to order an item without giving a reason will fail silently, which is a bug that I can fix, but following a grid check, I was able to request and approve orders on both the ordering and main cargo consoles.
