### ISSUE TITLE
Promethean Xenobiology is broken... Again

### ISSUE THREAD

**Issue by Dunmeritude** [PolarisSS13/Polaris#6680]
#### Brief description of the issue
Xenobiology for Prometheans is broken again. Disciplining a slime as a goop xenobio will cause them to grudge you forever, and ever, and ever. 

#### What you expected to happen
To have to wrongfully shoot a slime a few times before it hated me

#### What actually happened
One stray shot racewarred an entire pen against me, permanently

#### Steps to reproduce
Be prommie, be xenobio, shoot a slime, die

#### Additional info:
 - **Server Revision**: master - 2020-02-05
8df858659c1fd2ad57df36b431956cf64b2ad693

**Comment by Atermonera** [comment]
Seems to be intentional from #6128?

**Comment by Schnayy** [comment]
No, not intentional, confirmed by mechoid. It shouldn't hate you from a regular discipline.

**Comment by Dunmeritude** [comment]
but its not like anyone actually plays promethean xenobiology anymore am i right?
