### ISSUE TITLE
Circuit brains turn into real brains.

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#669]
When a drone is blown, it drops a circuit brain. After a moment, it turns into a fleshy brain somehow.

**Comment by Arokha** [comment]
Appears to work as it should on current code.
Destroying cyborgs with "Cyborg" title drops MMI'd brain. Destroying cyborgs with "Robot" title drops posibrain. Doesn't seem to change after any time.

**Comment by PsiOmegaDelta** [comment]
Could have been the "Click posibrain/robocircuit to pop out brain bug". Recently fixed on Bay.
