### ISSUE TITLE
DJOutpost1 Odysseus mob wrong faction

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#6716]
#### Brief description of the issue
The drones kill the Autonomous Odysseus at roundstart whenever this pOI spawns.

#### What you expected to happen
The mech to live

#### What actually happened
Drones to murder the hell out of it

#### Steps to reproduce
Spawn DJOutpost1

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
DJOutpost[1-4] don't have any autonomous odysseus mechs. Or if they are they aren't pathed with "ody" (did ctrl-f for that on each map with a text editor)
