### ISSUE TITLE
Admin rightclick deletion and '

### ISSUE THREAD

**Issue by Verkister** [PolarisSS13/Polaris#6724]
#### Brief description of the issue
Trying to right click delete an item with a ' in it's name deletes any mob named like the part of the item's name before the '

#### What you expected to happen
The item itself to be deleted.

#### What actually happened
Attempting to delete the item named "Red's sword" deleted it's owner instead. Multiple times, and never actually deleting the item itself.

#### Steps to reproduce
- (Step 1) Create an item named "Something's something"
- (Step 2) Create a mob named "Something"
- (Step 3) Right click and try to delete the item.
- (Step 4) Watch each attempt delete any mob named "Something" from anywhere in the world before ever getting to delete the item itself.

#### Additional info:
 - **Server Revision**: Current one (downstream)
 - **Anything else you may wish to add** Doesn't really affect regular players unless the bug deletes something affecting them.

**Comment by Neerti** [comment]
That explains that weird bug with deleting PDAs.

**Comment by Atermonera** [comment]
(Could not reproduce)[https://puu.sh/FhweM/f2f9cb06b5.mp4]
(Twice)[https://puu.sh/FhweM/f2f9cb06b5.mp4]
