### ISSUE TITLE
Rigsuit surgical removal is fucked all the way up

### ISSUE THREAD

**Issue by Dunmeritude** [PolarisSS13/Polaris#6739]
#### Brief description of the issue
When you saw off a rigsuit and remove it, it only removes the control panel- not the associated rig parts, like chestpiece, boots, etc, which become irreparably stuck to the player they were on

#### What you expected to happen
for the rigsuit to come off in one piece

#### What actually happened
Molly Highlander became one with the AMI, permanently

#### Steps to reproduce
- Surgically saw off a RIG
- Attempt to remove
- watch as the control module comes off, but everything else remains on the player

#### Additional info:
 - **Server Revision**: master - 2020-02-23
2bea80895de462c4dcbe8796b37fdc4d1d800c33 

 - **Anything else you may wish to add** She was handcuffed if that has anything to do with it, and there was a pAI in the intellicard thingy jack

**Comment by Nalarac** [comment]
Was the rig out of power when you attempted removal? If it was, then it was because of this bug: #4544

**Comment by Dunmeritude** [comment]
> 
> 
> Was the rig out of power when you attempted removal? If it was, then it was because of this bug: #4544

It may have been, but #4544 dictates that the power cell needs to be REMOVED;
> "3.) Remove power cell to kill power (Having a dead power cell instead makes no difference)"

**Comment by Nalarac** [comment]
That line specifically states that the cell doesn't need to be removed if it's dead (i.e. no power). I probably could have worded it better when I wrote the bug report 2 years ago.
