### ISSUE TITLE
Move the arrivals shuttle to the unused hanger to mitigate getting stuck when the power is out.

### ISSUE THREAD

**Issue by zylowalsh** [PolarisSS13/Polaris#6741]
Move the arrivals shuttle to the unused hanger to mitigate getting stuck when the power is out.  

Server revision: master - 2020-02-22

**Comment by Schnayy** [comment]
Hangar 3 is used for event purposes, as well as the arrival shuttle doors always being powered. Once you're inside, you just need a crowbar, which are in emergency lockers. The transfer shuttle doesn't function this way, but there are other ways to leave the round.
