### ISSUE TITLE
It is still possible to var-edit bound_x/y

### ISSUE THREAD

**Issue by Neerti** [PolarisSS13/Polaris#6759]
#### Brief description of the issue
An event manager var-edited `bound_x` on a mob, and this broke the movement animation byond does.

#### What you expected to happen
For unsafe variables like `bound_x` to not be visible, or at least be read-only, in VV, as we now have the ability to do that.

#### What actually happened
VV allowed someone to break movement for the whole round by modifying an unsafe variable. Because of BYOND, the movement breakage is not able to be fixed without a restart.

#### Steps to reproduce
Spawn any atom of your choice.
Open VV on it.
Look for bound_x/y.
Edit it.
Observe movement breaking because byond thinks the server is using pixel movement.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2020-02-25
d079fc6329e15f205e4574b562d01d5193380e2f 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
I'm not sure if `step_x/y` edits are blocked or not, but they will also break movement.

**Comment by Neerti** [comment]
Ater tells me there's already code to stop this from happening, so it seems that's broken now.

**Comment by Leshana** [comment]
> Ater tells me there's already code to stop this from happening, so it seems that's broken now.

That is correct, the code that is supposed to stop this is broken, but it is an easy fix.  It is on *atoms_movable.dm:47*
