### ISSUE TITLE
hotkey for toggling aim no longer works

### ISSUE THREAD

**Issue by Hubblenaut** [PolarisSS13/Polaris#676]
The verb the hotbutton was linked to is no longer there. Needs relinked

**Comment by Zuhayr** [comment]
What is a hotbutton? The verb was removed because it was pointless.

**Comment by Hubblenaut** [comment]
hotkey*

**Comment by Zuhayr** [comment]
What is the hotkey, exactly, not seeing it in the skin file.

**Comment by Nalarac** [comment]
In hotkey mode, you can press the letter J to use the verb toggle-gun-mode, but it shows up as an unrecognized or inaccessible verb.
