### ISSUE TITLE
Brain Mechs Can't Fire Projectiles

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#6764]
#### Brief description of the issue
When attempting to shoot a mech mounted gun (e.g. phase-emitter), the projectile will either not actually fire (if it's a beam) or simply sit on the ground and can hit things if they walk into it (phase bolt)
#### What you expected to happen
The brain mech to be able to fire projectiles like normal people in mechs.
#### What actually happened
The projectile was on the floor or didn't appear.
#### Steps to reproduce
1.) Put drone circuit into ripley
2.) Attach phase-emitter to ripley
3.) Attempt to fire at an object
4.) Move tile and notice projectile on floor.
#### Additional info:
 - **Server Revision**: master - 2020-02-25 d079fc6329e15f205e4574b562d01d5193380e2f

**Comment by Nalarac** [comment]
Fixed by #6765

**Comment by Atermonera** [comment]
Not fixed until #6765 is actually merged
