### ISSUE TITLE
Beepsky doesn't like white canes

### ISSUE THREAD

**Issue by Greenjoe12345** [PolarisSS13/Polaris#6782]
#### Brief description of the issue
Beepsky attacked me when I was holding a telescopic white cane

#### What you expected to happen
for him to not do that

#### What actually happened
Beepsky attacked a poor visually impaired Teshari

#### Steps to reproduce
get a telescopic white cane
find beepsky
see him attack

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by TheFurryFeline** [comment]
This sounds like it considered the cane to be an unauthorised weapon. 🤔

**Comment by TheFurryFeline** [comment]
`/mob/living/bot/secbot/proc/check_threat(var/mob/living/M)
	if(!M || !istype(M) || M.stat == DEAD || src == M)
		threat = 0

	else if(emagged && !M.incapacitated()) //check incapacitated so emagged secbots don't keep attacking the same target forever
		threat = 10

	else
		threat = M.assess_perp(access_scanner, 0, idcheck, check_records, check_arrest) // Set base threat level
		if(attacked)
			threat += SECBOT_THREAT_ATTACK // Increase enough so we can attack immediately in return
`
Not sure if you can add an exception now that I've looked into secbot code and idcheck. May need to repath it to fix the issue.

**Comment by Atermonera** [comment]
It's specifically this line and an associated line for the right hand that're looking for melee weapons
https://github.com/PolarisSS13/Polaris/blob/0021a3b0252ad45fed8be76917805f21a331cdd7/code/modules/mob/mob_helpers.dm#L530

Which is interesting, because I definitely didn't know about that when I pathed umbrellas as melee weapons once upon a forever ago

**Comment by TheFurryFeline** [comment]
Yeah, that looks like our culprit

**Comment by TheFurryFeline** [comment]
Could probably make a line and add a return that makes Beepsky not react to the item.

**Comment by Atermonera** [comment]
Or I can just repath them to not be melee weapons, and instead be a subtype of canes (which I probably commented on wanting that in the first place, or if not I distinctly remember wanting to)

**Comment by TheFurryFeline** [comment]
Sounds good.
