### ISSUE TITLE
Grabbing prone bodies as shields

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#682]
Seen it happen in a couple rounds now. Someone grabs a prone body that is either in crit or dead and drags it around with them and it works as a shield verses ranged attacks, no matter what side of the body the person is on, the majority of the shots directed at the person that has the body grabbed results in the shots hitting the prone corpse and or critical person.

**Comment by Zuhayr** [comment]
This is due to the neck grab forcing the person prone I believe. If you want a human shield you will always force them prone, irrespective of anything else, so it doesn't check for them being prone before applying the defense.

Code is a mess, not really familiar with how this would be fixed.
