### ISSUE TITLE
Runtime: Welding walls plays sound in an area.

### ISSUE THREAD

**Issue by Neerti** [PolarisSS13/Polaris#6827]
#### Brief description of the issue
I was shooting guns on the test map to test something, when I noticed the wall was damaged. Not wanting to space myself, I spawned a welder and fixed it, but got a runtime when I did.

#### What you expected to happen
No runtimes to happen.

#### What actually happened
```
[2020-03-13T03:28:40] Runtime in code/game/sound.dm,3: playsound(): source is an area
  usr: (the floor) (10,14,1) (/turf/simulated/floor/tiled/dark) (neerti)
  usr.loc: (the floor) (10,14,1) (/turf/simulated/floor/tiled/dark) (neerti)
```
#### Steps to reproduce
Damage a wall through some means, like shooting it.
Use a welder on it.
Get runtime.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2020-03-13
0021a3b0252ad45fed8be76917805f21a331cdd7 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
This happened on the test map but it shouldn't matter.
It's probably a `loc` somewhere where it shouldn't be in the playsound proc for when walls get repaired.

**Comment by TheFurryFeline** [comment]
Bruh, this has been a runtime for at least a year or two.
