### ISSUE TITLE
Size traits affecting Teshari speed (and possibly Tajaran?)

### ISSUE THREAD

**Issue by Dunmeritude** [PolarisSS13/Polaris#6836]
#### Brief description of the issue
Broad-Shouldered trait appears to negate Teshari running speed entirely, and I have a feeling that much like the leg actuators on a RIG, that the slowdown speed SETS someone's running speed, rather than modifying it. 

#### What you expected to happen
For the trait affecting a character's run speed to slow them down based on what they already have, not from a set amount. I expected to still be around Human speed, rather than Teshari Zoomspeed, but.... 

#### What actually happened
I moved like a fucking tree. 

#### Steps to reproduce
1: Be a teshari or a tajara
2: Be broad-shouldered or heavily-built
3: Move like molasses instead of closer to a reasonable human speed

#### Additional info:
 - **Server Revision**: master - 2020-03-13
4d6156d5586a073b47490e744ee9f193e4278816

**Comment by Atermonera** [comment]
Tested with the fat trait (broad-shouldered), move_speed (while actively moving, that appears to be necessary to get an accurate value in that var for some reason) went from ~2.3 to ~3.4 for a human, and from ~1.1 to ~2.2 for teshari (i.e., ~human speed). The fat and obese traits add 1.1 and 1.2 slowdown, and given the method by which movement speed is calculating (summing a whole bunch of potential factors) I'm not sure a multiplicative modifier would be feasible. This appears to be working as intended, unless you want to bring it up at a staff meeting.
