### ISSUE TITLE
MMIs and Posibrains in elevator inventory

### ISSUE THREAD

**Issue by Toranagasama** [PolarisSS13/Polaris#684]
After a full body prosthetic crew member enters an elevator, you can retrieve their brain equivalent from the storage.

**Comment by PsiOmegaDelta** [comment]
That's going to be a tricky one, since this was originally done deliberately to prevent roboticists from bringing the research posibrain with them.

**Comment by Zuhayr** [comment]
I fixed this, has it not gone live?

**Comment by Zuhayr** [comment]
Still happening despite fix.

**Comment by Yoshax** [comment]
Fixed in https://github.com/PolarisSS13/Polaris/commit/3198191ae3ed2af4673a8f226f354a1350ab37fe
