### ISSUE TITLE
Unable to build computers on wooden floors

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#686]
Engineer tested this earlier today, something occurs when attempting to secure a computer to a tile that has wooden floor tiles on it. The end result being that the computer could not be secured to the wooden floor and thus was unable to be built.

**Comment by Zuhayr** [comment]
'something happens' is not informative. Please supply more information.

**Comment by Woodratt** [comment]
"The end result being that the computer could not be secured to the wooden floor and thus was unable to be built."

**Comment by Zuhayr** [comment]
What I'm asking is precise reproduction steps.Are you specifically referring to not being able to wrench it down?

**Comment by SinTwo** [comment]
I believe that is what he is saying, yes.
