### ISSUE TITLE
Missing or Hidden Sprites for gloves

### ISSUE THREAD

**Issue by Jamini** [PolarisSS13/Polaris#6868]
#### Brief description of the issue

Glove items are missing or hidden on the in-game sprite.

![Screenshot_20200317_161553](https://user-images.githubusercontent.com/1775680/76897837-e077ef80-686a-11ea-9b43-00b2ec2c9333.png)

#### What you expected to happen

Gloves visible on my mob when I am wearing gloves.

#### What actually happened

My hands have invisible, super-gloves that I can totally use now to destroy the universe.

#### Steps to reproduce

Step 1. Acquire Gloves
Step 2. Equip Gloves
Step 3. Revel in your naked hands through your invisible gloves.

#### Additional info:
 - **Server Revision**: 
master - 2020-03-17
88bd01c27152fce06854b308db15a268d8453629 
 - **Anything else you may wish to add**
Worked Yesterday, but there was an update last night.
I am on Linux, so it may be a Linux thing. Non-Linux players should confirm.

**Comment by Dunmeritude** [comment]
Non-linux player confirming, it's also latex gloves and all others.
