### ISSUE TITLE
I'm tired of these motherf*cking ghost ships on my motherf*cking station!

### ISSUE THREAD

**Issue by Dunmeritude** [PolarisSS13/Polaris#6919]
#### Brief description of the issue
The Savings and Values ship, which notably got BTFO a while ago, seems to be making its rounds on the telecomms announcer still. 

#### What you expected to happen
For the S&V to rest in peace

#### What actually happened
GHOST SHIP TIME BABY!
![image](https://user-images.githubusercontent.com/9397405/77840838-6257fa80-7140-11ea-9b47-c25b37f830c5.png)

#### Steps to reproduce
Sit around for long enough for the random traffic control to bring up the MTV S&V, have a heart attack

#### Additional info:
 - **Server Revision**: master - 2020-03-25
630a46d490d362e0a43a1eb402716a31818168bf 

 - **Anything else you may wish to add** RIP S&V crew

**Comment by Atermonera** [comment]
I'm not aware of any canon events involving a morpheus ship being blown up, particularly one using one of the randomly-selected names.

**Comment by Dunmeritude** [comment]
whatever
