### ISSUE TITLE
Synthetic heads cannot be changed like other limbs 

### ISSUE THREAD

**Issue by Minijar** [PolarisSS13/Polaris#693]
They also get stuck once you've set your torso option, never changing again after you've selected a torso brand.

**Comment by Mark9013100** [comment]
I'm pretty sure this is intentional.

**Comment by Minijar** [comment]
I mean, by default the first torso you choose IE Bishop will lock your head to a bishop model, and thus results in you having a bishop head no matter the torso you choose thereafter.

**Comment by PsiOmegaDelta** [comment]
The only way I've found as a workaround is to use the full limb reset option, then you can select a new variant again.
