### ISSUE TITLE
Skin tone modification gives value to result at 35 upon edit

### ISSUE THREAD

**Issue by sabiram** [PolarisSS13/Polaris#695]
For example: skin tone of 70. Click to edit, and highlighted value is -35. Skin tone of 1 gives value of 34. 220 gives value of -185.

220 - 185, 70 - 35 and 1 + 34 all equal 35, the default value on blank slots.

Works as normal otherwise. Potentially intentional? Expected behavior would be to retain the previously entered value.

**Comment by Zuhayr** [comment]
Skin tone is a range from a negative value to a positive offset to appear only positive afaik. This is most likely intentional.

**Comment by GinjaNinja32** [comment]
Skin tone goes backwards iirc, the problem here is that it's keeping the backwards value as the default for the edit box.

**Comment by PsiOmegaDelta** [comment]
I think the issue is that Polaris is missing a Bay-tweak/correction in the character setup. When editing, the value that is normally subtracted from the entered skin value tone is added to the current one, before displaying it to the user.

**Comment by GinjaNinja32** [comment]
IIRC the actual value that's displayed normally is `35 - s_tone`, or equivalently `s_tone = 35 - input`
