### ISSUE TITLE
IV Drips have no effect

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#696]
When attempting to give someone blood via an IV drip, it will have no effect on the patient, it won't raise their blood level and admin intervention is required.
Zuhayr said this might be due to a container rewrite back on Bay.
Steps to reproduce:
1. Get someone with a low blood level.
2. Grab a IV drip and place a blood bag in it.
3. Attach the IV to the patient.

**Comment by Zuhayr** [comment]
They move the blood into the ingested reagent container.

**Comment by Mark9013100** [comment]
In simple terms?

**Comment by Neerti** [comment]
The game's thinking the person's drinking all the blood instead of going into the bloodstream.

**Comment by Mark9013100** [comment]
:V

**Comment by NortonDK** [comment]
I worked with it the other day, it does not have any trouble taking blood, only giving

**Comment by Woodratt** [comment]
Seems like the same thing happens when you inject someone with blood via a needle. On the whole it appears to have made virology impossible to do, as you cannot inject the monkeys with contaminated blood in order to get antibodies.
