### ISSUE TITLE
Central Command Update Shows Twice Per Message

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#6961]
#### Brief description of the issue
![image](https://user-images.githubusercontent.com/8042031/78461479-e7866680-768e-11ea-9d64-80cec18ac452.png)

#### What you expected to happen
Only one line of Central Command Update
#### What actually happened
Two Lines
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Shadow-Quill** [comment]
Cannot reproduce on latest master.
Someone must have manually typed in 'Central Command Update' for the report of the title, otherwise it would have showed as:
![image](https://user-images.githubusercontent.com/44811257/79944397-088ddc00-8431-11ea-9d29-6d0620d05b9c.png)
