### ISSUE TITLE
Don't Receive In-Chat Button For Vote

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#6963]
#### Brief description of the issue
https://gyazo.com/3b4e65f19be55a8010708c414a453f0f
#### What you expected to happen
To receive an option to vote in chat instead of going to the verb itself.
#### What actually happened
I had to go to the verb in the OOC tab (or type it out)
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Shadow-Quill** [comment]
Can't seem to replicate, latest master on testing server.
![image](https://user-images.githubusercontent.com/44811257/79941439-e9d81700-8429-11ea-9256-ae3a9f8a5abc.png)
