### ISSUE TITLE
Chief medical officer's office privacy shutters are useless because there is a glass door.

### ISSUE THREAD

**Issue by sabiram** [PolarisSS13/Polaris#702]

**Comment by Rowtree** [comment]
same with chaplain's office

**Comment by Woodratt** [comment]
Not a bug, working as intended. You see someone snooping about your door when you're having a private conversation you tell them to buzz off.

**Comment by sabiram** [comment]
It seems very silly to install privacy shutters in a room with a giant window that isn't obscured when the shutters are down.

**Comment by Minijar** [comment]
Gotta agree, just slap the windowless door down instead.
