### ISSUE TITLE
Welding Eye Trauma Inconsistency

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#704]
Fixing superficial dents on a prosthetic with a welder will yield no eye trauma. Robo-surgery with a welder does yield eye trauma, so this became apparent to me.

**Comment by Zuhayr** [comment]
Misread reffed PR.

**Comment by Nalarac** [comment]
Tested on: master - 2017-12-08 11757132352255fa88f0d06597edcb4efa816fa7 

This is no longer an issue.
