### ISSUE TITLE
Viruses can not infect new monkey mobs.

### ISSUE THREAD

**Issue by Jakksergal** [PolarisSS13/Polaris#706]
As the title says. This makes curing viruses impossible without killing an infected human as you can't infect a monkey to create antigens.

**Comment by Datraen** [comment]
See comments on #696.

**Comment by EmperorJon** [comment]
Can you confirm that the issue here was no infection occurring when injecting infected blood?

**Comment by Datraen** [comment]
Not really a duplicate bug report, but likely related to #696. Needs testing on new code.

**Comment by Datraen** [comment]
Had it work recently, closing.
