### ISSUE TITLE
Virology splicer computer not updated to the new virus code.

### ISSUE THREAD

**Issue by Jakksergal** [PolarisSS13/Polaris#707]
The old code would only have certain symptoms in only one stage of a virus, the new code is that any symptom can occur in any stage of the virus. However, the splicer computer will automatically move a symptom to what stage it would have been if we didn't have the new system.

i.e. Splicing off "Waiting Syndrome" on stage 4 will result in the same symptom on stage 1.

**Comment by Mark9013100** [comment]
Virology is going the way of genetics, so at this point it might as well be unmapped.

**Comment by NortonDK** [comment]
Mark9013100 how do you know that?

**Comment by GinjaNinja32** [comment]
I made this work when I adjusted the viruses to work in any position, so this isn't a case of not being updated, but of breaking afterwards.

**Comment by Mark9013100** [comment]
@NortonDK The RNG virology events have been disabled. So I don't really see the use for it anymore.

**Comment by Jakksergal** [comment]
@Mark9013100 RNG virology is disabled because virology is broken. Viruses are incurable.

**Comment by Zuhayr** [comment]
RNG virology is disabled because viruses are shit, not due to bugs.

**Comment by GinjaNinja32** [comment]
Behaving as expected. It'll give you a lower-stage disk, which you can then splice in at any equal-or-higher stage. Splicing off Waiting Syndrome from stage 4 will result in a stage 1 disk that can be spliced in at any position.
