### ISSUE TITLE
Holodeck chromic windows don't all work

### ISSUE THREAD

**Issue by BillyBangles** [PolarisSS13/Polaris#7140]
#### Brief description of the issue
Only two out of the six sets of electrochromic windows on the holodeck actually tint when you hit the switch.

#### What you expected to happen
All the windows to tint, or at least the ones along the maint hallway.

#### What actually happened
![not all windows tinted](https://puu.sh/FIPuQ/7e12f16024.png)

#### Steps to reproduce
1. Enter holodeck
2. Hit window tint switch
3. Cry 

#### Additional info:
 - **Server Revision**: master - 2020-05-06 
 - **Anything else you may wish to add**: If I had to guess, it's because not all the windows are set to the correct tag that the switch is set to.

**Comment by TheFurryFeline** [comment]
Map issue. Set the button's range var to 14 in the map editor.
