### ISSUE TITLE
Terminal Layering Issue

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#715]
http://i.imgur.com/ld8soZg.png

Basically if one takes up a floor tile and then puts it down again.

**Comment by Zuhayr** [comment]
Not sure why this is happening, the relevant code looks fine.

**Comment by PsiOmegaDelta** [comment]
I apparently fixed terminals not layering properly here, https://github.com/Baystation12/Baystation12/pull/11588, but I don't really see how.
