### ISSUE TITLE
Hybrid Tools are worse than useless

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#7169]
#### Brief description of the issue
Hybrid tools do not work at range in several cases. Including windows and walls, the two main things they're used for.

The radiation makes them uselss unless you're in a 100% radproof suit. There are only 2 of these in the game.

They do not perform the action when they malfunction. This happens often enough that you miss a step and waste time.

When the screwdriver malfunctions, it does not act as a screwdriver when interacting with things like autolathes. This means the Autolathe will eat your super expensive high tech screwdriver.

#### What you expected to happen
The most high tech expensive precursotech tools available to be better than basic toolbox stuff.

#### What actually happened
Got mad after I lost my screwdriver and murdered myself.

#### Steps to reproduce
Attempt to use Hybrid tools.

#### Additional info:
 - **Server Revision**: Server revision: master - 2020-05-12
eb8ad5791793b697492e9d6dd6382ac900f369c9

**Comment by lolman360** [comment]
#7172
