### ISSUE TITLE
Intercoms non-functional

### ISSUE THREAD

**Issue by PsiOmegaDelta** [PolarisSS13/Polaris#718]
Haven't seen any code changes to cause this, but I've had this problem 2 rounds in a row (the rounds themselves non-consecutive).

**How to reproduce**
* Be a station AI.
* Attempt to use intercoms.
* Realize that your speech isn't picked up, nor is anyone else's. Headsets is all that seem to work.

**Comment by Neerti** [comment]
Did some live testing and it appears to just be another ```show_message``` problem, which is easy enough to fix.
