### ISSUE TITLE
Disappearing Chemistry Grenades

### ISSUE THREAD

**Issue by InvisPinkUnicorn** [PolarisSS13/Polaris#720]
Chemistry grenades on a signal trigger disappear from containers spontaneously. This has happened to me three times so far- twice with grenades that were not armed in a backpack, and once with one that had been armed and was in a toolbox.

If it matters, two of them were 120/120 potassium/water, and the third was 60/60 potassium/water.

**Comment by Zuhayr** [comment]
Looks like a qdel() issue.

**Comment by FenodyreeAv** [comment]
Tested with potassium and water, and nitroglycerin. Neither caused an explosion.

**Comment by FenodyreeAv** [comment]
Mixing it in a beaker also just deleted the beaker, not creating anything.
Injecting all the components into a mob causes an explosion.
