### ISSUE TITLE
Cannot mismatch manufacturers on FBP limbs

### ISSUE THREAD

**Issue by InvisPinkUnicorn** [PolarisSS13/Polaris#721]
When creating a full-body prosthetic character, you can change the brands of their limbs as normal, and the different brands' sprites appear properly in the Character Creator window. However, upon actually spawning in, all limbs will be changed to match the brand of the head/torso. This significantly limits one's ability to customize an FBP's appearance.

Tested with multiple torso/head brands; all of them show the same effect.

**Comment by Zuhayr** [comment]
This might be due to the torso being applied first and then robotizing all children, which would cause later robotize procs to fail.

**Comment by GinjaNinja32** [comment]
I assume this was fixed? A link from here to the fix or the fix to here would be nice.

**Comment by GinjaNinja32** [comment]
looks like #731 was the fix

**Comment by Zuhayr** [comment]
Apologies, I closed a bunch without reffing.
