### ISSUE TITLE
oil stained clothes icon is bugged

### ISSUE THREAD

**Issue by Greenjoe12345** [PolarisSS13/Polaris#7234]
#### Brief description of the issue
![image](https://user-images.githubusercontent.com/33647525/82742891-5319b580-9d5b-11ea-9cf1-2cdcf0ef0f0c.png)

#### What you expected to happen
for the oil to be on the shoes and not all over the icon

#### Steps to reproduce
make some clothes oil-stained

**Comment by Cerebulon** [comment]
Almost certainly a result of #7179 ?
