### ISSUE TITLE
Hybrid Tools still irradiate you horribly

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#7250]
#### Brief description of the issue
Hybrid Tools are one of the most expensive, difficult to get things in R&D. Recently they were made so they wouldn't kill you with use.

Didn't work, radiation still occurs.

#### What you expected to happen
My tools to not kill me and everyoen near me.

#### What actually happened
Spam clicked a Crowbar on a Sleeper, the ensuing radiation killed the monkey in the sleeper and the HOS standing 2 tiles away.

#### Steps to reproduce
Spam click a Hybrid Crowbar.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by lolman360** [comment]
has the server been updated since the PR was merged?

**Comment by FenodyreeAv** [comment]
Correction, it's the crowbar, not the screwdriver.
