### ISSUE TITLE
table sprites do not update properly

### ISSUE THREAD

**Issue by Greenjoe12345** [PolarisSS13/Polaris#7260]
#### Brief description of the issue
when building or deconstructing a table, the sprites don't update properly
#### What you expected to happen
for the sprites to update properly
#### What actually happened
![image](https://user-images.githubusercontent.com/33647525/83205574-d44fbe80-a146-11ea-88c7-79d936d7405c.png)
![image](https://user-images.githubusercontent.com/33647525/83205603-ef223300-a146-11ea-8d3f-790017c27f39.png)
#### Steps to reproduce
build or deconstruct a table

**Comment by Greenjoe12345** [comment]
![image](https://user-images.githubusercontent.com/33647525/83340619-56b8b980-a2d2-11ea-8efc-deb1cd851b94.png)
seems walls have the issue too

**Comment by Atermonera** [comment]
#7363
