### ISSUE TITLE
Confusion Has No Status Icon

### ISSUE THREAD

**Issue by KillianKirilenko** [PolarisSS13/Polaris#7272]
#### Brief description of the issue
With the screen alerts that @Arokha ported, many status effects (such as blind and buckled) have their own icons. Confusion (the state where you move in random directions instead of the ones you input and will fall over if you run into something) doesn't.

#### What you expected to happen
Have an icon on my HUD top right that showed when I was Confused.

#### What actually happened
There was no icon, so I had no idea how long it lasted.

#### Steps to reproduce
1) Get confused.
2) Behold lack of icon.
3) Be confused about how long confusion is lasting, then accidentally run into a table at the last second and bruise your shin.

#### Additional info:
 - **Server Revision**: Current, probably? This came up in local tests in a fork that's up to date with the master branch.

**Comment by Atermonera** [comment]
#7354
