### ISSUE TITLE
Clicking a poster multiple times allows you to rip it multiple times.

### ISSUE THREAD

**Issue by Spacemanspark** [PolarisSS13/Polaris#728]
I've reported this bug on just about every code base at this point.
Might also still be an issue on Baystation, now that I think about it.
![](http://i.imgur.com/H4D3lzP.png)
Essentially, just click on the poster a billion times and click the 'yes' button a billion times.
You now have a very obnoxious noise maker.

**Comment by Hubblenaut** [comment]
This sort of click cooldown issue exists with many things currently, we should probably gather them all in a single thread.

For what I know, you can do the same to fire alarms and pry unlimited amounts of circuit boards out of them. All the do_after()s in the code should probably be checked on consistent if-statements.

**Comment by PsiOmegaDelta** [comment]
The most encompassing way is to always make do_after()s cancel prior ones.

**Comment by Spacemanspark** [comment]
/tg/ and Paradise have both fixed this issue, I should add.
