### ISSUE TITLE
Health Analyzers Work on Prosthetic Limbs

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#733]
Full Body Prosthetics show ERROR messages while scanning a human/alien with a prosthetic shows the damage values 

FBP - http://prntscr.com/9mkv4c
Human - http://prntscr.com/9mkvdu

**Comment by EmperorJon** [comment]
I think we need to decide which way we're going with this one. I'd personally say you're probably looking at it correctly, and that prosthetic limb damage shouldn't be diagnosable with a health scanner. Should we be subtracting the damage from the totals, so someone appears to be fine with some sort of notifier for the limb saying it's broadcasting it's damaged, and send them to the roboticist? If we just blank out the limb damage their total damage will still show, and we'll start confusing medics who think their patient should be fine and... yeah.

**Comment by Zuhayr** [comment]
Just obfuscate prosthetic values entirely from the health scanner and leave it at that.

**Comment by Anewbe** [comment]
Still happening

**Comment by Atermonera** [comment]
Unable to reproduce, I think:
[https://puu.sh/wNZpF/ac25adfce3.png](https://puu.sh/wNZpF/ac25adfce3.png)

Unless we want to be able to see the damages with the health scanner, in which case this is still an issue

**Comment by Nalarac** [comment]
That's an android. This issue was for organics that have, for example, a prosthetic arm. Testing it again just now, it appears this issue was fixed but never closed.

**Comment by Anewbe** [comment]
Thank you Nalarac.
