### ISSUE TITLE
Cryo-Escapepod does not Eject

### ISSUE THREAD

**Issue by DasIrrlicht** [PolarisSS13/Polaris#7341]
#### Brief description of the issue
The Escapepod that contains the Spawn/Despawn-Cryo of the station does not eject if one hits manual eject on the included console even if one has closed the doors and the pods status is 'armed' and the transfershuttle left. (Pods should work no matter the kind of round-end shuttle left)
#### What you expected to happen
Actually ejecting to happen.
#### What actually happened
Celebration over radio while the pod is stuck in station, all doors closed and bolted but no actual leaving.
#### Steps to reproduce
Wait for transfer-shuttle to leave. Check Escape-console. Override and close doors. Click Manual Eject, since it already is armed. Try again without having override turned on. Ghost/have a ghost/stationguy tell you that you are still on-station and never ejected.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
I got told, by Mechoid I think, that escapepods should work no matter what way the round gets end. This either is a bug with this special escapepod or the case with every pod. I have not tested it with others.

**Comment by Atermonera** [comment]
![testing](https://puu.sh/GdOqg/f9d5e714ab.png)
