### ISSUE TITLE
V-Chat does not allow links it should probably allow.

### ISSUE THREAD

**Issue by DasIrrlicht** [PolarisSS13/Polaris#7362]
#### Brief description of the issue
V-Chat does not allow the forum to be linked, nor discord invites (even if they are from our discord)
#### What you expected to happen
It to have 'https://forum.ss13polaris.com/index.php' as a thing on a Whitelist of links to post.
#### What actually happened
No external links.
#### Steps to reproduce
Try it, as a non-staff.
#### Additional info:
 - **Anything else you may wish to add** 
I have not tested it, but it should ideally allow the Wiki, too.
Probably all working as intended, but it should work different, if that is the case.

**Comment by Atermonera** [comment]
Those are config options, that were added to dissuade some spammers with a grudge against world server. Since they've come and gone, probably safe to reenable those

**Comment by Neerti** [comment]
This is hopefully resolved now, as if it works then all non-byond links will work soon.
