### ISSUE TITLE
Mercenary consistantly pulls full strength merc teams, when there are only 15-18 people ready. 

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#737]
Something that's been noticed over the past few days has been merc teams appear to be rolling full 6 man merc teams. 

This appears to also be the case for heist teams, with full strength heist teams being selected at round start with only 15 or so people being ready.

Not sure if this is intended behavior or not, but it has lopsided several rounds where six mercs get spawned in, but only one or two security officers.

**Comment by Mark9013100** [comment]
Pretty sure usual for a five man merc team is 25 players, and 3 ops is about 15.

**Comment by EmperorJon** [comment]
We just pulled 5 on a round where only 5 readied. My guess is that the _minimum _team size is at least being respected.
