### ISSUE TITLE
cold discomfort is broken for teshari? (maybe others?)

### ISSUE THREAD

**Issue by Greenjoe12345** [PolarisSS13/Polaris#7407]
#### Brief description of the issue
title
#### What you expected to happen
I was making a PR to add cold discomfort messages to tesh, but when I got to testing it seems that even when at levels lower then the teshari cold_discomfort_level, they don't get any sort of message, or even the thermometer showing you're feeling cold.
#### What actually happened
for teshari to feel cold at temperatures lower then their discomfort level.
#### Steps to reproduce
be a teshari?
be in a temperature lower then your cold_discomfort_level
see the lack of discomfort messages.
#### Additional info:
maybe it's something to do with vchat or the new alerts thing (not the over the head ones but the new ones at the side of the screen)

**Comment by Greenjoe12345** [comment]
as a small update, it seems that cold discomfort does work for Tajara, showing cold messages for them, but Teshari can walk around just fine even when it is way colder then their cold discomfort level (their discomfort level is around -90c iirc, but I was walking around naked as a Teshari in temps of near -200c without any sign of feeling cold)

**Comment by Greenjoe12345** [comment]
and another update, someone reported that they were standing on sif naked as a human with no cold discomfort

**Comment by Razgriz1032** [comment]
^
Also, Unathi ARE affected by cold. Unathi are naturally very vulnerable to cold temperatures. I haven't looked into the cold myself, but I would suspect that maybe something has changed the range of temperatures for every race and Unathi just happen to fall under fatal temperatures still.

**Comment by Razgriz1032** [comment]
I just got word from Yawn that their cryogaia map is freezing people to death, but not their sif map, so it might be map specific.

**Comment by Atermonera** [comment]
Cold discomfort works in a very janky manner

**Comment by Shadow-Quill** [comment]
> 
> 
> Cold discomfort works in a very janky manner

So why does that invalidate this issue?

**Comment by Razgriz1032** [comment]
This is trash.

**Comment by Razgriz1032** [comment]
What was the first PR that made it jank, like when you suddenly did not need a coat anymore.
