### ISSUE TITLE
Can't manually enter/eject out of a sleeper.

### ISSUE THREAD

**Issue by ChessPiece** [PolarisSS13/Polaris#741]
You can however enter by dragging yourself into the sleeper, but someone has to man the console to eject you out. Nor can someone else use the sleeper to eject you out without the console.

**Comment by MagmaRam** [comment]
Sleepers have been missing those verbs for a good while. If that's an oversight and not intended, I should be able to readd those easily enough.

**Comment by EmperorJon** [comment]
Sleepers and Advanced Scanners currently work in two different ways, one requiring a click-drag and one a grab-click. Probably a mix of bug and oversight.

**Comment by Kelenius** [comment]
You can exit them by moving. Not a bug.
