### ISSUE TITLE
Cleanbots don't clean filth

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#7414]
#### Brief description of the issue

Cleanbot will not clean filth.

#### What you expected to happen

Cleanbot to clean everything

#### What actually happened

Cleanbot cleaned everything but the filth

#### Steps to reproduce

Have filth on a tile, spawn in a cleanbot, wait.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.

Server revision: master - 2020-07-31 

8d731a153b120b0e0942a81eaa80844b68484684 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Schnayy** [comment]
fixed by #7656
