### ISSUE TITLE
FBPs have no way to fix their vision.

### ISSUE THREAD

**Issue by Datraen** [PolarisSS13/Polaris#742]
Optical sensors do not take damage or control sdisabilities, which causes FBPs to be permanently blind until admin intervention takes place.

**Comment by Zuhayr** [comment]
.. what? They are literally just eyeballs with ORGAN_ROBOT, please give more information.

**Comment by Datraen** [comment]
Last night, when I reported this, someone welderburned their eyes as a FBP. No damage on the optical sensor, which I confirmed using VV. sdisabilities was set to 1 at some point, and was not being corrected, even though the variables to control eye blindness were unset, causing blinded to be set to 1.

**Comment by Datraen** [comment]
Narrowed down to eye_blind not being reset.
