### ISSUE TITLE
Temperature damage occurs in the orange warning level

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#7446]
#### Brief description of the issue
The previous temperature warning icon turned red and flashed, to indicate you are taking damage.
Currently, you can die while still in the orange warning stage, with previously indicated that you were hot but not yet being injured by it.

#### What you expected to happen
My HUD to flash red to warn me that I am dying.

#### What actually happened
I died and was very confused as to what happened, because my HUD showed me I was fine.

#### Steps to reproduce
Set body temperature to 700, observe HUD icon. Set body temp to 9999, observe icon.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
[Cannot reproduce](https://puu.sh/GttSB/c9c8e95848.mp4) (mp4)

**Comment by FenodyreeAv** [comment]
There's 3 levels of temp warning, the 'im mildly warm' warning level, means you are ALREADY taking damage. Got the numbers a bit wrong, 700 was too high.


[](https://streamable.com/17avbu)
