### ISSUE TITLE
cannot cut pizzas with knives

### ISSUE THREAD

**Issue by Dibasic** [PolarisSS13/Polaris#745]
because you can eat with knives now, steel knives from the kitchen vending machine will act like forks with a pizza instead of cutting it

**Comment by Datraen** [comment]
Has to do with how kitchen utensils are in the code. I could add a check to see if the item is slicable or not and if it's a slicing utensil, in the case of a few other knives.

**Comment by Datraen** [comment]
Forgive the delay, not forgotten, I've just been busy with work.

**Comment by Zuhayr** [comment]
Dupe of #270
