### ISSUE TITLE
Xfer shuttle engines disappear

### ISSUE THREAD

**Issue by Schnayy** [PolarisSS13/Polaris#7468]
#### Brief description of the issue
The back of the transfer shuttle straight up disappeared and vented the x-fer shuttle.

#### What you expected to happen
Not that.

#### What actually happened
In the middle of the flight the back portion of the shuttle, including the brig and medical rooms, were cut off. When it landed, they returned. It vented those rooms.

#### Steps to reproduce
I have no fucking idea.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Closing stale issue. Difficult to retest, would require people actively present when it occurs to properly investigate.
