### ISSUE TITLE
breath masks block every body slot except face when adjusted to hanging

### ISSUE THREAD

**Issue by Spookerton** [PolarisSS13/Polaris#758]
This is because of a missing & in [breath.dm#19](https://github.com/PolarisSS13/Polaris/blob/master/code/modules/clothing/masks/breath.dm#L19) as of [this commit](https://github.com/PolarisSS13/Polaris/commit/fd8f6d9639989fee1e71522fc83d3590e1e5a510)

Simply, 
```
body_parts_covered = ~(FACE)
```
should be
```
body_parts_covered &= ~(FACE)
```
It might be nice to clean up, too, as [A](http://hastebin.com/raw/sepuhoboka) or [B](http://hastebin.com/raw/uqaqofitab)

**Comment by EmperorJon** [comment]
I feel that B retains a greater degree of readability at a glance. Testing the fix now.
