### ISSUE TITLE
Modular computers cannot download the camera monitoring program

### ISSUE THREAD

**Issue by Woodratt** [PolarisSS13/Polaris#7627]
#### Brief description of the issue

When one clicks on the camera monitoring program on a modular computer nothing occurs. Think this might be tied to the recent update to the camera console stuff with TGUI

#### What you expected to happen

To be able to download the camera monitor program and use it

#### What actually happened

It never downloaded

#### Steps to reproduce

Use a tablet, laptop or regular modular computer and attempt to download the camera monitoring program.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2020-09-02 

1a91b1c38044b7e517b0e68e7301200e109f6967 

 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
[Cannot reproduce](https://puu.sh/GtktD/a6a44a8c08.png) (mp4)
