### ISSUE TITLE
Cuffs can not be resisted while in on a bed

### ISSUE THREAD

**Issue by DasIrrlicht** [PolarisSS13/Polaris#7647]
#### Brief description of the issue
When placed on a medical rollerbed, you are unable to resist cuffs.
#### What you expected to happen
Be able to, at least, try to get the cuffs off.
#### What actually happened
Neither me nor the other person trieing on a seperate time was able to resist out of the cuffs, had them be taken off with help insteaad.
#### Steps to reproduce
Get cuffed, get on medical rollerbed. Try resisting. (may need to have been downed at least once while on the bed?)
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
Being buckled to a rollerbed is the same as being buckled to a chair. Except rollerbeds have a much higher tendency to move.
![not a bug](https://puu.sh/Gt8Dc/9b082b8553.png)
