### ISSUE TITLE
disposals doesn't have airtight flaps

### ISSUE THREAD

**Issue by Dibasic** [PolarisSS13/Polaris#766]
not sure whether this is intended, but the lack of airtight flaps has already claimed the lives of three idiots i've seen so far. people can just walk straight into disposals and die

**Comment by Zuhayr** [comment]
Not seeing a problem with this.

**Comment by Neerti** [comment]
It causes the disposal room to overpressurise as more and more people flush things down, since the disposal bin actually takes air along with whatever gets flushed.
