### ISSUE TITLE
Play Global Sound admin verb not working

### ISSUE THREAD

**Issue by Cerebulon** [PolarisSS13/Polaris#7674]
#### Brief description of the issue
The admin verb Play Global Sound does not actually play a sound. 

#### What you expected to happen
A sound to be played to everybody on the server who doesn't play "play admin midis" turned off.

#### What actually happened
No sound played for anybody.

#### Steps to reproduce
Hit Play Global Sound. Select a sound file. Hear nothing.

#### Additional info:
The Play Local Sound and Play Server Sound verbs DO work.

**Comment by Atermonera** [comment]
Could not reproduce, did you have the sound volume turned up?
