### ISSUE TITLE
Modular Computers Cannot Open Suit Sensor Tracking

### ISSUE THREAD

**Issue by Doctress** [PolarisSS13/Polaris#7706]
#### Brief description of the issue
I cannot open suit sensor tracking on tablets or on the lobby modular computer in medbay.

#### What you expected to happen
I click the button and the app opens.

#### What actually happened
No window pops up whenever said computers are running suit sensors.

#### Steps to reproduce
Open a tablet, download suit sensors, attempt to run it.
Go to medbay, click the main modular computer that auto-runs suit sensors.

#### Additional info:
Server revision: master - 2020-09-27 
a07b34a25540c4c1a13bf287679051e9c651e92d 

Computers that ONLY run suit sensors (such as the one near the advanced scanner) still work properly.

**Comment by Schnayy** [comment]
Fixed at some point, can't find specific PR.
