### ISSUE TITLE
Attempting to Photograph A Strange Rock Removes It

### ISSUE THREAD

**Issue by Doctress** [PolarisSS13/Polaris#7719]
#### Brief description of the issue
When taking a picture of a strange rock it results in the rock being deleted, and a black polaroid being created in its place.

#### What you expected to happen
To click on the rock held in one hand while holding a camera in the other, active hand and for nothing to happen.

#### What actually happened
It takes a 'photo' of the held rock which results in a black polaroid with no picture or information.

#### Steps to reproduce
Take a strange rock, take a polaroid camera. After several seconds of holding them both (the exact timing escapes me), click on the rock with any intent active and it will result in the bug. This seems to occur roughly after a ten second delay.

#### Additional info:
Server revision: master - 2020-09-30 

a07b34a25540c4c1a13bf287679051e9c651e92d 

Reproduction of the bug is semi-reliable and quite janky. If at first you don't succeed the following may be (but is not always) required;
Throw the camera on the ground, pick it back up and take a photo.
Change intents and take a photo.
Ensure the camera was the last object picked up.
Any combination of the above three.

**Comment by Atermonera** [comment]
Per its code, booping a strange rock with anything other than the intended implements has a 33% chance to destroy the rock. Holding it in one hand and clicking it with something in the other counts as booping.
https://github.com/PolarisSS13/Polaris/blob/37d7360423e3075af53aa12dc704acb7d06ae189/code/modules/xenoarcheaology/finds/finds.dm#L33
