### ISSUE TITLE
Random engine selection results in doubled up doors/windows

### ISSUE THREAD

**Issue by Cerebulon** [PolarisSS13/Polaris#7741]
#### Brief description of the issue
The SM containment chamber has two sets of stacked doors, windows etc.

#### What you expected to happen
One set of doors/windows etc.

#### What actually happened
Presumably, the engine spawning code is spawning certain map elements regardless of which thingy is selected.

#### Steps to reproduce
Load map. Look at engine room.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Shadow-Quill** [comment]
This can be closed

**Comment by zekesulastin** [comment]
Sorry for not using the proper keyword to link the issue ._. but yeah, fixed
