### ISSUE TITLE
Broken Syringe Description

### ISSUE THREAD

**Issue by redstryker** [PolarisSS13/Polaris#781]
The description for a broken syringe I shot out of a syringe gun said:
"A syringe. It is broken. It is broken."

**Comment by Dibasic** [comment]
just examined three broken syringes fired from a syringe gun and none of them had this, they all said "A syringe. It is broken."

**Comment by Atermonera** [comment]
Unable to reproduce:
[https://puu.sh/wNZeF/cb304a05b6.mp4](https://puu.sh/wNZeF/cb304a05b6.mp4)
