### ISSUE TITLE
NO ICON health

### ISSUE THREAD

**Issue by Albens** [PolarisSS13/Polaris#785]
On tin.
[Screenshot](https://gyazo.com/7de320dd247f2165856bc788ff00f80b) with text for log-diving if someone cares. Dated log 2016-01-14 (3 01 pm), EST.
I think I died from internal bleeding, but I cannot be sure.

**Comment by Ccomp5950** [comment]
Were you being worked on at the time?  Taken pain medicine?  I ask because it looks like Polaris hasn't pulled: https://github.com/Baystation12/Baystation12/pull/11724 yet.

**Comment by Albens** [comment]
It happened some time after going through surgery, I don't know if I had taken pain medicine. I had started to bleed from a wound that couldn't be seen, and then I passed out and died.

**Comment by Ccomp5950** [comment]
Fair enough, might be something different.
