### ISSUE TITLE
Ping on advanced who is budged down by one line

### ISSUE THREAD

**Issue by Greenjoe12345** [PolarisSS13/Polaris#7851]
#### Brief description of the issue
![image](https://user-images.githubusercontent.com/33647525/106973217-5cf91280-674a-11eb-88ce-0e0cb5da5705.png)

#### What you expected to happen
for the ping to be next to the actual user of the ping
#### What actually happened
see above
#### Steps to reproduce
press advanced who
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Schnayy** [comment]
Only appears for normal players, de-admin for testing a fix.

**Comment by Greenjoe12345** [comment]
this is fixed since ping isn't shown on advanced who anymore
