### ISSUE TITLE
Pilots do not appear on the PDA manifest

### ISSUE THREAD

**Issue by Greenjoe12345** [PolarisSS13/Polaris#7859]
#### Brief description of the issue
Title
#### What you expected to happen
for pilots to be on the manifest, maybe under science with the explorers merging into that?
#### What actually happened
they're not there, at all
#### Steps to reproduce
be a pilot, check the manifest on PDA
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** you do still show up on the manifest seen from the lobby screen or from the ghost tab. It's just the PDA manifest that doesn't have pilots.

**Comment by Schnayy** [comment]
May apply to any "miscellaneous" role. Will test when I have the chance if no one beats me to it.
