### ISSUE TITLE
Tomatoes make unathi sleepy

### ISSUE THREAD

**Issue by Schnayy** [PolarisSS13/Polaris#7876]
#### Brief description of the issue
Tomato make Seihos sleepy.
#### What you expected to happen
To eat my UNATHI CUISINE in peace.
#### What actually happened
YAWN.
#### Steps to reproduce
Be unathi. Eat tomato juice. Yawn.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
Mostly putting this here to remind myself to fix it. All juice makes unathi sleepy for some reason.

**Comment by PrismaticGynoid** [comment]
Looks like it was probably intended for sugary juices, but a couple of non-sugary juices get included under it. https://github.com/PolarisSS13/Polaris/pull/1638
