### ISSUE TITLE
[Request] Too many ores!

### ISSUE THREAD

**Issue by Schnayy** [PolarisSS13/Polaris#7885]
#### Brief description of the issue
Mining has become a bigger time sink, with less focus on what materials to get and too many of said materials to keep track of. Proposal and intended PR I will be putting up will make the following changes to #7811 : 

- 14.5 shells will be removed from the autolathe.
- R&D designs will have more rhyme and reason to what type of things require certain materials. 
- Remove tin as a material that spawns in the mines.
- Make the ore processor hide certain non-naturally generated materials unless they are actually in the ore processor. This allows us to add more materials for adminspawn/PoI's without intimidating new miners.

Any further requests or tweaks to the above may be commented here and considered before I sit down and make these changes.

#### What you expected to happen
N/A
#### What actually happened
N/A
#### Steps to reproduce
N/A
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Kholdstare34** [comment]
Basic tools (such as the multitool) should not require copper.
