### ISSUE TITLE
Hardsuit energy gun can't be configured

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#79]
It'll toggle to the original setting as soon as it's configured.

**Comment by Mark9013100** [comment]
Unable to reproduce on Bay's current dev branch.

**Comment by Neerti** [comment]
Confirmed to still exist.

**Comment by Zuhayr** [comment]
So. Still happening.

I added world << debugs to engage() and it's only being called once. I've also noticed that when you fire the egun and laser cannon, it will fire twice (second time is given 'the mounted energy gun cannot be used again so soon').

Having a hard time working this one out.
