### ISSUE TITLE
Examining your own ID examines yourself instead

### ISSUE THREAD

**Issue by Cerebulon** [PolarisSS13/Polaris#7901]
#### Brief description of the issue

Examining your OWN ID card instead examines you, the mob. Examining OTHER'S IDs works as intended.

#### What you expected to happen

Examine ID, get TGUI popup.

#### What actually happened

Get the chat message as if examining my own mob.

#### Steps to reproduce

Spawn in. Examine your own ID card. This also applies when attempting to examine the ID card from across the room - because you are in range of YOURSELF, instead of saying "the ID card is out of range", you examine yourself successfully.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add**
 - 
Was bughunting and found that the /obj/item/weapon/card/id/examine(mob/user) proc is not called at all when examining your own ID, instead examining your own mob. Potentially related to the root cause of #649 all the way back in 2015.
Shift-clicking to examine works as intended, weirdly.
Also of note, this does not appear to be an issue downstream so they seem to have fixed it at some point, intentionally or otherwise.

**Comment by Atermonera** [comment]
Oh not this gobbledygook again. Shift-click is calling examine directly on the clicked-on object, whereas right-click examine afaik passes it as a command that has to be parsed as text, so it very likely is the same issue.
