### ISSUE TITLE
Portable Patient Stabalizer issues

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#7908]
#### Brief description of the issue
The Portable Patient Stabilizer does not give the corpse the 'bloodpump_corpse' modifier as it should, (or any other bloodpump modifiers).

The 'bloodpump_corpse' modifier does not actually force the pulse variable to 1.

The pulse being forced to 1 does not cause reagents to process.

Pulse being forced to 1 does cause oxygen damage to reduce.

#### What you expected to happen
The Portable Patient Stabilizer to slowly reduce oxygen damage, and allow reagents to process slowly.

(Defib timer means that even with this, it's not a certainty that you can save someone far over 200 damage)

If Cargo, Surgery and Chemistry ALL get together and work on a body only just over 200 within 20 minutes of death, the person deserves to live.

#### What actually happened
PPS did absolutely nothing, because it didn't apply the bloodpump modifier.

#### Steps to reproduce
Have burned dead guy with over 200 damage, apply PPS.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
![retested](https://puu.sh/HqvvJ/568b9aa22d.png)
