### ISSUE TITLE
New stairs break pulls and cause runtimes

### ISSUE THREAD

**Issue by cadyn** [PolarisSS13/Polaris#7934]
#### Brief description of the issue
Pulls get broken if a user continues holding the movement key while going up stairs.
#### What you expected to happen
The pull to still work, especially when I was in range still.
#### What actually happened
The pull was broken, and a runtime was produced:
#### Steps to reproduce
1. Start pulling somebody (If you're on a test server, a carbon/human/dummy works great.)
2. Line yourself up with the stairs so that you can just hold down a movement key, and keep moving in the direction of the stairs.
3. Hold the movement key down as you go up the stairs
4. Your pull is broken. GG, especially if they were cuffed.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
Runtime:
![image](https://user-images.githubusercontent.com/35672377/109402428-a3393000-790a-11eb-8124-9392daff2504.png)

**Comment by Atermonera** [comment]
Higgs bugson on account of I haven't heard anyone on polaris run into this, and could not reproduce it locally myself, but it is reported as being reliably reproduced on vore. Suspect move speed differences are at fault

**Comment by Novacat** [comment]
Polaris just got the new stairs, and so far we have noticed odd behavior with the following two things.

1: Mobs buckled to other mobs moving through the stairs.
2: Mobs being thrown at stairs by other mobs.
