### ISSUE TITLE
Languages are tied to the body

### ISSUE THREAD

**Issue by Greenjoe12345** [PolarisSS13/Polaris#7957]
#### Brief description of the issue
Languages seem to be tied to the body, so brainswaps swap the languages you know too
#### What you expected to happen
for you to continue knowing a language you know after being brainswapped
#### What actually happened
you get the other person's languages
#### Steps to reproduce
Get two people with different languages
swap their brains
see each body didn't change languages with the brains being changed
#### Additional info:
This is a picture of my languages set in char creation, and the langauges I had after a brain-swap. Notice the difference between common skrellian and sign language
![image](https://user-images.githubusercontent.com/33647525/110266165-29154500-7fb5-11eb-9b4b-c9dcb9837c76.png)

**Comment by Atermonera** [comment]
#7524
