### ISSUE TITLE
Spiders cannot break through police tape

### ISSUE THREAD

**Issue by Lorwp** [PolarisSS13/Polaris#796]
When there's an (inevitable) outbreak of spiders, and they become the size of a chair, they seem to be unable to break through police tape placed on a door.

I'm not sure if this applies to police tape placed in the usual way, or engineering tape. Though i'll probably test it later.

**Comment by PsiOmegaDelta** [comment]
Would potentially be fixed by having spiders (and any hostile mob really) have their intent set to harm instead of help.
