### ISSUE TITLE
GPS UI is no longer(?) TGUI

### ISSUE THREAD

**Issue by Shadow-Quill** [PolarisSS13/Polaris#7984]
#### Brief description of the issue

Back to icky NanoUI.

**Comment by Greenjoe12345** [comment]
well, the GPS never was TGUI here. it outputted to chat before. this new GPS update added a UI for them, but not one made for TGUI.

**Comment by MistakeNot4892** [comment]
It's not NanoUI either, it's a browser. This isn't a bug.

**Comment by Shadow-Quill** [comment]
> well, the GPS never was TGUI here. it outputted to chat before. this new GPS update added a UI for them, but not one made for TGUI.

Seems like the PR that changed it to *be* TGUI was only pulled on Virgo.
