### ISSUE TITLE
RUST Broken

### ISSUE THREAD

**Issue by Razgriz1032** [PolarisSS13/Polaris#8005]
#### Brief description of the issue
https://github.com/PolarisSS13/Polaris/pull/7835 broke the RUST.

1. Warnings and settings appear in the general chat for everyone. It'll tick and flood the chat.
2. The gyro control console is broken. When the gyro is attempted to fire it creates a runtime. Whatever it tries to use to set the power intensity doesn't work, and so it doesn't fire.
3. Something broke in it that prevented the consoles from linking to the engine at map start. The id_tag variable on the console gets pre-nuked. Also code/modules/power/fusion/core/core_control.dm on like 9 commented out the id_tag variable entirely, yet somehow I can set the tag via the console later on, but I can't from view variables.

EDIT: Added more to 3rd issue.

**Comment by Atermonera** [comment]
I can't reproduce the runtime with gyrotrons, it seems to work fine on our code. If you could get me the runtime log, that'd be great. And what consoles aren't being correctly linked? Is it all of them? Or specific ones?

Also priority high because this issue has been raised by a downstream that actively uses the R-UST, and are experiencing problems caused by the changes we made while experimenting with them under the assumption that it wasn't used in such a capacity.

**Comment by Razgriz1032** [comment]
Here's the runtime

[2021-03-23T20:20:23] Runtime in gyrotron.dm,35: Undefined operation: "32" * 50000
   proc name: process (/obj/machinery/power/emitter/gyrotron/process)
   src: the gyrotron (/obj/machinery/power/emitter/gyrotron/anchored)
   src.loc: the plating (58,152,4) (/turf/simulated/floor/plating)
   call stack:
   the gyrotron (/obj/machinery/power/emitter/gyrotron/anchored): process(20)
   Machines (/datum/controller/subsystem/machines): process machinery(1)
   Machines (/datum/controller/subsystem/machines): fire(1)
   Machines (/datum/controller/subsystem/machines): ignite(1)
   Master (/datum/controller/master): RunQueue()
   Master (/datum/controller/master): Loop()
   Master (/datum/controller/master): StartProcessing(0)

**Comment by Atermonera** [comment]
Update: runtime reproduced. If you click on a knob instead of click-dragging, it opens a text field, and entering something into _that_ sends a string instead of a number

**Comment by Razgriz1032** [comment]
Can you double check the core field knob is also affected by that runtime/bug?

**Comment by Razgriz1032** [comment]
Update on problem #3. It got a lot more complicated. I have confirmed that the console "id_tag" variables are properly set, however on map load the variable gets nuked.

Edited to:
"3. Something broke in it that prevented the consoles from linking to the engine at map start. The id_tag variable on the console gets pre-nuked. Also code/modules/power/fusion/core/core_control.dm on like 9 commented out the id_tag variable entirely, yet somehow I can set the tag via the console later on, but I can't from view variables."
