### ISSUE TITLE
Prosthetic selection proceeds to type and brand selection even after cancellation

### ISSUE THREAD

**Issue by sabiram** [PolarisSS13/Polaris#802]
![](http://i.imgur.com/Z6AmxEh.png)

1) Click 'Adjust'
2) Click 'Cancel'
3) Select any option other than 'Normal'
4) Select a manufacturer if applicable

Result is listed as 'Bishop (for example) prosthesis' or 'Amputated'. No sprite changes on character generator.

Not tested if there are any gameplay implications. Fairly certain this is an old bug from before FBP.

**Comment by Zuhayr** [comment]
Reproduced, doesn't actually put anything in the list but does still occur.
