### ISSUE TITLE
Cargo Delivery Office APC is Bluescreened

### ISSUE THREAD

**Issue by Lorwp** [PolarisSS13/Polaris#804]
Every time i've seen the Delivery office APC, it seems to be Bluescreened on the current map, like it was taken over by a Malf AI. This happens even if the current gamemode makes it impossible without Admin Intervention.

![capture](https://cloud.githubusercontent.com/assets/8052896/12412026/a6e2dd16-bed7-11e5-80b7-0428c601f5a9.PNG)

**Comment by SledgeLP** [comment]
Don't think that is actually a bug, sometimes APCs will randomly bluescreen. Might be an issue with it not being that random if anything.

**Comment by Yoshax** [comment]
Unable to reproduce. Most likely just the RNG event as Sledge said.

**Comment by PsiOmegaDelta** [comment]
Did you ensure that the RNG event isn't strictly focusing on that one APC?

**Comment by Mark9013100** [comment]
Just seems to be RNG.

**Comment by Yoshax** [comment]
Well, when I tested it, it seemed to always be the cargo or nearby APCS, but that might have been because I was the only person on, and was in cargo.
