### ISSUE TITLE
Cyborg's beaker tool can be entered into some machinery, and broken that way.

### ISSUE THREAD

**Issue by Perniciles** [PolarisSS13/Polaris#806]
The beaker can be put into machines like the chemical dispenser, or the ChemMaster3000. I'm not sure if that is a feature or a bug, because this enables for example the Crisis module to work in the chemistry lab, which does sound intended.
The beaker then is no longer seen in the beaker tool, the tool looks like it's empty. If you eject the beaker from the machine, and then store the tool, you pick the beaker back up. All this might be intended, as it enables the cyborg to work in the chemistry lab, and one of the designs of the crisis module is called Drone - Chemistry (or something along those lines).

Now, here's the problem: If you store the empty beaker tool while the beaker is inside a machine and not ejected, you don't get the beaker back. After that you can't equip the beaker tool again, so you can't pick the beaker back up. That means the beaker module is broken until you get a module reset.

**Comment by Atermonera** [comment]
#1503 more accurately encompasses the associated issues
