### ISSUE TITLE
*deathgasp emote causes vomiting

### ISSUE THREAD

**Issue by Razgriz1032** [PolarisSS13/Polaris#8096]
*deathgasp emote no longer causes deathgasp emote. It now makes the character vomit.

This broke it.
https://github.com/PolarisSS13/Polaris/pull/7987

**Comment by MistakeNot4892** [comment]
Dammit, I had a fix for this but it was in a PR that got closed for an alternative. I'll cherrypick it out and get it PR'd.

**Comment by MistakeNot4892** [comment]
#8099

**Comment by MistakeNot4892** [comment]
This has been fixed.
