### ISSUE TITLE
Forks and Spoons Do Not Function

### ISSUE THREAD

**Issue by Doctress** [PolarisSS13/Polaris#8167]
#### Brief description of the issue
When attempting to eat with a fork or spoon, fork/spoonful of the food collects the food as per normal, but does not allow you to eat off the fork/spoon. It will also not allow you to take further spoon/forkfuls.

#### What you expected to happen
To click the food, then click myself, and to take a bite of food. To be able to repeat this.

#### What actually happened
Click food.
'You scoop up some Cheese wedge with the steel spoon!'
Attempt to eat food
'You don't have anything on the steel spoon.'
Attempt to scoop further food.
'You already have something on your the steel spoon.'

#### Steps to reproduce
Try to eat something with a fork/spoon.

#### Additional info:
Server revision: master - 2021-07-01 
959511918c3bbcc2c4a35e0f18da429690800c17

**Comment by MistakeNot4892** [comment]
#8165

**Comment by MarinaGryphon** [comment]
The issue still exists because the PR has yet to be merged.
