### ISSUE TITLE
Deleting player-controlled cyborgs can result in runtime errors

### ISSUE THREAD

**Issue by Datraen** [PolarisSS13/Polaris#819]
http://hastebin.com/apudabomif.hs

Results of this:
No Player Panel
No Follow dialogue box

**Comment by GinjaNinja32** [comment]
Was this cyborg VVed at all? The runtime error suggests it had a `connected_ai` that was actually a robot.

**Comment by GinjaNinja32** [comment]
Note that the `del()`-not-`qdel()` is IIRC an admin-delete thing; the 'cannot read null.name' is because `Destroy()` runtimed and didn't remove the mob from the mob list (it runtimed *before* `..()`), so the root cause of this is the robot's `connected_ai` not being an AI.

**Comment by Datraen** [comment]
Ah, that explains a lot more. Good to know. I VV'd the AI to something else, as I was testing on the main server and forgot that there was, in fact, an AI.

**Comment by Datraen** [comment]
Error was because of admin muckery.
