### ISSUE TITLE
NanoUI fails to work when buckled in.

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#823]
Anytime you try to use anything(PDA, camera consoles) with NanoUI while buckled into a chair, it won't work.

**Comment by EmperorJon** [comment]
IIRC it's not just nanoUI.

**Comment by Zuhayr** [comment]
This isn't a bug per se, it's because buckling is part of the restrained() check.

**Comment by Mark9013100** [comment]
Yep, it applies to all consoles.

**Comment by 9600bauds** [comment]
I'm not familiar with this codebase, but when we had this problem it was because of a canmove check rather than restrained (). Could be the culprit here, too

**Comment by robovelcro** [comment]
Someone else mentioned this bug - 
https://github.com/PolarisSS13/Polaris/issues/575
Also, I can definitely confirm this happens with consoles and PDAs.
