### ISSUE TITLE
Limbs sometimes stop working for no apparent reason

### ISSUE THREAD

**Issue by Minijar** [PolarisSS13/Polaris#827]
So yesterday in a Merc round, I was the hop, Anna Clifford. I become acting cap and get the headset, unfortunately I can't seem to remove my HOP headset, only by asking someone else to strip it off me can I remove it as clicking it does nothing. I admin help, and Mangled says that I apparently have no ears for the headset to be on. This later happens again with the broken ears and a new headset which also needed to be stripped. Then my left hand (Also left ear) stopped working, I couldn't pick anything up with it or swap items into that hand or interact with anything with that hand, Admin magic seemed to fix it.

**Comment by Zuhayr** [comment]
Did you modify your ID during this round?

**Comment by Minijar** [comment]
@Zuhayr I did yeah, the headset sometimes behaved similarly I think, Sometimes being in my hand and on the floor at the same time.
