### ISSUE TITLE
Wizard: MM doesn't work

### ISSUE THREAD

**Issue by Kelenius** [PolarisSS13/Polaris#828]
It just hovers in place and never targets anything.

**Comment by Lorwp** [comment]
> On 24 Jan 2016, at 2:30 AM, Kelenius <notifications@github.com> wrote:
> 
> It just hovers in place and never targets anything
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/PolarisSS13/Polaris/issues/828>.
> 
probably should rename this to ```magic missile doesn't work``` for clarification.

**Comment by PsiOmegaDelta** [comment]
I suspect it's because Polaris don't have the fix for projectile spells, and they still use the old way of launching projectiles, instead of the more simple ```projectile.Launch(target)```.
The old way runtimes which would explain why magic missiles, and fire balls end up hanging in the air doing nothing.

**Comment by EmperorJon** [comment]
There was some discussion as to whether the same issue is what's broken mech weapons from working. If that's the case it's definitely worth pulling the fix in. Wizard's been low-priority for fixing because there's a rewrite in progress.
