### ISSUE TITLE
TGUI Crafting Menu does not respect Material

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#8288]
#### Brief description of the issue
The TGUI crafting menu doesn't pass on the material of its ingredients to the finished product.

#### What you expected to happen
Using a Durasteel blade in my spear to produce a Durasteel spear.

#### What actually happened
The spear was made of glass, no matter the materials used up.

#### Steps to reproduce
Craft a spear using anything but a glass shard.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by MistakeNot4892** [comment]
Your attention to detail really shines through in this issue request.

**Comment by FenodyreeAv** [comment]
I hit enter to make a newline, but I was clicked outside the box ):

**Comment by FenodyreeAv** [comment]
I think this is happening because the parts used to make the spear should end up in it's contents, but they don't.
So `var/obj/item/weapon/material/N = locate(path) in result` returns null.

**Comment by Atermonera** [comment]
Were you standing ñext to any glass shards?

**Comment by FenodyreeAv** [comment]
Nope.

**Comment by FenodyreeAv** [comment]
https://streamable.com/ssvk2l

`/datum/crafting_recipe/spear/on_craft_completion(mob/user, atom/result)
	log_debug("Setting material")
	var/obj/item/weapon/material/M
	for(var/path in parts)
		var/obj/item/weapon/material/N = locate(path) in result
		log_debug("Part to inherit material from is [N]")
		if(istype(N, path))
			if(!istype(M))
				M = N
			else
				N.forceMove(get_turf(result))
	if(!istype(M))
		return

	var/obj/item/weapon/material/twohanded/spear/S = result
	S.set_material(M.material.name)
	log_debug("set as Material [M.material.name]")
	qdel(M)`

**Comment by Atermonera** [comment]
Fixed by #8296 ?
