### ISSUE TITLE
Wizard: spell buttons don't work

### ISSUE THREAD

**Issue by Kelenius** [PolarisSS13/Polaris#829]
If you try to unfold the scroll that shows spell buttons, you get black screen.

**Comment by Datraen** [comment]
Wizard buttons are, for some reason, appearing on the bottom of the screen when I test.

**Comment by Spookerton** [comment]
This is a result of incorrect positioning - I can't be bothered to go hunting for a git blame, but wizard buttons in general are intended to be positioned according to EAST-xoffset, NORTH-yoffset but are instead positioned as -xoffset,-yoffset, resulting in both incorrect positioning and a resize of the game view while the spell buttons are visible.

Someone wanting to fix this could probably start at [spell_screen_objects.dm#L40](https://github.com/PolarisSS13/Polaris/blob/master/code/_onclick/hud/spell_screen_objects.dm#L40) with reference primarily to [spell_screen_objects.dm#L60](https://github.com/PolarisSS13/Polaris/blob/master/code/_onclick/hud/spell_screen_objects.dm#L60)

**Comment by PsiOmegaDelta** [comment]
https://github.com/Baystation12/Baystation12/pull/11586

**Comment by Spookerton** [comment]
Well there you go then.
