### ISSUE TITLE
Wizard: mutate's laser doesn't work

### ISSUE THREAD

**Issue by Kelenius** [PolarisSS13/Polaris#830]
It makes a sound but no laser is made

**Comment by Datraen** [comment]
It's interesting, because I stumbled across the wish granter and played with it a bit, noticing that the laser doesn't work. Having read up on what it does, and what mutate does, same problem. Genetics laser eyes don't work.

**Comment by Datraen** [comment]
https://github.com/PolarisSS13/Polaris/pull/837 Fixes, wrote the wrong number.
