### ISSUE TITLE
Mobs and supermatter failing to transit

### ISSUE THREAD

**Issue by PrismaticGynoid** [PolarisSS13/Polaris#8310]
#### Brief description of the issue
When mobs (and certain objects like the supermatter) reach the edge of a z-level in space, they do not always transit, instead stopping short right at the edge of the map.

#### What you expected to happen
Ejected supermatter to transit to another z-level, exploding safely far away from the station.

#### What actually happened
Supermatter stopped at the edge of the Z-level, instead of transiting. Exploded while still in range of the station.

#### Steps to reproduce
Spawn a monkey in space, attempt to throw them off the map.

#### Additional info:
 - **Server Revision**: master - 2021-09-19
2ac361ca5e512ef90e3e194cceb25eb30a1c5d15 

 - **Anything else you may wish to add**: Doesn't seem to _always_ happen, but does frequently.

**Comment by MistakeNot4892** [comment]
This might be due to the can_die() runtime Ater fixed recently, how recently has it been observed?

**Comment by PrismaticGynoid** [comment]
Only noticed it happen recently, so it might be related. It's possible it's existed for longer, but I hadn't seen mobs having trouble with this before the last update.

**Comment by Atermonera** [comment]
Cannot reproduce: Ejected the supermatter, checked its position with SDQL2 queries. It eventually ended up on deck 3:
![image](https://puu.sh/IgkUl/12fe04639c.png)

**Comment by Atermonera** [comment]
Code I was testing with was out of date.
