### ISSUE TITLE
weird bug with a saved paper on a noticeboard

### ISSUE THREAD

**Issue by Greenjoe12345** [PolarisSS13/Polaris#8318]
#### Brief description of the issue
it's kinda hard to explain, but I took a paper from a noticeboard to read (it wouldn't work when I pressed read when it was on the noticeboard) and instead of opening a new window with the paper's contents, it replaced the top right area of the main game window, the area with the tabs for IC, OOC, preference stuff, etc,
![image](https://user-images.githubusercontent.com/33647525/134981721-2365382d-5b2d-4eed-b9ff-3894b0c0d444.png)
the paper also seemed to lack an item name and could not be right clicked
#### What you expected to happen
for the paper to open a new window to read it (and to not need to remove the paper from the noticeboard to read it)
#### What actually happened
it replaced that top right part of the screen
#### Steps to reproduce
get a paper from a noticeboard?
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Sypsoti** [comment]
Same as issue #8503
