### ISSUE TITLE
POI's can intersect the Checkpoint

### ISSUE THREAD

**Issue by Schnayy** [PolarisSS13/Polaris#8332]
#### Brief description of the issue
POI's can spawn over the checkpoint, at least the landing pad.

#### What you expected to happen
Not that.

#### What actually happened
![image](https://user-images.githubusercontent.com/26665154/136590355-1449250a-266a-4dc5-9f47-cd7788408ae0.png)

#### Steps to reproduce
Purely RNG.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Woodratt** [comment]
Should be fixed now.
