### ISSUE TITLE
Wearing thermal goggles with eye protection still damages eyes

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#835]
To reproduce: get thermal goggles, doesn't matter which.
Grab a voidsuit helmet and welder.
Start welding, regardless of what you've done with the goggles, you'll still take eye damage from welding.

**Comment by Magneld** [comment]
Intended behavior if the goggles are actually active I believe though if they're still hurting you when turned off that probably needs looked at.

**Comment by Datraen** [comment]
I don't think you can turn them off with a button like the mesons, I'll
double check.

**Comment by PsiOmegaDelta** [comment]
I believe Polaris may have the Bay eye-protection rewrite. If so, eye protection bonuses/penalties are no longer absolute (wear void-helmet, always safe), instead they stack.

In this case it means that active thermals decrease the protection of welding masks/helmets from full to moderate, as thermals have an explicit eye protection decrease (as they still provide their function even with welding protection on).

Never feel like I explain myself well..

**Comment by Mark9013100** [comment]
I'll add this also occurs with unactive thermal goggles.
