### ISSUE TITLE
Drills cannot drill walls

### ISSUE THREAD

**Issue by Greenjoe12345** [PolarisSS13/Polaris#8377]
#### Brief description of the issue
Title
#### What you expected to happen
For the wall to be drilled
#### What actually happened
It tries to engrave the wall, but drilling doesn't work
#### Steps to reproduce
Try to use a drill on a wall
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
#8378
