### ISSUE TITLE
Constructed canisters automatically connect to a port

### ISSUE THREAD

**Issue by Lorwp** [PolarisSS13/Polaris#840]
It seems like canisters constructed, if built on a port, automatically connect to that port. Not sure if this is a bug or a feature of some sort.

**Comment by PsiOmegaDelta** [comment]
It is that way to allowed mapped in canisters to connect to their port at round start.

**Comment by Lorwp** [comment]
@PsiOmegaDelta Got it, though is there any way to stop this behaviour after round start?
