### ISSUE TITLE
You can't properly aim with a scoped weapon.

### ISSUE THREAD

**Issue by N-Komaeda** [PolarisSS13/Polaris#8412]
#### Brief description of the issue
Using the aim feature while scoped does not respect your vision range, since the target is out of your 'normal' range.

#### What you expected to happen
To be able to threaten someone from two screens across.

#### What actually happened
![image](https://user-images.githubusercontent.com/78905387/156193843-e70c5a4d-1a37-44d7-b610-7d9b2517caeb.png)
You drop your aim because they are not an eligible target.

#### Steps to reproduce
Get a weapon with a scope, then aim at someone who is only visible to you while scoped.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
The point of aim mode is to hold someone at gunpoint and tell them to do things. It tells the target that they're being aimed at (And everyone around them). If they can't see that they're being aimed at, then they shouldn't magically know.
