### ISSUE TITLE
Hand Drill & Jaws of Life don't fit in a toolbelt

### ISSUE THREAD

**Issue by N-Komaeda** [PolarisSS13/Polaris#8413]
#### Brief description of the issue
You can't put the Hand Drill and the Jaws of Life in a toolbelt anymore.

#### What you expected to happen
To carry them in my toolbelt.

#### What actually happened
They don't fit.

#### Steps to reproduce
Get a Hand Drill and a Jaws of Life, then try to put them in an empty toolbelt.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc) I think it's a result from [#8387](https://github.com/PolarisSS13/Polaris/issues/8387), but I'm not sure.

**Comment by Atermonera** [comment]
https://github.com/PolarisSS13/Polaris/pull/8491
