### ISSUE TITLE
Mining sheet storage behaving strangely across rounds.

### ISSUE THREAD

**Issue by N-Komaeda** [PolarisSS13/Polaris#8414]
#### Brief description of the issue
The SheetStorage at Cargo seems to save resources improperly. It is no longer capped at 50 sheets to be stored across rounds, but it seems as if the sheets inside randomly disappear throughout the rounds.

#### What you expected to happen
To put in materials, and then keep a max of 50 sheets per resource over the rounds.

#### What actually happened
Weird amounts of various resources being in the machine, resources just... flat out disappearing.

#### Steps to reproduce
Put sheets into the storage, then check in later rounds. They don't match up to the normal cap and some just disappear.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc) This seems to be since the transfer to Cynosure Station.

**Comment by Sypsoti** [comment]
From what I hear from Prismatic, caused by the lossy type of storage added and how it handles removing sheets over time.

**Comment by Cerebulon** [comment]
> From what I hear from Prismatic, caused by the lossy type of storage added and how it handles removing sheets over time.

Was checking for storage persistence issues and just saw this. The bug as described is just how lossy sheet storage is intended to work. It loses a random (but capped) amount of sheets between each round.
Not a bug, but values may want to be tweaked if it seems excessive?
