### ISSUE TITLE
Cable coil does not work on open prosthetics

### ISSUE THREAD

**Issue by PrismaticGynoid** [PolarisSS13/Polaris#8433]
#### Brief description of the issue
Using a cable coil on to try repairing a robotic limb that has been opened does nothing.

#### What you expected to happen
Cable coil to repair burn damage.

#### What actually happened
Absolutely nothing.

#### Steps to reproduce
Damage robotic limb beyond external repair threshold.
Open up limb.
Try to use cable coil on said limb.

#### Additional info:
 - **Server Revision**: master - 2022-02-27 
[8d6542547cdce1f532cfef0412f20576397c0a15](http://127.0.0.1:61221/tmp15136/%3Ca%20href=%22https://github.com/PolarisSS13/Polaris/commit/8d6542547cdce1f532cfef0412f20576397c0a15%22%3Ehttps://github.com/PolarisSS13/Polaris/commit/8d6542547cdce1f532cfef0412f20576397c0a15%3C/a%3E)
 - **Anything else you may wish to add**: Nanopaste still works, as does repairing prosthetic organs.

**Comment by PrismaticGynoid** [comment]
Welders too, looks like.

**Comment by Sypsoti** [comment]
Some elaboration, it seems the basic cable_coil item and the basic welder DO work, but any children of those in the code do not.

**Comment by Atermonera** [comment]
https://github.com/PolarisSS13/Polaris/pull/8491
