### ISSUE TITLE
Cannot Change Species

### ISSUE THREAD

**Issue by Loneguyfly** [PolarisSS13/Polaris#844]
What it says on the tin. I cannot change species. I go in, I click on "Human," I click on one of my whitelisted races, and then.. Nothing. No change, no additional popups. I've tried this on multiple slots, no differences.

**Comment by Techhead0** [comment]
This has been noted to happen intermittently on Baystation: https://github.com/Baystation12/Baystation12/issues/11946

**Comment by Neerti** [comment]
Duplicate of #556, it seems.
