### ISSUE TITLE
Cannot surgically attach limbs

### ISSUE THREAD

**Issue by Sypsoti** [PolarisSS13/Polaris#8469]
#### Brief description of the issue
Limbs do not attach in surgery when using the limb on the body part.
#### What you expected to happen
Brand new limb!
#### What actually happened
They are missing that limb!
#### Steps to reproduce
Applies to meaty and robotic patients, both.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Atermonera** [comment]
https://github.com/PolarisSS13/Polaris/pull/8491
