### ISSUE TITLE
[Meta] Non-main branches on this repository

### ISSUE THREAD

**Issue by Spookerton** [PolarisSS13/Polaris#8487]
<https://github.com/PolarisSS13/Polaris/branches>

There are branches with commits ahead on this repo, which is atypical for a fork-PR driven model. While they are marked stale, I don't want to close them out of hand since I assume they're not misses:
<https://github.com/PolarisSS13/Polaris/tree/PROJECTSkill_System>
<https://github.com/PolarisSS13/Polaris/tree/af20>

There is also probably no longer a need for the mixed contributor cynosure branch, since it's been live:
<https://github.com/PolarisSS13/Polaris/tree/cynosure_map>

**Comment by Atermonera** [comment]
The skillsystem branch was from that one time where we considered implementation a mechanical skill system vaguely in the manner of bay. We then forgot about it.

The `af20` branch was the code used for the april fool's joke of 2020.
