### ISSUE TITLE
Supply Drop from Telecrystals never actually calls the drop

### ISSUE THREAD

**Issue by Varen** [PolarisSS13/Polaris#849]
The process() of the supplybeacon isn't actually called, or it aborts after the first call.
I suspect the latter, as the first lines of code are:
```
/obj/machinery/power/supply_beacon/process()
	if(!use_power || expended)
		return PROCESS_KILL
```

I believe the use_power should have a nil return, and expended should return PROCESS_KILL, separately.

Calling manually process() after the beacon is set up works, so there's that.

**Comment by Techhead0** [comment]
Issue reported on Baystaion as https://github.com/Baystation12/Baystation12/issues/11925
Fix available in https://github.com/Baystation12/Baystation12/pull/12021
