### ISSUE TITLE
Problem with executions.

### ISSUE THREAD

**Issue by OhEmGee** [PolarisSS13/Polaris#853]
Okay, so. I grabbed someone to execute them with a revolver by neck, and aimed to the head. I click on their sprite, the gun fires, but then suddenly I have bullet shrapnel stuck in my head.
I ahelp, and a admin logdives.
Here's the kicker: According to the logs, the gun fired, but the bullet never hit anyone. And yet, I got bullet shrapnel stuck in my face.

**Comment by OhEmGee** [comment]
also we need a WHAT THE FUCK label.

**Comment by Zuhayr** [comment]
No, we don't. The tracker isn't a joke.

**Comment by OhEmGee** [comment]
>No, we don't. The tracker isn't a joke.
r-right
I wasn't aware of the unwritten rules of github.

**Comment by Magneld** [comment]
Witness to the issue though so far I've not been able to recreate it for myself.
If it helps the gun used was a traitor revolver and the victim was an FPB.
