### ISSUE TITLE
[MAP] Atomspheric Technicians don't have access to their maintenance tunnel.

### ISSUE THREAD

**Issue by Datraen** [PolarisSS13/Polaris#857]
Door right next to their SMES, no access as atmospheric technician.

**Comment by Lorwp** [comment]
Checking the values of all the doors leading to the room the SMES is in, i can't see a direct problem, with the doors leading into the room the SMES is in having a `req_access` value of `(12,24)`. For good measure i've removed the `12` from this and this will probably be fixed in a PR.
