### ISSUE TITLE
Scienceborg Portable Destructive Analyzer Bug

### ISSUE THREAD

**Issue by McNanite** [PolarisSS13/Polaris#858]
The research module's portable destructive analyzer tool cannot seem to be used to increase the research level of R&D. I've tested a little bit, on a few arcade circuits and some choice items around the lab, and nothing seems to do it. I have tried resyncing the database and the tool multiple times, but that failed as well. Overall, this bug prevents the research borg from actually doing anything useful within R&D.

**Comment by Atermonera** [comment]
Unable to reproduce, tested this when bumping research levels up enough to print boards for a ripley while testing fixes for unrelated issues.

**Comment by Atermonera** [comment]
This should also have been closed by #2864
