### ISSUE TITLE
suhariki pack trash has no icon

### ISSUE THREAD

**Issue by Greenjoe12345** [PolarisSS13/Polaris#8592]
#### Brief description of the issue
title
#### What you expected to happen
for it to have an icon
#### What actually happened
No icon
#### Steps to reproduce
eat some suhariki, see the lack of rubbush icon when done.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Sypsoti** [comment]
#8397
