### ISSUE TITLE
Advanced body scanner reporting NaN/spurious data

### ISSUE THREAD

**Issue by ShadowWatchman** [PolarisSS13/Polaris#8611]
#### Brief description of the issue
Scanning a patient in the advanced scanner (patient was teshari) returned NaN weight. Temperature possibly also spurious
#### What you expected to happen
Absence of a NaN error
#### What actually happened
<img width="344" alt="Screenshot 2022-05-06 032427" src="https://user-images.githubusercontent.com/7407280/167056543-5fd2dadc-3dea-4a31-a43f-1fad1b0813fd.png">

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Cameron653** [comment]
<img width="268" alt="firefox_2022-09-15_11-20-54" src="https://user-images.githubusercontent.com/15969779/190442932-17e86730-63d8-40f4-a52c-1f8060f65a09.png">

Related problematic lines.
