### ISSUE TITLE
Emote activated implants don't function

### ISSUE THREAD

**Issue by FalseShepardPie** [PolarisSS13/Polaris#8642]
#### Brief description of the issue
When attempting to use implants that are activated using *[emote] (such as a freedom implant) do not activate, instead you just emote with no additional effects.

#### What you expected to happen
Using the emote listed in my notes and being immediately released from cable restraints/handcuffs (using the freedom implant example.)

#### What actually happened
Just the emote.

#### Steps to reproduce
Either print freedom implant from protolathe or buy any emote-activated implant from traitor uplink.
Implant yourself.
Use cable restraints/handcuffs on yourself.
Use activation emote.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add**: Tested on freedom implant and compressed matter implant, implanted in multiple body parts, using both cable restraints and handcuffs when testing freedom implants.

**Comment by Atermonera** [comment]
FWIW I'm pretty sure they have been broken since long before loaf overhauled emotes.
