### ISSUE TITLE
Two recipes on wiki aren't in code

### ISSUE THREAD

**Issue by BigDixy** [PolarisSS13/Polaris#8659]
#### Brief description of the issue
Two recipes; the 'Hot and Sour Soup' and 'Chicken Wings' are present in the wiki, but are not in the code, so of course all attempts to make them fail.
#### What you expected to happen
The recipes to be in the code and to be able to make them.
#### What actually happened
Recipes aren't in the code and miserably failing to make them.
#### Steps to reproduce
Follow the steps of the recipes on the wiki, watch as they inevitably fail, cry, check the code and see both recipes are gone.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Cerebulon** [comment]
Github code search just kind of blows:
Hot & Sour Recipe:
https://github.com/PolarisSS13/Polaris/blob/61084723c7b688b1fb8c31b4b43e5da084b0ffd3/code/modules/food/recipes_microwave.dm#L1129
Hot & Sour Food:
https://github.com/PolarisSS13/Polaris/blob/61084723c7b688b1fb8c31b4b43e5da084b0ffd3/code/modules/food/food/snacks.dm#L7274

Chicken Wings Recipe:
https://github.com/PolarisSS13/Polaris/blob/61084723c7b688b1fb8c31b4b43e5da084b0ffd3/code/modules/food/recipes_fryer.dm#L189
Food:
https://github.com/PolarisSS13/Polaris/blob/61084723c7b688b1fb8c31b4b43e5da084b0ffd3/code/modules/food/food/snacks.dm#L7236

The wiki listings were just missing the tofu and spices respectively, and I've fixed that now.
