### ISSUE TITLE
Fax machines cannot be used without a command ID

### ISSUE THREAD

**Issue by Greenjoe12345** [PolarisSS13/Polaris#8682]
#### Brief description of the issue
Title
#### What you expected to happen
To be able to use a fax machine with any ID.
#### What actually happened
Pressing log in with an engineer's ID and a cargo tech's ID did nothing. the CMO's ID worked.
#### Steps to reproduce
Try to log into a fax machine with a non-command ID.
#### Additional info:
Tested from the library fax machine.

**Comment by Atermonera** [comment]
![cannot reproduce](https://puu.sh/JjhYl/d4c1056b83.png)

**Comment by Atermonera** [comment]
(Tested on the library fax machine)
