### ISSUE TITLE
TCOMMSSAT Exists on Ship Map?

### ISSUE THREAD

**Issue by zaredman** [PolarisSS13/Polaris#87]
ATTN @Neerti - Apparently your domain to remove it.

**Comment by zaredman** [comment]
Oddly enough, radios do not function on the 'Centcom Z.'

**Comment by Neerti** [comment]
Centcom Z-level needs a specific relay added to it.
Your ship has Tcomms and you probably also included colony 3, soooo..

**Comment by zaredman** [comment]
Relay added on #103 - And the only two done shoulda been was Ship-1 and Ship-2. So was that just @SinTwo checking a wrong button?

**Comment by zaredman** [comment]
Yea sin forgot to check a thing.
