### ISSUE TITLE
Aim intent oversensitive!

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#876]
Aiming at a person can trigger autofire in several ways that it shouldn't.

Firstly, examining anything, including the floor, or turning not interacting with any inventory items causes the gun to fire.
Secondly, taking someone hostage in an aggressive grab while aiming. If you attempt to move with the person the gun will fire.

**Comment by Zuhayr** [comment]
These aren't bugs. The alternative to intercepting in Click() is doing an individual check for every possible action that might trigger shooting, which is excessive, and if you're aiming at someone and then force them to move while shooting them if they move... yes, you will shoot them.

Both of these things can be toggled off via the aim interface.
