### ISSUE TITLE
The firefighting helmet does not have an on-mob sprite for unathi

### ISSUE THREAD

**Issue by N-Komaeda** [PolarisSS13/Polaris#8795]
#### Brief description of the issue
The firefighting helmet and atmospheric firefighting helmet do not have an on-mob sprite for unathi.

#### What you expected to happen
Having a sick mask B)

#### What actually happened
I'M BALD

#### Steps to reproduce
Be unathi (I understand this step is very difficult), then wear a firefighter helmet as found in the Atmos Tech locker, or an Atmospheric Firefighter Helmet as available in loadout.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc): Unsure if this extends to the Chief Engineer variant, but I'd count on it.

**Comment by Cerebulon** [comment]
haha baldie (will have to make sprites for this probably)

**Comment by N-Komaeda** [comment]
Closed PR#8235 should have the sprites in part, I recall them being there as well.
