### ISSUE TITLE
Double-airlocks bug

### ISSUE THREAD

**Issue by Superbee29** [PolarisSS13/Polaris#880]
When you construct a multi-tile airlock assembly, moving it around is rather hard - to position it the way you want. Also, when it's finished, even if it's horizontal, it acts like vertical double-airlock, meaning you interact with it when you walk one tile. And when you walk up, you can step through the right tile, as if there was only the sprite.

**Comment by Superbee29** [comment]
Apparently, the airlock also reacts to you being in the right tile of it. It seems like it think it's occupying all four tiles in that square.

**Comment by Dennok** [comment]
Multi-tile airlock don't take dir from frame when created wisth ingame methods. Also need change bounds.

**Comment by Dennok** [comment]
Strange.
https://github.com/PolarisSS13/Polaris/blob/14e060f1a64f4ff8ef0ce56ff25cb73db76cd25e/code/game/objects/structures/door_assembly.dm#L286

**Comment by emmanuelbassil** [comment]
Shouldn't this be closed?

**Comment by PsiOmegaDelta** [comment]
The PR targeted BS12 but referenced this issue number.
