### ISSUE TITLE
Mech sleepers are completely OP

### ISSUE THREAD

**Issue by Kelenius** [PolarisSS13/Polaris#881]
Full paralyze and no way out once you're in unless the pilot releases you - holy shit why is this in the game?

**Comment by Zuhayr** [comment]
What a useful, unbiased and informative issue that is in no way a vehicle for a personal gripe! 10/10

**Comment by Kelenius** [comment]
2 seconds to load in for unresistable containment that leaves you blind, deaf, and unable to talk. Yep.

**Comment by Nalarac** [comment]
Despite the bias, Kelenius does have a point. Once loaded into the Odysseus sleeper, the patient is knocked unconscious which leads to the symptoms he describes. I'd probably consider it a balance issue.

**Comment by Zuhayr** [comment]
Whether or not it needs balancing is irrelevant to a useless issue title and a relative lack of info on circumstances for reproduction and desired/intended functionality, which was the point of my post.

**Comment by Kelenius** [comment]
There's no bias and no circumstances. I saw it jn the code. I don't know what he intended functionality is, but Ody with three sleepers can be built very quickly.

I guess they shouldn't knock you out and you should be able to leave them like you would a normal sleeper? They're probably not meant to be a kidnap device.

**Comment by Woodratt** [comment]
I'm fairly certain there is bias and circumstances related to this, considering this literally came up shortly after a round in which your character was placed in the sleeper on a oddy.

**Comment by Kelenius** [comment]
@Woodratt placed, yes, placed against his will, no. Seeing that I was knocked out did prompt me to check why it happens, and I saw that it's very abusable.

Can we focus on the facts instead of what you think is my opinion. The facts would be that it's either abusable or not abusable.

**Comment by Zuhayr** [comment]
The fact is also that you made a very salty issue near-immediately after getting dunked. Take five seconds to read your post and title and see if you can spot why it's easy to be dismissive of it as whinging.

**Comment by Kelenius** [comment]
By security. Not the ody. Which appeared much later and was only used to carry patients.

And really, even if I was - would it change the fact that permanent ggnore knockout shouldn't exist in this shape?

**Comment by Ccomp5950** [comment]
I'm trying and failing to imagine what a sleeper would do other then make you go to sleep.

**Comment by Kelenius** [comment]
Just inject the inaprovaline? We already have sleepers that don't put you to sleep, they are called sleepers and you can find them in medbay. Now, mech sleeper, which sounds like a portable version of the sleeper, is actually a completely different thing.

**Comment by Ccomp5950** [comment]
Sounds like the sleepers in medbay are bugged then.  Not even putting you to sleep, what's next Janitors that don't...janitize?
