### ISSUE TITLE
Engineering HAZMAT voidsuits are not radiation proof

### ISSUE THREAD

**Issue by N-Komaeda** [PolarisSS13/Polaris#8883]
#### Brief description of the issue
The HAZMAT suits that you can get by cycling an (engineering) hardsuit in a suit cycler does not protect against radiation, like it (codewise) implies it  should.

#### What you expected to happen
To not get irradiated while wearing one of these.

#### What actually happened
Space cancer:tm:

#### Steps to reproduce
Cycle an engineering suit with the Suit Cycler to the HAZMAT version, then wear it and stand near the Supermatter. Die in this process.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)
 ------
![image](https://user-images.githubusercontent.com/78905387/212444281-5d99e687-05ca-427a-86e0-054e03977fdc.png)
![image](https://user-images.githubusercontent.com/78905387/212444345-a94bd48d-7403-4eed-a0d7-d977136d2c94.png)

These are the HAZMAT hardsuits obtainable by cycling. Above is the IC description, below that is the code definition.

----------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/78905387/212444315-a0f18829-bd89-4cf7-878a-ee4d3183f190.png)
![image](https://user-images.githubusercontent.com/78905387/212444385-1661fa71-09c7-4e23-aee6-45561da01733.png)

This is the RD RIG, which also fully protects against radiation. Above is the IC description, below that is the code definition.

**Comment by Cerebulon** [comment]
Not a bug, just an unclear communication of what suit cyclers do, which is apply a 'skin' to a voidsuit. They do not switch out one type of voidsuit for another.
