### ISSUE TITLE
Linoleum flooring can't be removed

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#890]
Unlike regular carpet and floor tiles, linoleum can't be crowbarred out.

**Comment by Zuhayr** [comment]
Just needs a ````flags = TURF_REMOVE_SCREWDRIVER```` in /decl/flooring/linoleum.

**Comment by Mark9013100** [comment]
Quick fix, I can do that.

**Comment by Nalarac** [comment]
You should probably check for any other floor tiles that can't be removed as well.
