### ISSUE TITLE
Assembly_Holder doesn't allow to use its parts menus

### ISSUE THREAD

**Issue by Varen** [PolarisSS13/Polaris#891]
Take two assemblable things (e.g. igniter, proximity sensor), put them together. Secure them.
Using the item will open the menu, but none of the options do whatever when clicked: Timers cannot be set to countdown, nor sensors, nor can the signaleers channels be changed.

**Comment by GinjaNinja32** [comment]
Is this https://github.com/Baystation12/Baystation12/issues/10516?

**Comment by Varen** [comment]
Seems to be the same issue I describe, yes.
