### ISSUE TITLE
Items magically shrink when put into parcels.

### ISSUE THREAD

**Issue by Dragor** [PolarisSS13/Polaris#896]
They're a bulky item normally and shrink down to a normal-sized item when the wrapping paper is used on them.

This enables people to do funny stuff like actually carrying five roller beds in their satchel.

**Comment by PsiOmegaDelta** [comment]
The same can be done for objects such as rigs/voidsuits.

**Comment by Jakksergal** [comment]
Might want to rename the issue.

**Comment by Kelenius** [comment]
I'm pretty sure this is more or less intentional. Packages make the items smaller.

**Comment by Dragor** [comment]
But how. How does it make sense that they do that.

**Comment by Datraen** [comment]
Item sizes should be inherited by the package, rather than be a set number.

**Comment by SpadesNeil** [comment]
I cannot reproduce this issue any more.

**Comment by mistyLuminescence** [comment]
Unable to reproduce as of 21/5/19.
