### ISSUE TITLE
Missing feet do not cause pain.

### ISSUE THREAD

**Issue by FenodyreeAv** [PolarisSS13/Polaris#900]
Had my foot forcibly removed by a shotgun. Put a sticking plaster on it, and in ten minutes it was completely fine.

**Comment by zaredman** [comment]
![del](https://cloud.githubusercontent.com/assets/8041697/12823980/ef2a3dfa-cb3c-11e5-90bf-6a6c2c7f2745.gif)

**Comment by zaredman** [comment]
![del](https://cloud.githubusercontent.com/assets/8041697/12824011/18f19674-cb3d-11e5-89ba-2651e2ff9337.jpg)

**Comment by Neerti** [comment]
No surgery was done, it was a stump.

**Comment by FenodyreeAv** [comment]
I could wear boots and everything.

**Comment by Spookerton** [comment]
Stumps actually result in less pain than a prepared attachment point, based on hilarious testing. :(
