### ISSUE TITLE
Being blinded does not break existing gun aims

### ISSUE THREAD

**Issue by Spookerton** [PolarisSS13/Polaris#903]
Pretty much as titled. See quote for an example. Despite being blinded, Mason manages to almost kill Leshiy from a full screen away by having a pre-existing aim.

> ATTACK: Spraydoodle/(Leshiy Vaelyom) used a blindness rune on Beepboopbeta/(Mason Fisher) (INTENT: HELP) (JMP)
> ATTACK: Spraydoodle/(Leshiy Vaelyom) used a blindness rune on Fekkor/(Carter Moody) (INTENT: HELP) (JMP)
> ATTACK: Spraydoodle/(Leshiy Vaelyom) used a blindness rune on Crockers/(Bill Howard) (INTENT: HELP) (JMP)
> Holopad received, Mason Fisher pulls the trigger reflexively!
> Holopad received, Mason Fisher fires the laser carbine!
> Holopad received, Leshiy Vaelyom is hit by the laser in the head!
> Holopad received, Mason Fisher pulls the trigger reflexively!
> Holopad received, Mason Fisher fires the laser carbine!
> Holopad received, The laser misses Leshiy Vaelyom narrowly!
> Holopad received, Mason Fisher pulls the trigger reflexively!
> Holopad received, Mason Fisher fires the laser carbine!
> Holopad received, The laser misses Leshiy Vaelyom narrowly!
> Holopad received, Mason Fisher pulls the trigger reflexively!
> Holopad received, Mason Fisher fires the laser carbine!
> Holopad received, Leshiy Vaelyom is hit by the laser in the left leg!
> Holopad received, Mason Fisher pulls the trigger reflexively!
> Holopad received, Mason Fisher fires the laser carbine!
> Holopad received, The laser misses Leshiy Vaelyom narrowly!
> [04:14] [Security] Mason Fisher (Security Officer) exclaims, "SHOTS FIRED!"
> Holopad received, Mason Fisher pulls the trigger reflexively!
> Holopad received, Mason Fisher fires the laser carbine!
> Holopad received, Leshiy Vaelyom's head melts away, turning into mangled mess!
> Holopad received, Leshiy Vaelyom is hit by the laser in the head!
> Holopad received, Leshiy Vaelyom says, "JEESUS"
> Holopad received, Mason Fisher pulls the trigger reflexively!
> Holopad received, Mason Fisher fires the laser carbine!
> Holopad received, The laser misses Unknown (as Leshiy Vaelyom) narrowly!
> [04:14] [Security] Mason Fisher (Security Officer) shouts, "I can't see!"
> Holopad received, Mason Fisher pulls the trigger reflexively!
> Holopad received, Mason Fisher fires the laser carbine!
> Holopad received, Leshiy Vaelyom stutters, "F-Fir-r-r-rj-jj-ji r-r-r-rh-h-hiv-v maz-z-z-zen-nh-hor-r-r."
> Holopad received, The laser misses Unknown (as Leshiy Vaelyom) narrowly!
> Holopad received, Mason Fisher pulls the trigger reflexively!
> Holopad received, Mason Fisher fires the laser carbine!
> Holopad received, The laser misses Unknown (as Leshiy Vaelyom) narrowly!
> Holopad received, Mason Fisher lowers the laser carbine.
> Holopad received, Leshiy Vaelyom stammers, "H-Hakk-kr-rut-tj-j-j-ju gop-poen-nj-j-jim-m."
> Holopad received, Leshiy Vaelyom stutters, "EH-HHH-HGH-H . ."
> Holopad received, Carter Moody exclaims, "I can't seee!"
> Holopad received, Unknown (as Leshiy Vaelyom) disappears in a flash of red light!

**Comment by Datraen** [comment]
It sounds like blinded needs to call drop aim procs.

**Comment by Zuhayr** [comment]
Just check blindness/presence of eyes in the aiming process().

**Comment by Neerti** [comment]
Fixed by #922
