### ISSUE TITLE
Cannot click tiles to move objects

### ISSUE THREAD

**Issue by Sypsoti** [PolarisSS13/Polaris#9037]
#### Brief description of the issue
When pulling an item, like a crate, you were able to click a tile to move it there. It does not seem to work anymore.
#### What you expected to happen
Move a crate from tile A to tile B by clicking on tile B while pulling the crate.
#### What actually happened
Absolutely nothing.
#### Steps to reproduce
Pull an object. Click a turf. Nothing happens.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by Greenjoe12345** [comment]
Possibly related: Clicking on a tile with an airlock does not close that airlock anymore, either.
