### ISSUE TITLE
Botany Trays not absorbing new water and nutrients.

### ISSUE THREAD

**Issue by RoseCG** [PolarisSS13/Polaris#911]
The trays start with 100 Water, 10 Nutrient. You can refill them with more water and nutrients, but they aren't being absorbed. 

For example, Water on the tray is at 2/100. You fill the tray with 60 units of water. Scanning with the analyser reveals the tray has 60 units of water, but the value doesn't decrease and the tray continues with 2/100.

![polaris_traybug](https://cloud.githubusercontent.com/assets/4467044/12869526/394cefac-cd1a-11e5-909b-9d9389ce0e75.PNG)

**Comment by RoseCG** [comment]
As a note, trays that had a bucket of water and a bottle of nutrients still produced plants, despite the tray stats claiming there was no water or nutrients. So I am unsure of what's happening here.

**Comment by Zuhayr** [comment]
#921
