### ISSUE TITLE
Bar rags are broken

### ISSUE THREAD

**Issue by Spookerton** [PolarisSS13/Polaris#913]
Rags cannot be dampened reliably by adding water.
Rags cannot be dampened reliably by using with a sink.
Rags cannot be used to wipe drinking glasses when dry, and when damp, can only wring out into the glass and become dry.

**Comment by Techhead0** [comment]
Also noted on Bay. See here: https://github.com/Baystation12/Baystation12/issues/12077

**Comment by Zuhayr** [comment]
#921
