### ISSUE TITLE
Teshari issue megathread.

### ISSUE THREAD

**Issue by Zuhayr** [PolarisSS13/Polaris#917]
- [x] Eyeware sprites are wonky.
- [x] Ear sprites are wonky.
- [x] On-mob sprites do not show up when picked up.
- [x] Also don't seem to spawn with shoes unless you add sandals/toeless jackboots to your loadout.

**Comment by Anewbe** [comment]
Also don't seem to spawn with shoes unless you add sandals/toeless jackboots to your loadout.

**Comment by Dragor** [comment]
They also have no money at all.
