### ISSUE TITLE
Plant Analyzers don't report if a plant produces or consumes gases

### ISSUE THREAD

**Issue by RoseCG** [PolarisSS13/Polaris#925]
I have been noticing in Xenobotany I get plants that produce or consume gases, but nothing is reported on the plant analyser. Meaning that innocent looking exotic mushroom tray is now filling the lab with phoron.

I had heard that plant analysers reported on whatever a plant produced gases or not (without saying which kind of gas), so I'm not sure if this is a bug or not.

**Comment by Datraen** [comment]
#983
