### ISSUE TITLE
Give defaults to 'no'

### ISSUE THREAD

**Issue by Mark9013100** [PolarisSS13/Polaris#927]
Title.

**Comment by EmperorJon** [comment]
Change from Bay was presumably done to prevent you taking items whilst typing. Discussion needs to be had on whether it's worth reverting or just waiting a while for people to get used to it - the previous behaviour _was _rather annoying.

**Comment by Spookerton** [comment]
Strong preference for keeping no as default behavior for Y/N popups. In my experience, people try to hand me something when I'm in the middle of typing about 90% of the times people are trying to hand me something. I'd rather decline by default than accept before I can even register that there's a popup.

**Comment by Kelenius** [comment]
Alternate solution: make it a chat link instead of a popup.

**Comment by Zuhayr** [comment]
Given how unstable BYOND is with links now, I would be very, very much opposed to that.

**Comment by GinjaNinja32** [comment]
Does Bay give not default to no too?

**Comment by Neerti** [comment]
Bay currently defaults to no, we inherited this change from the latest baymerge, hence this issue report showing up.

**Comment by GinjaNinja32** [comment]
Ah, I see.

**Comment by Lorwp** [comment]
Also, see #916. Though this is probably better polled on the forums than here.
