### ISSUE TITLE
De-antagging a changeling doesn't remove powers

### ISSUE THREAD

**Issue by JonathonED** [PolarisSS13/Polaris#928]
A "you are no longer a changeling" message was provided, but the 'ling in question still had access to various changeling verbs/tabs/info.

**Comment by Kelenius** [comment]
https://github.com/Baystation12/Baystation12/issues/10616

**Comment by PsiOmegaDelta** [comment]
While the issues are indeed the same I don't believe the solutions will be, due to Polaris' rewritten changeling.

**Comment by Serithi** [comment]
Still an issue as of June 10 2018.
