### ISSUE TITLE
Merc Channel intercepts without Telecomms working

### ISSUE THREAD

**Issue by Albens** [PolarisSS13/Polaris#939]
Traitor accessible merc radio key was able to intercept messages while telecoms was manually disabled. These messages where unable to be seen by anyone, sender included, but the merc key was still intercepting them.

**Comment by Neerti** [comment]
I think mercs hearing other merc headsets always is a feature.  Not sure if them hearing everything else while comms are down is also a feature, a "feature", or radio code being bad again.

**Comment by Atermonera** [comment]
The tcomms equipment that handles merc comms is on the centcomm Z, and is set to listen to everything, so it follows that disabling comms for the station won't make the equipment on centcomm stop listening.
