### ISSUE TITLE
Protolathe will not eject materials

### ISSUE THREAD

**Issue by Searif** [PolarisSS13/Polaris#94]
What it says on the tin

**Comment by Neerti** [comment]
95% sure inherited from baycode, sooooo gonna try updating soon.

**Comment by Searif** [comment]
I should also note that I have more glass in there then the material cap

**Comment by Searif** [comment]
like it was something like 12637/12500

**Comment by Szunti** [comment]
Experienced the same. Neither the Protolathe nor the Circuit Imprinter gave back metal or glass sheets.
