### ISSUE TITLE
Space cleaner does not update icons of sprayed mobs. 

### ISSUE THREAD

**Issue by Jakksergal** [PolarisSS13/Polaris#940]
Title.

**Comment by Lorwp** [comment]
This seems to also apply to anything that cleans you in this was. E.g showers

**Comment by Atermonera** [comment]
Still an issue:
[https://puu.sh/wNY8l/ce755aeeed.mp4](https://puu.sh/wNY8l/ce755aeeed.mp4)
[https://puu.sh/wNYmM/ce684917f3.mp4](https://puu.sh/wNYmM/ce684917f3.mp4)
