### ISSUE TITLE
Teshari Smocks De-Select Themselves From Custom Items List

### ISSUE THREAD

**Issue by Loneguyfly** [PolarisSS13/Polaris#941]
After every round, I have to reselct the smock item, or I simply do not spawn with the smock. I'm not really sure why, but the game doesn't seem to remember it in the custom item list.

**Comment by Zuhayr** [comment]
Does it persist if you alter and resave your slot?

**Comment by Loneguyfly** [comment]
Yes, it does. I've tried adding new things to the list and resaving it, deleting things, etc. It doesn't seem to stick.

**Comment by Zuhayr** [comment]
Looks like it's an issue with all whitelisted loadout gear, may be a problem with preferences_mob().

**Comment by Loneguyfly** [comment]
This is fixed, now!
