### ISSUE TITLE
Hydroponics tray can't be refilled with nutrients and water once they run out.

### ISSUE THREAD

**Issue by Ithalan** [PolarisSS13/Polaris#946]
Haven't been able to exhaustively test this yet, but once the trays have used up their initial 100 water units and 10 nutrient units, they can't be refilled.

Any attempts to do so seems to instead deposit the water and nutrients in a different variable (which can be viewed by using the plant analyzer, and seems to be capped at a combined total of 200). The plants aren't using this variable either, as it never seems to decrease, and plants quickly die out after exhausting the initial water and nutrient in the tray.

**Comment by Zuhayr** [comment]
This is fixed but the server hasn't been updated.
