### ISSUE TITLE
FBP bloodied sprites have their species' blood appear on them instead of black/oil when attacked

### ISSUE THREAD

**Issue by Neerti** [PolarisSS13/Polaris#949]

**Comment by Zuhayr** [comment]
God dammit I thought I fixed this.

**Comment by Anewbe** [comment]
Believe this was fixed by the Terminator Update.

**Comment by Atermonera** [comment]
Unable to reproduce:
[https://puu.sh/wNXRB/521cf71eed.mp4](https://puu.sh/wNXRB/521cf71eed.mp4)
[https://puu.sh/wNXXL/36ab0eeba3.mp4](https://puu.sh/wNXXL/36ab0eeba3.mp4)

**Comment by Anewbe** [comment]
Seems to be fixed in most recent build, closing.
