### ISSUE TITLE
Fixing burns on robolimbs broke as fuck

### ISSUE THREAD

**Issue by Searif** [PolarisSS13/Polaris#95]
This may just be that the technique was changed, but burns don't get fixed by using wire on them. If this was changed its a dumb as fuck change.

**Comment by Searif** [comment]
Turns out, you can fix robolimbs with bandaids and ointment, that makes no fucking sense

**Comment by Searif** [comment]
It also got infected, why is this so fucking broke

**Comment by Mark9013100** [comment]
I guess you could say it got a virus.

**Comment by zaredman** [comment]
@Searif is this a Polaris-code exclusive bug or is this a problem on BS12 Dev-Freeze too?

**Comment by Mark9013100** [comment]
Was able to reproduce on the current dev branch of Bay.

**Comment by Neerti** [comment]
Needs re-testing.
