### ISSUE TITLE
Items within the new loadout menu are impossible to differentiate

### ISSUE THREAD

**Issue by Yoshax** [PolarisSS13/Polaris#950]
For example, hair flower pin in Hats and Headwear, there's 6 of them and it's impossible to tell what color they are. This applies to a number of items.

From what I could see:
Hair Flower Pin
Hard Hat
Leather Jacket
Military Jacket
Skrellian Accessories

**Comment by Datraen** [comment]
I can confirm this to be the case for headtail cloths, as well.

**Comment by Zuhayr** [comment]
This is a problem with those items not having distinct names or descriptions rather than a problem with the loadout system. That said, it should be using the display name from the datum, not sure why it would be using identical item names.
