### ISSUE TITLE
Teshari Ears Clip Through Helmets

### ISSUE THREAD

**Issue by Loneguyfly** [PolarisSS13/Polaris#956]
Tested this with emergency softsuit and merc suit, only have a picture of merc suit:
http://prntscr.com/a19cgu

**Comment by Spookerton** [comment]
maybe-feature :3

**Comment by Datraen** [comment]
It's probably the same bug that results in Skrell headtails coming through certain helmets.

**Comment by Zuhayr** [comment]
It's because I made the ears part of the default head instead of part of the hair. Will do some adjusting of icons today.

**Comment by Zuhayr** [comment]
Fixed in #974.
