### ISSUE TITLE
Teshari loneliness does not seem to result in negative effects.

### ISSUE THREAD

**Issue by Zuhayr** [PolarisSS13/Polaris#958]
See above. Spent most of a round alone with no increase in shock or hallucination.

**Comment by Loneguyfly** [comment]
Huh. I spent a large part of the (opening) of my antag round alone, and I managed to start getting Pun Puns and flipping screens. 

It vanished randomly, though, so it might have been something else?

**Comment by Loneguyfly** [comment]
Vanished randomly and, well, while I was alone.*

**Comment by Telvayne** [comment]
Are ghosts being counted?

**Comment by Anewbe** [comment]
No longer relevant, closing
