### ISSUE TITLE
Explosive grenade vanishing before detonation

### ISSUE THREAD

**Issue by Yithani** [PolarisSS13/Polaris#967]
I planted a grenade consisting of,
1x Large Chemical Grenade Casing
1x Large Beaker (120u water)
1x Large Beaker (120u potassium)
1x Timer+Igniter Assembly (40sec timer)
in the forensics laboratory during an antagonist round in order to disrupt their search for information.

The grenade vanished without a trace, causing no log that Mangled could see (apparently).

I have not yet attempted to test this again, on account of possibly blowing shit up if it doesn't happen

**Comment by Varen** [comment]
Should be the same as this issue:
https://github.com/PolarisSS13/Polaris/issues/870

**Comment by Yithani** [comment]
Knew I should've scanned the list better. Definitely the same thing.
