### ISSUE TITLE
Changeling armblade and flavortext fuckery

### ISSUE THREAD

**Issue by BlittzOff** [PolarisSS13/Polaris#969]
Getting stunned or otherwise disarmed as a ling will instantly remove the armblade you just shelled 20 chems for, leaving lings to constantly reform it in combat.
The armblade does not seem deflect any projectile weapons. Not sure if this is an issue or if its just intended to work with lasers.

Changing identities while having snowflake text will retain the previous snowflake text, making lings a dead giveaway to the powergaymen in red suits.

**Comment by Zuhayr** [comment]
First issue could be resolved by setting canremove = 0 on the armblade item, I think.
