### ISSUE TITLE
[MAIN MAP] Transfer shuttle airlocks don't open when docked

### ISSUE THREAD

**Issue by SledgeLP** [PolarisSS13/Polaris#97]
What it says on the tin, when the shuttle was docked, the doors didn't open. Shuttle did move correctly, just the doors aren't opening, maybe issues with tags?

**Comment by SledgeLP** [comment]
On top of that, the shuttle doesn't seem to launch correctly.

**Comment by zaredman** [comment]
Duplicate of #96
