### ISSUE TITLE
Spiderbot Hearing and Crawling bugs.

### ISSUE THREAD

**Issue by Mechoid** [PolarisSS13/Polaris#973]
Spiderbots are unable to hear cyborgs, pAI's, and AI's speaking, and instead get asterisk-swapped sentences. This also causes them to hear 'synthesized voice' with asterisks instead of the previous speaking on radio.
Spiderbots are also unable to crawl through vents, with the error being that 'They must not be carrying anything or have anything equipped when crawling through a vent.' despite not having slots or carrying an item.

**Comment by Zuhayr** [comment]
Spiderbots are pretty unmaintained/legacy. Updating them is almost not worth it.

**Comment by Atermonera** [comment]
Hearing is likely related to languages, and so needs retesting. Ventcrawling is covered by #2907
