### ISSUE TITLE
Chemical dispenser not solid

### ISSUE THREAD

**Issue by Superbee29** [PolarisSS13/Polaris#979]
Character can walk through it. At least the one on research outpost.

**Comment by BlittzOff** [comment]
![](http://4.bp.blogspot.com/-2qfMk68WoXs/VZx0O9dv1CI/AAAAAAAAB8M/L-K6ckiKm6g/s1600/Bug%2Bor%2BFeature.jpg)

**Comment by Mark9013100** [comment]
I believe this is intentional.

**Comment by Zuhayr** [comment]
It is. Not a bug. No idea what the reasoning is, but it was deliberately done.
