### ISSUE TITLE
The map lacks beacons for floorbots, beepsky

### ISSUE THREAD

**Issue by Magneld** [PolarisSS13/Polaris#99]
I forget the name of the item at the moment but essentially under the floor on say the Exodus there are little navbeacons beepsky, floorbots and I think mules use in order to path around the station and do their thing. Northern star lacks said beacons so the bots just sort of sit there all sad and confused unless a mess happens in a cleanbots sightrange/a criminal scum goes near beepsky.

**Comment by zaredman** [comment]
Does the summon function for beepsky still work?

**Comment by Magneld** [comment]
I havent had a chance to test that, assume no though.

**Comment by Woodratt** [comment]
Working on it, just something that hasn't been added yet.

**Comment by Woodratt** [comment]
Beepsky and I are no longer on speaking terms.

**Comment by Magneld** [comment]
;n;
