### ISSUE TITLE
Analyzing Health Shows Improper Overall Status

### ISSUE THREAD

**Issue by Nalarac** [PolarisSS13/Polaris#994]
Using a health analyzer on people will show proper damage values on the individual, but the overall status will be wrong. An uninjured person will show up with 100% health (which is normal), an injured person will show up with 0% health even if it's only a minor injury, and a person in crit will show up as -100% health.

**Comment by Zuhayr** [comment]
This is probably related to my changes to maxhealth/health reporting. Will look into it.

**Comment by Anewbe** [comment]
Still a thing as of 9/29

**Comment by Anewbe** [comment]
Closed by #2704
